Cray-HPE/docs-csm

- install/prepare_site_init.md
These steps have not been necessary since the FIXMEs were removed from the stable customizations.yaml in CASMINST-1886.
> CASMINST-3055:  Remove the unnecessary steps for removing FIXMEs in customizations.yaml

- 101-NCN-BOOTING.md
The current commands for setting the NCN boot order assume that all desired boot options are already marked as active. If this is not the case (and thus the * character is absent from them), the current command does not work. This PR changes the command so that it works whether or not the options are currently marked as active. It also adds an additional command to mark the desired boot options as active. Finally, it mentions that the "USB Boot Priority" BIOS option can override the order specified by the efibootmgr commands.
> CASMINST-3109: Update boot order set instructions

- background/ncn_boot_workflow.md
- install/redeploy_pit_node.md
- operations/CSM_product_management/Manage_a_Configuration_with_CFS.md
- operations/validate_csm_health.md
This PR includes:
* The boot order changes from this PR: https://github.com/Cray-HPE/docs-csm/pull/48
* The CFS configuration management section has two errors which result in broken commands (one of which is particularly bad since it does not cause the command to fail, but causes errors further down the line, after much time has been spent). These were fixed by previous commits, but the most recent commit to that page restored the bugs on accident. This PR restores the fixes.
* Minor linting done on CSM Health Validation and Redeploy Pit Node sections
> CASMINST-3109: Fix broken commands; restore previous commits that were overwritten; linting

- install/bootstrap_livecd_usb.md
We were placing the typescript file onto the USB device that we were writing over a few steps later.   We want to put it on local disk and then copy it the USB after we have rewritten it with the new ISO.   This also prevents downloading the ISO to the same USB that we are rewriting as well.
Changed the install of the cray-site-init rpm to find the rpm in the tarball rather than hardcoding the path.  This path has been changing a lot lately.
> CASMINST-3120: Fix cray-site-init installation and typescript logging prior to booting the LiveCD

- operations/node_management/Enable_Passwordless_Connections_to_Liquid_Cooled_Node_BMCs.md
Minor update to how to generate the System Configuration Service configuration in the "Enable Passwordless Connections to Liquid Cooled Node BMCs" procedure.
> STP-2903: Updated scsd config in procedure

- 101-NCN-BOOTING.md
Restore my original doc changes that were mistakenly reverted.
This is ready to be merged.
> Revert "Revert "CASMINST-3109: Update boot order set instructions to account for inactive boot options""

- operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
- operations/index.md
Added an operational procedure to specify new resource limits for the collector in customizations.yaml and redeploy the collector. Also added some guidance on how the resource limits for the collector can be adjusted.
The process of updating customizations.yaml was tested on Wasp.
> (CSM 1.1) CASMHMS-5167: Add process to apply new resource limits to the collector

- operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
- operations/index.md
Added an operational procedure to specify new resource limits for the collector in customizations.yaml and redeploy the collector. Also added some guidance on how the resource limits for the collector can be adjusted.
The process of updating customizations.yaml was tested on Wasp.
> (CSM 1.2) CASMHMS-5167: Add process to apply new resource limits to the collector

- operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
- operations/index.md
Added an operational procedure to specify new resource limits for the collector in customizations.yaml and redeploy the collector. Also added some guidance on how the resource limits for the collector can be adjusted.
The process of updating customizations.yaml was tested on Wasp.
> (main) CASMHMS-5167: Add process to apply new resource limits to the collector

- operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
- operations/index.md
Added an operational procedure to specify new resource limits for the collector in customizations.yaml and redeploy the collector. Also added some guidance on how the resource limits for the collector can be adjusted.
The process of updating customizations.yaml was tested on Wasp.
> (CSM 1.0) CASMHMS-5167: Add process to apply new resource limits to the collector

- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
Copy operations/system_managment_health/Troubleshoot_Prometheus_Alerts.md  from release/1.0 to release/0.9 so it is available for csm-0.9.6
Resolves 
* CASMPET-4936 for release/0.9
> CASMPET-4936 : DOCS - Get the Alert troubleshooting doc copied into the release/0.9 branch (for CSM-0.9.6)

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Adding rolling reboot.
Cleaning up the kubelet pem process to remove some legacy unsupported contexts.
Cherry pick release/1.0 commit to release/0.9
Resolves CASMINST-3100 for 0.9
> CASMINST-3100 0.9 - update to the cert renewal process.

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Adding rolling reboot.
Cleaning up the kubelet pem process to remove some legacy unsupported contexts.
> CASMINST-3100 1.0 - update to the cert renewal process.

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Adding rolling reboot.
Cleaning up the kubelet pem process to remove some legacy unsupported contexts.
Cherry pick release/1.0 commit to release/1.1
Resolves CASMINST-3100 for 1.1
> CASMINST-3100 1.1 - update to the cert renewal process.

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Adding rolling reboot.
Cleaning up the kubelet pem process to remove some legacy unsupported contexts.
Cherry pick release/1.0 commit to main
Resolves CASMINST-3100 for main
> CASMINST-3100 main - update to the cert renewal process.

- upgrade/0.9/csm-0.9.4/README.md
- upgrade/0.9/csm-0.9.4/scripts/remove-service-repos.sh
- upgrade/0.9/csm-0.9.5/README.md
- upgrade/0.9/csm-0.9.5/scripts/remove-service-repos.sh
- upgrade/0.9/csm-0.9.6/README.md
- upgrade/0.9/csm-0.9.6/scripts/update-ncns.sh
We had this logic in csm-9.2 and csm-9.3.  It was missing in
csm-9.4, csm-9.5, and csm-9.6
> CASMTRIAGE-2299: add calls to remove service repos

- operations/validate_csm_health.md
Add additional postgres error that can be ignore to the validate csm health md
Resolves
* CASMINST-3134 : DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod. (for csm-1.1)
> CASMINST-3134 1.1: DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod.

- operations/validate_csm_health.md
Add additional postgres error that can be ignore to the validate csm health md
Resolves
* CASMINST-3134 : DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod. (for csm-1.2)
> CASMINST-3134 1.2: DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod.

- operations/validate_csm_health.md
Add additional postgres error that can be ignore to the validate csm health md
Resolves
* CASMINST-3134 : DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod. (for main)
> CASMINST-3134 main : DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod.

- operations/validate_csm_health.md
Add additional postgres error that can be ignore to the validate csm health md
Resolves
* CASMINST-3134 : DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod. (for csm-1.0)
> CASMINST-3134 1.0: DOCS: Postgres health check failed with one error message for gitea-vcs-postgres pod.

- operations/validate_csm_health.md
Because the cmsdev tests are not being updated for csm-1.1, this PR changes the health check docs so that the VCS test is not run (as it will fail). It also makes a minor clarification to the instructions for finding the test log. This is ready to merge, pending approvals.
> CASMCMS-7342: Do not run VCS test in csm-1.1 health checks

- operations/validate_csm_health.md
Add a minor clarification on where to find the cmsdev test logs in the CSM health check.
This is ready for merge pending approval.
> CASMCMS-7342: Minor updates to cmsdev section of CSM health checks

- upgrade/0.9/csm-0.9.6/README.md
- upgrade/0.9/csm-0.9.6/scripts/update-bss-metadata.sh
- upgrade/0.9/csm-0.9.6/scripts/update-ncns.sh
This PR addresses:
CASMINST-3193: 0.9.6 patch instructions don't make call to update bss metadata
CASMINST-3194: update-ncns.sh script in 0.9.6 patch has several issues
> Fixes for 0.9.6 patch install

- introduction/PowerDNS_migration.md
- introduction/differences.md
Document introduction of PowerDNS, upcoming DNS record naming changes, and upcoming deprecation of cray-dns-unbound-manager job.
> CASM-2656 - DNS deprecation notice

- introduction/PowerDNS_migration.md
- introduction/differences.md
Document introduction of PowerDNS, upcoming DNS record naming changes, and upcoming deprecation of cray-dns-unbound-manager job.
> CASM-2565 - DNS deprecation notice

- troubleshooting/index.md
- troubleshooting/known_issues/incorrect_output_for_bos_command_rerun.md
The command BOA outputs to re-run a failed operation is faulty. This
describes how to correct the faulty command to make it runnable.
> CASMCS-7255

- 008-CSM-VALIDATION.md
There were some improvements made to the barebones boot documentation in csm-1.0 that equally apply to csm-0.9. This PR backports them. This is ready for merge pending appprovals.
> CASMINST-3198: Backport improvements to barebones boot procedure

- operations/node_management/Rebuild_NCNs.md
This PR is an overhaul of the NCN rebuild procedure documentation. No substantive changes are made to the actual procedure. Instead this reorganizes, clarifies, fixes some minor errors, and otherwise makes it more user friendly.
This is ready for merge pending approvals.
> CASMINST-3198: Corrections and improvements to NCN rebuild procedure

- upgrade/0.9/csm-0.9.6/README.md
Doc only change to add image verification steps for openSSL CVE commits for 0.9.6 patch.
> Fixes CASMPET-4964: add image validation for openSSL CVE

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Remove specific Shasta v1.3 information from the Cert Renewal docs
Resolves
* CASMPET-4962 for 1.0
> CASMPET-4962 1.0 : Remove Shasta v1.3 content from cert renewal process

- upgrade/1.0/scripts/upgrade/ncn-upgrade-k8s-worker.sh
Before upgrading worker NCNs, the upgrade script checks all of the postgres clusters. Among other things, it checks the maximum lag values they report, and fails if any of them are reporting any lag. Often a lag value will be temporarily non-0 not because of any real problem. In this case, the upgrade script fails, but a retry may succeed. On some systems, multiple retries may be required, since every postgres cluster is checked on every attempt.
This PR modifies the previous behavior as follows:
1) If the maximum lag value for a cluster is non-0, this does not result in immediate failure. The script will now sleep for 10 seconds and then check again. The script only fails if the lag is non-0 for 10 attempts.
2) The lag check (but not the overall postgres check) can be skipped by …
> CASMINST-3215: Add retries and skip capability to postgres lag check

- upgrade/1.0/Stage_5.md
This PR makes explicit that stage 5 should be skipped if no switches of the relevant model are on the system. This PR also does extensive linting of the page. Despite the extensiveness of the changes, no real content changes are made.
> CASMINST-3212: Clarify and lint upgrade stage 5 documentation

- operations/validate_csm_health.md
Resolves for release/1.0
* CASMINST : Update the ignorable error message for postgres health check script
Adds another postgres error that can be ignored.
> CASMPUNST-2999 1.0 : DOCS: 1.0 : Update the ignorable error message for postgres health check script

- operations/validate_csm_health.md
Resolves for release/1.1
* CASMINST : Update the ignorable error message for postgres health check script
Adds another postgres error that can be ignored.
> CASMINST-2999 1.1 : DOCS: 1.0 : Update the ignorable error message for postgres health check script

- operations/validate_csm_health.md
Resolves for release/1.2
* CASMINST : Update the ignorable error message for postgres health check script
Adds another postgres error that can be ignored.
> CASMINST-2999 1.2 : DOCS: 1.0 : Update the ignorable error message for postgres health check script

- operations/validate_csm_health.md
Resolves for main
* CASMINST : Update the ignorable error message for postgres health check script
Adds another postgres error that can be ignored.
> CASMINST-2999 main : DOCS: 1.0 : Update the ignorable error message for postgres health check script

- RELEASE_NOTES.md
- troubleshooting/index.md
- troubleshooting/known_issues/incorrect_output_for_bos_command_rerun.md
The command BOA outputs to re-run a failed operation is faulty. This
describes how to correct the faulty command to make it runnable. It
provides cut and paste instructions to fix the command.
> CASMCMS-7255: Describe how to modify fault BOA re-run command

- install/deploy_management_nodes.md
- operations/network/metallb_bgp/Update_BGP_Neighbors.md
Update path of mellanox_set_bgp_peers.py script to the correct location
> CASMINST-3229 - DOCS: Change the location of the BGP script (Mellanox) in the docs

- RELEASE_NOTES.md
- troubleshooting/index.md
- troubleshooting/known_issues/cfs_sessions_stuck_in_pending.md
This adds documentation detailing how to check for and recover from CFS sessions that are stuck in a pending state.
* Resolves CASMCMS-7606
Tested on:
* NA, docs
None
> CASMCMS-7606: Add docs for stuck CFS sessions (0.9)

- install/collecting_ncn_mac_addresses.md
Added details and example on conman usage to the documentation in the step where the user needs to connect to a console using conman.
Merging changes from this PR to the release/1.2 branch:
https://github.com/Cray-HPE/docs-csm/pull/183
> CASMINST-3037 - refine conman info, merge to release/1.2

- .github/workflows/backport.yaml
Cherry-pick of https://github.com/Cray-HPE/docs-csm/pull/212 to release/0.9 branch.
> CASMINST-3116 Automatic backport of closed PRs to selected branches (0.9)

- operations/configuration_management/Version_Control_Service_VCS.md
Fixes the command for updating the VCS password secret.  Adds a missing "\" for line continuation as well as fixing a deprecated usage of --dry-run so that the command works in more recent kubernetes versions.
* Resolves CASMCMS-7632
Tested on:
* Mug
Updated the VCS password
None
> CASMCMS-7632: Fix docs for updating VCS password (1.2)

- RELEASE_NOTES.md
Adds information on the broken "branch" parameters in CFS configurations to the known issues in the release notes.
* Resolves CASMINST-3267
Tested on:
* NA, docs only
None
> CASMINST-3267: Add info on broken CFS feature to release notes (1.1)

- install/install_csm_services.md
- operations/validate_csm_health.md
CASMINST-3249 - Added an item underneath the hms_discovery_verify.sh interpreting results section in the Validate CSM health document. The BMC for an Apollo XL645D may not be discovered when the `hms_discovery_verify.sh` is ran during an install, as it requires an operational task to be completed near the end of the CSM Install process.
CASMINST-3247 - Added a known issue for the install.sh script were it may fail due to the `sls-s3-credentials` secret is not present in the services namespace.
> (CSM 1.1) CASMINST-3249/3247

- install/install_csm_services.md
- operations/validate_csm_health.md
CASMINST-3249 - Added an item underneath the hms_discovery_verify.sh interpreting results section in the Validate CSM health document. The BMC for an Apollo XL645D may not be discovered when the hms_discovery_verify.sh is ran during an install, as it requires an operational task to be completed near the end of the CSM Install process.
CASMINST-3247 - Added a known issue for the install.sh script were it may fail due to the sls-s3-credentials secret is not present in the services namespace.
> (CSM 1.2) CASMINST-3249/3247

- install/install_csm_services.md
- operations/validate_csm_health.md
CASMINST-3249 - Added an item underneath the hms_discovery_verify.sh interpreting results section in the Validate CSM health document. The BMC for an Apollo XL645D may not be discovered when the hms_discovery_verify.sh is ran during an install, as it requires an operational task to be completed near the end of the CSM Install process.
CASMINST-3247 - Added a known issue for the install.sh script were it may fail due to the sls-s3-credentials secret is not present in the services namespace.
> (main) CASMINST-3249/3247

- Jenkinsfile.github
- install/deploy_management_nodes.md
- install/prepare_management_nodes.md
- install/wipe_ncn_disks_for_reinstallation.md
- operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
- operations/node_management/Reboot_NCNs.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Change_EX_Cabinet_Global_Default_Password.md
- operations/security_and_authentication/Provisioning_a_Liquid-Cooled_EX_Cabinet_CEC_with_Default_Credentials.md
- operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md
- operations/validate_csm_health.md
- troubleshooting/known_issues/cfs_sessions_stuck_in_pending.md
1. Tries to make it more obvious that the automated goss tests are only to be run from the PIT node.
2. Tries to make it more obvious what manual procedure should be carried out in the case that an automated test fails with "/dev/sdc" errors
3. Minor improvements to the recovery steps in the case that the manual checks show a problem
I also pulled in my linting commit for CASMINST-3344
> CASMINST-3270: Clarify when to run goss tests, how to run manual LVM test

- operations/validate_csm_health.md
Resolves CASMPET-5087 for csm-1.2 and also make minor changes to align this doc with that on main.
> CASMPET-5087 main : postgres health check failing after ncn-m001 reboot

- 007-CSM-INSTALL-REBOOT.md
- scripts/patch-ceph-runcmd.py
Resolves CASMINST-3351.
Testing:
```
ncn-m001:~/swallace # cray bss bootparameters list --hosts $(ssh ncn-s001 cat /etc/cray/xname) --format json > ncn-s001.json
Warning: Permanently added 'ncn-s001,10.252.1.10' (ECDSA) to the list of known hosts.
ncn-m001:~/swallace # cray bss bootparameters list --hosts $(ssh ncn-s002 cat /etc/cray/xname) --format json > ncn-s002.json
Warning: Permanently added 'ncn-s002,10.252.1.11' (ECDSA) to the list of known hosts.
ncn-m001:~/swallace # cray bss bootparameters list --hosts $(ssh ncn-s003 cat /etc/cray/xname) --format json > ncn-s003.json
Warning: Permanently added 'ncn-s003,10.252.1.12' (ECDSA) to the list of known hosts.
ncn-m001:~/swallace # python3 /usr/share/doc/metal/scripts/patch-ceph-runcmd.py
BSS entry for x3000c0s26b0n0/ncn-s003 patched. …
```
> Added patching of data.json to remove storage-ceph-cloudinit.sh from runcmd of s001.

- background/cray_site_init_files.md
- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/prepare_configuration_payload.md
- introduction/differences.md
- operations/network/metallb_bgp/Update_BGP_Neighbors.md
CASMINST-2950
Changed ntp-pool to ntp-pools in all sample commands for "csi config init -ntp-pools".
> CASMINST-2950; change ntp-pool to ntp-pools in all sample commands

- 008-CSM-VALIDATION.md
This change adds documentation about a known issue for the FAS snapshot test that runs as part of the validation tests for HMS. It informs users that certain types of failures of the test_fas_snapshots_ncn-functional_remote-functional.tavern.yaml test can be safely ignored since the test will attempt to verify FAS snapshots that may have been previously captured on the system while in a bad state.
* Resolves CASMHMS-5234 in release/0.9.
Pasted the updated documentation into StackEdit to verify it renders correctly.
No risks.
> CASMHMS-5234 Update HMS CT test known issues section with FAS snapshot example csm-0.9

- install/redeploy_pit_node.md
CSM 1.2 renamed the network interfaces to indicate their function, users should also now be performing administrative functions via the CMN.
> CASMINST-3461 - DOCS: Update documentation to collect IP address of ncn-m002 bond0.cmn0

- install/collecting_bmc_mac_addresses.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/393. Cherry-picked from  for branch release/1.2.
> [Backport release/1.2] CASMTRIAGE-2549

- install/collecting_bmc_mac_addresses.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/393. Cherry-picked from  for branch release/1.1.
> [Backport release/1.1] CASMTRIAGE-2549

- upgrade/1.0/Stage_0_Prerequisites.md
- upgrade/1.0/Stage_2.md
- This ensures we don't re-run the storage cloud init
- This will re-run the enable ceph services script on reboot.
> CASMINST-3464 - Update storage node runcmds

- troubleshooting/known_issues/api_requests_sds.txt
This adds a troubleshooting guide for a problem that we've seen
several times recently where the Envoy container disallows
outbound requests with an error like
`TLS error: Secret is not supplied by SDS`.
> CASMPET-2610: Add troubleshooting doc for Envoy SDS failure

- operations/kubernetes/Disaster_Recovery_Postgres.md
Document how to recreate a completely failed instance of the cray-console-data postgres database.
* Resolves CASMCMS-7656
Documentation change only.  I worked through this process on Gamora so verified these steps work exactly as documented.
No risks to the release - documentation only.
> CASMCMS-7656: Add recovery instructions for console database.

- operations/kubernetes/Disaster_Recovery_Postgres.md
Document how to recreate a completely failed instance of the cray-console-data postgres database. Merge to main.
Original PR: https://github.com/Cray-HPE/docs-csm/pull/412
* Resolves CASMCMS-7656
Documentation change only. I worked through this process on Gamora so verified these steps work exactly as documented.
No risks to the release - documentation only.
> CASMCMS-7656: Add recovery instructions for console database - merge to main.

- operations/kubernetes/Disaster_Recovery_Postgres.md
Document how to recreate a completely failed instance of the cray-console-data postgres database. Merge to release/1.2.
Original PR: https://github.com/Cray-HPE/docs-csm/pull/412
* Resolves CASMCMS-7656
Documentation change only. I worked through this process on Gamora so verified these steps work exactly as documented.
No risks to the release - documentation only.
> CASMCMS-7656: Add recovery instructions for console database - merge to csm-1.2

- operations/kubernetes/Disaster_Recovery_Postgres.md
Document how to recreate a completely failed instance of the cray-console-data postgres database. Merging change to release/1.1 branch.
Original PR: https://github.com/Cray-HPE/docs-csm/pull/412
* Resolves CASMCMS-7656
Documentation change only. I worked through this process on Gamora so verified these steps work exactly as documented.
No risks to the release - documentation only.
> CASMCMS-7656: Add recovery instructions for console database - merge to csm-1.1.

- troubleshooting/interpreting_hms_health_check_results.md
Add known Mountain BMC Warning flag issue SDEVICE-3319 to HMS health check documentation for csm-1.0. This section was previously removed since SDEVICE-3319 is fixed in the Mountain BMC firmware version included with csm-1.0, however this issue may still cause test failures during upgrades to csm-1.0 from csm-0.9 if BMC firmware isn't also updated.
* Resolves CASMHMS-5244 in csm-1.0.
Verified that the Markdown documentation changes rendered successfully in StackEdit.
No risks.
> CASMHMS-5244 Add known Mountain BMC Warning flag issue to HMS health check documentation csm-1.0

- upgrade/1.0/Stage_0_Prerequisites.md
- upgrade/1.0/Stage_3.md
The prerequisites.sh script prints a warning about unmounting /mnt/pitdata, but that warning is no longer accurate after some script changes. This adds a note to the upgrade documentation that clarifies what the script actually does.
> CASMINST-3437: Add note to correct message printed by prerequisites.sh

- upgrade/update_management_network.md
Per Sean Lynn, this was mistakenly pulled into the csm-1.0 docs but should only be in the csm-1.2 docs. We ran into this during the creek csm-1.0 RC 3 upgrade. This PR just removes the mistakenly added lines from the update management network document.
> CASMINST-3460: Remove reference to CAN vrf in BGP from csm-1.0 docs

- upgrade/1.0/Stage_2.md
rescan ssh keys/fingerprints on all storage nodes after upgrade. It is blocking storage nodes reboot after 0.9 -> 1.0 upgrade
* Resolves [CASMINST-3462](https://connect.us.cray.com/jira/browse/CASMINST-3462)
* `drax`
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?yes
- Were continuous integration tests run? If not, why?no, this is doc only change
- Was upgrade tested? …
> rescan ssh keys on all storage nodes

- upgrade/1.2/scripts/upgrade/update-customizations.sh
Bifurcated CAN breaks the system domain out into multiple subdomains (cmn.<system_domain>, can.<system_domain>, chn.<system_domain>, nmn.<system_domain>, hmn.<system_domain>)
In order to have External DNS populate these zones correctly rather than just populating the top level <system_domain>, domain filters need to be specified via the External DNS `--domain-filter` command line option.
* Resolves CASMNET-1000
Tested on:
* Fresh install tested on wasp
Requires:
* Upgrade testing
> CASMNET-1000 - cray-externaldns is not populating the cmn and can DNS zones

- operations/boot_orchestration/Session_Templates.md
Adds a second boot set to the BOS session template example to reinforce the idea that a template can have more than one boot set.
* Resolves CASMCMS-7547
Tested on:
* NA, docs change only
None
> CASMCMS-7547: Add second boot set to the BOS session template example

- operations/validate_csm_health.md
With the added automation for csm-validate-health, the .md needs to be updated and cleaned up to call the goss suite for ncn-healthcheck.
CASMPET-5140 : DOCS: update section 1 of validate_csm_health.md
The following have already merged for the automation work, the above is for the doc changes needed to support the automation:
CASMPET-4673 Create a 'general k8s health' goss-test suite
CASMPET-5126 Create a ncn-healthcheck automated goss testing script
Resolves [issue id](issue link)
https://connect.us.cray.com/jira/browse/CASMPET-5140
Change will also be needed in main
Future work required by [issue id](issue link)
Documentation changes required in [issue id](issue link)
Merge with/before/after <insert PR URL here>
Tested with local markdown editor
Tested on:
Test description:
Were the …
> CASMPET-5140 1.2 : DOCS: update section 1 of validate_csm_health.md

- operations/CSM_product_management/Change_Passwords_and_Credentials.md
Add "Change Passwords and Credentials" procedure to the CSM 0.9 docs. For the procedures that are not currently present in markdown the _HPE Cray EX System Administration Guide 1.4 S-8001_ PDF. This is an overarching procedure to change passwords and credentials on a CSM system.
This is a continuation of the PR that has already been merged to CSM 0.9 branch: https://github.com/Cray-HPE/docs-csm/pull/479
> CASMHMS-5163: Add "Change Passwords and Credentials" procedure to the CSM 0.9 docs.

- 008-CSM-VALIDATION.md
This change adds a note to the HMS CT test documentation about known issue CASMHMS-5239 that can cause test failures due to BMCs being set to an unexpected state in HSM. These test failures can be safely ignored.
* Resolves CASMHMS-5247 in csm-0.9.
Verified that the Markdown changes rendered successfully.
No risks.
> CASMHMS-5247 Document HMS test known issue for BMCs in "On" states csm-0.9

- operations/validate_csm_health.md
- troubleshooting/interpreting_hms_health_check_results.md
This change adds a note to the HMS CT test documentation about known issue CASMHMS-5239 that can cause test failures due to BMCs being set to an unexpected state in HSM. These test failures can be safely ignored.
* Resolves CASMHMS-5247 in csm-1.0.
Verified that the Markdown changes rendered successfully.
No risks.
> CASMHMS-5247 Document HMS test known issue for BMCs in "On" states csm-1.0

- operations/validate_csm_health.md
Add note about how to get ceph status if ncn-s001 is down.
* Resolves [CASMTRIAGE-2693](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2693)
N/A
N/A
N/A
N/A
> Add note about how to get ceph status when ncn-s001 is down

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/security_and_authentication/Update_NCN_Passwords.md
Clarify the NCN password change procedure by splitting the Vault password update into a different section than the CFS session creation sections (either standalone password changes or through NCN personalization).
Also, add pod shell prompts to the commands run in a pod to set NCN passwords in Vault.
* Resolves [CASMTRIAGE-2690](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2690)
* Also requires changes to `release/1.2` and `main` branches.
N/A
N/A
- [ x ] Version number(s) incremented, if applicable
- [ x ] Copyrights updated
- [ x ] License file intact
- [ x ] Target branch correct
- [ x ] CHANGELOG.md updated
- [ x ] Testing is appropriate and complete, if applicable
- [ x ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
> CASMTRIAGE-2690: Clarify NCN Password Update Procedures

- install/install_csm_services.md
- update_product_stream/index.md
- upgrade/1.0.1/README.md
- upgrade/index.md
- upgrade/prepare_for_upgrade.md
- upgrade/update_management_network.md
This is the first draft of the csm-1.0.1 upgrade procedure. It involved making some small edits to the existing upgrade documents, so that there was a path for users to follow for 1.0.0 upgrades and 1.0.1 upgrades. 
For the 1.0.1 procedure itself, I essentially copied the 0.9.6 update procedure, removing the parts that do not apply to this upgrade. We can of course build off this skeleton if we want to add additional checks or update operations.
> CASMCMS-7673: First draft of csm-1.0.1 upgrade procedure

- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
CASMINST-3022: Explain how to set version string for k8s/ceph images when changing root password or ssh keys
Without setting the version string of the kernel, initrd, and squashfs there is an error when using set-sqfs-links.sh.
visual inspection
> CASMINST-3022: Explain how to set version string for k8s/ceph images when changing root password or ssh keys

- operations/validate_csm_health.md
Found during latest wasp 1.2 alpha 16 install
CASMPET-5149 DOCS: Add pit vs ncn info when running ncn-healthcheck
* Resolves [CASMPET-5149](https://connect.us.cray.com/jira/browse/CASMPET-5149)
* Change will also be needed in release/1.2
wasp
> CASMPET-5149 main : DOCS: Add pit vs ncn info when running ncn-healthcheck

- install/redeploy_pit_node.md
CASMINST-3500: Revised the section for configuring DNS and NTP on all management nodes except ncn-m001
Corrected command prompts since the commands are run on ncn-m001 in this part of the workflow.
> CASMINST-3500: Revised the section for configuring DNS and NTP on all management nodes except ncn-m001

- operations/node_management/NCN_Identify_Drives_Using_ledctl.md
- utilizes ledmon/ledctl for drive led beacon
* Resolves CASMPET-5066
* mug
Enabled and disabled the LED locator beacon on drives in the mug environment.  DHCW confirmed the drive beacons were turned on and off.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? n/a
- Were continuous integration tests run? If not, why? n/a
- Was upgrade tested? If not, why? n/a
- Was downgrade tested? If not, why? n/a
- Were new tests (or test issues/Jiras) created for this change? n/a
n/a
> CASMPET-5066 - Drive location doc

- background/ncn_boot_workflow.md
In the document to get the BMCs for the NCNs "/etc/dnsmasq.d/statics.conf" file has mentioned which infact is not working when the system is in NCN mode . This will work when the system is in PIT . 
Since the Command is running from NCNs , Updated the file name as /etc/hosts in stead of "/etc/dnsmasq.d/statics.conf".
> CASMINST-3450 : Update the file name to get the BMCs for the NCNs

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- scripts/operations/configuration/apply_csm_configuration.sh
- scripts/operations/configuration/replace_ssh_keys.sh
- scripts/operations/configuration/restore_ssh_keys.sh
Adds documentation for scripts to automate parts of the installation.  The three scripts allow admins to modify keys and deploy keys for passwordless ssh.
(Scripts PR can be found here: https://stash.us.cray.com/projects/CSM/repos/scripts/pull-requests/64/overview)
* Resolves CASMCMS-7473
Tested on:
* Mug
Tested each script with all parameter options
None
> CASMCMS-7473: Add documentation on automatically applying csm config

- install/deploy_management_nodes.md
- install/index.md
CASMINST-2949: Adjust management node firmware check/update while booted from PIT/LiveCD to reference HFP documentation
There is no check/update of the firmware for the PIT node.
For the other management nodes, this PR adds a reference to the HFP documentation for checking and updating without FAS.
> CASMINST-2949: Adjust management node firmware check/update while booted from PIT/LiveCD to reference HFP documentation

- 004-CSM-REMOTE-LIVECD.md
This change brings in 1.0 instructions to update docs and wars if installing via remote iso (was in the usb version).
* Resolves [CASMINST-3547](https://connect.us.cray.com/jira/browse/CASMINST-3547)
Just leveraged the usb instructions already there.
N/A
N/A
Low
> Add instructions to update docs and wars for remote iso

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
The install configuration scripts were moved to a new location and the documentation was not updated to reflect that.
* Resolves CASMCMS-7473
> CASMCMS-7473: Fix documented paths for configuration scripts

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/security_and_authentication/Update_NCN_Passwords.md
Clarify the NCN password change procedure by splitting the
Vault password update into a different section than the
CFS session creation sections (either standalone password changes
or through NCN personalization).
Add pod shell prompts to the commands run in a pod to set NCN
passwords in Vault.
* Resolves [CASMINST-3524](https://connect.us.cray.com/jira/browse/CASMINST-3524)
N/A
N/A
> CASMINST-3524: Clarify NCN password change procedure

- install/redeploy_pit_node.md
Adds a step to correct a bug in 1.0 NTP setup.
* Resolves CASMINST-3489
* Merge after https://github.com/Cray-HPE/metal-cloud-init/pull/10
* Merge after https://github.com/Cray-HPE/metal-cloud-init/pull/11
* Merge after https://github.com/Cray-HPE/metal-cloud-init/pull/12
* `#mug` ncn-m001 and ncn-w004
Low.  The module can still run as normal and this fixes up the NTP config.
> CASMINST-3489 fix ntp config on ncn-m001

- troubleshooting/interpreting_hms_health_check_results.md
This change adds a section to the HMS Health Check documentation about test failures that may or may not block system installations from proceeding.
* Resolves CASMINST-3512 in csm-1.2.
Viewed the new rendered Markdown documentation and verified that it looks as expected. Also confirmed that the new link on the page functions properly.
Low risk.
> CASMINST-3512 Document install blocking vs non-blocking HMS test failures csm-1.2

- operations/UAS_user_and_admin_topics/UAI_Network_Attachments.md
- operations/boot_orchestration/Compute_Node_Boot_Issue_Symptom_Duplicate_Address_Warnings_and_Declined_DHCP_Offers_in_Logs.md
- operations/network/customer_access_network/CAN_with_Dual-Spine_Configuration.md
- operations/network/customer_access_network/Troubleshoot_CAN_Issues.md
- operations/network/network_management_install_guide/aruba/management_network_configuration_example.md
- operations/network/network_management_install_guide/aruba/ncn_tcpdump.md
- operations/network/network_management_install_guide/aruba/reboot_pxe_fail.md
- operations/network/network_management_install_guide/mellanox/management_network_configuration_example.md
- operations/network/network_management_install_guide/mellanox/ncn_tcpdump.md
- operations/network/network_management_install_guide/mellanox/reboot_pxe_fail.md
- operations/node_management/Configuration_of_NCN_Bonding.md
- operations/node_management/Rebuild_NCNs.md
- operations/package_repository_management/Troubleshoot_Nexus.md
- operations/utility_storage/Troubleshoot_an_Unresponsive_S3_Endpoint.md
- scripts/CASMINST-2015.sh
- upgrade/1.2/Stage_1.md
- upgrade/1.2/scripts/upgrade/ncn-upgrade-cloud-init.sh
Changes instances of `vlan00*` to the new names.
* Resolves CASMINST-3416
N/A
Low.
> CASMINST-3416 change vlan00* names to bond0.*mn0 names

- install/clear_gigabyte_cmos.md
- install/deploy_management_nodes.md
- install/set_gigabyte_node_bmc_to_factory_defaults.md
- operations/network/management_network/update_management_network_firmware.md
De-references bundled PIT firmware and points users to the HFP package included with a Shasta release.
* Resolves MTL-1558
n/a 
n/a
Low
> MTL-1558 reference HFP firmware location

- operations/node_management/Find_Node_Type_and_Manufacturer.md
Several commands were missing the `--format` option, causing the commands to fail.
* Resolves [STP-3061](https://connect.us.cray.com/jira/browse/STP-3061)
N/A
Gamora
N/A
None.
> STP-3061 (1.1): Commands missing --format option

- operations/node_management/Find_Node_Type_and_Manufacturer.md
Several commands were missing the `--format` option, causing the commands to fail.
* Resolves [STP-3061](https://connect.us.cray.com/jira/browse/STP-3061)
N/A
Gamora
N/A
None.
> STP-3061 (main): Commands missing --format option

- operations/node_management/Find_Node_Type_and_Manufacturer.md
Several commands were missing the `--format` option, causing the commands to fail.
* Resolves [STP-3061](https://connect.us.cray.com/jira/browse/STP-3061)
N/A
Gamora
N/A
None.
> STP-3061 (1.0): Commands missing --format option

- install/redeploy_pit_node.md
Adds the HMN Unbound DNS server into the BSS metadata so it is picked up by the BMC DNS script.
* Resolves CASMINST-3514
* Resolves CASMTRIAGE-2735 
* `#wasp`
Low.
> add HMN unbound DNS server to handoff command so it is used by BMCs

- upgrade/1.2/scripts/upgrade/ncn-upgrade-cloud-init.sh
1.2 has an updated set of `run_cmds`.  This aligns the upgrade path to use those
scripts and gets rid of non-existent ones.
* Resolves CASMINST-3597
* Relates to CASMINST-3593
Validated the changes are valid JSON.  This plugs into an existing workflow known to work.
Low.
> CASMINST-3597-CASMINST-3593 update run_cmds

- install/prepare_compute_nodes.md
Improves documentation for configuring Apollo 6500 iLO and the switch port it is connected to.
* Resolves [CASMINST-3554](https://connect.us.cray.com/jira/browse/CASMINST-3554)
NA
NA
Low
> CASMINST-3554 Update Apollo 6500 iLO prep

- upgrade/1.0.1/README.md
- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/README.md
- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/install-hotfix.sh
- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/scripts/lib.sh
- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/scripts/metal-lib.sh
- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/scripts/mini-install.sh
- upgrade/lib/validation/README.md
This change brings the updated CSM 1.2 bootcode from MTL-1535 into 1.0.1 upgrades.
Yes; 0.9, 1.0, and forwards compatible with 1.2.
* Resolves [MTL-1545](https://connect.us.cray.com/jira/browse/MTL-1545)
* Merge with/after https://github.com/Cray-HPE/csm/pull/84
Testing of the new content was already done, testing of this hotfix in the context of this repo was not done.
_Are there known issues …
> MTL-1545 1.2.bootfixes

- upgrade/1.0/Stage_1.md
- upgrade/1.0/scripts/ceph/lib/k8s-scale-utils.sh
- upgrade/1.0/scripts/upgrade/list-cephfs-clients.sh
Re-introduce scale down of user namespace/slurm
* Resolves [https://connect.us.cray.com/jira/browse/CASMTRIAGE-2756](CASMTRIAGE-2756)
Not tested, but simple revert
Not tested, but simple revert
N/A
Low
> Include user namespace to include slurm in scale down and up during stage 0 upgrade

- install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml
This change reflects corresponding change in lib/setup-nexus.sh, brought in
with commit 53e3472a643d0c3a67582184b7c724b718b3c516. For compatibility with
csm-1.0, image folders located under dtr.dev.cray.com are copied to the root folder
of bootstrap nexus (temporary nexus instance running on pit node). Same is done for
quay.io/skopeo/stable:latest.
(https://connect.us.cray.com/jira/browse/CASMINST-3604?filter=-1)
* `surtur`
Run yapl pipeline with modified pipeline file. Ensured that images are synchronized as expected.
Risks are minimal since this is alpha release
> CASMINST-3604 copy images into root folder in bootstrap nexus

- install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml
Fixing a typo introduced into YAPL pipeline script with https://github.com/Cray-HPE/docs-csm/pull/607/
* Resolves CASMIST-3628
* `surtur`
Uploaded modified script and re-run yapl pipeline with `--no-cache` option
Low risk - alpha release
> CASMINST-3628 BREAK/FIX: install CSM service script is failed

- upgrade/1.2/Stage_1.md
- upgrade/1.2/scripts/upgrade/verify-k8s-nodes-upgraded.sh
Update k8s upgrade version to 1.20.13
* Resolves [CASMINST-3653](https://connect.us.cray.com/jira/browse/CASMINST-3653)
craystack
craystack
```
ncn-m002:~ # kubectl get nodes
NAME       STATUS   ROLES                  AGE     VERSION
ncn-m001   Ready    control-plane,master   5m34s   v1.20.13
ncn-m002   Ready    control-plane,master   8m12s   v1.20.13
ncn-m003   Ready    control-plane,master   5m33s   v1.20.13
ncn-w001   Ready    <none>                 5m35s   v1.20.13
ncn-w002   Ready    <none>                 5m34s   v1.20.13
ncn-w003   Ready    <none>                 5m35s   v1.20.13
```
Low
> Bump version of K8S version to 1.20.13 for upgrade in 1.2

- install/bootstrap_livecd_remote_iso.md
The bootstrap_livecd_remote_iso.md procedure creates a duplicate mount of the PITDATA volume on /mnt/pitdata for compatibility with the prepare_site_init.md procedure.
SLES 15 SP3 flat out rejects a second mount of a device that is already mounted, a bind mount should be used instead.
* Resolves [CASMINST-3655](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3655)
* Tested during `hela` install.
Created bind mount
```
hela-ncn-m001-pit:~ # mount -v --bind /var/www/ephemeral/ /mnt/pitdata/
mount: /var/www/ephemeral bound on /mnt/pitdata.
```
The expected contents is visible on the new path
```
hela-ncn-m001-pit:~ # ls /mnt/pitdata
configs  cray-site-init-1.12.3-1~pr_96~20211202233331.1887911.x86_64.rpm  csm-1.2.0-alpha.31  csm-1.2.0-alpha.31.tar.gz  data  lost+found  prep  static
```
> CASMINST-3655 - Remote ISO installs should use bind mount for /mnt/pitdata

- operations/system_management_health/Access_System_Management_Health_Services.md
- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
- operations/validate_csm_health.md
CASMINST-3495: For CSM 1.2 Update info about troubleshooting Prometheus alerts
Related to CSM 1.0 version
https://github.com/Cray-HPE/docs-csm/pull/625
Documentation only change.
> CASMINST-3495: For CSM 1.2 Update info about troubleshooting Prometheus alerts

- upgrade/1.0/scripts/ceph/lib/ceph-upgrade-rgws.sh
- upgrade/1.0/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
- Fixes issue with the rgw only deploying on 3 nodes.  It will now deploy across all storage nodes.
- Fixes issue with a mon process redeploy which only works on nodes 1,2,3.  This has been removed and the second command in the will loop and include this now.
* Resolves CASMINST-3645
* mug - command syntax only (waiting on fanta for full testing)
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? 
- Were continuous integration tests run? If not, why? N/A
- Was upgrade tested? If not, why? 
- N/A
> CASMINST-3645 - Fixes to the 1.0 storage upgrade to address clusters larger than 3

- operations/hardware_state_manager/Add_an_NCN_to_the_HSM_Database.md
- operations/node_management/Add_a_Standard_Rack_Node.md
- operations/node_management/Move_a_Standard_Rack_Node.md
- operations/system_layout_service/Dump_SLS_Information.md
- operations/system_layout_service/Load_SLS_Database_with_Dump_File.md
Updated the get_token functions that used python2 in the CSM documentation to now use jq instead, as python2 is no longer available on NCNs.
Also moved step 11 in the `Add a Standard Rack Node` procedure earlier in the procedure, and removed the command to discover a river chassis BMC as those don't exist.  
* Resolves [CASMTRIAGE-2715](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2715) …
> (CSM 1.0) CASMTRIAGE-2715: Use jq in place of python2 in get_token functions

- operations/hardware_state_manager/Add_an_NCN_to_the_HSM_Database.md
- operations/node_management/Add_a_Standard_Rack_Node.md
- operations/node_management/Move_a_Standard_Rack_Node.md
- operations/system_layout_service/Dump_SLS_Information.md
- operations/system_layout_service/Load_SLS_Database_with_Dump_File.md
Updated the get_token functions that used python2 in the CSM documentation to now use jq instead, as python2 is no longer available on NCNs.
Also moved step 11 in the `Add a Standard Rack Node` procedure earlier in the procedure, and removed the command to discover a river chassis BMC as those don't exist.  
* Resolves [CASMTRIAGE-2715](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2715) …
> (CSM 1.2) CASMTRIAGE-2715: Use jq in place of python2 in get_token functions

- operations/hardware_state_manager/Add_an_NCN_to_the_HSM_Database.md
- operations/node_management/Add_a_Standard_Rack_Node.md
- operations/node_management/Move_a_Standard_Rack_Node.md
- operations/system_layout_service/Dump_SLS_Information.md
- operations/system_layout_service/Load_SLS_Database_with_Dump_File.md
Updated the get_token functions that used python2 in the CSM documentation to now use jq instead, as python2 is no longer available on NCNs.
Also moved step 11 in the `Add a Standard Rack Node` procedure earlier in the procedure, and removed the command to discover a river chassis BMC as those don't exist.
Changes from this PR are missing from the main branch: https://github.com/Cray-HPE/docs-csm/pull/372
* Resolves …
> (main) CASMTRIAGE-2715: Use jq in place of python2 in get_token functions

- upgrade/1.0/scripts/ceph/ceph-upgrade.sh
This was making an unused call to the ceph cluster which will not work
on nodes that do not have admin creds
* Resolves CASMINST-3647
> CASMINST-3647 - fix enable ceph services

- upgrade/1.0/scripts/ceph/ceph-upgrade.sh
This change ensures ceph commands can run on non-mon nodes such that haproxy can be properly configured and goss tests can run on nodes greater than 3.
* Resolves [CASMINST-3681](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3681)
Ran the code:
```
ncn-s001:~/bklein # ./foo.sh
Ensuring ceph commands can be executed on all storage nodes
Copying client.admin key to: ncn-s004
ceph.client.admin.keyring
```
...now tests succeed:
```
ncn-s004:~ # GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/suites/ncn-upgrade-tests-storage.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..........
Total Duration: 37.579s
Count: 10, Failed: 0, Skipped: 0
```
...and re-running the script to setup haproxy now succeeds:
```
ncn-s004:~ # tail …
```
> Ensure ceph commands can run on all storage nodes

- install/prepare_site_init.md
Update commands in documentation to load images from the correct path now that dtr.dev.cray.com images are no longer being shipped.
* Resolves [CASMINST-3692](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3692)
* Change will also be needed in `csm` to update the generator
* Merge with `https://github.com/Cray-HPE/csm/pull/262`
* `surtur`
New documentation followed, updated generator used to generate PALs SealedSecret.
> CASMINST-3692 - Remove dtr.dev.cray.com references from prepare_site_init.md process

- upgrade/1.0.1/Stage_3.md
Add note for 1.0.1 upgrade to validate the kubeadm upgrade command has started pods with their new images.
* Resolves [CASMINST-3697](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3697)
Ran the command on fanta.
* `fanta`
Ran the command on fanta.
Low
> Add step to verify kubeadm upgrade has succeeded

- upgrade/1.0.1/Stage_3.md
Adds note to wait and retry if  ncn-upgrade-k8s-worker.sh postgres cluster check fails
Also add link to Postgres troubleshooting if above does not resolve the issue
* Resolves [CASMINST-3702](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3702)
Based on what was seen on fanta during 0.9.6 -> 1.0.1 upgrade.
NA …
> CASMINST-3702 1.0.0-v2 : Add note where ncn-upgrade-k8s-worker.sh is run to re-try in 30m if postgres check fails

- operations/node_management/Clear_Space_in_Root_File_System_on_Worker_Nodes.md
- troubleshooting/known_issues/kubernetes_node_rootFS_out_of_space.md
This is to address a known bug and not users filling up the volume.
* Resolves CASMPET-5207
*N/A
N/A
> CASMPET-5207 - Document fixing space issue on k8s nodes

- troubleshooting/known_issues/kubernetes_node_rootFS_out_of_space.md
This only addresses fixing the know bug and not users filling up the space.
* Resolves CASMPET-5207
* N/A
N/A
> CASMPET-5207 - Fix for space issues on k8s nodes for known bug

- scripts/operations/xnamevalidation.sh
This adds the xnamevalidation script, which can be used to enable or disable spire xname validation on a cluster.
* Resolves [CASMPET-5203](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5203)
* wasp
Validated that the appropriate workloads were created and deleted, that the opa policy and spire settings were updated, and that customizations.yaml was properly saved back to the site-init secret.
- Were continuous integration tests run? If not, why? N, does not exist for this change
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N
Adding new workloads can take a large amount of …
> CASMPET-5203 Add xname validation toggle script

- upgrade/1.0.1/Stage_2.md
Add note to verify BGP is healthy before starting NCN image upgrades in stage 2.
* Resolves [CASMINST-3708](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3708)
N/A
N/A
N/A
Low
> Add note to check BGP before first PXE boot

- operations/boot_orchestration/Edit_the_iPXE_Embedded_Boot_Script.md
The `Edit_the_iPXE_Embedded_Boot_Script.md` document uses an incorrect command to load in the edited cray-ipxe-bss-ipxe ConfigMap which causes cray-ipxe to fail to build the binary on restart.
* Resolves [CASMINST-3711](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3711)
* `hela`
* Set the maxattempts parameter to 10 in the ConfigMap
* Validated that cray-ipxe successfully built a new ipxe.efi binary 
* Validated that the new binary contained the amended maxattempts parameter.
> CASMINST-3711 - Correct documentation for editing bss.ipxe script

- install/redeploy_pit_node.md
Mostly minor linting of the redeploy PIT node page. 
The only non-trivial change is that I moved the reminder about backing up conman console logs to an earlier step and provided commands to do it. This way those logs will be backed up along with the other stuff in the prep directory, using the existing backup steps. I've been meaning to make this change for a while, because especially for our internal installs it is useful to preserve those logs.
https://github.com/Cray-HPE/docs-csm/pull/675
https://github.com/Cray-HPE/docs-csm/pull/676
None other than visual inspection of the changes through GitHub.
Very low risk.
- [N/A] Version number(s) incremented, if applicable
- [N/A] Copyrights updated
- [N/A] CHANGELOG.md updated
- [N/A] [HPC Product …
> CASMINST-3714: Linting of redeploy pit node / deploy final NCN page

- operations/kubernetes/TDS_Lower_CPU_Requests.md
- upgrade/1.0.1/README.md
- upgrade/1.0.1/scripts/k8s/tds_lower_cpu_requests.sh
New script to lower CPU requests for several services which have unnecessarily high CPU request for three worker node systems.
* Resolves [CAST-28531](https://jira-pro.its.hpecorp.net:8443/browse/CAST-28531)
twister
* `twister`
Ran on twister.  
Before:
```
Resource           Requests           Limits
--------           --------           ------
cpu                54605m (85%)       432 (675%)
memory             73980585728 (27%)  732824456448 (271%)
Resource           Requests            Limits
--------           --------            ------
cpu                61342m (95%)        503250m (786%)
memory             102818069760 (38%)  653225176320 (242%)
Resource           Requests           Limits
--------           --------           ------
cpu                48650m (76%)       445650m …
```
> Add script to lower cpu requests for tds systems

- upgrade/1.2/scripts/upgrade/update-customizations.sh
A few more changes were made to customizations.yaml in the release/1.2 branch of the csm repo without making matching changes to update-customizations.sh for upgrade.   This brings update-customizations.sh back up-to-date with the latest customizations.yaml.
* Resolves CASMINST-3726
I ran update-customizations.sh against a 1.0 customizations.yaml and then compared the results against a 1.2 customizations.yaml without these changes to verify that the correct changes were made.
- [n/a] Version number(s) incremented, if applicable
- [n/a] CHANGELOG.md updated
- [n/a] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
> CASMINST-3726:  Sync update-customizations.sh with recent changes to customizations.yaml

- background/ncn_boot_workflow.md
- install/deploy_management_nodes.md
- install/index.md
- install/install_csm_services.md
- install/redeploy_pit_node.md
- operations/conman/ConMan.md
- operations/conman/Log_in_to_a_Node_Using_ConMan.md
- operations/validate_csm_health.md
This PR is correcting issues that I saw during an install of hela a while ago. Much of this PR consists of typical MitchLint(TM) of the install docs, as well as minor changes to clarify or add emphasis. Other than those types of changes, the main things in this PR are:
* Explain why the Barebones Boot Test is important and that skipping it is not recommended
* Warn that running HMS tests concurrently on different nodes can produce false failures.
* Add a jq command to directly extract the first-master-node field from data.json in the "deploy management nodes" procedure
* Remove redundant execution of "kubectl get nodes" command in "deploy management nodes" procedure
* Move "wait 15 minutes after csm install" to be an explicit step at the end of the CSM install procedure.
* Since the …
> CASMINST-3475: Minor corrections, clarifications, revisions, and linting of fresh install docs

- upgrade/0.9/csm-0.9.6/scripts/validate_versions.sh
validate_versions script for 0.9.6 upgrade does not handle multiple istiod pods appropriately. This PR
fixes the issue. 
* Resolves [CASMINST-3728]
* `wasp`
Tested the changed kubectl command in wasp, and verified that it produced the unique version string.
Low. The script already does the similar thing for hms-redfish-translation-service, so it should work
as expected.
> Fixes CASMINST-3728: handle multiple istiod pods in validate_versions script

- install/create_ncn_metadata_csv.md
- install/wipe_ncn_disks_for_reinstallation.md
CASMINST-3509: Correct wipe_ncn_disks_for_reinstallation
Several commands were added that had been used on the test on hela and the overall flow of the steps was adjusted to be more explicit upon which type of node the command should be run.
Also, indicate that install/create_ncn_metadata_csv.md will be pulling data from the SHCD HMN tab.
> CASMINST-3509 PR 1.2 Correct wipe_ncn_disks_for_reinstallation

- install/create_ncn_metadata_csv.md
- install/wipe_ncn_disks_for_reinstallation.md
CASMINST-3509: Correct wipe_ncn_disks_for_reinstallation
Several commands were added that had been used on the test on hela and the overall flow of the steps was adjusted to be more explicit upon which type of node the command should be run.
Also, indicate that install/create_ncn_metadata_csv.md will be pulling data from the SHCD HMN tab.
> CASMINST-3509-main Correct wipe_ncn_disks_for_reinstallation

- install/prepare_site_init.md
Added note to indicate that `secrets-reencrypt.sh` and `secrets-seed-customizations.sh` should not be run until directed to by the `prepare_site_init.md` document.
* Resolves [CASMINST-3094](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3094)
> CASMINST-3094 - Added note to meta/init.sh step of prepare_site_init.md

- operations/validate_csm_health.md
CASMINST-3025: Correct UAI image references for SP2 and registry.local instead of dtr.dev.cray.com
> CASMINST-3025: Correct UAI image references for SP2 and registry.local

- operations/validate_csm_health.md
CASMINST-3025: Correct UAI image references for SP3 and registry.local instead of dtr.dev.cray.com
> CASMINST-3025: Correct UAI image references for SP3 and registry.local 

- upgrade/1.2/scripts/upgrade/prerequisites.sh
CASMINST-3749: BREAK/FIX: prerequisites.sh is installing wrong version of cray/proxy2 precache image
CASMINST-3750: BREAK/FIX: prerequisites.sh did not catch when the PRECACHE_NEXUS_IMAGES step failed
CASMINST-3752: BREAK/FIX: cray cps deployments list at the end of prerequisites.sh should only run if CPS is installed
* Resolves [CASMINST-3749](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3749)
* Resolves [CASMINST-3750](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3750)
* Resolves [CASMINST-3752](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3752)
Tested the new code on drax (and shandy to validate cps test works when cps installed)
* `drax/shandy`
Tested portions of the script w/out running complete script on existing systems.
Low
> Several fixes to prerequisites.sh

- .github/workflows/backport.yaml
- Jenkinsfile.github
- LICENSE
- Makefile
- install/scripts/check_lvm.sh
- operations/hardware_state_manager/scripts/backup_smd_postgres.sh
- operations/system_layout_service/scripts/backup_sls_postgres.sh
- operations/system_layout_service/scripts/restore_sls_postgres_from_backup.sh
- runLint.sh
- scripts/CASMINST-2015.sh
- scripts/patch-ceph-runcmd.py
- toc.sh
- upgrade/1.0/scripts/upgrade/CASMINST-2689-lib.sh
- upgrade/1.0/scripts/upgrade/prerequisites.sh
- upgrade/1.1/scripts/upgrade/csm-service-upgrade.sh
- upgrade/1.1/scripts/upgrade/join-spire-on-storage.sh
- upgrade/1.1/scripts/upgrade/update-customizations.sh
- upgrade/1.1/scripts/upgrade/update-spire-entries.sh
License headers need to be updated to cover copyright year 2022, and fix headers where they are missed/malformed.
* Resolves [CASMINST-3761](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3761)
Testing is generally not available for documentation. However, CI/CD checks completed, which indicates that license headers are what they are expected to be, and syntax is correct at least in Jenkinsfile and Makefile.
> CASMINST-3761 Fix license headers [release/1.1]

- install/scripts/csm_services/steps/5.setup_nexus.yaml
Updated line 36 of nexus_check_pod to include a | grep -v Completed. This is necessary to ignore the nexus-init pods that stay in a Completed state. Similar PR for the setup-nexus.sh script in https://github.com/Cray-HPE/csm/pull/339.
_Summarize what has changed. This is a critical bug fix. I added a grep -v Completed to the nexus_check_pod variable in the script. This is needed to ignore the init pods that stay in a Completed state.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? Not Applicable
* Resolves CASMINST-3762 https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3762
* Change will also be needed in …
> CASMINST-3762 updated nexus_check_pod to exclude init pods in completed state

- upgrade/1.2/scripts/upgrade/update-customizations.sh
The FQDNs that are on NMN or HMN are on a separate load-balancer subnet than the actually NMN/HMN subnets so they need to have a different subdomain:  nmnlb and hmnlb.
This adds those subdomains to the domain filter and the ingressgateway cert.  It also fixes some of the FQDNs specified in customizations for auth, api, hmcollector, etc.
* Resolves CASMINST-3727
* Merge with https://github.com/Cray-HPE/csm/pull/356
* `drax`
Ran the update-customizations.sh and verified that the FQDNs are added/changed correctly.
No risks.  It is broken the way that it is now.
> CASMINST-3727: Fix nmn/hmn subdomains that should be nmnlb/hmnlb

- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/scripts/metal-lib.sh
This code is removing entries before ensuring new entries are properly
added.  Make it such that the code doesn't care if the drive is
currently marked bootable.  It will be marked bootable later.
* Resolves CASMINST-3791
* Tested on fanta and surtur with CRAY entries that were marked bootable, and not marked bootable.
> CASMINST-3791: be agnostic about whether an entry is marked bootable

- upgrade/1.2/README.md
- upgrade/1.2/Stage_1.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Need to flip the order of image upgrades such that ceph goes first, so newer buckets/secrets are available to configure s3fs when the K8S cloud-init runs.
* Resolves [CASMTRIAGE-2889](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2889)
N/A
N/A
N/A
Low
> Add back step to create new buckets, flip k8s/ceph image upgrade order

- install/deploy_management_nodes.md
CASMINST-3733 - updated line 514 of deploy management nodes to unique section number 3.3.4 instead of duplicate 3.3.3
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_ This is a simple section renumbering to remove a duplicate section number from the docs
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ backwards compatible
* Resolves [CASMINST-3733](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3733)
* Change will also be needed in `N/A`
* Future work required by `N/A`
* Documentation changes required in `This is the docs change
* Merge …
> CASMINST-3733 - updated line 514 of deploy management nodes to unique section number

- RELEASE_NOTES.md
- troubleshooting/known_issues/kube_multus_pod_in_ImagePullBackOff.md
Doc a known issue for csm-1.0.x regarding kube-multus IPBO issue
* Resolves [CASMPET-5264](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5264)
* Change will also be needed in NA (not an issue for csm-1.2)
* Documentation changes required NA
Issue was encountered and fixed on odin and loki.
* odin, loki
Verified the IPBO issue and followed doc'ed steps to resolve.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? NA
- Were continuous integration tests run? If not, why? NA
- Was upgrade tested? If not, why? NA
- Was downgrade tested? If not, why? NA
- Were new tests …
> CASMPET-5264 1.0.x : Doc: failed to pull and unpack image "docker.io/nfvpe/multus:v3.1"

- background/ncn_operating_system_releases.md
- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- install/install_csm_services.md
- operations/UAS_user_and_admin_topics/Troubleshoot_UAS_Issues.md
- operations/UAS_user_and_admin_topics/UAI_Host_Node_Selection.md
- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
- operations/kubernetes/Configure_kubectl_Credentials_to_Access_the_Kubernetes_APIs.md
- operations/kubernetes/Retrieve_Cluster_Health_Information_Using_Kubernetes.md
- operations/node_management/Rebuild_NCNs.md
- operations/resiliency/Restore_System_Functionality_if_a_Kubernetes_Worker_Node_is_Down.md
- troubleshooting/kubernetes/Troubleshoot_Kubernetes_Node_NotReady.md
The output of the "kubectl get nodes" command changed in csm-1.2. This updates the example output in the docs to reflect that. No content changes.
I just added another commit which does some linting of the "Install CSM services" page, and adds commands to retain the log file from the yapl tool.
> CASMINST-3835: Update kubectl get nodes output for csm-1.2

- upgrade/1.2/scripts/upgrade/update-customizations.sh
Fixes cut-n-paste error in update-customizations.sh for cray-oauth2-proxies sealed-secrets
* Resolves CASMINST-3854
* `drax`
Ran update-customizations.sh and checked the resulting customizations.yaml to make sure the sealed_secrets that were references for customer-access and customer-high-speed were correct.
No known issues
> CASMINST-3854:  Fix sealed_secrets update for cray-oauth2-proxies

- install/deploy_final_ncn.md
This adds the commands needed to install the testing RPMs on m001 after being redeployed from the PIT node. This will happen automatically during NCN customization, but often that is not done until after the CSM health validation procedure, and these RPMs are necessary for that.
NOTE that these commands will need to be updated after [CASMINST-3810](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3810) is resolved (I've made a comment to this effect in that ticket as well).
> CASMINST-3807: Manually install/upgrade RPMs on ncn-m001 after PIT redeploy

- upgrade/1.0.1/scripts/upgrade/add_pod_priority.sh
- upgrade/1.0.10/README.md
The script to apply pod priorities is not called on the 1.0.10 upgrade path, this change adds that.  Also, when applying to etcd clusters, the script needs a tweak to apply to the correct section in the etcdcluster crd.
* Resolves [CASMINST-3856](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3856)
tested on fanta
```
ncn-m001:/usr/share/doc # kubectl get po -n services cray-bss-etcd-8xplplwvpv -o yaml | grep prior
f:priorityClassName: {}
priority: 1000000
priorityClassName: csm-high-priority-service
```
* `fanta`
Made the script change and ran it -- bss etcd pods came up with pod priorities
Low
> Add pod priority application to 1.0.10 upgrade path

- install/deploy_management_nodes.md
- operations/validate_csm_health.md
Add mention of new required SW_ADMIN_PASSWORD variable when running the LiveCD preflight checks and ncn-health-checks.
backwards compatible
* Resolves [CASMPET-3996](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-3996)
* Merge after https://github.com/Cray-HPE/csm-testing/pull/176
For testing see: https://github.com/Cray-HPE/csm-testing/pull/176
Low risk
> (CSM 1.2) CASMPET-3996: Add mention of new required SW_ADMIN_PASSWORD variable when running the LiveCD preflight checks and ncn-health-checks.

- install/deploy_management_nodes.md
- operations/validate_csm_health.md
Add mention of new required SW_ADMIN_PASSWORD variable when running the LiveCD preflight checks and ncn-health-checks.
backwards compatible
* Resolves [CASMPET-3996](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-3996)
* Merge after https://github.com/Cray-HPE/csm-testing/pull/176
For testing see: https://github.com/Cray-HPE/csm-testing/pull/176
Low risk
> (main) CASMPET-3996: Add mention of new required SW_ADMIN_PASSWORD variable when running the LiveCD preflight checks and ncn-health-checks.

- operations/security_and_authentication/Manage_Sealed_Secrets.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/upgrade/prerequisites.sh
The stage0 instructions are missing the step to generate the 5 sealed secrets that get added to customizations.yaml in 1.2.    The steps to do that regeneration need to have the extracted tarball which happens in prerequisites.sh.  Therefore, all of the customizations update steps were added into prerequisites.sh.
The manual steps documented in stage0 were replaced by a placeholder for updating SLS for now installers don't miss doing that.   There is a tool being implemented in CASMNET-693 that will be added to the instructions or to the automation in place of this placeholder.
Also, while referencing https://github.com/Cray-HPE/docs-csm/blob/release/1.2/operations/security_and_authentication/Manage_Sealed_Secrets.md, I found a couple of minor things to be fixed.
* Resolves CASMINST-3841 …
> CASMINST-3841:  Move update-customizations.sh into prerequisites.sh and add sealed secret generation

- install/bootstrap_livecd_usb.md
`csi` throws a nonsensical error if the target specified in `csi pit populate pitdata` does not exist.
This documentation change ensures that the intended target directories are created along with the other required directories.
The error handling of `csi` will also be enhanced to correctly report when the target directory does not exist.
* Resolves [CASMINST-3866](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3866)
Tested directories are created as expected with new mkdir syntax
```
mkdir: created directory '/mnt/pitdata'
mkdir: created directory '/mnt/pitdata/admin'
mkdir: created directory '/mnt/pitdata/prep'
mkdir: created directory '/mnt/pitdata/configs'
mkdir: created directory '/mnt/pitdata/data' …
```
> CASMINST-3866 - Copy the NCN Artifacts step is failing

- upgrade/1.0.1/Stage_0_Prerequisites.md
- upgrade/1.0.10/README.md
Adds instructions to back up BSS data before performing a system upgrade.
This enables the restoration of this data should the BSS data get lost during the upgrade.
* Resolves [CASMINST-3873](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3873)
Verified given command produces the expected output.
* mug
Executed documented command and verified resulting file.
- Were continuous integration tests run? N/A   If not, why? doc changes
- Was upgrade tested?  N/A   If not, why? doc changes
- Was downgrade tested?  N/A   If not, why? doc changes
- Were new tests (or test issues/Jiras) created for this change? No
This is a low risk change to documentation.
> Add instructions to back up BSS data before performing an upgrade.

- upgrade/1.2/Stage_2.md
- upgrade/1.2/scripts/k8s/apply-coredns-pod-affinity.sh
We added anti-affinity for coredns for fresh installs, but missed it on the 1.2 upgrade path.
* Resolves [CASMINST-3938](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3938)
* `vshasta`
```
ncn-m001-072d00d9:/home/bklein # ./apply-coredns-pod-affinity.sh
Applying pod anti-affinity to coredns pods
deployment.apps/coredns configured
```
```
ncn-m001-072d00d9:/home/bklein # kubectl get po -n kube-system coredns-7c5b77c849-9wkpq -o json | jq '.spec.affinity'
{
"podAntiAffinity": {
"requiredDuringSchedulingIgnoredDuringExecution": [
{
"labelSelector": {
"matchExpressions": [
{
"key": "k8s-app",
"operator": "In",
"values": [
"kube-dns"
]
}
]
},
"topologyKey": "kubernetes.io/hostname"
}
]
}
}
```
Low
> Add script to apply anti-affinity to coredns pods on upgrade

- install/bootstrap_livecd_remote_iso.md
On some installs using remote ISO PIT nodes, the parted command used to prepare a temporary filesystem fails because the disk is in use by a volume group and/or raid array. This PR adds the steps needed to remediate this issue if it occurs. I tested them on my install of wasp, which hit this issue.
> CASMINST-3932: Add instructions to workaround parted failure in bootstrap remote ISO procedure

- upgrade/1.2/Stage_0_Prerequisites.md
Adds instructions to back up BSS data before performing a system upgrade.
This enables the restoration of this data should the BSS data get lost during the upgrade.
* Resolves [CASMINST-3873](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3873)
Verified given command produces the expected output.
* mug
Executed documented command and verified resulting file.
- Were continuous integration tests run? N/A   If not, why? doc changes
- Was upgrade tested?  N/A   If not, why? doc changes
- Was downgrade tested?  N/A   If not, why? doc changes
- Were new tests (or test issues/Jiras) created for this change? No
This is a low risk change to documentation.
> Add instructions on how to back up BSS data to the upgrade process.

- upgrade/1.2/Stage_0_Prerequisites.md
Adds instructions to back up BSS data before performing a system upgrade.
This enables the restoration of this data should the BSS data get lost during the upgrade.
* Resolves [CASMINST-3873](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3873)
Verified given command produces the expected output.
* mug
Executed documented command and verified resulting file.
- Were continuous integration tests run? N/A   If not, why? doc changes
- Was upgrade tested?  N/A   If not, why? doc changes
- Was downgrade tested?  N/A   If not, why? doc changes
- Were new tests (or test issues/Jiras) created for this change? No
This is a low risk change to documentation.
> Add instructions to back up BSS data before starting an upgrade.

- install/wipe_ncn_disks_for_reinstallation.md
1.2 - CASMTRIAGE-2929: Fix spelling errors for description of the dmsetup command in 1.2 
Fix spelling errors -  'wil' -> 'will'; 'comand' -> 'command' in dmsetup command description.
CASMTRIAGE-2929
N/A
Low
N/A
> CASMTRIAGE-2929: Fix dmsetup description spelling error in 1.2

- install/wipe_ncn_disks_for_reinstallation.md
1.0 - CASMTRIAGE-2929: Fix dmsetup syntax error in main
Fix syntax error - remove "-" in 'dmsetup -ls' command line.
CASMTRIAGE-2929
N/A
Low
N/A
> CASMTRIAGE-2929: Fix dmsetup syntax error in 1.0

- install/wipe_ncn_disks_for_reinstallation.md
Master - CASMTRIAGE-2929: Fix dmsetup syntax error in main
Fix syntax error - remove "-" in `dmsetup -ls' command line.
CASMTRIAGE-2929
N/A
Low
N/A
> CASMTRIAGE-2929: Fix dmsetup syntax error in main

- operations/UAS_user_and_admin_topics/Configure_a_Broker_UAI_Class.md
- operations/UAS_user_and_admin_topics/Troubleshoot_Broker_SSSD_Cant_Use_sssd_conf.md
- operations/UAS_user_and_admin_topics/Troubleshoot_UAI_Authentication_Issues.md
- operations/UAS_user_and_admin_topics/User_Access_Service_UAS.md
Add a Troubleshooting sub-section to the UAS/UAI Guide to describe how to reconfigure the Pod Security Policy for the `uas` namespace so that Broker UAIs can be configured correctly for SSSD.  Also add a step to the _Configure a Broker UAI_ section of that document to put back `/etc/sssd/conf.d` after `/etc/sssd/sssd.conf` has been mounted as a volume.
This change is backwards compatible.
* Resolves [CASMUSER-2940](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2940)
Reproduced the original problem described in the CAST and then play tested this documentation using virtual shasta.
- Were continuous integration tests run? If not, why? N/A
- Was upgrade tested? If …
> CASMUSER-2940 - Add Troubleshooting for Broker UAI SSSD Configuration Issues

- install/create_hmn_connections_json.md
Update image path for the hms-shcd-parser-image to reflect changes from CASM-2670.
* Resolves CASMINST-3939
* Mug
_How were the changes tested and success verified? If schema changes …
> Update image path for SHCD parser image

- operations/index.md
- operations/system_layout_service/Add_an_alias_to_a_service.md
Document procedure to add a DNS alias for an existing service definition such as pbs_service.
* Resolves [CASMNET-1020](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1020)
* `hela`
Followed procedure and verified the the DNS alias was successfully added.
> CASMNET-1020 - Document procedure to add a DNS alias or correct DNS entries in SLS

- upgrade/1.2/scripts/upgrade/create_rgw_buckets.sh
We missed porting this script from 1.0 -- needed in 1.2 as well.
* Resolves [CASMINST-3948](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3948)
Script is well tested in 1.0
* `fanta`
Manually copied to continue with fanta upgrade.
Low
> Add create_rgw_buckets.sh script to 1.2 upgrade path

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Adding to the Troubleshoot Postgres a case where after the reinit (to fix lag), the member remains stopped. 
In Pawsey prod environment this was seen and was a result of one member running out of disk space prior to the reinit.
The reinit did cleanup the WAL files but there were remaining pg_internal.init.* files that were truncated when the file system filled up; these needed to be cleaned up so that the stopped member would restart.
This change also includes a minor change to remove lag number from Leader line in patronictl list output.
This change also pulls in some formatting changes that were done on the release/1.2 branch to improve readability.
Is this change is backwards compatible
* Resolves [CASMPET-5292](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5292) for CAST-28984 …
> CASMPET-5292 1.0 : DOCS: Add case for postgres cluster member stopped after reinit

- .github/workflows/link-checker.yaml
Check links directly in md files, thus making it a commit status check.
* Resolves [CASMINST-3961](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3961)
This adds a new workflow to repository, invoked on each push. Running workflow represents a valid test.
Test run on push reveal many broken links (which is expected, we need to go over the list and fix them):
https://github.com/Cray-HPE/docs-csm/runs/5069996488?check_suite_focus=true
Risk is minimal as this is a non-mandatory github commit status check only.
> CASMINST-3961 Enable markdown link checking on docs-csm [release/1.2]

- .github/workflows/link-checker.yaml
Check links directly in md files, thus making it a commit status check.
* Resolves [CASMINST-3961](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3961)
This adds a new workflow to repository, invoked on each push. Running workflow represents a valid test.
Test run on push reveal many broken links (which is expected, we need to go over the list and fix them):
https://github.com/Cray-HPE/docs-csm/runs/5069996488?check_suite_focus=true
Risk is minimal as this is a non-mandatory github commit status check only.
> CASMINST-3961 Enable markdown link checking on docs-csm [main]

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
This adds in a change that got missed in a carry forward from 1.0.
Fixes 1.2 ceph node image upgrades for cluster larger than 3.
* Resolves CASMINST-3954
* in 1.0 code
> CASMINST-3954 - Fix 1.2 ceph node upgrade

- operations/CSM_product_management/Configure_Keycloak_Account.md
1.0 - CASMTRIAGE-2944: Incorrect Security and Authentication link in 1.0
Fix "Validate CSM Health" link.
Update link to "Security and Authentication"
CASMTRIAGE-2944
N/A
Low
N/A
> CASMTRIAGE-2944: Incorrect Security and Authentication link in 1.0

- operations/CSM_product_management/Configure_Keycloak_Account.md
main - CASMTRIAGE-2944: Incorrect Security and Authentication link in main
Fix "Validate CSM Health" link.
Update link to "Security and Authentication"
CASMTRIAGE-2944
N/A
Low
N/A
> CASMTRIAGE-2944: Incorrect Security and Authentication link in main

- install/deploy_management_nodes.md
- operations/network/metallb_bgp/Update_BGP_Neighbors.md
The `mellanox_set_bgp_peers.py` script assumes the prefix length of the CAN network is `/24` which may not be correct for all users environments.
This script is deprecated in CSM 1.2 in favour of using CANU to configure BGP so this ticket updates the CSM 1.0 docs with a warning and workaround for this issue.
* Resolves [CASMNET-1135](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1135)
* Discovered and workaround tested on the training system `brook`
Ran script after workaround was applied, verified BGP configuration was present and correct on both spine switches.
> CASMNET-1135 - Document mellanox_set_bgp_peers.py assumption that the CAN subnet is a /24

- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-k8s-worker.sh
Lumi saw this -- it caught the error but the script marched on.  This fix is specific to 1.0 (different path in progress for 1.2 upgrade).
* Resolves [CASMINST-3844](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3844)
N/A
N/A
N/A
Low
> Change etcd check for number of pods to halt upgrade

- upgrade/1.0.1/scripts/upgrade/prerequisites.sh
During the pawsey upgrade to csm-1.0, we observed that the upgrade script incorrectly recorded the CPS nodes, which resulted in CPS being deployed on all of the worker nodes. The fix is just a small change to the jq query being used when generating the list of CPS nodes.
[csm-1.2 PR](https://github.com/Cray-HPE/docs-csm/pull/853)
I tested the updated command on pawsey and verified that it worked as expected.
Low risk. The fix is very straightforward.
- [N/A] Version number(s) incremented, if applicable
- [N/A] CHANGELOG.md updated
- [N/A] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
> CASMINST-3965: Correctly record cps nodes before csm upgrade

- introduction/differences.md
Added a note about the removal of the unused CFS v1 API.
* Resolves CASMCMS-7287
* Merge after Cray-HPE/csm#450
See Cray-HPE/csm#450
> Add cfs v1 api removal in differences.md

- install/configure_administrative_access.md
- operations/firmware/FAS_Admin_Procedures.md
- operations/firmware/Update_Firmware_with_FAS.md
- operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md
This adds instructions for locking/unlocking NodeBMCs of NCNs when locking/unlocking NCNs. Locking NCNs as well as their BMCs will prevent unintended FAS actions from affecting NCNs
* Resolves [CASMHMS-5346](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5346)
* loki
The new procedure was tested by running it on Loki.
- Were continuous integration tests run? If not, why? N/A
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A
- Were new tests (or test issues/Jiras) created for this change? N/A
None
> Add NodeBMCs to locking procedures for locking/unlocking NCNs

- upgrade/1.2/scripts/k8s/upgrade_control_plane.sh
Add istio-ca as api audience for kube-api on upgrade (already handled in fresh install)
* Resolves [CASMINST-3978)](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3978)
Fanta
* `fanta`
Ran subset of script on fanta, saw kube-api pods restart with correct audience.
Low
> Add istio-ca api audience on upgrade path for kube-api

- upgrade/scripts/get_mountain_cmm_firmware_versions.py
- upgrade/update_management_network.md
The changes made in this PR correct problems first observed by me last year during the SSI install of hela, and then more recently on the Pawsey customer upgrade.
This PR corrects a number of errors on the "update management networks" procedure for the upgrade to csm-1.0. Most notably it fixes some commands which are incorrect and do not work as given, as well as supplying some commands which are absent from the page.
The procedure to get the Mountain CMM firmware has been replaced with a Python script, rather than having the user run a large number of commands manually.
In addition to those major changes this PR also reorganizes the procedure to make it clearer, fixes some broken links, and does other linting.
All changes are to that single page.
None.
I tested the changes (most notably …
> CASMINST-3458: Fix broken "update management networks" procedure

- index.md
- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/collect_mac_addresses_for_ncns.md
- install/collecting_ncn_mac_addresses.md
- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- install/install_csm_services.md
- introduction/index.md
- troubleshooting/index.md
- update_product_stream/index.md
- upgrade/1.2/README.md
* [CASMINST-3936](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3936): In csm-1.2, if there are any workarounds needed for the release, they will be embedded into the docs. As such, there will not be a need for the csm-install-workarounds RPM. This PR removes references to it (and the workaround breakpoints) from the docs. And because I cannot resist, there was also some linting.
* [CASMINST-3911](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3911): I also pulled in a commit which takes care of [CASMINST-3911](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3911), reducing the chance of errors when completing the BMC NTP/DNS section by replacing manual commands with a bash loop.
* [CASMINST-3937](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3937): Revert the …
> CASMINST-3936, CASMINST-3911, CASMINST-3937

- install/redeploy_pit_node.md
Rather than have the user manually execute 3 commands for each NCN BMC (a total of at least 24 commands), this instead uses a single Bash loop. In addition, we have had multiple problems where users thought they were supposed to ssh to the other NCNs to run the scripts. This change should prevent that.
> CASMINST-3911: Change BMC NTP/DNS steps into a loop, to reduce errors and manual steps

- upgrade/1.2/scripts/upgrade/update-customizations.sh
This fixed a bug in the upgrade process for oauth2-proxies. The hostAliases had the wrong domain name for the discovery url leading to oauth2 proxies failing to start. 
* Resolves [CASMINST-3982](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3982)
The test was run locally by running the script against a customization 1.0 file and checking the output to make sure it was the correct output for oauth2-proxies.
No known risks
> CASMINST-3982: Fix the host aliases for oauth2-proxies

- upgrade/1.2/scripts/upgrade/update-customizations.sh
Adds the nexus admin credential sealed secret to the cray-nexus chart at the time of an upgrade.
Resolves CASMINST-3980 
Tested by manually running the script against the current customizations and then feeding the output into manifestgen.
Verified the output had the expected sealed secret under the cray-nexus chart (details in the bug).
> CASMINST-3980 Add the nexus admin credential sealed secret

- upgrade/1.2/Stage_0_Prerequisites.md
At this point in the upgrade, the config-data bucket will have been created, but the s3fs mount point won't be available until m001 is booted into his new image.  So let's use cray artifacts to push the backup to S3 instead of S3fs.
* Resolves [CASMINST-3996](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3996)
```
ncn-m001:~ # cray artifacts create config-data bss-backup-2022-02-11.json bss-backup-2022-02-11.json
artifact = "bss-backup-2022-02-11.json"
Key = "bss-backup-2022-02-11.json"
ncn-m001:~ # cray artifacts list config-data
[[artifacts]]
Key = "bss-backup-2022-02-11.json"
LastModified = "2022-02-14T17:45:29.624000+00:00"
ETag = "\"ae5757bfd9d6f4e0b4bba457e4d9b26a\""
Size = 76401
StorageClass = "STANDARD"
[artifacts.Owner]
DisplayName = ""
ID = "STS"
```
* `drax`
Ran the cli …
> Backup bss data using cray cli instead of s3fs mount point

- upgrade/1.2/scripts/k8s/update_kubeapi_service_issuer.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-master.sh
Need to reconfig the un-upgraded api server on m001 before upgrading workers, as istiod can't start with the 1.0 config.
* Resolves [CASMINST-4006](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4006)
Updated on drax and fixed the issue, tested new script in vshasta
* `drax`
Update on drax and fixed the issue, tested new script in vshasta
Low
> Add step to reconfig m001 kube-api service issuer before worker upgrades

- upgrade/1.2/scripts/k8s/upgrade_control_plane.sh
We need the new control plane images pulled with the artifactory prefix to match what's being precached and in nexus.  Need to update the config map used during upgrade to point to the same.
* Resolves [CASMINST-4009](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4009)
Tested manually on drax
* `drax`
Manually updated the configmap and the upgrade control plane script found the images.
Low
> Update kubeadm image repository prior to control plane upgrade

- operations/validate_csm_health.md
DOC update to provide detailed steps for removing a failed velero backup
* Resolves [CASMPET-5327]([CASMPET-5327](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5327))
* Change will also be needed in `release/1.2 and main`
> CASMPET-5327 1.0 : DOCS: Update Velero backup docs for the known failure for CAST-29171

- operations/validate_csm_health.md
DOC update to provide detailed steps for removing a failed velero backup
* Resolves [CASMPET-5327]([CASMPET-5327](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5327))
* Change will also be needed in `release/1.2 and release/1.0`
> CASMPET-5327 main : DOCS: Update Velero backup docs for the known failure for CAST-29171

- upgrade/1.0.1/scripts/k8s/reinit-postgres.sh
- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-k8s-worker.sh
- upgrade/1.0.11/scripts/k8s/reinit-postgres.sh
- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-k8s-worker.sh
Adds reinit-postgres.sh which is an independent script that can be run to re-init any postgres cluster.
Adds automated re-init process to the existing ncn-upgrade-k8s-workers.sh script.
* If a postgres clusters is found to have lagging member(s), an attempt will be made to reinit the member(s).
* If needed, a reinit is done for any cluster except sma; sma re-init can take hours so this is better handled outside of the upgrade if found to not be healthy.
* In addition, the retry login has been modified to check the health twice and reinit if the first attempt finds lag.
The upgrade script will still exit if after two attempts any of the clusters are not healthy (no leader, lag, etc)
This change is only needed for csm 1.0.x (1.0.1 & 1.0.11)
_Is this change backwards incompatible, backwards …
> CASMPET-5318 1.0 : Automate reinit of cluster members found to be lagging in csm 1.0 ncn-upgrade-k8s-worker.sh

- upgrade/1.0.11/README.md
- upgrade/1.0.11/Stage_5.md
Provide CVE description and verification steps post 1.0.11 upgrade for:
* CVE-2022-0185: Linux kernel buffer overflow/container escape 
* CVE-2021-4034: pwnkit: Local Privilege Escalation in polkit's pkexec
* Resolves [CASMINST-4003](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4003)
> CASMINST-4003: Update 1.0.11 patch instructions for kernel and polkit CVE fixes

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
Simplify the search path for rpms in the tarball.
* Resolves [CASMINST-4037](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4037)
```
rax-ncn-m001-pit:/var/www/ephemeral/csm-1.0.11-alpha.6 # find ${CSM_RELEASE}/rpm/ -name "goss-servers*.rpm" | sort -V | tail -1
/var/www/ephemeral/csm-1.0.11-alpha.6/rpm/embedded/cray/csm/sle-15sp2/noarch/noarch/goss-servers-1.6.28-20210722162456_b3376c5.noarch.rpm
```
* `drax`
Changing the path worked for the find command
Low
> Fix path to goss-servers rpm (and others) during livecd bootstrap

- upgrade/1.0.11/README.md
- upgrade/1.0.11/Stage_5.md
Provide CVE description and verification steps post 1.0.11 upgrade for:
- [CVE-2022-23307](https://nvd.nist.gov/vuln/detail/CVE-2022-23307) - critical vulnerability in chainsaw used in log4j 1.2.x.
- [CVE-2022-23305](https://nvd.nist.gov/vuln/detail/CVE-2022-23305) - affects log4j 1.x when it is configured with JDBCAppender.
- [CVE-2022-23302](https://nvd.nist.gov/vuln/detail/CVE-2022-23302) - affects log4j 1.x when it is configured with JMSSink.
- [CVE-2021-4104](https://nvd.nist.gov/vuln/detail/CVE-2021-4104) - affects log4j 1.x when it is configured with JMSAppender.
* Resolves [CASMINST-4004](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4004)
> CASMINST-4004: Update CSM-1.0.11 patch instructions for log4j changes

- install/deploy_final_ncn.md
- operations/network/management_network/collect_data.md
- operations/network/management_network/validate_shcd.md
- operations/network/management_network/validate_switch_configs.md
- operations/network/upgrade_planning.md
- operations/system_configuration_service/Configure_BMC_and_Controller_Parameters_with_scsd.md
- operations/validate_csm_health.md
* Add CSM health validation remediation step for cfs-state-reporter test failures on storage nodes
* Correct command syntax errors caused by using "fancy" quote characters
* Removed outdated warning about running some health checks during CSM upgrades
* Include path to set_ssh_keys.py script on Configure_BMC_and_Controller_Parameters_with_scsd.md
* Improve Deploy Final NCN procedure by using previously-defined environment variables and other small tweaks
* Linting (of course)
> CASMINST-4070: Doc fixes based on csm-1.2.0-alpha.70 surtur install

- operations/validate_csm_health.md
Remediation steps for velero backup test don't permanently delete a backup, need to use velero command instead (not kubectl).
* Resolves [CASMINST-4059](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4059)
Ran the velero delete on surtur, the backup did not come back.
* `surtur`
Manually ran the new remediation step and it worked.
None/Low
> Change velero backup test remediation to really delete PartiallyFailed backups

- operations/network/management_network/load_saved_switch_config.md
require the switch to reboot after config is applied.
this is required when adding/removing a port from a VRF.
CASMNET-1152
drax
> CASMNET-1152

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Hardening for update-customizations.sh section of prerequisites.sh.
CASMINST-3926 was opened when update-customizations.yaml was run on an empty customizations.yaml file.   This allows us to catch the error when the site-init file doesn't exist rather than moving on with the empty customizations.yaml.
* Resolves CASMINST-3926
* `fanta`
Tested by running the fixed section of prerequisites.sh on fanta with changes that trigger failures in the three piped commands.   Also ran the success case with valid secrets.
Low risk.  Just adds hardening against failure cases.
> CASMINST-3926: Handle case where secrets don't exist

- operations/network/external_dns/Ingress_Routing.md
Updated old references to keycloak gatekeeper in Ingress Routing to properly reflect oauth2 changes. Also updated references to Ansible variables to customizations.yaml.
* Resolves [CASMPET-5347](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5347)
> CASMPET-5346: Update Ingress_Routing.md

- upgrade/1.2/scripts/upgrade/update-customizations.sh
If a Customer selects the CHN for Bifurcated CAN (User traffic comes in over the HSN), then MetalLB needs to peer with the edge routers (generally Arista) to distribute CSM service endpoints to to the customer site.
This adds logic to update-customizations.sh to add the edge router peer to the metallb config map if it exists in SLS.
* Resolves item #3 in CASMNET-1157
Tested by running on hela (with CHN) and fanta (without CHN).
I ran the update-customizations.yaml in the following scenarios:
* on hela (CHN) with customizations.yaml that did not have `spec.network.metallb`
* on hela (CHN) with customizations.yaml from the previous run. (effectively 1.2 -> 1.2 upgrade)
* on …
> CASMNET-1157: Add peer for CHN edge router if it exists

- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
When a new blade is added to the system, the sysadmin will want to boot
these new nodes. This docuentation update checks if a BOS Session
template uses the node_list to specify names explicitly. If so, the
new nodes need to be added into the Session template, so they can be
booted using that template.
(cherry picked from commit 1a7a16a4467dadb0fb3baf351c182aeb9a0e5582)
* Resolves CASMTRIAGE-2988
* Hela
Tested to see the commands worked.
Low.
> CASMTRIAGE-2988: Instructions on adding xnames to BOS session templates

- operations/power_management/Prepare_the_System_for_Power_Off.md
This change fixes a command line instruction which incorrectly told the
user to tee the contents of stdout to the file `sat.capture-state`. When
running `sat bootsys shutdown --stage capture-state`, no information is
expected to be written to stdout, and the state capture is instead
written to S3. Thus the `tee` pipeline should be removed as not to
confuse the admin.
> CRAYSAT-1345: Remove unnecessary "| tee sat.capture-state"

- operations/power_management/Prepare_the_System_for_Power_Off.md
This change improves the "Prepare the System for Power Off" procedure
to clarify how SAT is used in this process
- Additional context was added to the "Prerequisites" section to
indicate the reason for linking the user to other pages and
documents.
- The order of steps 2 and 3 was reversed, as a SAT authentication
token may be necessary for using `sat status`.
- Additional context was added to step 2 (previously step 3) in order
to indicate the reason for linking the user to other pages and
documents. The text of this change is identical to that of the
change noted above.
- The link to the "Authenticate an Account with the Command Line" page
was removed due to it not being relevant to step 2 (previously step
3.)
> CASMINST-4039: Clarify power off preparation procedure

- operations/power_management/Power_On_Compute_and_IO_Cabinets.md
- operations/power_management/Shut_Down_and_Power_Off_the_Management_Kubernetes_Cluster.md
This change removes a link to the "System Security and Authentication"
page in the Prerequisites sections of the k8s power off and compute/IO
cabinet power off instructions in relation to authenticating SAT. This
link does not contain information on SAT and so is not relevant to that
instruction.
> CRAYSAT-1346: Remove link to "System Security and Authentication" page

- operations/node_management/Reboot_NCNs.md
Update documentation to make it clear that the `CASMINST-2015.sh` needs to be run after any NCN workaround to avoid the scenario where there are duplicate IPs.
Note that the script is incorrectly named, the original ticket for this issue is CASMINST-2105
* Resolves [CASMTRIAGE-3013](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3013)
* `odin`
> CASMTRIAGE-3013 - Clarify use of CASMINST-2015.sh workaround script during NCN reboot.

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
The correct container image is present in the storage node image, however
the restore of the containers overwrites this and corrupts a layer of the image.
* Resolves CASMINST-4099
* Drax
Ran the command on drax-ncn-s002.
> CASMINST-4099 - Fix issue with ceph container image on node rebuild

- upgrade/1.2/scripts/k8s/update_kubeapi_istio_ca.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-master.sh
kube-api needs to be reconfigured on upgrade of a master node to include the isito-ca audience prior to worker upgrades when istio ingress pods get restarted.
* Resolves [CASMINST-4101](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4101)
Ran the new script and calling code on drax.
* `drax`
Ran the new script and calling code on drax.
Low
> Add istio-ca audience during upgrade to api server manifest prior to worker upgrades

- upgrade/1.2/Stage_0_Prerequisites.md
Backing up BSS data to vbis bucket that exists in 1.0 (when prereq runs).
* Resolves [CASMINST-4093](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4093)
```
ncn-m001:~/UpgradeLogs # cray artifacts create vbis bss-backup-2022-02-22.json  bss-backup-2022-02-22.json
artifact = "bss-backup-2022-02-22.json"
Key = "bss-backup-2022-02-22.json"
```
* `drax`
Ran the command with vbis bucket
Low
> Backup BSS data in a bucket available in 1.0 during prereq step

- upgrade/1.2/scripts/strimzi/kafka-prereq.sh
- upgrade/1.2/scripts/upgrade/csm-service-upgrade.sh
The paths were set incorrect in the previous PR. This fixes that issue. pushd/popd is also being added to the kafka-prereq run since that script references paths based on that directory instead of using the full paths to files.
> CASMINST-4100 Fix strimzi script paths

- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
Minor change to DVS steps after discussing with DVS writer/team.
The reference to the DVS Admin Guide isn't necessary. The authoritative instructions for verifying that CFS finished successfully should be in the CSM docs, not in the DVS (now COS) guide. It references a Shasta 1.4.1, guide, which is no longer relevant. Step 20 is also the only place in this procedure that CFS is even mentioned. None of the earlier steps say to start CFS.
* Resolves [STP-3127](https://jira-pro.its.hpecorp.net:8443/browse/STP-3127)
N/A
N/A
N/A
None.
> STP-3127: removed innacurate step and stale DVS guide reference

- operations/network/dns/Troubleshoot_Common_DNS_Issues.md
Correction to commands in docs for cray-dns unbound. Old troubleshooting command does not use correct container name for cray-dns.unbound.
* Resolves CASMINST-4118 [(issue link)](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4118) …
> CASMINST-4118

- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-common.sh
- upgrade/1.0.1/scripts/upgrade/prerequisites.sh
- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-common.sh
- upgrade/1.0.11/scripts/upgrade/prerequisites.sh
Cleanup normal ssh keygen messages that look like errors, make missing doc rpm obviously an error
* Resolves [CASMINST-4124](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4124)
```
ncn-m001:~ # ./foo.sh
Updating SSH keys for node ncn-m001 with IP address of 10.248.5.11
Updating SSH keys for node ncn-m002 with IP address of 10.248.2.52
Updating SSH keys for node ncn-m003 with IP address of 10.248.3.25
Updating SSH keys for node ncn-s001 with IP address of 10.248.2.208
Updating SSH keys for node ncn-s002 with IP address of 10.248.6.35
Updating SSH keys for node ncn-s003 with IP address of 10.248.3.120
Updating SSH keys for node ncn-w001 with IP address of 10.248.1.172 …
```
> Cleanup ssh keygen noise that is confusing

- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
The wipe commands don't care if a device is mounted or not.  They
will wipe it regardless.
Modify the code so the list of devices to wipe doesn't include the
USB.  This borrows code that is in dracut for the same reason.
While here, reduce the number of lines needed to figure out which
device is the USB device.  (IMO, this code doesn't need to care about
whether the USB device is mounted or not, but it's a smaller code
change to leave that logic in place.  And it's harmless.)
* Resolves [CASMINST-4125](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4125)
* `redbull`
Tested the snippets on redbull, but echoing the commands instead of executing them.
No additional risk.
> CASMINST-4125: never wipe USB devices

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/sls/csm_1_2_upgrade/sls_updates.py
- upgrade/1.2/scripts/sls/sls_updater_csm_1.2.py
Bugfixes:
* Previous BGP ASN defaults included an RFC-specified "documentation" ASN.  This was fixed in the SLS upgrade as well as CSI, but during upgrade from CSM 1.0 to CSM 1.0 this new default caused issues if it was not matched with MetalLB configs.  This fix retains the <= CSM 1.0 defaults for upgraded systems.
* During upgrade the kube-api and CAN switch reservations were removed very early on in the process to prevent gaps in sequential IPs from occuring.  This, unfortunately caused NCN IP's to shift around by one to three IP addresses during upgrade which caused overlapping IPs just during the upgrade process.  This overlap caused a race condition.  This fix removes kube-api and CAN switch IPs much later in the process to help retain NCN IPs and prevent the race condition.
Doc …
> CASMNET-1164 and CASMTRIAGE-3007 SLS upgrade BGP and IP overlap fixes

- install/deploy_management_nodes.md
CASMINST-1673 has been fixed so we no longer need the note about having to reset the terminal after running the livecd-preflight-check.
* Related to CASMINST-1673
> CASMINST-1673: Remove note about having to reset the terminal after livecd-preflight test

- upgrade/1.0.11/Stage_5.md
This will allow the validation to occur from any master, not just the original master where the tarball existed
* Resolves [CASMINST-4150](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4150)
```
ncn-m001:/usr/share/doc # pdsh -w $(grep -oP 'ncn-\w\d+' /etc/hosts | sort -u | tr -t '\n' ',') "uname -a"
ncn-s002: Linux ncn-s002 5.3.18-24.99-default #1 SMP Sun Jan 23 19:03:51 UTC 2022 (712a8e6) x86_64 x86_64 x86_64 GNU/Linux
ncn-s001: Linux ncn-s001 5.3.18-24.99-default #1 SMP Sun Jan 23 19:03:51 UTC 2022 (712a8e6) x86_64 x86_64 x86_64 GNU/Linux
ncn-s003: Linux ncn-s003 5.3.18-24.99-default #1 SMP Sun Jan 23 19:03:51 UTC 2022 (712a8e6) x86_64 x86_64 x86_64 GNU/Linux
ncn-m001: Linux ncn-m001 5.3.18-24.99-default #1 SMP Sun Jan 23 19:03:51 UTC 2022 (712a8e6) x86_64 x86_64 x86_64 …
```
> Change validation step to use /etc/hosts instead of script in tarball

- install/wipe_ncn_disks_for_reinstallation.md
The issue was seen when testing NCN Remove/Add and was also noted many times in slack as triage questions.
There is no need to stop the raids as they will be wiped and rebuilt as part of the existing process.
During the testing, we continued after hitting these errors and thus determined that stopping the raids is not needed and just adds confusion.
* Resolves [CASMPET-5375](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5375) (Was originally MTL-1627)
* Change will also be needed in main and 1.0
mug 
During testing of Remove/Add …
> CASMPET-5375 1.0 : DOCS : how to free up /dev/md/AUX, BOOT, ROOT and SQFS so the RAIDs can be stopped cleanly

- install/wipe_ncn_disks_for_reinstallation.md
The issue was seen when testing NCN Remove/Add and was also noted many times in slack as triage questions.
There is no need to stop the raids as they will be wiped and rebuilt as part of the existing process.
During the testing, we continued after hitting these errors and thus determined that stopping the raids is not needed and just adds confusion.
* Resolves [CASMPET-5375](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5375) (Was originally MTL-1627)
* Change will also be needed in main and 1.0
mug 
During testing of Remove/Add …
> CASMPET-5375 1.2 : DOCS : how to free up /dev/md/AUX, BOOT, ROOT and SQFS so the RAIDs can be stopped cleanly

- install/wipe_ncn_disks_for_reinstallation.md
The issue was seen when testing NCN Remove/Add and was also noted many times in slack as triage questions.
There is no need to stop the raids as they will be wiped and rebuilt as part of the existing process.
During the testing, we continued after hitting these errors and thus determined that stopping the raids is not needed and just adds confusion.
* Resolves [CASMPET-5375](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5375) (Was originally MTL-1627)
* Change will also be needed in 1.2 and 1.0
mug 
During testing of Remove/Add …
> CASMPET-5375 main : DOCS : how to free up /dev/md/AUX, BOOT, ROOT and SQFS so the RAIDs can be stopped cleanly

- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-k8s-master.sh
- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-k8s-master.sh
Change order to update bss last when promoting a new master, so if any steps fail, re-running the script will get back into the RECONFIGURE step.
* Resolves [CASMTRIAGE-3053](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3053)
Simple order change to what we know is necessary
No new code, just order flip
N/A
Low
> Update first master in bss after new master is promoted

- upgrade/1.0.1/scripts/upgrade/add_pod_priority.sh
- upgrade/1.0.11/scripts/upgrade/add_pod_priority.sh
Ensure we have 3 etcd members before applying pod priorities
* Resolves [CASMINST-4136](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4136)
```
ncn-m001-ee11a084:~/bklein # ./add_pod_priority.sh
validated etcd cluster: cray-bos-etcd has three running members...
validated etcd cluster: cray-bss-etcd has three running members...
validated etcd cluster: cray-hbtd-etcd has three running members...
validated etcd cluster: cray-hmnfd-etcd has three running members...
validated etcd cluster: cray-uas-mgr-etcd has three running members...
Creating csm-high-priority-service pod priority class
priorityclass.scheduling.k8s.io/csm-high-priority-service configured
Patching cray-bss deployment in services namespace
deployment.apps/cray-bss patched
.
.
```
* `vshasta`
Ran on vshasta
Low
> Ensure we have 3 etcd members before applying pod priorities

- operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
The vlan004 and vlan007 interfaces have changed in 1.2.  
This updates the vlan interface validation that is part of the post boot rebuild process.
*After further review - it was determined that these IP checks for vlan004 and vlan007 can be removed from the 1.2 docs*
* Resolves [CASMPET-5376](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5376)
* Documentation changes required NA
mug
Verified the following which is now in sync with the docs
{code}
ncn-w006:~ # NODE=ncn-w006
ncn-w006:~ # dig +short ${NODE}.hmn
10.254.1.20
ncn-w006:~ # ip …
> CASMPET-5376 : DOCS: Update Power Cycle and Rebuild for vlan interface naming change

- upgrade/1.2/scripts/k8s/promote-initial-master.sh
The cert refresh join script runs fine during automation/manual runs, but not via cron since it doesn't know where the kubernetes config file is (non standard location).
* Resolves [CASMTRIAGE-3068](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3068)
```
W0307 17:23:01.641059 4090429 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[upload-certs] Using certificate key:
f49d64cca4647a383e9781a08872e58578de3de6b4d9c20e866a495c937c8d55
W0307 17:23:01.884750 4090489 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
```
* …
> Point token cert refresh script at kube config file for run via cron

- troubleshooting/known_issues/craycli_403_forbidden_errors.md
After deleting an LDAP federation or group, we must re-run the keycloak localize job to pick up the change.  This PR adds those steps.
* Resolves [CASMINST-4158](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4158)
Ran this process on tab when triaging CASMTRIAGE-3055.
* `tab`
Ran these steps on tab.
Low
> Add keycloak localize job re-run after deleting an ldap federation/group

- operations/power_management/Prepare_the_System_for_Power_Off.md
Removes one of the two methods for finding running BOS sessions before power-down.  The primary way listed to do this was unreliable do to bugs.
* Resolves CASMTRIAGE-3065
* NA
NA
None
> CASMTRIAGE-3065: Removed unreliable method of finding running BOS sessions (1.1)

- install/bootstrap_livecd_remote_iso.md
The `bootstrap_livecd_remote_iso.md` document has the admin copy the session typescript log to `/mnt/pitdata/prep/admin` however `/mnt/pitdata` is not mounted at this time when performing a remote ISO install.
The correct directory path is `/var/www/ephemeral/admin/prep`
* Resolves [CASMINST-4184](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4184)
* `hela`
Tested new procedure, session log present in the expected location. This procedure is already present in the CSM 1.2 documentation.
> CASMINST-4184 - Copy of typescript log uses incorrect directory path

- upgrade/1.0.1/README.md
- upgrade/1.0.10/README.md
- upgrade/1.0.11/README.md
- upgrade/index.md
Modified the upgrade docs to clearly state the required CSM levels for the different upgrade paths.
> CASMINST-4187: Clarify minimum CSM versions for different upgrade paths

- operations/validate_csm_health.md
The title pretty much says it all. Two character fix.
> Fix formatting issue in Velero remediation instructions

- operations/node_management/Reboot_NCNs.md
Adds documentation to the procedure for rebooting NCNs, to check node status in CFS and reset error-counts if necessary so that nodes configure after the reboot.
* CASMTRIAGE-2998
* NA - docs only
NA - docs only
None
> CASMTRIAGE-2998: Add docs for resetting CFS error counts prior to rolling reboots

- operations/node_management/Reboot_NCNs.md
Adds documentation to the procedure for rebooting NCNs, to check node status in CFS and reset error-counts if necessary so that nodes configure after the reboot.
Manual backport to 1.2
* CASMTRIAGE-2998
* NA - docs only
NA - docs only
None
> [Backport release/1.2] CASMTRIAGE-2998: Add docs for resetting CFS error counts prior to rolling reboots

- upgrade/1.0.11/upgrade_troubleshooting.md
This adds workaround information for a bug that can invalidate CFS configurations on upgrade to 1.0.11.
* Resolves CASMTRIAGE-3070
* NA
NA, docs only
None
> CASMTRIAGE-3070: Add troubleshooting section for CFS in 1.0.11

- background/ncn_boot_workflow.md
Fix disk boot order command in 1.2 install docs deploy final ncn step 1 sub-step 2 here https://github.com/Cray-HPE/docs-csm/blob/release/1.2/background/ncn_boot_workflow.md#setting-order. 
First command as currently written gives no output. Correct one is below it with its output.
pit 2022-03-09 05:03:28 /var/www/ephemeral/prep/admin # efibootmgr | grep cray | tee /tmp/bbs2
pit 2022-03-09 05:03:32 /var/www/ephemeral/prep/admin # efibootmgr | grep -i cray | tee /tmp/bbs2
Boot0012* CRAY UEFI OS 1
Docs change for bad command
* Resolves [CASMINST-4198](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4198)
* Future work required by [issue …
> CASMINST-4198 

- upgrade/1.2/scripts/upgrade/upgrade-state.sh
Need to make target_ncn a local variable in function sourced by upgrade scripts, to prevent changing the value in the calling script.
* Resolves [CASMINST-4209](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4209)
Before:
```
ncn-m001:/etc/cray/upgrade/csm # /usr/share/doc/csm/upgrade/1.2/scripts/upgrade/ncn-upgrade-master-nodes.sh ncn-m002
====> UPDATE_M001_KUBEAPI_SERVICE_ISSUER ...
BRAD1 target_ncn: ncn-m001
====> UPDATE_KUBEAPI_ISTIO_CA ...
BRAD2 target_ncn: ncn-m001
BRAD3 target_ncn: ncn-m001
```
After:
```
ncn-m001:/etc/cray/upgrade/csm # /usr/share/doc/csm/upgrade/1.2/scripts/upgrade/ncn-upgrade-master-nodes.sh ncn-m002
====> UPDATE_M001_KUBEAPI_SERVICE_ISSUER ...
BRAD1 target_ncn: ncn-m002
====> UPDATE_KUBEAPI_ISTIO_CA ...
BRAD2 target_ncn: ncn-m002
BRAD3 target_ncn: …
```
> Prevent target_ncn from being changed in parent upgrade script

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/node_management/Configure_NTP_on_NCNs.md
- operations/resiliency/NTP_Resiliency.md
The change in the documentation is related to a system administrator making changes to the timezone used by the system. The current documentation is missing any warnings in regards to the consequences of changing the system time, especially the hardware clock. A few warnings, notes, and exceptions have been added to the documentation. Also, a few lines have been removed that changed the hardware clock timezone as well. These commands might be copied without understanding the impact. And any system administrator that wants to change the hardware clock for a specific reason will probably already know what needs to be done.
* Resolves [CASMINST-3962](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3962)
> CASMINST-3962: Alter NTP time documentation to limit adjustments of hardware clock

- operations/power_management/Prepare_the_System_for_Power_Off.md
Fixes backport cruft left in https://github.com/Cray-HPE/docs-csm/pull/1058/files
* Resolves CASMTRIAGE-3065
* NA
NA
None
> CASMTRIAGE-3065: Remove merge conflict left from backport

- upgrade/1.2/scripts/upgrade/prerequisites.sh
The ADD_MTL_ROUTES section in prerequisites.sh fails on 1.2 -> 1.2 upgrades because it fails immediately when it doesn't find the vlan002 interface.  This happens because `set -e` is set at the beginning if prerequisites.sh.
The fix is to disable the -e in that small section of code that checks for the vlan002 since we expect a non-zero return code in that section.
* Resolves CASMINST-4212
* `surtur`
Tested by running that section of code on surtur including the `set -e` at the top.   I tested it first without the fix to verify that it was failing consistently.  I then tested with the fix to ensure that it was succeeding on a system with 1.2 installed.
> CASMINST-4212: Prevent the ADD_MTL_ROUTES section from exiting immediately on 1.2 -> 1.2 upgrades

- upgrade/1.0.1/scripts/upgrade/add_pod_priority.sh
- upgrade/1.0.11/scripts/upgrade/add_pod_priority.sh
Instead of just relying on pod running state for etcd clusters, also verify the operator sees three healthy members before moving on with the rolling restart.
* Resolves [CASMINST-4220](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4220)
```
ncn-m001-ee11a084:/home/bklein # ./add_pod_priority.sh
validated etcd cluster: cray-bos-etcd has three running members...
validated etcd cluster: cray-bss-etcd has three running members...
validated etcd cluster: cray-hbtd-etcd has three running members...
validated etcd cluster: cray-hmnfd-etcd has three running members...
validated etcd cluster: cray-uas-mgr-etcd has three running members...
Patching cray-bss-etcd etcdcluster in services namespace
etcdcluster.etcd.database.coreos.com/cray-bss-etcd patched
pod "cray-bss-etcd-6w2pvnmgp4" …
```
> Improve pod priority script to wait for operator to report healthy members

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/collect_mac_addresses_for_ncns.md
This removes references to `csi pit validate --network`, which was only in place until GOSS tests could be added.  The output from that flag is useless without context as it only prints the output of `ip a s`.  This has been fully replaced with GOSS tests so it is no longer needed.
This is not backwards compatible, as the flag will be removed in the related PR below for 1.2.
* Resolves CASMINST-4230
* Merge with https://github.com/Cray-HPE/cray-site-init/pull/131
N/A this is removing deprecated and confusing functionality.
Low
> CASMINST-4230 remove references to 'csi pit validate --network' flag

- operations/network/gateway_testing.md
- scripts/operations/gateway-test/gateway-test-defn.yaml
- scripts/operations/gateway-test/gateway-test.py
This adds the gateway tests to the docs repo to allow running as needed.   It includes a page of instructions to show how to run the tests from various location and what the expected output will be.
This includes tests for 24 services as defined on this page:  https://connect.us.cray.com/confluence/display/~johren/Multiple+Gateway+Testing
Further tests will be added.
* CASMNET-866
* `mug`
* `surtur`
* `hela`
The tests have been run from an NCN and from outside (laptop and csm-remote-pit).   The tests have also been run briefly from a compute node and a UAN on hela.  Further work is needed once those nodes are available again on hela.
None
> CASMNET-866: Add gateway tests

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
This is to fix container image corruption of cached images
* Resolves CASMINST-4239
* surtur
Performed a boot loop with this change overnight.  we hit first try success 88% of the time and the additional 12% were boot based issues that resolved on the second boot.
> Casminst-4239 Fixes to ceph node image upgrade

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
Remove confusing and outdated references to `csi pit validate --services`, which have long since been replaced by GOSS tests.
* Resolves CASMINST-4238
* Merge with https://github.com/Cray-HPE/cray-site-init/pull/132
* Merge with https://github.com/Cray-HPE/csm-testing/pull/245
N/A
Low.
> CASMINST-4238 remove references to 'csi pit validate --services' flag 

- upgrade/1.2/README.md
CASMCMS-7890: Revert "CASMTRIAGE-3070: Add troubleshooting section for upgraded CFS content"
This reverts commit 105c766e71051b4e401d4292c5e12803e80ad0ad.
A new version of csm-config provided in CASMCMS-7890 (v1.9.24) makes this doc change unnecessary.
* Resolves CASMCMS-7890
* Reverts CASMINST-3070
* Merge with https://github.com/Cray-HPE/csm/pull/592
See https://github.com/Cray-HPE/csm/pull/592 for testing information.
Low
> CASMCMS-7890: Revert CASMTRIAGE-3070 (CSM 1.2 version)

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_4.md
- upgrade/1.2/Stage_5.md
Ensure that NCN personalization doesn't run on NCNs when they reboot since this will configure them with old Ansible plays from a previous version. Add a stage 5 to re-enable configuration using the current configuration from the new configuration branch in git.
* Resolves CASMINST-4218
* `Hela`
None
> CASMINST-4218: clarify ncn configuration enable/disable during 1.2 upgrade

- scripts/operations/configuration/apply_csm_configuration.sh
Due to a recent change in the install process, BMCs are now given the Management role, and this was causing the apply_csm_configuration script to print non-impactful errors because BMCs are not valid targets for CFS.  This restricts the call listing Management components to only Nodes, which was previously the only component type that had the Management role.
* Resolves CASMINST-4206
* Surtur
Ran the new command and verified the output.
None
> CASMINST-4206: Update apply_csm_config  script to restrict it to Nodes

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- scripts/operations/configuration/apply_csm_configuration.sh
- scripts/operations/configuration/replace_ssh_keys.sh
- scripts/operations/configuration/restore_ssh_keys.sh
Pulls in changes to the 1.2 docs for NCN configuration, including some helper scripts.  These were discovered missing while fixing an issue the the apply_csm_configuration script for CASMINST-4206 in the 1.2 branch.
This PR includes the new fix for CASMINST-4206:
Due to a recent change in the install process, BMCs are now given the Management role, and this was causing the apply_csm_configuration script to print non-impactful errors because BMCs are not valid targets for CFS.  This restricts the call listing Management components to only Nodes, which was previously the only component type that had the Management role.
* Resolves CASMINST-4206
* Surtur
Ran the new command and verified the output.
None
> CASMINST-4206: Copy all NCN configuration changes/scripts from 1.2

- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/install-hotfix.sh
Instead of assuming all target NCNs are up, check for a successful
scp and emit a warning if it fails.
* Resolves [MTL-1640](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1640)
* Relates to: [CAST-29492](https://jira-pro.its.hpecorp.net:8443/browse/CAST-29492)
* code snippet change was tested on redbull
> MTL-1640: issue a warning if a node is down

- upgrade/1.2/scripts/upgrade/util/update-customizations.sh
It was found that the way externaldns domain filters were configured could result in records being created in the wrong zone (e.g. `cmn.hela.dev.cray.com` records could be created in the `hela.dev.cray.com` zone) if externaldns performed an update before powerdns-manager had completed its first pass and created all the zones.
Reconfigured externaldns to prohibit updates to the TLD.
* Resolves [CASMTRIAGE-3123](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3123)
* Merge with https://github.com/Cray-HPE/csm/pull/605
* `hela`
Ran new version of `update-customizations.sh` on a CSM 1.0 `customizations.yaml` on hela and validated the output file had the desired change.
```
ncn-m001:~ # yq r customizations.yaml spec.kubernetes.services.cray-externaldns
external-dns:
domainFilters:
- …
```
> CASMTRIAGE-3123 - Update externaldns domain filters to only permit subdomain updates

- operations/CSM_product_management/Post_Install_Customizations.md
- operations/package_repository_management/Nexus_Deployment.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
- operations/security_and_authentication/Preserve_Username_Capitalization_for_Users_Exported_from_Keycloak.md
Update instructions that edit customizations.yaml but never upload the new file to k8s so it is available later. This ensures updates are grabbed if we redeploy a newer version of Keycloak.
* Resolves [STP-3146](https://jira-pro.its.hpecorp.net:8443/browse/STP-3146) and [CASMTRIAGE-3102](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3102)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1108 and https://github.com/Cray-HPE/docs-csm/pull/1109
N/A
N/A
N/A
None
> STP-3146: add missing step when customizations.yaml file is modified

- operations/CSM_product_management/Post_Install_Customizations.md
- operations/package_repository_management/Nexus_Deployment.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
- operations/security_and_authentication/Preserve_Username_Capitalization_for_Users_Exported_from_Keycloak.md
Update instructions that edit customizations.yaml but never upload the new file to k8s so it is available later. This ensures updates are grabbed if we redeploy a newer version of Keycloak.
* Resolves [STP-3146](https://jira-pro.its.hpecorp.net:8443/browse/STP-3146) and [CASMTRIAGE-3102](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3102)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1101 and https://github.com/Cray-HPE/docs-csm/pull/1109
N/A
N/A
N/A
None
> STP-3146-1.0: add missing step when customizations.yaml file is modified

- operations/CSM_product_management/Post_Install_Customizations.md
- operations/package_repository_management/Nexus_Deployment.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
- operations/security_and_authentication/Preserve_Username_Capitalization_for_Users_Exported_from_Keycloak.md
Update instructions that edit customizations.yaml but never upload the new file to k8s so it is available later. This ensures updates are grabbed if we redeploy a newer version of Keycloak.
* Resolves [STP-3146](https://jira-pro.its.hpecorp.net:8443/browse/STP-3146) and [CASMTRIAGE-3102](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3102)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1101 and https://github.com/Cray-HPE/docs-csm/pull/1108
N/A
N/A
N/A
None
> STP-3146-main: added missing step after modifying customizations.yaml

- upgrade/1.2/scripts/upgrade/ncn-upgrade-master-nodes.sh
Similar to updating m001's service issuer before workers get rebooted, we also need to add istio-ca to m001 before istio ingress gateways get restarted as part of the worker upgrades.
* Resolves [CASMINST-4273](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4273)
```
ncn-m002:/etc/cray/upgrade/csm/csm-1.2.0-beta.89 # /usr/share/doc/csm/upgrade/1.2/scripts/k8s/update_kubeapi_istio_ca.sh ncn-m001
Adding istio-ca api audience for kube-api on ncn-m001:
ncn-m001: Warning: Permanently added 'ncn-m001,10.252.1.4' (ECDSA) to the list of known hosts.
Sleeping for one minute to let kube-apiserver restart on ncn-m001
```
* `wasp`
Ran the script on wasp from m002 reconfiguring m001.
Low
> Update m001 kube api with istio-ca audience before workers get rebuilt

- install/prepare_site_init.md
Add work-around if podman overlay issue hit when running the load container images script.
* Resolves [CASMINST-4280](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4280)
Tested sed cmd in vshasta.
* `vshasta`
Tested sed cmd in vshasta.
Low
> Add WAR if podman overlay issue in load-container-images.sh script

- RELEASE_NOTES.md
- operations/validate_csm_health.md
- troubleshooting/index.md
- troubleshooting/known_issues/Gigabye_Missing_Redfish_Data.md
- troubleshooting/known_issues/cfs_sessions_stuck_in_pending.md
- troubleshooting/known_issues/component_power_state_mismatch.md
- troubleshooting/known_issues/craycli_403_forbidden_errors.md
- troubleshooting/known_issues/discovery_aruba_snmp_issue.md
- troubleshooting/known_issues/gitea_vcs_401_errors.md
- troubleshooting/known_issues/incorrect_output_for_bos_command_rerun.md
- troubleshooting/known_issues/kube_multus_pod_in_ImagePullBackOff.md
- troubleshooting/known_issues/kubernetes_node_rootFS_out_of_space.md
- troubleshooting/known_issues/orphaned_cfs_pods.md
- troubleshooting/known_issues/unbound_clbo.md
- troubleshooting/known_issues/wait_for_unbound_hang.md
Most of this PR just documents how to identify and correct a known issue with Gitea/VCS on fresh installs. The details are all in a new page in the troubleshooting/known_issues folder. This issue is linked to both from the main release notes and from the CSM health validation page (as this is where the problem is most likely to be initially detected).
In addition to the above, I did some linting of some of the other known issues pages. I didn't mean to, I just couldn't help myself.
> CASMCMS-7927: Document known Gitea/VCS 401 issue; some linting

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/upgrade/prerequisites.sh
This adds a step before running prerequisites.sh to set the SW_ADMIN_PASSWORD environment variable.  This variable is needed to run the goss-switch-bgp-neighbor-aruba-or-mellanox.yaml to check the status of the BGP peering sessions before attempting to boot the nodes.
I did this very early in prerequisites.sh so we could catch it right away before any of the other steps have been done.   This avoids having to resume after some of the steps have already been run.
* Work required by CASMINST-4265
* `drax`
I manually applied the change to prerequisites.sh and ran the first part of the script both with and without the environment variable set to test that it properly checks for that variable and exits if it is not set. 
Very low.   The test has not been added yet so we can make sure that this …
> CASMINST-4265:  Make sure SW_ADMIN_PASSWORD is set before running prerequisites.sh

- operations/configuration_management/Version_Control_Service_VCS.md
- operations/security_and_authentication/Manage_System_Passwords.md
Consolidates some information on managing VCS passwords to keep the information near the docs on how to access the VCS UI, and avoid duplicating information.
* Resolves CASMTRIAGE-3135
NA - docs only
NA - docs only
None
> CASMTRIAGE-3135: Consolidate information on managing VCS passwords

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- scripts/operations/configuration/apply_csm_configuration.sh
Previously the script assumed the first entry in the product catalog was the most recent, however this is not always true, so this updates it to find the highest version.
This also expands the override parameters to distinguish between the csm release version and the csm configuration version, as well as improves documentation around the script.
* Resolves CASMINST-4292
* Drax
Tested the changed portion of the scripts, including overriding both version and release.
None
> CASMINST-4292: Fix apply_csm_configuration script for default release

- install/deploy_final_ncn.md
Currently only the conman logs are copied into the prep directory before the PIT node redeploy, preserving them from being lost. This PR adds a few more files to the list of those being preserved. The step is optional (and stated as such), but this is useful information to retain if there are problems found later.
> CASMINST-4308: Retain additional files from PIT node before redeploy

- operations/package_repository_management/Manage_Repositories_with_Nexus.md
- operations/package_repository_management/Repair_Yum_Repository_Metadata.md
Fixes the missed commit from previous merge. This does not change any documentation only syntax errors, capitalization and formatting.
* Resolves [CASMPET-5427](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5427)
> CASMPET-5427-1.2: Fix docs relating to Nexus Keycloak integration

- operations/package_repository_management/Manage_Repositories_with_Nexus.md
- operations/package_repository_management/Repair_Yum_Repository_Metadata.md
Fixes the missed commit from previous merge on 1.2 that got transferred to 1.2.5. This does not change any documentation only syntax errors, capitalization and formatting.
* Resolves [CASMPET-5427](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5427)
> CASMPET-5427-1.2.5: Fix docs relating to Nexus Keycloak integration

- install/deploy_management_nodes.md
- install/redeploy_pit_node.md
- operations/index.md
- operations/node_management/Configure_NTP_on_NCNs.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
- operations/security_and_authentication/Update_NCN_Passwords.md
- upgrade/1.0.11/Stage_0_Prerequisites.md
CASMINST-4289-1.0 Revised password, ssh key, and timezone change for k8s-image and ceph-image
Revised procedures to change the NCN images (k8s-image and ceph-image) to be done from PIT node or later when PIT node is not available.  Both procedures will change the root password, ssh keys and authorized_keys for root, and optionally change the timezone.
The install procedure now refers to this procedure as the security best practices recommended method to change the root password from the PIT node before deploying any of the other NCNs.
Added image changing to the Upgrade procedure and changed non-PIT operational procedure to also do a BSS update and recommend a Rolling Rebuild (if not doing a CSM upgrade)
This also address timezone procedure issue from …
> CASMINST-4289-1.0 Revised password, ssh key, and timezone change for k8s-image and ceph-image

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/index.md
- operations/node_management/Configure_NTP_on_NCNs.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_node.md
- operations/security_and_authentication/Update_NCN_Passwords.md
- upgrade/1.2/Stage_0_Prerequisites.md
[CASMINST-4289](https://jira-pro.its.hpecorp.net:8443/secure/QuickSearch.jspa?searchString=CASMINST-4289)-1.2 Revised password, ssh key, and timezone change for k8s-image and ceph-image
Revised procedures to change the NCN images (k8s-image and ceph-image) to be done from PIT node or later when PIT node is not available. Both procedures will change the root password, ssh keys and authorized_keys for root, and optionally change the timezone.
The install procedure now refers to this procedure as the security best practices recommended method to change the root password from the PIT node before deploying any of the other NCNs.
Added image changing to the Upgrade procedure and changed non-PIT operational procedure to also do a BSS update and recommend a Rolling Rebuild (if not doing a CSM …
> Casminst 4289 1.2 Revised password, ssh key, and timezone change for k8s-image and ceph-image

- install/deploy_management_nodes.md
Change in the documentation for the deployment of the storage NCNs with a single compound command rather than three steps.
* Resolves [CASMINST-4270](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4270)
* surtur
I've performed this command on numerous installs. The only difference between this approach on the three step approach this replaces is the preciseness of the delay between the booting of the other storage nodes and ncn-s001.
This is a low risk change, plus I've used this same approach on numerous installs.
> Change storage node deployment into a single command

- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
This adds a check to the upgrade scripts for 1.0.11 that ensure BSS contains NTP data. The NTP data itself is not validated, it is just tested to exist at all.
* Resolves [MTL-1645](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1645)
* `Rocket`
Tested on Rocket by executing the script for both success paths and failure paths.
> MTL-1645: Add check for NTP data in BSS.

- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-cloud-init.sh
- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-cloud-init.sh
This addresses an issue where we remove the cloud init call from runcmds in
prequisites, but the upgrade script comes in afterwards and puts it back.
It can cause some issues if the cloud-init is run and re-creates some csi references
* Resolves CASMTRIAGE-3157
> Fixes to remove storage-ceph-cloudinit from being put back into runcmds

- operations/security_and_authentication/Change_Air-Cooled_Node_BMC_Credentials.md
- operations/system_configuration_service/Set_BMC_Credentials.md
After using SCSD to change credentials perform a rediscovery. 
* Resolves [CASMHMS-5459](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5459)
* Frigg with CSM 1.0.10
- Were the install/upgrade-based validation checks/tests run (goss …
> After using SCSD to change credentials perform a rediscovery

- operations/power_management/Power_Off_Compute_and_IO_Cabinets.md
I found a commit in the master branch which belongs in this branch as well, but was accidentally omitted.
> CASMINST-4331: Pull in commits that were accidentally only in master branch (csm-1.0)

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/node_management/Configure_NTP_on_NCNs.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
- operations/security_and_authentication/Update_NCN_Passwords.md
- upgrade/1.2/Stage_0_Prerequisites.md
Adjust docs to account for no default root password/keys
> MTL-1647: adjust docs to account for no default root password/keys

- operations/index.md
- operations/spire/Update_Spire_Intermediate_CA_Certificate.md
This adds documentation on how to replace the Spire intermediate CA cert if it's expired or close to becoming expired. This was the method used to Fix Odin in [CASMTRIAGE-3127](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3127).
> CASMPET-5082 Add spire int ca regen steps

- upgrade/1.2/Stage_0_Prerequisites.md
Just disabling components in CFS is not sufficient, since steps taken between stage 0 and stage 5 reboot nodes and cause CFS to become re-enabled.  This updates the documentation to unset the desired configuration in stage 0 as well.
Stage 5 already includes steps to set the desired configuration, so no changes are needed there.
* Resolves CASMINST-4330
* Mug
- Tested the updated command on mug.
None
> CASMINST-4330: Update 1.2 upgrade stage 0 for disabling CFS

- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
because of refactoring, metal.no-wipe=0 is not in a state wrapper so when it reruns, it always flip back to metal.no-wipe=0. the fix is to move metal.no-wipe=1 out of a state wrapper so we make sure rerun will always set metal.no-wipe=1
* Resolves CASMINST-4356
* Local development …
> always set metal.no-wipe=1 during rerun

- operations/validate_csm_health.md
This is to address known issue where we occasionally run the test
prior to cloud-init being fully completed on the storage nodes
* Resolves CASMINST-4356
> Adding known issue for test failures for ceph csi k8s reqs

- troubleshooting/index.md
- troubleshooting/known_issues/ssl_certificate_validation_issues.md
This adds some basic troubleshooting information for the 3 most common SSL validation failures.
> CASMTRIAGE-3168 Add SSL Troubleshooting doc

- install/redeploy_pit_node.md
Removes the offending `known_hosts` after a rebuild.
* Resolves CASMINST-3781
Verified the command to get the NCN names worked.
* `redbull`
Low. WAR
> CASMINST-3781 war if bootraid artifacts script fails 

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
This will allow the rgw process to start and us not enter a race condition where the goss test is checking for a process that does not get spawned until after the cluster is healthy
* Resolves CASMINST-4920
tested the logic out on a craystack instance
* craystack
> CASMINST-4290 - Add wait for rgw to be started on upgraded node

- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
Also, fix a couple of typos / bad wording.
> CASMINST-4380: clarify usage/docs for the SQUASHFS_ROOT_PW_HASH variable

- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
Documentation change for CASMPET-5382 and CASMPET-5378
[CASMPET-5382](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5382): CPU THROTTLING - Gatekeeper pods
[CASMPET-5378](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5378): PostgresqlHighRollbackRate on spire and smd postgres pods- add smd to the known issue list?
* Resolves -  https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5382
https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5378
> Documentation change for CASMPET-5382 and CASMPET-5378

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/upgrade/prepare-assets.sh
This PR contains two small changes:
1. Remove an unnecessary manual command in the upgrade docs.
2. Add a check of the df command output to an upgrade script
I have tested both to verify that the command is indeed superfluous and to validate that the df output check works as expected.
> CASMINST-4384: Remove superfluous manual command; validate df command output

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Add to postgres troubleshooting to cover the case where reinit fails and leader pod needs to be restarted.
* Resolves [CASMINST-4390](DOCS: K8s upgrade on w001 throws error)
This issue was seen on drax where 0.1.11 to 1.2.0 beta 96 upgrade was occurring.
In the past this procedure has been used instead of waiting 45m for the lag to resolve.
Low
> CASMINST 1.0 : DOCS: K8s upgrade on w001 throws error

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Add to postgres troubleshooting to cover the case where reinit fails and leader pod needs to be restarted.
* Resolves [CASMINST-4390](DOCS: K8s upgrade on w001 throws error)
This issue was seen on drax where 0.1.11 to 1.2.0 beta 96 upgrade was occurring.
In the past this procedure has been used instead of waiting 45m for the lag to resolve.
Low
> CASMINST-4390 main : DOCS: K8s upgrade on w001 throws error

- .github/workflows/markdown-lint.yaml
- .markdownlint.yaml
Adds markdown linter. Initial configuration very permissive. The plan is to tighten restrictions one by one, by turning them on in configuration file and fixing violations.
* Resolves CASMINST-4387
Successful run:
https://github.com/Cray-HPE/docs-csm/runs/5762333785?check_suite_focus=true
Unsuccessful run to exclude false positive (line length limit is temporarily decreased to 999 chars):
https://github.com/Cray-HPE/docs-csm/runs/5762323018?check_suite_focus=true
* github runners
Performed run with current configuration (successful) and temporarily tightened configuration (unsuccessfull).
Minimal - optional CI/CD check
> CASMINST-4387 Add markdown linter to docs-csm [1.2]

- .github/workflows/markdown-lint.yaml
- .markdownlint.yaml
Adds markdown linter. Initial configuration very permissive. The plan is to tighten restrictions one by one, by turning them on in configuration file and fixing violations.
* Resolves CASMINST-4387
Successful run:
https://github.com/Cray-HPE/docs-csm/runs/5762333785?check_suite_focus=true
Unsuccessful run to exclude false positive (line length limit is temporarily decreased to 999 chars):
https://github.com/Cray-HPE/docs-csm/runs/5762323018?check_suite_focus=true
* github runners
Performed run with current configuration (successful) and temporarily tightened configuration (unsuccessfull).
Minimal - optional CI/CD check
> CASMINST-4387 Add markdown linter to docs-csm [1.0]

- .github/workflows/markdown-lint.yaml
- .markdownlint.yaml
Adds markdown linter. Initial configuration very permissive. The plan is to tighten restrictions one by one, by turning them on in configuration file and fixing violations.
* Resolves CASMINST-4387
Successful run:
https://github.com/Cray-HPE/docs-csm/runs/5762333785?check_suite_focus=true
Unsuccessful run to exclude false positive (line length limit is temporarily decreased to 999 chars):
https://github.com/Cray-HPE/docs-csm/runs/5762323018?check_suite_focus=true
* github runners
Performed run with current configuration (successful) and temporarily tightened configuration (unsuccessfull).
Minimal - optional CI/CD check
> CASMINST-4387 Add markdown linter to docs-csm [main]

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/scripts/common/ncn-common.sh
- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
- upgrade/1.2/scripts/common/upgrade-state.sh
- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-master-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/prepare-assets.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
- upgrade/1.2/scripts/upgrade/util/update-customizations.sh
- Redirect all output except for long running process to log files (wait for boot, wait for cloud-init)
- add validation after csm service upgrade
- add back doc to download tarball before csm services upgrade
- CASMINST-4388
- CASMINST-4389
- CASMINST-4391
- Were new tests (or test …
> CASMINST-4394 add preflight check after csm service upgrade

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
add note to use a valid, reachable NTP server when running `csi config init`
* Resolves MTL-1661
* 
N/A
Low.
> MTL-1661 add note to use a valid, reachable NTP server

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
Adds a step to remove the default NTP pool since code for it will be removed in MTL-1662
* Resolves MTL-1663
Validated the sed and pdsh commands run.
* `#wasp`
Low.
> MTL-1663 remove default pool during deploy to prevent contention issues

- scripts/operations/node_management/Add_Remove_Replace_NCNs/add_management_ncn.py
Query KEA for an active DHCP lease for the BMC, instead of HSM incase if there is cruft left in HSM while the BMC in is a limbo state between having a random IP from DHCP and its statically assigned IP.
* Resolves [CASMHMS-5378](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5378)
* Local System
* Fanta
Performed a dry run on Fanta and local system for adding ncn-m002.
Very low, the script is currently broken.
> CASMHMS-5378: Query KEA for BMC IP & reverse some linting changes.

- operations/index.md
- operations/security_and_authentication/Keycloak_User_Management_with_Kcadm.md
This is a new procedure explaining how to use Keycloak's kcadm.sh utility to troubleshoot Keycloak user account issues that may result during an install or upgrade that would prevent the proper initialization of the Cray CLI.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5297
* Related to [CAST-28940](https://jira-pro.its.hpecorp.net:8443/browse/CAST-28940) Unable to set / create password for user crayadm within keycloak.
* Related to [CAST-28948](https://jira-pro.its.hpecorp.net:8443/browse/CAST-28948) Configure Keycloak Account via a CLI is required.
All procedures documented here were tested on Mug and VShasta.
None
> CASMPET-5297 Add Keycloak kcadm user management application notes.

- install/cable_management_network_servers.md
This corrects the interface names for CSM 1.2+
No, the interface names changed to remove the extraneous mgmt2 and mgmt3 NICs
* Resolves [MTL-1666](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1666)
* Change will also be needed in `release/1.2.5` and `main`
> Mtl 1666 fix ports 1.2

- install/cable_management_network_servers.md
This corrects the interface names for CSM 1.2+
No, the interface names changed to remove the extraneous mgmt2 and mgmt3 NICs
* Resolves [MTL-1666](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1666)
* Change will also be needed in `release/1.2.5` and `main`
> MTL-1666 fix ports 1.2.5

- install/cable_management_network_servers.md
This corrects the interface names for CSM 1.2+
No, the interface names changed to remove the extraneous mgmt2 and mgmt3 NICs
* Resolves [MTL-1666](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1666)
* Change will also be needed in `release/1.2.5` and `main`
> MTL-1666 fix ports main

- operations/node_management/Add_Remove_Replace_NCNs/Boot_NCN.md
- operations/utility_storage/Add_Ceph_Node.md
- operations/utility_storage/Remove_Ceph_Node.md
* CASMPET-5450 : kube-etcdbackup jobs fail when NCN ncn-s001 is removed
Added `systemctl stop keepalived.service` to removed storage node otherwise rgw-vip may stop working and cause things like kube-etcdbackup to start failing.
* CASMPET-5449 : NCN Storage replace 
Minor doc improvements
* Resolves [CASMPET-5450](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5450) and [CASMPET-5449](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5449)
fanta
* dev system
Replace storage node by swapping identity ncn-s001 (sn0 slot13)->(sn4 slot36) and …
> CASMPET-5450 1.0 : kube-etcdbackup jobs fail when NCN ncn-s001 is removed

- operations/kubernetes/Restore_Postgres.md
An additional step was needed during restore of spire postgres at archer2 to ensure spire-jwks was healthy.
* Resolves [CASMPET-5319](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5319)
* Change will also be needed in 1.0, 1.2, 1.2.5, main
archer2
- Was downgrade tested? If not, …
> CASMPET-5319 1.0 : DOC : Add to spire postgres restore steps

- operations/kubernetes/Restore_Postgres.md
An additional step was needed during restore of spire postgres at archer2 to ensure spire-jwks was healthy.
* Resolves [CASMPET-5319](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5319)
* Change will also be needed in 1.0, 1.2, 1.2.5, main
archer2
- Was downgrade tested? If not, …
> CASMPET-5319 1.2 : DOC : Add to spire postgres restore steps

- operations/kubernetes/Restore_Postgres.md
An additional step was needed during restore of spire postgres at archer2 to ensure spire-jwks was healthy.
* Resolves [CASMPET-5319](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5319)
* Change will also be needed in 1.0, 1.2, 1.2.5, main
archer2
- Was downgrade tested? If not, …
> CASMPET-5319 1.2.5 : DOC : Add to spire postgres restore steps

- operations/kubernetes/Restore_Postgres.md
An additional step was needed during restore of spire postgres at archer2 to ensure spire-jwks was healthy.
* Resolves [CASMPET-5319](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5319)
* Change will also be needed in 1.0, 1.2, 1.2.5, main
archer2
- Was downgrade tested? If not, …
> CASMPET-5319 main : DOC : Add to spire postgres restore steps

- background/ncn_plan_of_record.md
- operations/node_management/customize_pcie_hardware.md
- upgrade/1.2/scripts/upgrade/util/update-customizations.sh
We need prevent UAIs from getting to CMN like we do with NMNLB.   The way this is being accomplished with NMNLB is that a route exists on the UAI that goes to a gateway that it cannot get to.   We are doing the same thing for CMN by adding the CMN subnet to macvlan routes defined in customizations.yaml.  This causes it to be added to the relevant network attachment definitions.
While testing the idempotency, I found that there was still an issue adding `generated` to the cray-oauth2-proxy SealedSecrets when they are already encrypted.   Fixed those as well.
- Fixes #CASMINST-4283
I pulled the customizations.yaml out of the site-init secret on hela and then ran this new update-customizations.yaml on it.  I checked the diff between the original customizations.yaml and the updated one to …
> CASMINST-4283: Add CMN route to net attach defs

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Adds another case seen only during 1.0 -> 1.2 upgrade where postgres lag requires a reinit, but reinit fails and needs manual remediation
* Resolves [CASMINST-4412](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4412)
* Change will also be needed in `main, 1.2.5, 1.0`
surtur
Resolved the issues on surtur using the additional troubleshooting procedure
> CASMINST-4412 1.0 : DOCS: Troubleshoot Postgres needs additional details when TL is different

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Adds another case seen only during 1.0 -> 1.2 upgrade where postgres lag requires a reinit, but reinit fails and needs manual remediation
* Resolves [CASMINST-4412](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4412)
* Change will also be needed in `main, 1.2, 1.0`
surtur
Resolved the issues on surtur using the additional troubleshooting procedure
> CASMINST-4412 main : DOCS: Troubleshoot Postgres needs additional details when TL is different

- upgrade/1.2/README.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/Stage_5.md
- upgrade/1.2/scripts/sls/README.SLS_Upgrade.md
This PR includes formatting, style, punctuation corrections and/or improvements from the README up through Stage 3. It also includes moving note about stable and upgrade node that is not referenced in later stages until ncn-m001 is rebooted. This This also removes a large block wall of text from a --help output that is not needed in the docs as we inform the user to use the --help option to get a list of all options.  We further inform the user in the Update SLS step they need to review the update SLS doc for details to understand what options the installer should use. We still provide examples for 2 of the common options.
* Resolves [CASMINST-4272](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4272)
* Change will also be needed in `release/1.2.5`
_List the environments in which …
> CASMINST 4272 - Streamline upgrade docs - Readme through Stage 5

- install/deploy_management_nodes.md
Omits ncn-m001 from a list of hosts to target for a command that fixes an NTP issue.
* Resolves CASMINST-4438
* `#surtur`
Ran the entire command.
Low.
> CASMINST-4438 dont run ntp pool workaround for ncn-m001 (PIT)

- operations/system_configuration_service/Manage_Parameters_with_the_scsd_Service.md
SCSD Doc Update - JSON examples - CASMHMS-5484
Updated SCSD documentation - Manage parameters with the SCSD Service to correct JSON arrays in examples.
> SCSD Doc Update - JSON examples - 1.0

- operations/system_configuration_service/Manage_Parameters_with_the_scsd_Service.md
SCSD Doc Update - JSON examples - CASMHMS-5484
Updated SCSD documentation - Manage parameters with the SCSD Service to correct JSON arrays in examples.
> SCSD Doc Update - JSON examples - 1.2

- operations/system_configuration_service/Manage_Parameters_with_the_scsd_Service.md
SCSD Doc Update - JSON examples - CASMHMS-5484
Updated SCSD documentation - Manage parameters with the SCSD Service to correct JSON arrays in examples.
> SCSD Doc Update - JSON examples - 1.2.5

- operations/system_configuration_service/Manage_Parameters_with_the_scsd_Service.md
SCSD Doc Update - JSON examples - CASMHMS-5484
Updated SCSD documentation - Manage parameters with the SCSD Service to correct JSON arrays in examples.
> SCSD Doc Update - JSON examples - Main

- upgrade/1.2/Stage_4.md
We have seen this occur once, but adding it as it is good documentation to have.
* Resolves CASMINST-4447
* drax
> CASMINST-4447 - Adding Ceph upgrade restart if image pull failed

- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
Remove the duplicated step of saving the original squashfs images.
Also, clarify that the set-sqfs-links.sh step should be skipped
after modifying the k8s image if you're also modifying the ceph
image.
This verbiage only exists in the `release/1.0` branch.
> CASMINST-4440: remove duplicate step, clarify another

- operations/spire/Update_Spire_Intermediate_CA_Certificate.md
After updating the Spire intermediate certificate, it is necessary to have NCNs rejoin Spire.
The following command was added:
`ncn# kubectl rollout restart -n spire daemonset request-ncn-join-token `
* Resolves [STP-3185](https://jira-pro.its.hpecorp.net:8443/browse/STP-3185) and [CAST-29620](https://jira-pro.its.hpecorp.net:8443/browse/CAST-29620)
* Change will also be needed in `release/1.2`, `release/1.2.5`, and `main`
N/A
N/A
N/A
None.
> STP-3185: added step for NCNs to rejoin Spire

- install/bootstrap_livecd_usb.md
Seen during fanta 1.2 fresh install.
Paths to install or upgrade podman and lsscsi RPMS need correcting
* Resolves [CASMPET-5528](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5528)
* Change will also be needed in 1.0, 1.2, 1.2.5 and main
* fanta
- Were continuous …
> CASMPET-5528 main : DOCS: Fix paths to podman and lsscsi RPMS

- install/bootstrap_livecd_usb.md
Seen during fanta 1.2 fresh install.
Paths to install or upgrade podman and lsscsi RPMS need correcting
* Resolves [CASMPET-5528](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5528)
* Change will also be needed in 1.0, 1.2, 1.2.5 and main
* fanta
- Were continuous …
> CASMPET-5528 1.2.5 : DOCS: Fix paths to podman and lsscsi RPMS

- install/bootstrap_livecd_usb.md
Seen during fanta 1.2 fresh install.
Paths to install or upgrade podman and lsscsi RPMS need correcting
* Resolves [CASMPET-5528](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5528)
* Change will also be needed in 1.0, 1.2, 1.2.5 and main
* fanta
- Were continuous …
> CASMPET-5528 1.2 : DOCS: Fix paths to podman and lsscsi RPMS

- install/bootstrap_livecd_usb.md
Seen during fanta 1.2 fresh install.
Paths to install or upgrade podman and lsscsi RPMS need correcting
* Resolves [CASMPET-5528](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5528)
* Change will also be needed in 1.0, 1.2, 1.2.5 and main
* fanta
- Were continuous …
> CASMPET-5528 1.0 : DOCS: Fix paths to podman and lsscsi RPMS

- upgrade/1.2/scripts/upgrade/prerequisites.sh
During testing the nexus repo providing the RPMs from the tarball existed on the system, but in reality this is false. This change simply adds the repo for a one-time-use in the CASMINST-4458 function.
The fix allowed the failing step to continue:
```bash
====> UPDATE_SSH_KEYS has been completed
====> CHECK_CLOUD_INIT_PREREQ has been completed
====> UPDATE_DOC_RPM has been completed
====> UPDATE_CUSTOMIZATIONS has been completed
====> SETUP_NEXUS has been completed
====> DISABLE_SERVICE_REPOS has been completed
====> REMOVE_DUPLICATE_BMC_DNS_RECORDS ...
====> REMOVE_DUPLICATE_BMC_DNS_RECORDS has been completed
====> UPGRADE_BSS ...
====> UPGRADE_BSS has been …
```
> CASMTRIAGE-3225 Nexus repo does not exist

- install/deploy_management_nodes.md
Recently a step was added to the "Deploy Management Nodes" state of the CSM install (for both csm-1.0 and 1.2). This step edits the NTP configuration on all of the NCNs. However, it tries to do this using a `pdsh` command on the PIT node, and this command fails with SSH authentication issues. This is because passwordless SSH is not configured from the PIT node to the other NCNs, and even if it was configured, the command would still fail because of the lack of entries in the known_hosts file.
This PR modifies the command so that it instead is an `ssh` command to ncn-m002, and from there it uses passwordless SSH to the NCNs via `pdsh`. This does mean that the user is prompted once for the root password for ncn-m002, but that's all.
I tested this during my install of surtur today and the …
> CASMINST-4464: Modify pdsh command to avoid authentication errors

- upgrade/1.2/scripts/common/upgrade-state.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
Add a .ssh/config file that will ignore host key issues for
unknown hosts.  On error, Remove it and restore the original
one that existed.
While here, fix another bug:
Use -gt for numerical comparison.
`>` is for comparing strings and does not work like you'd expect
for numbers.
```
C02YR1QYLVCJ:~ heemstra$ counter=10
C02YR1QYLVCJ:~ heemstra$ if [[ $counter > 5 ]]; then echo "larger"; fi
C02YR1QYLVCJ:~ heemstra$ if [[ $counter -gt 5 ]]; then echo "larger"; fi
larger
C02YR1QYLVCJ:~ heemstra$
```
> CASMINST-4468: use an ssh config to ignore unknown hosts

- operations/security_and_authentication/Change_Air-Cooled_Node_BMC_Credentials.md
- operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md
- operations/security_and_authentication/Change_SNMP_Credentials_on_Leaf_Switches.md
- operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md
Provide special character handling when changing SNMP, Air-cooled Node BMC, ServerTech PDU, and CEC password change procedures.
* Resolves CASMTRIAGE-3149
* Surtur
* Fanta
- Were the install/upgrade-based validation checks/tests run (goss …
> CASMTRIAGE-3149: Provide special character handling when changing SNMP, Air-cooled Node BMC, ServerTech PDU, and CEC password change procedures.

- operations/network/gateway_testing.md
- scripts/operations/gateway-test/gateway-test-defn.yaml
- scripts/operations/gateway-test/gateway-test.py
- scripts/operations/gateway-test/uai-gateway-test.sh
This adds a new uai-gateway-test.sh script.  This script will spin up a UAI with the new cray-uai-gateway-test image and then run the gateway tests included in that image.
I modified gateway-test.py to not require specifying the network.  I had to make some modifications to gateway-test.py to be able to run in an environment (like UAIs and UANs) that will not have access to SLS to get some of the network confiiguraiton.   To make gateway-test.py to run, it will just cycle through all networks.  I modified the gateway-test.md description to no longer specify the network and updated the example give in that document.
* Resolves CASMINST-4246
* Related uai-images PR: https://github.com/Cray-HPE/uai-images/pull/10
* `hela`
Ran uai-gateway-test.sh on hela.   I tested both success and failure …
> CASMINST-4246:  Add uai-gateway-test.sh

- upgrade/1.2/scripts/upgrade/prerequisites.sh
We want the cleanup function to run in the case of a kill or a control-C as well.
> CASMINST-4468: invoke the cleanup function on more signals

- operations/network/management_network/backup_custom_config.md
Most of this PR is pure linting. The only non-linting change is correcting one command on a Dell switch. The command used the `include` command, but on Dell switches that should be the `grep` command.
* [csm-1.2 backport](https://github.com/Cray-HPE/docs-csm/pull/1390)
* This page does not exist prior to 1.2
I tested the updated Dell command on a switch on mug.
Very low risk.
> CASMINST-4476: Lint and correct error in Backup Custom Config page

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/prepare_site_init.md
- operations/network/management_network/snmp_exporter_configs.md
This ticket consists of a few changes:
* Modify the two bootstrap PIT node procedures to try and remove needless inconsistencies.
* Define additional common environment variables and add them to the PIT environments for both paths.
* Make use of these variables aggressively to reduce and simplify commands, both in the bootstrap procedures and the prepare site-init procedure
* One notable effect of this is that we no longer need the temporary "shim" mount in the remote ISO path before following the prepare site init procedure (nor the cleanup step after)
* Linted and cleaned up both bootstrap procedures
* Made use of the new common variables to correct an error in the "SNMP Exporter" page
* Removed sections of the bootstrap documents that were added when the `site-init.sh` script was …
> CASMINST-4477: Streamline and lint bootstrap PIT node, prepare site-init procedures

- upgrade/1.2/scripts/ceph/ceph-services-stage2.sh
- upgrade/1.2/scripts/ceph/create_rgw_buckets.sh
- Check to see if admin.conf is present
- add enable ceph services to a post rebuild task
Addresses issues found in CAST-29770
* Resolves CASMINST-4486
* WASP
Tested the components of the script that were added in the exact way that they would be called. 
> CASMINST-4486 - Add conditionals to upgrade for storage nodes

- upgrade/1.0.11/scripts/ceph/ceph-services-stage1.sh
- upgrade/1.0.11/scripts/upgrade/create_rgw_buckets.sh
- Check to see if admin.conf is present
- add enable ceph services to a post rebuild task
Addresses issues found in CAST-29770
* Resolves CASMINST-4486
* WASP
Tested the components of the script that were added in the exact way that they would be called. 
> CASMINST-4486 - 1.0 branch adding conditionals for post ceph node reuild

- upgrade/1.2/scripts/ceph/ceph-services-stage2.sh
This PR cherry-picks a minor typo commit from csm-1.2 into main branch. It accidentally was omitted from the corresponding main branch PR yesterday.
This is just changing a single character, to correct capitalization.
No backport of this PR is needed, since this commit already exists in the other relevant branches.
This should have gone in with https://github.com/Cray-HPE/docs-csm/pull/1400, but that PR merged before it got pulled in. The other PRs for that ticket included this commit in their merge:
* https://github.com/Cray-HPE/docs-csm/pull/1401
* https://github.com/Cray-HPE/docs-csm/pull/1402
N/A
Incalculable.
> CASMINST-4490: Backport missing commit into main from csm-1.2

- operations/network/gateway_testing.md
This is the csm-1.2 backport of this PR: https://github.com/Cray-HPE/docs-csm/pull/1411
This PR also includes a commit that removes a line that was accidentally included in the csm-1.2 version of the file, but that Jeanne had intended to remove before merging.
> CASMINST-4491: Linting of operations/network/gateway_testing.md

- operations/image_management/Customize_an_Image_Root_Using_IMS.md
- operations/image_management/Import_External_Image_to_IMS.md
More than just minor linting of the pages, but no content changes -- some sections were slightly reorganized, but the procedure is unchanged.
csm-1.2 backport https://github.com/Cray-HPE/docs-csm/pull/1413
csm-1.0 backport https://github.com/Cray-HPE/docs-csm/pull/1418
None
Never tell me the odds.
> CASMINST-4492: Linting: Import_External_Image_to_IMS, Customize_an_Image_Root_Using_IMS

- upgrade/1.2/README.md
Note that clock skew can resolve on it's own, given time.
* Resolves CASMINST-4494
N/A
Low.
> CASMINST-4494 note that clock skew can resolve on its own

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
Reverts Cray-HPE/docs-csm#1433
There were still open comments on #1432 , #1433 should not have merged.
> Revert "[Backport release/1.2] CASMINST-4502 Ensure PITDATA is set"

- install/bootstrap_livecd_usb.md
When we are going a USB fresh install on a system that had a prior install, m001 will have old multus and weave CNI configuration.  However, while we are setting up the USB image from m001, those two CNIs are no longer available because the cluster has been shut down.   This causes warnings when using podman because the old configuration is causing it to look for the CNIs.    This adds a step to only the USB path to remove that old configuration.
This is not an issue with Remote ISO installs because we boot into the Remote ISO right away.
* Resolves CASMINST-4454
* `drax`
Reproduced the issue at this specific point of the install on drax using the documented podman commands.   I then removed the files as documented in this new step and ran the podman commands again.  This time I did not …
> CASMINST-4454:  Remove prior weave and multus CNI configuration on USB fresh install

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
Ensure that the `umount` call in the USB directions uses the absolute path to the disk-label, since the PITDATA env var is no longer set. Also remove hardcodes for setting PITDATA to `/var/www/ephemeral` and set it
via `lsblk`.
No.
* Resolves [CASMINST-4502](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4502)
> CASMINST-4502 Ensure PITDATA is set

- upgrade/1.0.1/scripts/upgrade/add_pod_priority.sh
- upgrade/1.0.11/scripts/upgrade/add_pod_priority.sh
Fix minor logic bug in pod priority wait script
* Resolves [CASMINST-4523](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4523)
```
ncn-m001-fec36008:/home/bklein # ./add_pod_priority.sh
Found 3 running pods in cray-bss-etcd etcd cluster
Found 3 ready members in cray-bss-etcd etcd cluster
Found status of Running for cray-bss-etcd etcd cluster
Creating csm-high-priority-service pod priority class
priorityclass.scheduling.k8s.io/csm-high-priority-service configured
Patching cray-bss-etcd etcdcluster in services namespace
etcdcluster.etcd.database.coreos.com/cray-bss-etcd patched (no change)
pod "cray-bss-etcd-dtnlvjtbj9" deleted
Sleeping for ten seconds waiting for 3 pods in cray-bss-etcd etcd cluster
Sleeping for ten seconds waiting for 3 pods in cray-bss-etcd etcd cluster
Sleeping …
```
> Fix wait function to wait on 3 members AND running state for pod priority script

- RELEASE_NOTES.md
- troubleshooting/index.md
- troubleshooting/known_issues/console_log_storage_filling.md
Add documentation for a defect discovered where log rotation is not working correctly and console logs may expand to fill all available space on the volume.
* Resolves [CASMTRIAGE-3258](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3258)
* `Wasp`, and `Shandy`
I used shandy and wasp to verify the workaround steps and insure accurate documentation.
This is just a documentation change - no code risk.
> CASMTRIAGE-3258 - add known issue with console log files filling storage space.

- upgrade/1.2/scripts/k8s/reconfigure_haproxy.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
Change kube-api haproxy health check from tcp to http, which makes failover more responsive and doesn't hork up postgres.
* Resolves [CASMTRIAGE-3263](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3263)
```
====> RECONFIGURE_HAPROXY_MASTERS ...
====> RECONFIGURE_HAPROXY_MASTERS has been completed
[OK] - Successfully completed
```
```
ncn-m003:~ # diff /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
44,46c44
<     option httpchk GET /readyz HTTP/1.0
<     option  log-health-checks
<     http-check expect status 200
---
>     option tcp-check
48c46
<     default-server verify none check-ssl inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
---
>     default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue …
```
> Add step in prereq's to reconfigure haproxy on masters

- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- scripts/ceph-upload-file-public-read.py
> Remove script references to private repo -- add script here

- install/wipe_ncn_disks_for_reinstallation.md
The disk wipe procedure referred to versions 1.4 and 1.5 without saying whether that was CSM or Shasta (or something else). Since we no longer use the Shasta versions normally, I updated the document so it clearly stated the appropriate CSM versions.
I also did an overall linting of the page, correcting a number of small errors, and making some things clearer.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1450
csm-1.0 backport: https://github.com/Cray-HPE/docs-csm/pull/1451
None. No processes were changed.
Low risk.
> CASMINST-4509: Lint/clarify disk wipe procedure

- install/wipe_ncn_disks_for_reinstallation.md
This backports all of the improvements made to the disk wipe procedure since csm-1.0, since none of those changes is not applicable to csm-1.0 as well. This also pulls in the changes being made for CASMINST-4509 (see https://github.com/Cray-HPE/docs-csm/pull/1447)
> Backport CASMINST-4509 and other improvements to disk wipe procedure in csm-1.0 docs

- operations/network/dns/Manage_the_DNS_Unbound_Resolver.md
Document procedure to change the site DNS server Unbound forwards queries to post-install.
* Resolves [CAST-25340](https://jira-pro.its.hpecorp.net:8443/browse/CAST-25340)
* Change will also be needed in `main`
* `hela`
Tested procedure on hela, also tested that the cray-dns-unbound chart deploys correctly with a second forwarder configured.
> CAST-25340 - Added procedure to reconfigure Unbound forwarder

- .github/config/markdown_style.yaml
- .github/workflows/link-checker.yaml
- install/deploy_management_nodes.md
There is a formatting error in the page which causes the step numbering to be mess up in section 3.2. This PR corrects that, makes a few other small linting changes, and makes a small improvement to how the initial environment variables are set.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1466
csm-1.0 backport: https://github.com/Cray-HPE/docs-csm/pull/1467
N/A.
Low risk.
> CASMINST-4525: Minor linting and enhancements to Deploy Management Nodes

- .github/workflows/license-check.yaml
- .github/workflows/link-checker.yaml
- .github/workflows/markdown-lint.yaml
- .github/workflows/spell-check.yaml
Determine list of changed files only from `pull_request` event. Unfortunately, there's no way to determine list of changed files reliably for `push` event, so we'll have to skip these checks on regular push and only perform them when action is taken on existing PR. 
* Resolves [CASMINST-4539](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4539)
* Github actions on sandbox repository `test-actions`
Tested various combinations in dedicated sandbox repository. It appears that in case of triggering with `push` event, the following issues observed:
* List of files may appear empty on push
* If PR already exists, check triggered on `push` will be added as additional PR status check, which will cause confusion.
Therefore, the simple and most reliable solution is just to trigger on …
> [release/1.2] CASMINST-4539 Fix list of changed files for spell, style, link and license checks

- .github/workflows/license-check.yaml
- .github/workflows/link-checker.yaml
- .github/workflows/markdown-lint.yaml
- .github/workflows/spell-check.yaml
Determine list of changed files only from `pull_request` event. Unfortunately, there's no way to determine list of changed files reliably for `push` event, so we'll have to skip these checks on regular push and only perform them when action is taken on existing PR. 
* Resolves [CASMINST-4539](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4539)
* Github actions on sandbox repository `test-actions`
Tested various combinations in dedicated sandbox repository. It appears that in case of triggering with `push` event, the following issues observed:
* List of files may appear empty on push
* If PR already exists, check triggered on `push` will be added as additional PR status check, which will cause confusion.
Therefore, the simple and most reliable solution is just to trigger on …
> [release/1.0] CASMINST-4539 Fix list of changed files for spell, style, link and license checks

- install/prepare_site_init.md
- troubleshooting/known_issues/incorrectly_tagged_zeromq_image.md
CSM 1.0.11 introduced an issue such that the shasta-cfg `zeromq` secret generator requires the image to be tagged differently to how it was shipped in the product tarball.
This PR documents how to re-tag the image in the event that a fresh install of CSM 1.0.11 is occurring on an air-gapped system with no access to arti.dev.cray.com.
* Resolves [CAST-29739](https://jira-pro.its.hpecorp.net:8443/browse/CAST-29739)
* These changes are not required for any other release, CSM 1.2 and beyond have now switched to an artifactory.algol60.net tagged version of this image.
Ran through `prepare_site_init.md` steps using the CSM 1.0.11 PIT in a virtual machine with no network access.
Verified secrets were created correctly
```
pit:~ # …
```
> CAST-29739 - Incorrectly tagged zeromq image causes secret generation to fail

- install/deploy_management_nodes.md
- install/install_csm_services.md
Currently during the install we enable passwordless SSH at the start of the "Install CSM Services" step. There is no reason it needs to happen that far into the install. This PR moves that step to the middle of the "Deploy Management Nodes" step, which is about the earliest we can do it.
The benefit is that this will remove the requirement that installers manually enter root passwords for various operations.
Relatedly, I modified some of the commands in the "Deploy Management Nodes" procedure to take advantage of this change.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1501
I tested all of the updated commands on the PIT node on drax.
Low.
> CASMINST-4534: Enable passwordless SSH on PIT earlier in the install

- upgrade/1.2/scripts/sls/csm_1_2_upgrade/sls_updates.py
- upgrade/1.2/scripts/sls/sls_updater_csm_1.2.py
- upgrade/1.2/scripts/upgrade/util/update-customizations.sh
Renames the uai_macvlan_bridge reservation in the uai_macvlan subnet to uai_nmn_blackhole.   uai_macvlan_bridge is no longer being used.  We are repurposing that reservation to be used as the gw for the NMNLB route in UAIs.  This will block access to the NMNLB from the UAI.
* Resolves CASMTRIAGE-3253
* `hela`
Ran update-customizations.sh with the site-init secret on hela.  Checked that the NMNLB route in spec.wlm.macvlansetup.routes was updated correctly.    Ran the update-customizations.sh multiple time to check the idempotency.
Ran sls_updater_csm_1.2.py using the 1.0 sls data from Loki.   Checked that the uai_macvlan_bridge reservation was renamed correctly.
> CASMTRIAGE-3253:  Blocking access to NMNLB from UAIs

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
The primary change in this PR is a very slight change to the `csi` command used in the "Deploy Final NCN" step, so that it will only upload SquashFS images with a `secure-` filename prefix. This prefix will be there if the `ncn-image-modification.sh` script was run on the images earlier, as required for csm-1.2 installs.
This PR also contains some minor linting of a couple of pages.
* csm-1.2 backport PR: https://github.com/Cray-HPE/docs-csm/pull/1512
* csm-1.0 backport PR for just the linting parts of this PR: https://github.com/Cray-HPE/docs-csm/pull/1514
* The preflight checks performed before deploying NCNs are also being changed to help address this problem. [main PR for this test change](https://github.com/Cray-HPE/csm-testing/pull/297)
None
Very low risk.
> CASMINST-4538: Only upload customized NCN images into S3

- install/deploy_management_nodes.md
The Deploy Management Nodes procedure contains a manual validation that the etcd service is running on master nodes outside of Kubernetes. However, since csm-1.0 there has been a Goss test which does this, and that test already runs in that same procedure. Therefore I'm using this ticket to remove the manual validation step.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1527
csm-1.0 backport: https://github.com/Cray-HPE/docs-csm/pull/1528
> CASMINST-4559: Remove superfluous manual etcd master node check from Deploy Management Nodes

- install/deploy_management_nodes.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1526
> 1.2 backport: CASMINST-4559: Remove superfluous manual etcd master node check from Deploy Management Nodes

- install/deploy_management_nodes.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1526
> 1.0 backport: CASMINST-4559: Remove superfluous manual etcd master node check from Deploy Management Nodes

- upgrade/1.2/scripts/k8s/reconfigure_haproxy.sh
When running prerequisites for the second time (1.2 to 1.2 upgrade), the haproxy reconfigure script reconfigures etcd incorrectly instead of realizing kube-api has already been configured to use http.
* Resolves [CASMINST-4558](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4558)
Tested code snippet on surtur
* `surtur`
Tested code snippet on surtur
Low
> Make haproxy reconfigure script idempotent

- install/configure_administrative_access.md
- operations/firmware/Upload_Olympus_BMC_Recovery_Firmware_into_TFTP_Server.md
Added prerequisites for uploading BMC recovery firmware into tftp servers. Added a note in the install procedures to skip uploading to tftp if FAS not installed and ready, and to run the step after that has been completed.
> CASMTRIAGE-3232: Uploading BMC Recovery Firmware into TFTP Servers

- upgrade/1.2/scripts/ceph/lib/ceph-health.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
After a node has been upgraded, verify the mon daemon starts successfully after the tarfile is restored on the node.  If not, delete the daemon and let ceph create a new podman container.
* Resolves [CASMINST-4557](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4557)
```
ncn-s002:/usr/share/doc/csm/upgrade/1.2/scripts/ceph/lib # check_mon_daemon ncn-s002
Removing/restarting mon daemon for node ncn-s002...
Removed mon.ncn-s002 from host 'ncn-s002'
Sleeping for five seconds waiting for 3 running mon daemons...
Sleeping for five seconds waiting for 3 running mon daemons...
Sleeping for five seconds waiting for 3 running mon daemons...
Sleeping for five seconds waiting for 3 running mon daemons...
Sleeping for five seconds waiting for 3 running mon daemons...
Found 3 running mon …
```
> Check for running mon daemon on upgraded ceph node, restart if necessary

- upgrade/1.2/scripts/upgrade/prepare-assets.sh
Adds the --progress=dot:giga option to the wget download of the release image.
This changes the progress indicator output that gets written to the output.log file
from over 700000 lines to just a little over 1000 lines.
* Resolves [CASMINST-4561](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4561)
* surtur
Ran the prepare_assets.sh script through the download part of the script to verify it
downloaded correctly, and verified the progress output was a much smaller amount.
Low risk. Only change is the amount of output …
> Add wget progress option for image download

- operations/configuration_management/Version_Control_Service_VCS.md
- upgrade/1.2/scripts/upgrade/prerequisites.sh
Support 1.x and 1.2 gitea data path versions on upgrade (changed from /data to /var/lib/gitea).
* Resolves [CASMINST-4556](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4556)
1.0.11:
```
ncn-m001:~/bklein # ./foo.sh
Defaulting container name to vcs.
Use 'kubectl describe pod/gitea-vcs-7c6f5b5c45-tzv4q -n services' to see all of the containers in this pod.
tar: removing leading '/' from member names
data/
data/ssh/
data/ssh/ssh_host_rsa_key.pub
data/ssh/ssh_host_rsa_key
data/ssh/ssh_host_dsa_key
data/ssh/ssh_host_ecdsa_key.pub
data/ssh/ssh_host_ecdsa_key
data/ssh/ssh_host_dsa_key.pub
data/ssh/ssh_host_ed25519_key
data/ssh/ssh_host_ed25519_key.pub
data/gitea/
data/gitea/curl
data/gitea/crayvcs_user_created
.
.
.
```
1.2:
```
ncn-m001:~/bklein # ./foo.sh
Defaulting container name to …
```
> Change vcs backup path for gitea 1.2

- upgrade/1.2/scripts/rebuild/ncn-rebuild-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
There is a syntax error in two scripts where the "let" command was used without quotes:
```
arbus:$ count=1
arbus:$ let count += 1
-bash: let: +=: syntax error: operand expected (error token is "+=")
arbus:$ echo $count
1
arbus:$ let "count += 1"
arbus:$ echo $count
2
```
On the vale system, this was worked around by removing the spaces, it may also be resolved by quoting the arguments to let. This error may have not have occurred in the past as the "cray cps deployments list ..." command worked the first time.
* Resolves CASMTRIAGE-3306
Tested locally and on `vale`
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Impacted script was rerurn with the fix
- Were continuous integration tests run? If not, why? N
- Was upgrade tested? If not, …
> Fix syntax for let command

- upgrade/1.2/scripts/ceph/lib/ceph-health.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Move mon test to health check to give ceph a chance to come up before intervening.
* Resolves [CASMINST-4594](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4594)
drax
* `drax`
Jim is trying s003 with the fix
Low
> Check mon status after we've waited for good health first

- install/install_csm_services.md
- upgrade/1.0.1/scripts/upgrade/add_pod_priority.sh
- upgrade/1.0.11/scripts/upgrade/add_pod_priority.sh
Take a backup of bss before applying pod priorities, wait for deployments/statefulsets/daemonsets to roll out with their changes, as well as introduce a delay after re-adding a node to give the etcd operator a chance to complete a reconcile.
* Resolves [CASMINST-4597](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4597)
```
surtur-ncn-m001-pit:/usr/share/doc/csm/upgrade/1.0.11 # ./scripts/upgrade/add_pod_priority.sh
Found 3 running pods in cray-bss-etcd etcd cluster
Found 3 ready members in cray-bss-etcd etcd cluster
Found status of Running for cray-bss-etcd etcd cluster
Sleeping for thirty seconds to let the etcd operator reconcile
Creating csm-high-priority-service pod priority class
priorityclass.scheduling.k8s.io/csm-high-priority-service configured
Patching cray-bss deployment …
```
> Take a backup before applying pod priorities to bss-etcd and add some delays for the etcd operator to reconcile

- .github/workflows/spell-check.yaml
Coloring is off in spell checker log, which makes it hard to identify which word is misspelled. Spell checker prints entire sentence, and it's not clear which word is misspelled. This change enforces color indication of misspelled word.
* Resolves [CASMINST-4602](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4602)
Will add and revert a dummy commit to this PR to introduce a change in markdown file.
* Workflow run: https://github.com/Cray-HPE/docs-csm/runs/6373973422?check_suite_focus=true
Low  - non-mandatory check on docs build.
> CASMINST-4602 Fix coloring in spell checker workflow [release/1.2]

- .github/workflows/spell-check.yaml
- README.md
Coloring is off in spell checker log, which makes it hard to identify which word is misspelled. Spell checker prints entire sentence, and it's not clear which word is misspelled. This change enforces color indication of misspelled word.
* Resolves [CASMINST-4602](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4602)
Will add and revert a dummy commit to this PR to introduce a change in markdown file.
* Workflow run: https://github.com/Cray-HPE/docs-csm/runs/6373973422?check_suite_focus=true
Low  - non-mandatory check on docs build.
> CASMINST-4602 Fix coloring in spell checker workflow [main]

- .github/workflows/spell-check.yaml
Coloring is off in spell checker log, which makes it hard to identify which word is misspelled. Spell checker prints entire sentence, and it's not clear which word is misspelled. This change enforces color indication of misspelled word.
* Resolves [CASMINST-4602](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4602)
Will add and revert a dummy commit to this PR to introduce a change in markdown file.
* Workflow run: https://github.com/Cray-HPE/docs-csm/runs/6373973422?check_suite_focus=true
Low  - non-mandatory check on docs build.
> CASMINST-4602 Fix coloring in spell checker workflow [release/1.0]

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Now that the precache chart is upgraded in prereqs, and the chart has a wait for job that ensures the pods are running and have cached their images, we can remove the explicit image pulls during prereqs.  The pods will re-try every two minutes to pull the images and be easier on nexus.
* Resolves [CASMINST-4604](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4604)
Saw the failure on surtur, re-running succeeded.
Low
> Remove redundant/explicit image pulls during prerequisites

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Adds a final step the the K8S Cert renewal to update the client cert for kube-etcdbackup
* Resolves [CASMPET-5608](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5608)
* Change will also be needed in release/1.2, release/1.0
vshasta and PDC/KTH (system has been installed using CSM 0.9.5 one year ago)
- Was downgrade …
> CASMPET-5608 : Update Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD for kube-etcdbackup client cert

- update_product_stream/index.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1594
> csm-1.0 backport: CASMINST-4599: Download docs-csm RPM so that it overwrites existing copies

- update_product_stream/index.md
- upgrade/1.2/Stage_0_Prerequisites.md
In a couple of places in the docs we download the docs-csm RPM using a wget command which will not overwrite an existing docs-csm RPM file in the same location. Instead it will create a "docs-csm...-1" file. If the user does not notice this, they may then install the previous RPM rather than the new one.
This PR modifies those wget commands to use the -O option, which will overwrite the target if it exists.
Backport PR forthcoming
I manually tested the new commands to make sure that they correctly overwrote the existing files as desired.
Low risk.
> CASMINST-4599: Download docs-csm RPM so that it overwrites existing copies

- scripts/operations/gateway-test/uai-gateway-test.sh
The new version of the uai-gateway-test.sh does not work with the 1.6.0 version of the gateway-test image.    When we do a 1.2 -> 1.2 upgrade, we discovered that we can end up with both the old (1.6.0) and new (1.6.1) image registered in uas.   The uai-gateway-test.sh currently grabs the first one it finds which is 1.6.0.   
To deal with this, I'm sorting the gateway-test images and grabbing the last one.   This is a best-effort sort since any number of additional images could be added.   To be safe, I am also filtering out 1.6.0 from the list since we know that one does not work with the latest uai-gateway-test.sh.
* Resolves CASMINST-4603
* `surtur` and `wasp`
I am no longer able to test the condition that initiated this ticket.   This happened on the 1.2 -> 1.2 upgrade on drax. …
> CASMINST-4603: Filter out 1.6.0 gateway-test images and grab the latest

- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
Remove wait for CPS pods to start after worker upgrade and cps is redeployed
* Resolves [CASMINST-4611](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4611)
Being tested on vale currently
* `vale`
In progress
Low
> Remove wait for CPS pods to start after worker upgrade and cps is redeployed

- .spelling
- operations/validate_csm_health.md
Add note about etcd restore resulting in an etcd pod w/out a PVC, which causes the SMS tests to fail.
* Resolves [CASMINST-4610](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4610)
N/A
N/A
N/A
Low
> Add note about SMS test failure after etcd restore

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- scripts/operations/configuration/write_root_secrets_to_vault.py
It is common for csm-1.2 installs to encounter issues after running NCN personalization because of bad or incomplete data written to Vault for the root password or root SSH keys. This PR creates a script which automates the common case of this process (namely, it reads in the current root password hash and SSH keys from the NCN, writes them to vault, and then reads them back to verify that it succeeded). The PR also updates the associated docs to include the script (and to recommend it as the default). 
Further work will be required to refine the documentation in this area, but this alleviates the worst of the problems.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1612
I have run the script on hela, mug, and wasp and verified that it performs as expected. I tested it again …
> CASMINST-4475: Create script to write root password and SSH keys to Vault; document same

- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- scripts/operations/configuration/write_root_secrets_to_vault.py
Backport of https://github.com/Cray-HPE/docs-csm/pull/1611
> csm-1.2 backport: CASMINST-4475: Create script to write root password and SSH keys to Vault; document same

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
These are small corrections (and associated linting) to errors found in the bootstrap procedures during the hermod csm-1.2.0-rc.2 install. There are content changes here, but they are minor.
The main corrections are:
* The bootstrap remoteISO procedure tries to mount PITDATA twice. The second mount command fails (because it is already mounted), and this causes some mkdir commands to not run. The fix is just to remove the superfluous second mount command. This issue does not exist in the USB bootstrap procedure.
* In both remoteISO and USB bootstrap procedures, the command to install the cray-site-init RPM does not include the --force flag. On the hermod install, this resulted in the rpm install command failing, because the RPM was already installed at the same level. In our case, we …
> Corrections to install bootstrap PIT procedures

- install/bootstrap_livecd_remote_iso.md
csm-1.0 backport of https://github.com/Cray-HPE/docs-csm/pull/1622 (but only the fix for [CASMINST-4629](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4629), as the other two issues don't exist in the csm-1.0 bootstrap docs.
> csm-1.0 backport: Corrections to install bootstrap PIT procedures

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
During the mug install I noticed some small errors in the docs, and some areas for improvement. This PR contains those, plus the necessary linting to make the style and spell checkers happy.
One thing I removed was a step in Deploy Final NCNs which had the installer change the NCN root password if they didn't customize it in the NCN image. Now that we require it to be customized in the image, that step is no longer needed.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1562
csm-1.0 backport: https://github.com/Cray-HPE/docs-csm/pull/1563
> CASMINST-4589: Install document linting, corrections, and improvements

- install/deploy_management_nodes.md
Some of the manual checks from the Deploy Management Nodes procedure have been replaced by automated tests. This ticket updates the procedure to omit the manual checks that are no longer needed.
There is a csm-1.2 backport for this, but it does not remove everything that this one does, because some of the test changes were held back from csm-1.2.
Backport PR forthcoming.
We have been testing the new automated tests for weeks now. In that time we haven't seen anything get caught by the redundant manual checks that was missed by the automated tests.
Very low risk -- just removing steps.
> CASMINST-4631: Remove now-automated manual steps from Deploy Management Nodes

- upgrade/1.2/Stage_0_Prerequisites.md
The `curl` command used to upload the migrated data to SLS can fail silently if the `TOKEN` environment variable is not set leading an admin to believe that the upload has been successful when it has not.
This PR introduces the `--fail` option to the `curl` command so that the HTTP return code is printed if the command fails.
* Resolves [CASMNET-1546](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1546)
* `hela`
Verified the desired change in behaviour introduced by the `--fail` option.
```
curl: (22) The requested URL returned error: 503
```
Without this option the same command fails silently
```
ncn-m001:~/cspiller/sls_updater # curl -H "Authorization: Bearer ${TOKEN}" -k -L -X POST 'https://api-gw-service-nmn.local/apis/sls/v1/loadstate' -F 'sls_dump=@sls_input_file.json' …
```
> Ensure command to upload migrated SLS file does not fail silently due to errors

- upgrade/1.2/scripts/sls/csm_1_2_upgrade/sls_updates.py
- upgrade/1.2/scripts/sls/sls_updater_csm_1.2.py
Previously if a BICAN, CMN or CHN networks existed in the SLS file to be upgraded by `sls_updater_csm_1.2.py`, the upgrade process would provide an informational warning but continue onward, often failing in a later step.  These networks are new artifacts in CSM 1.2.  The upgrader exists explicitly in the 1.0 to 1.2 upgrade section of the docs and 1.2-to-1.2 upgrades were not expected given location.  
This change allows processing of a previously upgraded 1.2 SLS file in an idempotent manner.  The behavior is as follows if a 1.2 SLS file is discovered:
1. SKIP: Migrate switch naming (in order): leaf to leaf-bmc and agg to leaf.
2. Remove api-gateway entries from HMLB subnets for CSM 1.2 security.\n
3. Remove kubeapi-vip reservations for all networks except NMN.\n
4. SKIP: Create the new …
> CASMINST-4560 - Do not allow upgrader to run on CSM 1.2 or later SLS files

- install/create_hmn_connections_json.md
Use CSM_PATH instead of CSM_RELEASE when generating hmn_connections.json.
* Resolves CASMINST-4630
* Hermod
Tested these changes on Hermod while fresh install CSM 1.2. …
> CASMINST 4630: Use CSM_PATH instead of CSM_RELEASE when generating hmn_connections.json

- install/create_hmn_connections_json.md
Use CSM_PATH instead of CSM_RELEASE when generating hmn_connections.json.
* Resolves CASMINST-4630
* Hermod
Tested these changes on Hermod while fresh install CSM 1.2. …
> (main) CASMINST-4630: Use CSM_PATH instead of CSM_RELEASE when generating hmn_connections.json

- .vscode/settings.json
- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/collect_mac_addresses_for_ncns.md
- install/collecting_bmc_mac_addresses.md
- install/deploy_management_nodes.md
- install/restart_network_services_and_interfaces_on_ncns.md
- operations/firmware/FAS_Admin_Procedures.md
- operations/kubernetes/Restore_Postgres.md
- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
- operations/node_management/Build_NCN_Images_Locally.md
- operations/node_management/Reboot_NCNs.md
- operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
- operations/power_management/Standard_Rack_Node_Power_Management.md
- troubleshooting/pxe_runbook.md
Correcting several instances throughout the docs where fenced code blocks start with a triple-backtick marker
but are never closed with a corresponding one.
* Resolves [STP-3186](https://jira-pro.its.hpecorp.net:8443/browse/STP-3186) and https://github.com/Cray-HPE/docs-csm/issues/952
* Change will also be needed in `release/1.2` and `main`
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1310 and https://github.com/Cray-HPE/docs-csm/pull/1476
N/A
N/A
N/A
None.
> STP-3186 (1.0): correcting broken fenced code blocks

- operations/node_management/Configure_NTP_on_NCNs.md
Uses the full path for `csm_ntp.py`
* Resolves  CASMINST-4625
* 
N/A
Low
> CASMINST-4625 use full path for csm_ntp.py

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
Omits the need for getting a `TOKEN` to run `csm_ntp.py`.  Also adjust the successful output so the user can see that it is a success.
* Resolves CASMINST-4646
* Introduced in CASMTRIAGE-3336
* `#redbull`
Low
> CASMINST-4646 run csm_ntp.py during fresh installs

- upgrade/1.2/scripts/sls/sls_updater_csm_1.2.py
The fix for CASMINST-4560 to allow running the SLS updater on 1.2->1.2 upgrades had an ordering issue that caused it to skip converting the 1.0 CAN to the 1.2 CAN.   This resulted in incorrect CIDR and VLANID for the CAN network in SLS.
We are using the existence of the BICAN network as an indicator of whether the current configuration is 1.0 or 1.2.   The issue was that we are adding the BICAN network part-way through the process. That caused the rest of the script to think it was a 1.2 config when it was 1.0.   The fix was simply to move the creation of the BICAN network to the last step after it has done all other modifications.
* Resolves CASMINST-4649
* `surtur`
The following tests were performed:
* Ran the fixed sls_updater_csm_1.2.py on the 1.0 SLS data on surtur.   
** Verified …
> CASMINST-4649:  Fix sls updater ordering

- .github/workflows/markdown-lint.yaml
- runLint.sh
Example of a successful run:
```bash
=============== Linting \” (https://www.compart.com/en/unicode/U+201C and U+201D) ...
OK: check_quotes
```
Example of a discovered, directional quote:
```bash
=============== Linting \” (https://www.compart.com/en/unicode/U+201C and U+201D) ...
index.md:2:”
Malformed quotes detected (bad: ” vs. good: ").
Failed: check_quotes
```
N/A
* Resolves [CASMINST-4648](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4648)
* …
> [release/1.2] CASMINST-4648 Ensure no directional quotes exist

- .github/workflows/markdown-lint.yaml
- runLint.sh
Example of a successful run:
```bash
=============== Linting \” (https://www.compart.com/en/unicode/U+201C and U+201D) ...
OK: check_quotes
```
Example of a discovered, directional quote:
```bash
=============== Linting \” (https://www.compart.com/en/unicode/U+201C and U+201D) ...
index.md:2:”
Malformed quotes detected (bad: ” vs. good: ").
Failed: check_quotes
```
N/A
* Resolves [CASMINST-4648](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4648)
* …
> [release/1.0] CASMINST-4648 Ensure no directional quotes exist

- .github/workflows/markdown-lint.yaml
- runLint.sh
Example of a successful run:
```bash
=============== Linting \” (https://www.compart.com/en/unicode/U+201C and U+201D) ...
OK: check_quotes
```
Example of a discovered, directional quote:
```bash
=============== Linting \” (https://www.compart.com/en/unicode/U+201C and U+201D) ...
index.md:2:”
Malformed quotes detected (bad: ” vs. good: ").
Failed: check_quotes
```
N/A
* Resolves [CASMINST-4648](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4648)
* …
> CASMINST-4648 Ensure no directional quotes exist

- operations/kubernetes/Backups_for_etcd-operator_Clusters.md
Move the User Access Service (UAS) from the list of services that use etcd and are not automatically backed up to the list of services that use etcd and are automatically backed up, since that is now true as of CSM release 1.2.
Backward compatible change
* Resolves [CASMINST-4609](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4609)
Verified that cray-uas-mgr was in the list of services to be backed up daily with in etcd-backup configuration and verified that I could create a backup of the cray-uas-mgr etcd contents and then restore it using the standard procedures for backup and restore.  Verified that the backed up configuration was restored as expected and the UAS saw the newly restorred configuration correctly.
- Were the install/upgrade-based validation …
> CASMINST-4609 Move UAS from non-backed-up to backed up etcd

- .github/config/markdown_style.yaml
- .spelling
- operations/validate_csm_health.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_1.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/Stage_4.md
- upgrade/1.2/Stage_5.md
- upgrade/index.md
Much of this PR is linting, large and small. The most noteworthy non-linting changes are:
* The Stage 5 NCN personalization instructions, as written, resulted in existing layers being removed. This corrects that.
* The list of Ceph process types in Stage 4 omitted the "crash" type
* Changed some of the Stage 4 Ceph steps to be clearer and more explicit in what is being checked.
* Removed the outdated ncn-w001/UAI limitation from the health validation procedures.
* Added a note to the health validation procedures for the UAI gateway test that the docs-csm RPM must be installed.
There were a number of other small corrections.
There will be backport PRs (although only a limited slice of the changes will be backported to csm-1.0).
In any case where commands were altered, I tested them during …
> CASMINST-4644: Upgrade procedure linting, fixes, and improvements

- install/deploy_final_ncn.md
- upgrade/1.2/Stage_2.md
Switches CAN to CMN in 2 spots where appropriate.
* Resolves [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549)
* `Redbull`
Tested on Redbull by booting the images and manually running the template file.
> CASMNET-1549: Switch 'CAN' to 'CMN'

- operations/spire/Restore_Spire_Postgres_without_a_Backup.md
This fixes some issues where spacing would cause the command to try to run rm / if you copy/pasted it. It also replaces the sysmgmt hand-edits with a for loop that will reduce errors and prevent the sysmgmt.yaml that's saved in the loftsman namespace from being overwritten. Commands were tested on Loki.
> CASMPET-5593 Update spire postgres without backup restore doc

- scripts/operations/gateway-test/uai-gateway-test.sh
There was one cray command in the `uai-gateway-test.sh` that did not specify the output format and relied on the default `toml` format.   This causes problems when the `CRAY_FORMAT` environment is set and it is not `toml`.
I checked all other gateway tests to make sure there were no other cases of this.
* Resolves CASMINST-4702
* `hermod`
I ran the `uai-gateway-test.sh` with `CRAY_FORMAT` unset, with `CRAY_FORMAT=toml`, and with `CRAY_FORMAT=json`.   The test ran successfully in all cases.
> CASMINST-4702: Make sure the --format is specified in all cray commands in gateway tests

- upgrade/1.2/scripts/rebuild/ncn-rebuild-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
I found a few cases in our scripts where we rely on the Cray CLI output being in a specific format, but we do not use the --format command line argument. This ticket just adds that argument in those cases. The changes are tiny and it is very clear that these commands will fail if the wrong format is used.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1702
The risk of not fixing this is worse than the tiny risk of this accidentally introducing an error. The changes are so small that it is very easy to see their impact.
> CASMINST-4707: Specify Cray CLI output format when it matters

- operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md
Fix multiple issues in the storage rebuild instructions related to RGW placement and the configuration of apparmor, haproxy, and keepalived.
* Resolves [CASMINST-4725](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4725)
```
ncn-m001:~ # pdsh -w ncn-s00[1-3] -f 2 'source /srv/cray/scripts/metal/update_apparmor.sh ; reconfigure-apparmor; /srv/cray/scripts/metal/generate_haproxy_cfg.sh > /etc/haproxy/haproxy.cfg; systemctl enable haproxy.service; systemctl restart haproxy.service; /srv/cray/scripts/metal/generate_keepalived_conf.sh > /etc/keepalived/keepalived.conf; systemctl enable keepalived.service; systemctl restart keepalived.service'
ncn-s001: Reconfiguring apparmor for haproxy
ncn-s002: Reconfiguring apparmor for haproxy
ncn-s003: Reconfiguring apparmor for haproxy
```
* …
> Fix rebuild instructions for RGW deployment

- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
Add missing `\` on command continuation
> CASMINST-4727: add missing `\` on command continuation

- operations/node_management/Configure_NTP_on_NCNs.md
Adds an explicit step to export the token for use in `csm_ntp.py`
* Resolves CASMINST-4709
* `#redbull`
```
ncn-s004:~ # TOKEN=token
ncn-s004:~ # /srv/cray/scripts/common/chrony/csm_ntp.py
You must set BSS TOKEN environment variable
ncn-s004:~ # export TOKEN
ncn-s004:~ # /srv/cray/scripts/common/chrony/csm_ntp.py
Chrony configuration created
Problematic config found: /etc/chrony.d/cray.conf.dist
Problematic config found: /etc/chrony.d/pool.conf
Restarted chronyd
```
Low.
> CASMINST-4709 export token for ntp script

- .spelling
- operations/kubernetes/Troubleshoot_Postgres_Database.md
- operations/network/management_network/aruba/ntp.md
- operations/network/management_network/dell/ntp.md
- operations/network/management_network/mellanox/ntp.md
Corrects a couple more triple-backtick code-block formatting errors
> More incorrect triple-backtick code block formatting

- .spelling
- install/bootstrap_livecd_usb.md
**This is a fix for a RELEASE_CRITICAL ticket -- prompt reviews appreciated**
When setting variables after booting to the USB PIT node, they must also be exported, in order to make them available after the typescript is started. This PR just does that (and slightly rewords the description of the step, to include that we are exporting them).
Backport PRs:
This fix is not needed in 1.0, because the USB bootstrap procedure is different for that release. However, this PR also adds Podman to the spelling file. We should keep the three spelling files common, I think, so the 1.0 backport PR contains just that commit.
csm-1.2: https://github.com/Cray-HPE/docs-csm/pull/1726
csm-1.0 (spelling file addition only): https://github.com/Cray-HPE/docs-csm/pull/1725
I tested that exporting the variables …
> CASMINST-4736: Export environment variables to make them available after starting typescript

- operations/network/management_network/bican_enable.md
- scripts/operations/bifurcated_can/bican_route.py
Generally, once the BICAN "toggle" is set in SLS, system installation and upgrades will process the information and "do the right thing" as a part of normal process.  This document describes the automatic process steps as well as providing more details, validation and remediation for enabling Bifurcated-CAN to either CAN (management network pathing), or CHN (Highspeed network pathing).   Particular emphasis is given to cut-over to CHN as well as procedures for NCN, UAN and UAI.
* Resolves CASMINST-4135
* Requires CASMNET-1543 (CHN compute IPs)
* Hela
Each section was tested individually.
> CASMINST-4135 - BICAN cutover procedure

- .spelling
- install/collecting_ncn_mac_addresses.md
Backport PR for: https://github.com/Cray-HPE/docs-csm/pull/1743
(just the fixes, without the linting and other minor improvements)
> csm-1.2 backport: CASMINST-4747: Collect NCN MAC addresses: Fix command error and add missing step to recovery procedure

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
This relates to CAST-29991 - During cert renewal, the etcd-client-cert secret used by the prometheus active targets to connect from the worker node to the master nodes to check etcd metrics also needed to be updated. 
* Resolves [CASMPET-5641](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5641)
* Change will also be needed in main, 1.2 and 1.0 branches
vshasta
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …
> CASMPET-5641 1.0 : DOCS: Regenerate the 'etcd-client-cert' secret in the sysmgmt-health namespace

- install/deploy_final_ncn.md
The Deploy Final NCN procedure has a redundant instruction to set an API token, when one was just set two steps earlier. This removes it (but does note that it is required).
No main branch PR needed because the chrony step is not in the 1.3 procedure.
> CASMINST-4758: Remove redundant instruction to set API token from Deploy Final NCN procedure

- troubleshooting/known_issues/craycli_403_forbidden_errors.md
Modify the procedure to restart the keycloak-users-localize job to delete and re-create instead of re-apply.
* Resolves [CASMTRIAGE-3444](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3444)
* Change will also be needed in main, release/1.2 and release/1.0
Testing in vale and vshasta
Vale hit a case where keycloak-users-localize job was incrementally added more users each time the job ran which is not the expected behavior. After deleting and re-creating the job, all LDAP users were successfully …
> CASMTRIAGE-3444 main : DOCS : keycloak-users-localize is not grabbing all of the user defined in LDAP

- operations/network/metallb_bgp/Check_BGP_Status_and_Reset_Sessions.md
CSM 1.2 updates the version of the MetalLB chart and the MetalLB config is now passed into the chart via `customizations.yaml`.
The procedure to reset BGP/MetalLB does not take this into account and uninstalls the `cray-metallb` chart then redeploys it with no configuration.
* Resolves [CASMTRIAGE-3449](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3449)
* Change will also be needed in `main`
* `hermod`
Followed procedure and verified BGP sessions were established.
> CASMNET-1588 - Update BGP/MetalLB reset procedure to incorporate config from customizations.yaml

- troubleshooting/known_issues/craycli_403_forbidden_errors.md
Modify the procedure to restart the keycloak-users-localize job to delete and re-create instead of re-apply.
* Resolves [CASMTRIAGE-3444](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3444)
* Change will also be needed in main, release/1.2 and release/1.0
Testing in vale and vshasta
Vale hit a case where keycloak-users-localize job was incrementally added more users each time the job ran which is not the expected behavior. After deleting and re-creating the job, all LDAP users were successfully …
> CASMTRIAGE-3444-1.0 : DOCS : keycloak-users-localize is not grabbing all of the user defined in LDAP

- .spelling
- install/collecting_ncn_mac_addresses.md
This ticket corrects two problems seen during the tyr CSM install.
1. One of the copy commands has a syntax error (an asterisk that should not be there), which causes it to fail. This ticket corrects that.
2. The recovery procedure should also specify that BMCs need to be reset to DHCP in some cases. This ticket adds that information.
3. I also included a commit which does linting and other minor improvements. I will not include that commit in the backport PRs, since I know that 1.2 is locked down.
csm-1.2 backport: https://github.com/Cray-HPE/docs-csm/pull/1744
I put my csm-1.0 backport into a PR of Ryan's that was already editing the same file:
https://github.com/Cray-HPE/docs-csm/pull/1677
We used the correct command and missing step during the tyr install.
Much riskier to omit the …
> CASMINST-4747: Collect NCN MAC addresses: Fix command error and add missing step to recovery procedure

- .spelling
- install/collect_mac_addresses_for_ncns.md
- install/collecting_bmc_mac_addresses.md
- install/collecting_ncn_mac_addresses.md
- install/deploy_management_nodes.md
- install/prepare_site_init.md
CASMINST-4664: Improvements from my experience fresh installing Hermod
- All modified files were updated to appease the markdown linter.
- Collect MAC Addresses for NCNs:
- Changed "Remove" to "Rename" in some steps to reflect the intent of the step better
- Add an exit code check to grep checking for the placeholder MACs
- Collecting BMC MAC addresses
- Use ipmitool locally to extract ncn-m001's BMC
- Collecting NCN MAC Addresses:
- Add a step to power off NCNs after collecting MAC addresses
- Deploy management nodes
- Add command example to power off NCNs after verifying node time
- Prepare Site-init
- Add better descriptions for the BMC & SNMP credentails …
> CASMHMS-4664: Improvements from my experience fresh installing Hermod / CASMINST-4747 backport

- install/shcd_hmn_connections_rules.md
Amongst the 21 files that have tables in them,  as found by 
`grep -r "| ---" .`
only **one**, although one that I just happened to be looking at for info,
`./install/shcd_hmn_connections_rules.md`
has tables without a blank line after the table blocks.
The lack of that blank line, whilst clearly not fazing some MD renderers,
causes issue for Jekyll.
Adding a blank line makes the MD source a bit more readbale anyway,
so why not put them in?
Update from Mitch: I created backport PRs for this:
https://github.com/Cray-HPE/docs-csm/pull/1765
https://github.com/Cray-HPE/docs-csm/pull/1766
> Add blank lines after table block

- install/configure_administrative_access.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/configure_cray_cli.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1749
> csm-1.2 backport: CASMINST-4759: Correct minor install docs issues

- operations/CSM_product_management/Configure_Compute_Nodes_with_CFS.md
- operations/index.md
This adds documentation for adding a new playbook (https://github.com/Cray-HPE/csm-config/pull/54/files) to the configuration that is applied to Compute images.  This will be the new method of deploying the CFS and BOS reporters.
* Resolves CASMCMS-6989
* NA, docs only.  Code from other PR was tested on Hela
NA, docs only
None
> CASMCMS-6989: Add docs for applying CSM configuration to compute images

- .github/workflows/shell-check.yaml
Existing shell check causes confusion - it checks all sh files in repo, and error result is hard for interpretation. This PR changes behavior:
* Only files changed within current PR are checked (inline with other checks)
* Output is easy to interpret
* Resolves [CASMINST-4786](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4786)
* Github action runs
Temporarily added a commit to this PR, which introduces shell check violation. Violation was successfully detected and clearly explained - this tests for false positive: …
> CASMINST-4786 Rework shell check [main]

- .github/workflows/shell-check.yaml
Existing shell check causes confusion - it checks all sh files in repo, and error result is hard for interpretation. This PR changes behavior:
* Only files changed within current PR are checked (inline with other checks)
* Output is easy to interpret
* Resolves [CASMINST-4786](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4786)
* Github action runs
Temporarily added a commit to this PR, which introduces shell check violation. Violation was successfully detected and clearly explained - this tests for false positive: …
> CASMINST-4786 Rework shell check [release/1.0]

- .github/workflows/shell-check.yaml
Existing shell check causes confusion - it checks all sh files in repo, and error result is hard for interpretation. This PR changes behavior:
* Only files changed within current PR are checked (inline with other checks)
* Output is easy to interpret
* Resolves [CASMINST-4786](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4786)
* Github action runs
Temporarily added a commit to this PR, which introduces shell check violation. Violation was successfully detected and clearly explained - this tests for false positive: …
> CASMINST-4786 Rework shell check [release/1.2]

- operations/validate_csm_health.md
Adds instructions for running the gateway tests externally to the CSM validation.
* Resolves CASMNET-1588
* docs only
> CASMNET-1588:  Add link to instructions for running gateway tests externally

- .github/config/markdown_style.yaml
- .spelling
- RELEASE_NOTES.md
- glossary.md
- introduction/differences.md
- operations/compute_rolling_upgrades/CRUS_Workflow.md
- operations/compute_rolling_upgrades/Compute_Rolling_Upgrades.md
- operations/compute_rolling_upgrades/Troubleshoot_Nodes_Failing_to_Upgrade_in_a_CRUS_Session.md
- operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Bad_Parameters.md
- operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Unmet_Conditions.md
- operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md
- operations/index.md
- operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
- troubleshooting/index.md
Make sure the messaging is consistent and visible that CRUS is deprecated in csm-1.2 and will be removed in a future release.
This needs to make it into the csm-1.2 docs that we ship with.
- Resolves [CASMCMS-7991](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7991)
- Relates to [CASMCMS-7704](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7704)
- [main backport](https://github.com/Cray-HPE/docs-csm/pull/1790)
- Backport PRs forthcoming
> CASMCMS-7991: Add/update CRUS deprecation notices

- operations/node_management/Reboot_NCNs.md
The NCN reboot procedure currently includes a call to the `csi` tool. However, that tool is only available on the PIT node, and it is inconvenient at best to manually retrieve it. However, in this case the tool is just being used to call the Goss Postgres tests, and there already is a Goss script which does this same thing. Thus, there is no need to involve the `csi` tool here. This ticket replaces the call to the `csi` tool with a call to the appropriate Goss script.
- Resolves [CASMINST-4696](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4696).
- [1.2 backport PR](https://github.com/Cray-HPE/docs-csm/pull/1785)
- No 1.0 backport is needed because that version of the procedure used the old Postgres health check shell script
I ran the Goss suite on hela and verified that it runs …
> CASMINST-4696: Replace csi call with Goss script in NCN reboot procedure

- operations/kubernetes/Troubleshoot_Postgres_Database.md
In the past, usually during upgrades, issues have been seen where the Postgres information reported by `patronictl` conflicts with the Postgres status reported by querying Postgres members using `curl`. 
Some of the remediation procedures used to recover from this are already included in our Postgres troubleshooting documentation, but I did not find a section about the specific case of this conflicting information. This ticket adds steps to check for that, and if it is found, points to the remediation steps that were successful when this situation was encountered during upgrades.
- Resolves [CASMINST-3459](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3459).
- [main backport PR](https://github.com/Cray-HPE/docs-csm/pull/1782)
- [1.0 backport …
> CASMINST-3459: Add procedure to detect and remediate inconsistent Postgres cluster states

- .github/config/markdown_style.yaml
- .spelling
- glossary.md
- introduction/differences.md
- operations/compute_rolling_upgrades/CRUS_Workflow.md
- operations/compute_rolling_upgrades/Compute_Rolling_Upgrades.md
- operations/compute_rolling_upgrades/Troubleshoot_Nodes_Failing_to_Upgrade_in_a_CRUS_Session.md
- operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Bad_Parameters.md
- operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Unmet_Conditions.md
- operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md
- operations/index.md
- operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
- troubleshooting/index.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1789
Modified the notification language to indicate the future deprecation (in csm-1.2).
> 1.0 backport: CASMCMS-7991: Add/update CRUS deprecation notices

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1781
I also backported a few linting commits that had been made to this file in 1.2 but had not been made in 1.0, which was causing my backport to fail due to conflicts.
> [Backport release/1.0] CASMINST-3459: Add procedure to detect and remediate inconsistent Postgres cluster states

- troubleshooting/index.md
- troubleshooting/known_issues/kafka_upgrade_failure.md
- upgrade/1.2/README.md
- upgrade/1.2/Stage_3.md
This adds documentation for fixing the shared-kafka cluster if it fails to upgrade properly during upgrade due to a race condition.
> CASMPET-5700 Add kafka upgrade failure docs

- .spelling
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
CASMTRIAGE-3411 was opened during the csm-1.2 install of tyr. The short version is that the NCN image modification script behaved in a way that the installer did not expect, and it resulted in a mismatch of SSH keys on the NCNs. This was not a bug in the script, but resulted because of how it was documented. After I determined the root cause of what had happened during that install, I opened CASMINST-4790 to address a couple of specific issues that helped cause the situation. However, in the course of making those changes I realized that the page as a whole is not easy to follow for people who are not that familiar with the process. So I used this PR to not only correct the specific problems we saw on tyr, but also to reorganize the page to make it more user friendly.
The actual procedure …
> CASMINST-4790: Reorganize and clarify NCN image modification instructions

- .github/CODEOWNERS
Taking a stab at adding a codeowners.
This was created initially by @mitcharf and @rustydb.
Once this PR has approvals and has addressed any feedback backports will be created.
Backports:
- https://github.com/Cray-HPE/docs-csm/pull/1829
- https://github.com/Cray-HPE/docs-csm/pull/1830
> CASMINST-4740 CODEOWNERS

- .github/CODEOWNERS
Taking a stab at adding a codeowners.
This was created initially by @mitcharf and @rustydb.
Once this PR has approvals and has addressed any feedback backports will be created.
For simplicity this was copied directly from `main`, it may include folders that do not exist.
> CASMINST-4740 1.0

- .github/CODEOWNERS
Taking a stab at adding a codeowners.
This was created initially by @mitcharf and @rustydb.
Once this PR has approvals and has addressed any feedback backports will be created.
For simplicity this was copied directly from `main`, it may include folders that do not exist.
> CASMINST-4740 1.2

- operations/validate_csm_health.md
- scripts/operations/pyscripts/pyscripts/__init__.py
- scripts/operations/pyscripts/pyscripts/cli.py
- scripts/operations/pyscripts/pyscripts/commands/__init__.py
- scripts/operations/pyscripts/pyscripts/commands/cmd_test_bican_external.py
- scripts/operations/pyscripts/pyscripts/commands/cmd_test_bican_internal.py
- scripts/operations/pyscripts/pyscripts/commands/test_bican_external/__init__.py
- scripts/operations/pyscripts/pyscripts/commands/test_bican_external/can_toggle_tests_external.yaml
- scripts/operations/pyscripts/pyscripts/commands/test_bican_external/chn_toggle_tests_external.yaml
- scripts/operations/pyscripts/pyscripts/commands/test_bican_external/test_bican_external.py
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/__init__.py
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/can_toggle_tests.yaml
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/chn_toggle_tests.yaml
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/test_bican_internal.py
- scripts/operations/pyscripts/pyscripts/core/__init__.py
- scripts/operations/pyscripts/pyscripts/core/csm_api_utils.py
- scripts/operations/pyscripts/pyscripts/core/log_config.py
- scripts/operations/pyscripts/pyscripts/core/ssh/__init__.py
- scripts/operations/pyscripts/pyscripts/core/ssh/ssh_connection.py
- scripts/operations/pyscripts/pyscripts/core/ssh/ssh_host.py
- scripts/operations/pyscripts/pyscripts/core/ssh/ssh_targets.py
- scripts/operations/pyscripts/setup.py
- scripts/operations/pyscripts/start.py
This introduces automated SSH access tests for the BiCAN test plan. Features:
1. Internal and external testing of SSH access
2. Automatically detects whether using CHN or CAN bican toggle.
3. Customizable tests: choose which node types to test from, which node types to test to, and over which networks
4. Automatically selects nodes by querying SLS API and checking the status of each node through the HSM API
5. Framework for scripting and testing commands on multi-layered SSH connections.
6. Provisions to add more automated tests and tasks in the future, using existing utilities for APIs and SSH access
7. Docs on how to run these tests
> CASMNET-1022-12

- operations/configuration_management/Version_Control_Service_VCS.md
The procedure to change the VCS password uploads `customizations.yaml` to the loftsman namespace site-init secret before the new credentials have been encrypted resulting in an error next time `manifestgen` is run.
* Changed ordering of steps in the procedure so encrypted credentials are uploaded
* Fixed errors identified with directory paths relative to working directory while testing new procedure.
> CASMTRIAGE-3505 - Upload customizations.yaml to Kubernetes after the new credentials have been encrypted

- upgrade/1.2/scripts/sls/csm_1_2_upgrade/sls_updates.py
To minimize UAN downtime during upgrade from CSM 1.0 to CSM 1.2, the IPv4 address of a UAN should be maintained while the CSM 1.0 CAN is converted to the CSM 1.2 CMN.  This is accomplished by prioritizing the`bootstrap_dhcp` subnet in the transition/migration from old CAN to new CMN.
* Relates to CASMTRIAGE-3402 and CASMUSER-3025 switch-related changes.
* Tested with Hela and Loki data.
* Tested with data from one large customer.
* Also backports previous 1.2 change that makes the upgrader idempotent when running against 1.2 SLS configs.
This is part of a larger strategy of minimizing the state changes on UANs and allowing the Customer to self-select the required outage timing. …
> CASMINST-4797: Preserve UAN IPs during upgrade

- .github/workflows/stale.yml
Add stale labels to PRs and issues.
The stale label will help reviewers, or at least the docs-team, in identifying PRs that have been sitting for a while. Otherwise I've been doing this in my personal notes, I think having a GH label would make them easier to identify with the human eye.
> Add stale labels to PRs and Issues

- upgrade/1.2/Stage_1.md
During stage 1 of the frigg upgrade, the SSI installer was uncertain if the output he was seeing for the node-exporter status was acceptable. I talked to Craig and have made this PR to clarify what the installer should validate (and what they can ignore).
I also updated some of the example output to reflect the versions we're using as of rc.4.
main backport: https://github.com/Cray-HPE/docs-csm/pull/1843
> CASMINST-4816: Upgrade: Clarify how to determine if alertmanager, node-exporter are OK

- upgrade/1.2/scripts/k8s/remove_opa_req_affinity.sh
- upgrade/1.2/scripts/k8s/remove_spire_req_affinity.sh
- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
Like with istio, update opa and spire deployments on upgrades with required pod affinity to improve resiliency on upgrades.
Validated as much as I could on a 1.2 system but the true test will be during an upgrade from 1.0 or 1.2.
- [ x] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.
> CASMINST-4809: Update anti affinity for opa/spire on upgrades

- upgrade/1.2/Stage_2.md
Stage 2 of the CSM upgrade tells the upgrader to check where some istio and spire pods are running, and to move them if needed. The SSI upgrader did not know how to check this, so this PR adds some instructions to that end.
> CASMINST-4817: Upgrade: Stage 2: Give instructions on how to check istio and spire pods

- troubleshooting/index.md
- troubleshooting/known_issues/SLS_Not_Working_During_Node_Rebuild.md
- upgrade/1.2/README.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_1.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/Stage_4.md
- upgrade/1.2/Stage_5.md
[CASMTRIAGE-3255](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3255) documents a case we have seen twice now where SLS is not healthy when calling CSI to set the no-wipe flag, resulting in the upgrade hanging. Currently the root cause of the issue is not understood.
[CASMINST-4821]https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4821) is adding better checking for this condition to the upgrade scripts.
This PR is adding documentation on how to detect if a system is in this situation, and the remediation steps that have worked in the cases where this was seen.
I wrote up the procedure so that it should apply whether this is seen during an upgrade or otherwise. Until we know the root cause, we don't know if this can only happen during upgrades, or if it can happen during any …
> CASMINST-4820: Add troubleshooting/remediation steps for SLS postgres SyncFailed

- .spelling
- upgrade/1.2/scripts/upgrade/prepare-assets.sh
This changes the URL from `releases` to `csm-releases`, where tarballs will now be published.
This is a backport of: https://github.com/Cray-HPE/docs-csm/pull/1851
> CASMINST-4818 Use New csm-releases Repository

- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
- upgrade/1.2/scripts/rebuild/prerequisites.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
This commit makes the following changes:
1. In upgrade/prerequisites.sh, correct/verify the chrony config
for every node. Do this instead of doing it one node at a time
as they are upgraded. After `csm_ntp.py` has been run on a node,
use `chronyc makestep` to force time to sync immediately. With
this approach, time should be in sync across the cluster prior
to the upgrade beginning in earnest.
2. Once an upgraded node is online and settled, use `chronyc makestep`
to force time to sync immediately.
> CASMTRIAGE-3536: time hack

- upgrade/1.2/scripts/common/ncn-common.sh
- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
- upgrade/1.2/scripts/rebuild/ncn-rebuild-master-nodes.sh
- upgrade/1.2/scripts/rebuild/ncn-rebuild-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-master-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
[CASMTRIAGE-3255](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3255) documents a case we have seen twice now where SLS is not healthy when calling CSI to set the no-wipe flag, resulting in the upgrade hanging. Currently the root cause of the issue is not understood.
In order to provide a better failure condition (rather than an infinite loop), this PR adds a very simple SLS health check before making the CSI call to set the no-wipe flag.
In order to better isolate the problem, this PR also adds this same check just before the "drain node" step (because it would be helpful to know if it is the drain which is causing this problem).
At Di's suggestion, I added this logic for node rebuilds both inside and outside of the upgrade context.
The SLS health check consists of 2 API calls, …
> CASMINST-4821: Validate SLS health before using CSI to set no-wipe during node rebuilds

- .spelling
- upgrade/1.2/README.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/plan_and_coordinate_network_upgrade.md
As per offline discussion about minimizing UAN disruption and a clear upgrade story for BICAN.
```
DOCS updates
1.  New CAN prep procedure - next NET person, possibly a no-op.
2.  Overview of UAN/UAI migration procedure to user segmented network. - Atif
1.  Ahead of Raspberry upgrade
1.  *[DONE]* Coordinate with casmnet for the application of the 1.2 preconfig for switches
2.  *[DONE]* Identify subnet for new CAN
3.  *[DONE]* Advise users that domain names will be changing, examples (in release notes already)
2.  During Raspberry upgrade
1.  At step 0.2
1.  *[DONE]* Advise sysadmins that CFS will be temporarily disabled for UANs
2.  *[DONE -- but need manual command to fix after reboot]* UAN reboots require rememdiation
3.  *[DONE]* Access to UAIs will be disrupted until CSM upgrade …
```
> CASMUSER-3024-main-Update_Raspberry_upgrade_docs_to_warn_admins_about_UAN_CAN_network_outage

- operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
Add a step to the 1.0 power on procedure to enable the goss-servers prior to running any goss tests.
This issue was fixed in the 1.2 image but the workaround needs to be documented in csm 1.0
Resolves [CASMPET-5738](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5738)
Relates to [CASMTRIAGE-3573](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3573)
Tested on fanta where the issue was reported
> CASMPET-5738 1.0 : DOCS: add enabling goss-servers as part of csm-1.0 power on

- .spelling
- operations/UAS_user_and_admin_topics/UAI_macvlans_Network_Attachments.md
Add warning about CPE instructions changing UAS defaults from nmn to hsn.
> CASMUSER-3027: Include warning about CPE instructions converting macvlan to hsn

- .github/PULL_REQUEST_TEMPLATE.md
This PR fixes the PR Template link for the documentation and conventions to point to `main`.
> MTL-1816 Fix link to point to main

- .spelling
- operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md
- operations/validate_csm_health.md
CSM 1.0 backport of: https://github.com/Cray-HPE/docs-csm/pull/1796 for ServerTech PDUs that fail discovery. The HPE PDU content was not backported, due to CSM 1.0 not supporting HPE PDUs.
- CASMHMS-5367
- CSM 1.2 PR: https://github.com/Cray-HPE/docs-csm/pull/1796 
- main PR: https://github.com/Cray-HPE/docs-csm/pull/1865
> CASMHMS-5367: Backport CSM 1.2 doc changes For ServerTech PDUs

- .spelling
- operations/network/external_dns/Update_the_cmn-external-dns_Value_Post-Installation.md
- upgrade/1.2/scripts/sls/README.SLS_Upgrade.md
* Added steps to update `customizations.yaml` and SLS to the procedure to change the `external-dns` IP address.
* Added a link to the `externap-dns` IP address update procedure to the SLS Upgrade documentation.
Addresses the following JIRA tickets.
[CASMNET-1637](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1637) - Document process to change system_to_site_lookups if CAN isn't converted to CMN
[CASMNET-1638](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1638) - Add steps to update customizations and SLS to procedure to change external DNS IP
> CASMNET-1637/CASMNET-1368 - Improve documentation for updating the `external-dns` IP address.

- upgrade/1.2/scripts/upgrade/prerequisites.sh
* CASMTRIAGE-3597: Correct a bad rsync
* CASMTRIAGE-3598: wait up to 90s for a node to be in sync
* CASMTRIAGE-3599: spelling is hard...
> CASMTRIAGE-359[7-9]: fixup NTP issues in prereq.sh

- upgrade/1.2/scripts/upgrade/prerequisites.sh
This adds a weave check to prerequisites.sh to do two things:
1.  Check to see if weave is in sleeve mode and the hotfix hasn't been applied yet.
If it does find weave in sleeve-mode with at least one peer, it will fail the upgrade and tell them to consult the weave MTU hotfix field notice.   We don't want to move forward and start upgrading nodes until this is fixed.
2.  Make sure kubernetes-weave-mtu is set to 1376 in BSS.
> CASMINST-4840: Add a CHECK_WEAVE stage to prerequisites.sh

- scripts/operations/pyscripts/pyscripts/commands/test_bican_external/test_bican_external.py
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/can_toggle_tests.yaml
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/chn_toggle_tests.yaml
- scripts/operations/pyscripts/pyscripts/commands/test_bican_internal/test_bican_internal.py
- scripts/operations/pyscripts/pyscripts/core/ssh/ssh_connection.py
- scripts/operations/pyscripts/pyscripts/core/ssh/ssh_host.py
Some SSH access tests are failing because they are incorrectly configured.
Note:
- These tests are run as per docs "Validate CSM Health" so it is important we configure these correctly for the release.
- The changes are confined to SSH access automated tests
Changes are as per the analysis of CASMTRIAGE-3586 and CASMTRIAGE-3587:
- NCN master and storage nodes should not be able to access UANs/UAIs/CNs over CHN
- All NCNs and switches must be able to access UANs and CNs over NMNs.
- UANs/UAIs/CNs must be able to access other UANs/UAIs/CNs over NMN.
- When on an Aruba switch, should resolve host names to IPs for all customer network target hostnames (CHN/CAN/CMN) as the workaround for CASMNET-1599 (previously, this was only doing it for CMN)
[1]: …
> CASMNET-1640 Update config files as per updated access matrix

- Jenkinsfile.github
Git-tags are stable builds that should publish to a sub-directory containing their major and minor versions (e.g. v1.2.6 
docs-csm/1.2).
Every git-tag should also push a latest RPM. This means there is a risk that rebuilding a previous tag will overwrite the latest RPM, this can be remedied by rebuilding the latest tag for the CSM release.
> CASMINST-4833 Updates

- operations/UAS_user_and_admin_topics/Customize_End-User_UAI_Images.md
Add nexus creds to podman push command that is used to push custom UAI images in the UAS/UAI Instructions.
Backwards compatible bugfix
* Resolves [CASMUSER-3023](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3023)
* `vale`
Ran through the procedure described on the change with the specified changes and verified that they worked as written.
- Were continuous integration tests run? If not, why? N/A
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A
- Were new tests (or test issues/Jiras) created for this change? N/A
No known risks.
> CASMUSER-3023 1.2

- install/deploy_management_nodes.md
- install/index.md
- introduction/scenarios.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/CSM_product_management/Perform_NCN_Personalization.md
- upgrade/index.md
The hyperlink text for the GSG currently references 22.06 in the CSM 1.2 docs. The version has since changed to 22.07, so the text needs to be updated to reflect the correct version.
> STP-3257: Updated GSG version in hyperlink text

- operations/node_management/Add_additional_Liquid-Cooled_Cabinets_to_a_System.md
added general guidelines for the networking portion of adding a liquid cooled mountain cabinet
> CASMINST-3806 - add management network steps for adding mountain cabinet

- scripts/operations/configuration/apply_csm_configuration.sh
This continues the work started in [CASMINST-4831](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4831), adding more checking to the script, both to its command line arguments and to commands that it runs during its execution. No changes to the logic of the script are made -- just additional validation that errors do not occur during execution.
I tested this during the surtur 1.2.0-beta.137 upgrade and verified that it correctly catches invalid arguments and also still works properly otherwise.
> CASMINST-4832: Improve checking in apply_csm_configuration.sh

- .spelling
- install/index.md
- operations/system_management_health/Access_System_Management_Health_Services.md
- operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
- operations/validate_csm_health.md
Minor improvements related to CSM health validation, based on things I noticed when helping SSI do CSM upgrades.
I also pulled in a couple of linting commits that I did for this main branch PR for [CASMMON-127](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-127):
https://github.com/Cray-HPE/docs-csm/pull/1904
That's because that PR is not being backported to the earlier branches, but some of my linting applies to the earlier branches.
> CASMINST-4847: Minor improvements related to CSM health validation

- install/pre-installation.md
The `zypper update` command fails because neither `csm-testing` or `goss-servers` are installed on the LiveCD by default. This command needs to be `zypper install`.
> MTL-1817 This needs to be install

- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
The master servers to do not have /srv/cray/tmp which is required for
the csi-configuration.sh script.  (ceph-csi)
> CASMTRIAGE-3628 - Fix for missing directory required for upgrades

- operations/network/dns/Troubleshoot_Common_DNS_Issues.md
The Unbound record data in the `cray-dns-unbound` documentation is compressed and the troubleshooting documentation does not have the correct command to extract it.
> CASMNET-1533 - Update troubleshooting doc to reflect that the Unbound records data is compressed

- .spelling
- RELEASE_NOTES.md
Update release notes for CSM 1.2 in order to include the list of security vulnerability exceptions (as of the csm-1.2-rc5 build) for container images.
This is a new section under the 'Known Issues' section of the CSM 1.2 release notes to include a listing of all container images that still have critical/high security vulnerabilities and a very high level explanation of why we are carrying the exception.
> CASMPET-5356 - Add security vulnerability exceptions to CSM 1.2 release notes

- operations/CSM_product_management/Validate_Signed_RPMs.md
Crayport instances were replaced with My HPE Software Center
Updated the content based on the [JIRA ticket 3179](https://jira-pro.its.hpecorp.net:8443/browse/STP-3179)
> STP-3179: Crayport instances were replaced to My HPE Software Center

- operations/CSM_product_management/Validate_Signed_RPMs.md
Backport changes to the main branch for STP-3179.
> STP:3179-main: Backport changes

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/k8s/blacklist-kernel-modules.sh
In order to not cause problems during the Slingshot Host Software
install we need to blacklist the rpcrdma kernel module.  This is
accomplished by added a kernel boot param to blacklist the module.
The doc change instructs the admin to run this script prior to
starting the upgrade.  This ensures that the worker nodes have
this module blacklisted on their first boot.  This also ensures
the boot params, including this new parameter, get automagically
added to the grub.cfg during the first network boot.
> NETETH-1987 CASMINST-4877: blacklist the `rpcrdma` kernel module

- operations/validate_csm_health.md
It is possible for `cray-powerdns-manager` to get "stuck" updating a zone due to attempting to generate duplicate records based on SLS/SMD data. ([CASMNET-1143](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1143)).
This can result in the internal SSH test failing because it cannot resolve all of the hostnames for the test.
This change documents the workaround required to force the records to be created correctly.
This WAR has been successfully tested on `drax` by the QE team.
> CASMTRIAGE-3642 - Internal SSH Test failing during Final Validation

- troubleshooting/known_issues/admin_client_auth_not_found.md
This backports https://github.com/Cray-HPE/docs-csm/pull/1956 and also fixes the command prompts to be in the 1.2 docs-csm style.
> CASMINST-4882: Clarify how to proceed after 'admin-client-auth secret not found' procedure

- upgrade/1.2/Stage_0_Prerequisites.md
Add clarity around an upgrade pre-req step that is not needed on all systems.
> CASMINST-4893: add a command to determine if running the blacklist script is required

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_2.md
Describe how the upgrade procedure clears the CFS configuration from worker nodes
and how to restore required configuration for other products to ensure the compute
nodes and UANs remain functional during the upgrade.
> CASMINST-4883: Provide details on restoring CFS configuration for NCN worker nodes

- operations/conman/Establish_a_Serial_Connection_to_NCNs.md
This clarifies what needs to be done in order to monitor a worker node while it is being rebooted.
> CASMTRIAGE-3625: Update console node evacuation procedure

- operations/conman/Establish_a_Serial_Connection_to_NCNs.md
This clarifies what needs to be done in order to monitor a worker node while it is being rebooted.
> CASMTRIAGE-3625: Update console node evacuation procedure (1.2)

- install/deploy_management_nodes.md
The current line is not idempotent and if ran again will result in multiple instances of `module_blacklist`:
```bash
if [[ "$ncn" =~ 'ncn-w' ]]; then
sed -i -E 's/rd.luks(=1)?\s/rd.luks=0 module_blacklist=rpcrdma module_blacklist=rpcrdma module_blacklist=rpcrdma /g' script.ipxe
fi
```
The resulting line if ran more than once remains the same:
```bash
if [[ "$ncn" =~ 'ncn-w' ]]; then
sed -i -E 's/rd.luks(=1)?\s/rd.luks=0 module_blacklist=rpcrdma /g' script.ipxe
fi
```
> CASMINST-4884 Prevent Duplicates

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4898 to ensure the opa envoy image (1.0 version) is pre-cached on newly built workers during NCN rebuilds, ensuring opa can start (and subsequently nexus calls work, preventing IPBO's).
```
ncn-m001-48d9c509:/home/bklein # kubectl get configmap -n nexus cray-precache-images -o yaml | sed '/kind: ConfigMap/i\    docker.io/sonatype/nexus3:3.25.0\n    dtr.dev.cray.com/baseos/busybox:1\n    dtr.dev.cray.com/cray/istio/proxyv2:1.7.8-cray2-distroless\n    docker.io/openpolicyagent/opa:0.24.0-envoy-1' | kubectl apply -f -
configmap/cray-precache-images configured
```
```
images_to_cache: |-
artifactory.algol60.net/csm-docker/stable/docker.io/nfvpe/multus:v3.7
artifactory.algol60.net/csm-docker/stable/k8s.gcr.io/coredns:1.7.0 …
```
> Add 1.0 version of opa envoy image to the list of key images to pre-cache during NCN rebuilds

- troubleshooting/known_issues/kube_multus_pod_in_ImagePullBackOff.md
This multus IPBO issue was encountered at a customer site.   They found that the documented workaround in troubleshooting/known_issues/kube_multus_pod_in_ImagePullBackOff.md did not work because they are airgapped.   They found the casmrel-631_multus-image_hotfix-0.0.1.tar.gz mentioned in a JIRA and that allowed them to resolve the issue.  They are asking that this option get added to the documentation.
This page only in the 1.0 branch so backports are not needed for any other branch.
> CASMINST-4892: Add casmrel-631_multus-image_hotfix option

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Fixing typo for csm 1.0.x docs
backporting to release/1.2 and main
> CASMPET-5767 1.0 : DOCS: Fix typo in cert renewal step

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Fixing typo for csm 1.0.x docs
backporting to release/1.2 and main
> CASMPET-5767-main : DOCS: Fix typo in cert renewal step

- .spelling
- operations/power_management/Power_Off_Compute_and_IO_Cabinets.md
- operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
- operations/power_management/System_Power_On_Procedures.md
1.2 - CASMPET-5769: Review and update System Shutdown and Startup Procedure
Update System Power On/Off procedure with changes that resulted from review of the procedures.
**System Power On Procedures** 
Reordered sequence of tasks in System_Power_On_Procedures such that Lustre is powered on before the Kubernetes Management Cluster.
Removed "Bring up the Slingshot Fabric" section.
Clarified Procedure step #3 in **Power on and Start the Management Kubernetes Cluster**.
Corrected Procedure step #1 in **Power Off Compute and IO Cabinets** by adding a link to correct section.
CASMPET-5769
Discused changes.
If schema changes were part of this change, how were those handled in your …
> CASMPET-5769: Review and update System Shutdown and Startup Procedure

- operations/CSM_product_management/Configure_CSM_Packages_with_CFS.md
- operations/README.md
Renames a section on compute configuration since the configuration will now also include application nodes.
> CASMCMS-6989: Rename compute configuration to csm configuration

- upgrade/1.2.6/scripts/update-customization.sh
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4902
fix file name issue introduced in last PR:
we appended timestamp to the file name which is used as "key" when uploading to k8s secret. our loftsman and other tools are using hardcoded "customizations.yaml" which leads to loftsman fail to find the secret
> NOTE: this is only for 1.2.6 so please do not backport to main
> CASMINST-4902 fix naming issue

- install/pre-installation.md
This adds the `ncn-image-modification.sh` script call to the pre-installation.md page, that is necessary to invoke before invoking the preflight tests.
The call is added right after the images are extracted.
Additionally the step to extract the images was changed to extract images into a versioned directory by using a faster rsync command. The versioned directory will help keep things neat, and will align better with NCN smoke-testing/metal-testing.
The faster rsync command entails using hardlinks, which avoid wasting space by avoiding duplication of the NCN artifacts on the same file system.
> CASMINST-4915 ncn-image-modification

- install/pre-installation.md
This includes `docs-csm` in the Zypper calls in the beginning of the pre-installation page. This also breaks the Zypper calls out into three steps, dividing the 3 groupings of packages up for easier stop-and-checking.
> CASMINST-4917 Install docs-csm

- operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
Main - CASMPET-5773: Docs: Remove inconsistent line. Update operations index.
Now that powering on the Lustre file system takes place before the **Power On and Start the Management Kubernetes Cluster** procedure, remove line at end of the **Power On and Start the Management Kubernetes Cluster** procedure referring to starting Lustre file system. 
CASMPET-5773
Discussed changes.
Low
N/A
> CASMPET-5773: Docs: Remove inconsistent line. Update operations index.

- install/deploy_non-compute_nodes.md
Some of the checks had been removed from the deploy NCNs step in the main branch prior to the docs overhaul, and it looks like they accidentally got added back in when that merged. They had been removed because they are replaced by Goss tests which run at the same time. This PR re-removes them.
> CASMINST-4910: Remove superfluous tests that were mistakenly added back during docs overhaul

- install/re-installation.md
Add two steps to the reinstall scenario
1. Ensure there is a valid DNS server configured for m001 if it's being used to prepare the USB stick.
2. Add a note that the admin should ensure there's enough disk space for what they're about to do in the case of using m001 to prepare the USB stick.
> CASMINST-3039: add a couple reinstall-specific steps

- install/prepare_management_nodes.md
Add two steps to the reinstall scenario
1. Ensure there is a valid DNS server configured for m001 if it's being used to prepare the USB stick.
2. Add a note that the admin should ensure there's enough disk space for what they're about to do in the case of using m001 to prepare the USB stick.
> CASMISNT-3039: add a couple reinstall-specific steps

- upgrade/1.2/scripts/strimzi/kafka-restart.sh
- upgrade/1.2/scripts/strimzi/patch-listeners.yaml
During this part of the upgrade, if the kafka sma cluster object does not have
listeners setup correctly, the upgrade cannot continue.
So detect if/when the listeners are not setup yet, and if so json merge patch
the data in.
Additionally ensure that the kafka-kafka pods are at a Running status and Ready
state of 1/1. Old installs have two containers and we want to ensure we're
restarting the new setup at this point. So if there are any non Running pods or
pods not at 1/1 Ready, delete the pods as well.
Fix issues discovered while testing on rocket. Rewrote the script to be run at the step in the upgrade where when run it did not correct the issue. Script is rewritten to be idempotent and to reconcile loop until it detects a positive condition that is known good. Validated the logic …
> CASMTRIAGE-3665: Patch sma kafka cluster resource and add listeners

- upgrade/1.2/scripts/sls/README.SLS_Upgrade.md
- upgrade/1.2/scripts/sls/csm_1_2_upgrade/sls_updates.py
- upgrade/1.2/scripts/sls/sls_updater_csm_1.2.py
CSI versions prior to and including Shasta 1.4 contained the incorrect IPv4 addresses for Unbound DNS in both NMNLB and HMNLB subnets.  Prior to CSM 1.2 this data was not used, but currently CANU uses this data to configure management network switches.  This change looks for missing and incorrect Unbound DNS addresses and patches SLS as part of the overall SLS Upgrade strategy in CSM 1.2.
- Surtur data which was a no-op
- Sif data which contained incorrect IPv4 addresses
- Locally with missing Unbound reservations
> CASMTRIAGE-3673: Ensure Unbound DNS IPv4 address is correct in SLS

- operations/kubernetes/Troubleshoot_Intermittent_503s.md
Added common envoy response flags and corrective actions to help troubleshoot common issues.
> CASMTRIAGE-3668: add common error flags

- install/deploy_final_non-compute_node.md
- install/deploy_non-compute_nodes.md
- install/install_csm_services.md
- install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml
- install/scripts/csm_services/steps/2.create_site_init_secret.yaml
- install/scripts/csm_services/steps/3.deploy_sealed_secret_decryption_key.yaml
- install/scripts/csm_services/steps/4.deploy_csm_application_and_services.yaml
- install/scripts/csm_services/steps/5.setup_nexus.yaml
- install/scripts/csm_services/steps/6.set_management_NCN_to_use_unbound.yaml
No Jira for this because Jira is sad. This fixes several places in the docs where paths are hardcoded and should be using the PIT variables. It also corrects places where the old CSM_RELEASE format is being assumed.
The install is broken without some of these fixes.
Of course, even with all of these fixes it is currently broken, but less so.
> Update csm-1.3 install docs and scripts to reflect changed PIT variables

- .github/CODEOWNERS
- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
- scripts/hotfixes/kdump/README.md
- scripts/hotfixes/kdump/create-kdump-artifacts.sh
- scripts/hotfixes/kdump/dracut-lib.sh
- scripts/hotfixes/kdump/hotfix.sh
- upgrade/1.2/README.md
- upgrade/1.2/Stage_1.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/Stage_3.md
**DO NOT BACKPORT THIS TO `main`**, a fix for `main` is merging imminently and this hot-fix is not important for the current 1.3.0.alpha builds.
This includes a hotfix for fixing kernel-dump for NCNs during install, rebuilds, and upgrade.
This was tested on fanta (CSM 1.2 with no pit), and surtur (CSM 1.3, but with a pit).
Output example:
```bash
/usr/share/doc/csm/scripts/hotfixes/kdump/hotfix.sh
Uploading hotfix files to ncn-m001:/srv/cray/scripts/common/ ... Done
Uploading hotfix files to ncn-m002:/srv/cray/scripts/common/ ... Done
Uploading hotfix files to ncn-m003:/srv/cray/scripts/common/ ... Done
Uploading hotfix files to ncn-s001:/srv/cray/scripts/common/ ... Done
Uploading hotfix files to ncn-s002:/srv/cray/scripts/common/ ... Done
Uploading hotfix files to …
```
> CASMTRIAGE-3591 kernel dump fix

- scripts/hotfixes/kdump/create-kdump-artifacts.sh
This amends the #2004 PR by toggling debug mode for kdump, this will assist triage if a kdump bug were to be created after running the hotfix.
> MTL-1835 Also run kdump with debug

- install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml
podman as installed with 1.3 no longer accepts a registry location we now put
that information into the pit-nexus tarball directly.
Fix for 1.3 issues observed on surtur. Depends on https://github.com/Cray-HPE/pit-nexus/pull/13 going in to work however.
> CASMTRIAGE-3697: Update podman load command for newer podman

- operations/network/metallb_bgp/Check_BGP_Status_and_Reset_Sessions.md
The BGP procedure in the docs gives an invalid command to use for clearing BGP sessions on Aruba switches. This PR corrects it to what I believe is the correct command, but **_some net SMEs need to review this to make sure._**
I also did some linting of the page, including removing a reference to a nonexistent procedure (in our current docs) at the end of the Mellanox switch section.
> CASMINST-4954: Correct Aruba BGP clear command; other linting of BGP procedures

- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- update cray bss update parameter for [operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md](https://github.com/Cray-HPE/docs-csm/blob/release/1.2/operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md)
> CASMINST-3717-csm-1.2 - update cray bss update param

- RELEASE_NOTES.md
This adds in a note in the release notes talking about the new Nexus export and restore procedure. It also gives the recommendation to take an export of Nexus and save it off system.
> CASMPET-5783: Add note about new nexus export procedure

- troubleshooting/interpreting_hms_health_check_results.md
This PR updates the HMS Health Check troubleshooting documentation with an additional Known Issues section about failures related to custom component roles and subroles in HSM. It also includes many formatting and linting updates.
* Resolves CASMHMS-5469.
Low risk, test documentation update.
> CASMHMS-5469 Add Known Issue for custom component roles and subroles in HSM, linting for CSM-1.0

- upgrade/README.md
- upgrade/Stage_5.md
Update the version of CSM shown in example output from querying the
product catalog from 1.2.0 to 1.3.0. Also update the import_branch in
that example to show the current 1.10.0 version. This may change before
the release of CSM 1.3.0, but it's okay because it's noted that the
output is an example.
Update the value of the `--csm-release` option for CSM 1.3.0 in the call
to `apply_csm_configuration.sh`. This will default to the latest
version, but if the user specifies it here, they would want to specify
CSM 1.3.0.
Fix broken link in `upgrade/README.md`
The file `upgrade/1.2/README.md` moved to `upgrade/upgrade_ncn_nodes.md`
in CASMINST-4943, but the link in `upgrade/README.md` was not updated,
so the link was broken. Update the link. Note that the contents of that
file still needs to be …
> CASMINST-4948: Update CSM version in NCN Personalization Steps

- install/create_cabinets_yaml.md
Format changes to Ryan's PR. I am putting them in a separate PR so he can merge them if he agrees with them. It seemed better than leaving a long list of comments.
https://github.com/Cray-HPE/docs-csm/pull/2060
> CASMHMS-5568: Format changes to create_cabinets_yaml.md

- upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Remove /var/lib/containers from ceph_backup in ncn-upgrade-ceph-nodes.sh
> CASMPET-5792 Remove /var/lib/containers from ceph_backup  in ncn-upgrade-ceph-nodes.sh

- .spelling
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Manage_Sealed_Secrets.md
- update_product_stream/README.md
- upgrade/Stage_0_Prerequisites.md
- upgrade/Stage_2.md
- upgrade/Stage_3.md
- upgrade/scripts/common/upgrade-state.sh
- upgrade/scripts/cps/snapshot-cps-deployment.sh
- upgrade/scripts/rebuild/ncn-rebuild-worker-nodes.sh
- upgrade/scripts/upgrade/ncn-upgrade-worker-nodes.sh
- upgrade/scripts/upgrade/prepare-assets.sh
- upgrade/scripts/upgrade/prerequisites.sh
I checked through the doc repo for everywhere that CSM_RELEASE was used (both docs and scripts), and made sure that in 1.3 we always use it in its new form (a.b.c). For cases where the old format was useful, I set the CSM_REL_NAME variable to be equal to csm-${CSM_RELEASE}.
> CASMINST-4970: Be consistent in how CSM_RELEASE is used in 1.3

- operations/kubernetes/Troubleshoot_Postgres_Database.md
- operations/kubernetes/View_Postgres_Information_for_System_Databases.md
Update docs to include postgres container as needed. 
Reviewed all the docs on the main branch and found a few places that also needed updates.
This is a follow on from CASMTRIAGE-3727
> CASMPET-5786 1.3 : DOCS: Update postgres kubectl exec/logs calls to include postgres container

- install/re-installation.md
The `lan` variable is not used, it should be capitalized or the others lower cased.
> CASMINST-4996 Fix undefined variable

- install/pre-installation.md
The double-quotes surround the command break running it if it is copy and pasted verbatium.
> CASMINST-4980 Fix Broken Command

- operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
hms-hmcollector has been split into ingress and poll pods so the ingress pods can run with 3 replicas. This mod updates the hmcollector resource tuning guide to reflect the change.
[CASMHMS-5561](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5561)
> CASMHMS-5561 Update Resource Tuning Instructions for cray-hms-hmcollector 1.2

- operations/node_management/Wipe_NCN_Disks.md
Update the manual wipe to align to the current automated wipe, using a for-loop for calling `wipefs` as well as including NVME.
Also restructure the page to be more generic, and remove redundant directions.
> MTL-1851 Update Manual Wipe

- operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md
Add in missing EthernetInterface delete command to the removing a liquid-cooled blade procedure. The 4th step in the `Cleanup Hardware State Manager` section to include the missing command within the for loop.
Also appease the markdown linter, and conform to the new command prompt spec.
> CASMTRIAGE-3699: Add in missing EthernetInterface delete command to the removing a liquid-cooled blade procedure.

- operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_from_Role.md
- upgrade/scripts/k8s/promote-initial-master.sh
This has recently changed, use the new filename.
> CASMTRIAGE-3767: Update kubeadm.cfg source file location

- upgrade/scripts/k8s/upgrade_control_plane.sh
- upgrade/scripts/upgrade/util/verify-k8s-nodes-upgraded.sh
read version from kubeadm on m002 to detect what to upgrade to
> CASMINST-5050 - read version from kubeadm on m002 to detect what to upgrade to
