Cray-HPE/docs-csm

install/deploy_non-compute_nodes.md, install/pre-installation.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
This fixes the Change NCN Password and SSH Keys on PIT Node page to use the correct paths to the images.
This also removes the duplicate steps for invoking `ncn-image-modification.sh` and `set-sqfs-links.sh`, which were invoked in both the `pre-installation.md` and `deploy_non-compute_nodes.md` pages. The steps in `deploy_non-compute_nodes.md` were redundant, since
`pre-installation.md` is _required_ before starting the `deploy_non-compute_nodes.md` page.
This also fixes a typo that went unnoticed, the storage-ceph image path was using the `kubernetes_version` variable. This wasn't causing problems because the two versions are _usually_ the same, but since they potentially can differ this ensures that either case is handled.
[1]: …
=> CASMINST-5041 Remove Dupe Steps and Fix Password

operations/node_management/Configure_NTP_on_NCNs.md
Adds verbiage indicating that clock make take some time and provides command to check clock stats.
=> CASMINST-4799

scripts/operations/gateway-test/gateway-test-defn.yaml
The URL being used to test communication with CAPMC was removed. Changed it to the health CAPMC health URL.
Validated new CAPMC health URL on surtur.
PASS - [cray-capmc]: https://api.cmn.surtur.hpc.amslabs.hpecorp.net/apis/capmc/capmc/v1/health - 200
Overall Gateway Test Status:  PASS
=> CASMINST-5031: Change CAPMC URL to target for test

operations/network/management_network/validate_shcd.md
Previously when validating SHCDs the meaning of CANU `-a` architecture was unclear.  This change directly states the vendors and configuration involved in the three architectures available.
=> CASMNET-1725 Clarify CANU architectures overview

install/pre-installation.md
This adds links for each seed file on how to manually create that seed file.
Currently Admins are being directed at step 3.2 in `pre-installation.md` to _jump_ to 1.2 documentation, I think this is because some do not realize the manual steps still exist in the 1.3 branch (`main`) of this repository. These added notes ensure that an administrator will be given notice of what to do when auto-generation does not succeed and where the manual documentation lives.
=> CASMINST-5089 Add References to Manual Steps

upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Add sleep before tests are run in ncn-upgrade-ceph-nodes.sh. Tests should no longer result in false negatives because storage node was not fully up
=> CASMPET-5828

upgrade/scripts/k8s/promote-initial-master.sh
Prior fix for file name would only allow for 1.3->1.3 upgrades, this should
tackle 1.2 as well by symlinking the old config file if found to the expected location.
=> CASMINST-5087: Add logic for prmote-initial-master to work on 1.2 and 1.3

upgrade/scripts/upgrade/prerequisites.sh, upgrade/scripts/upgrade/util/update-customizations.sh
CASMPET-5795 Added the `api` name to the hmn-gateway.   CASMPET-5817 added the `auth` name and added allowed-issuers to the hmn-gateway.   This is doing those additions to customizations.yaml for an upgrade.  
I also put back the update-customizations.sh script since we do not yet have a suitable replacement for 1.3.   I moved the two items (for argo and cray-nls) that were added directly to prerequisites.sh to the update-customizations.sh.   While testing, I found that the argo item was not idempotent so I added a fix for that as well.
Tested on mug.
Ran the update-customizations.sh by itself multiple times to check idempotency.  Ran just the "UPDATE_CUSTOMIZATIONS" stage of prerequisites.sh on mug (without writing it back to the site-init secret) to test the changes to that stage.
=> CASMPET-5811: Adding allowed-issuers and api/auth names to hmnlb gateway

install/pre-installation.md
Use `exit` instead, and ensure the `admin/` directory exists by listing it and moving `exit` into a separate step.
=> CASMINST-5112 User reported `logout` fails

upgrade/1.2/scripts/common/upgrade-state.sh, upgrade/1.2/scripts/upgrade/prerequisites.sh
The cleanup function referenced by `trap` in prerequisites.sh
is also used in other contexts. However, only prerequisites.sh
deals with creating a backup ssh config file.  If the trap function
is run from another context, it blindly removes the system ssh
config.
=> CASMTRIAGE-3786: be more careful when deleting .ssh/config

operations/package_repository_management/Nexus_Space_Cleanup.md
This adds a note in the Nexus space requirements about the size that the raspberry install takes up.
=> CASMPET-5756: Update space requirements for Nexus

upgrade/1.2/scripts/strimzi/kafka-restart.sh
Fixes for issues encountered upgrading CSCS as well as a couple other issues I noticed while re-reading through the script and validating all the code piecemeal on a running 1.2 system.
Noticed there was a missing, stop trying to restart logic missing from a comment. Added that logic in. As well as noticed a bit of a no-op in a conditional that shouldn't impact things but technically resulted in a check of [ "Running" = "Running" ] which isn't too useful where the intent was to see if there were other states as well in the kafka pods.
- [ x] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.
=> CAST-30583: Kafka restart bugfixes

upgrade/1.2/scripts/strimzi/kafka-restart.sh
the `--namespaces` flag was incorrect hiding that the delete wasn't working
Signed-off-by: Douglas Jacobsen <dmjacobsen@lbl.gov>
The procedure to restart strimzi related services is non-functional in the csm 1.2 upgrade.  This is at least one part of why that is true.
=> fix typo and shadowed issues

operations/firmware/FAS_Admin_Procedures.md, operations/firmware/FAS_CLI.md, operations/firmware/FAS_Recipes.md, operations/firmware/FAS_Use_Cases.md, operations/firmware/Update_Firmware_with_FAS.md, operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md, operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md
CASMINST-4608 - cray-hmnfd-etcd instructions reference nonexistent service
CASMINST-4838 - ServerTech PDU documentation incomplete
CASMHMS-5598 - Clarify failures of firmware updates related to locking
=> CASMINST-4608 / CASMINST-4838 / CASMHMS-5598

upgrade/1.2/scripts/strimzi/kafka-restart.sh
Nothing special just a nit removing a now useless grep in favor of just awk.
=> CAST-30583: Remove a now useless grep and do it all with awk instead

install/pre-installation.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, scripts/operations/node_management/ncn-image-modification.sh, upgrade/scripts/upgrade/prerequisites.sh
* move ncn-image-modification.sh to docs-csm
* update paths in prerequisites.sh
* add logic to ncn-image-modification.sh to remove ssh host keys while the image is unsquashed
Requires: https://github.com/Cray-HPE/csm/pull/1065
=> CASMINST-4805: move `ncn-image-modification.sh` to docs-csm; remove ssh host keys

.gitignore, operations/node_management/Add_Remove_Replace_NCNs.md, operations/node_management/Add_Remove_Replace_NCNs/Update_Firmware.md, operations/node_management/Add_Remove_Replace_NCNs/Update_NCN_BIOS_TPM_State.md
Add step to enable TPM in the BIOS when adding NCN
=> CASMHMS-5595 Set TPM State when adding an NCN

operations/validate_csm_health.md, troubleshooting/cms_barebones_image_boot.md
This documents the new option in the barebones boot test that allows users to override the default behavior and specify the IMS image to be used.
Source PR: https://github.com/Cray-HPE/cms-tools/pull/44
csm PR: https://github.com/Cray-HPE/csm/pull/1072
csm-rpms PR: https://github.com/Cray-HPE/csm-rpms/pull/518
=> CASMCMS-8068: Document option to specify image in barebones boot test

scripts/reconfigure_containerd.sh, upgrade/1.2/scripts/upgrade/prerequisites.sh
Change for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3803 -- add containerd config for artifactory.algol60.net to support upgrading unbound before NCNs are upgraded.
```
ncn-m001-48d9c509:/home/bklein # ./foo.sh
Reconfiguring containerd on ncn-w001:
reconfigure_containerd.sh                                                                                                  100%  653     1.6MB/s   00:00
ncn-w001: Warning: Permanently added 'ncn-w001,10.1.0.7' (ECDSA) to the list of known hosts.
ncn-w001: Adding artifactory.algol60.net to containerd config
ncn-w001: Restarting containerd
Reconfiguring containerd on ncn-w002:
reconfigure_containerd.sh                                                                                                  100%  653     1.3MB/s   00:00 …
```
=> CASMTRIAGE-3803 Add artifactory.algol60.net to containerd for air-gapped systems on upgrade

install/deploy_final_non-compute_node.md
Each host in the BMC array had a trailing newline character, causing
problems for DNS resolution during execution of the bmc/dns script.
Tested on surtur.
=> CASMISNT-5128: fix BMC hostname array

operations/image_management/Create_UAN_Boot_Images.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, operations/security_and_authentication/Update_NCN_Passwords.md
This PR corrects two main problems with the procedure used for customizing NCN passwords (and for generating password hashes in general).
1. [CASMINST-5134](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5134): Fixes a typo on the NCN image modification procedures that prevents the script from being found.
2. [CASMTRIAGE-3817](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3817) - Uses "echo -n" instead of "echo" when piping the password into the openssl command. The addition of the newline was generating incorrect hashes. However, using the echo option is better than specifying the password on the command line to openssl, since that can be seen by anyone on the system in ps -ef output.
I tested the updated commands on surtur and validated that they generate the correct …
=> CASMINST-5134/CASMTRIAGE-3817: Corrections to password setting/changing procedures

scripts/nexus-space-usage.sh
This changes the reporting script to not need an external jar to get information needed to clean up nexus.
=> CASMPET-5843: Change nexus-space-usage to not need external jar

operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md
Add missing step to rediscover a ChassisBMC after blade removal. 
Removed class filter to allow more than mountain, which allows this procedure to also remove Hill hardware. This is due a change in HSM made in CSM 1.2 that causes Hill liquid-cooled blades to have the Hill class. 
These changes were tested on Loki.
=> CASMTRIAGE-3777: Add missing step to rediscover a ChassisBMC after blade removal.

operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md
Add missing step to rediscover a ChassisBMC after blade removal. 
Removed class filter to allow more than mountain, which allows this procedure to also remove Hill hardware. This is due a change in HSM made in CSM 1.2 that causes Hill liquid-cooled blades to have the Hill class. 
These changes were tested on Loki.
=> (CSM 1.2) CASMTRIAGE-3777: Add missing step to rediscover a ChassisBMC after blade removal.

install/deploy_final_non-compute_node.md
We don't want to quote these arrays. If quoted, bash treats them
like a single element vs a list to iterate over.
Tested on surtur
=> CASMINST-5146: don't quote array

scripts/operations/gateway-test/gateway-test-defn.yaml, scripts/operations/gateway-test/gateway-test.py
Adding HMNLB network to the gateway tests now that the hmn-gateway has authN and authZ.
Currently, the behavior for services that are not on the gateway (e.g. cray-bos) is different for HMNLB (returns 403) than it is for CAN/CHN (returns 404).    This is being investigated in CASMPET-5853.   In the meantime, the gateway tests have been modified to handle this difference.
I added the cray-nls (argo) service to the set of tested services since that was added in 1.3.
I also changed the use-api-gw-override to false so the test is no longer using api-gw-service-nmn.local.   We are starting to move away from that name.
Ran the gateway tests on both NCN and UAI on surtur.   All UAI tests passed.  The only NCN tests that failed were valid issues with the argo service.   The endpoint was returning …
=> CASMNET-1741:  Adding hmnlb network to the gateway tests

operations/kubernetes/Check_for_and_Clear_etcd_Cluster_Alarms.md, operations/kubernetes/Check_the_Health_and_Balance_of_etcd_Clusters.md, operations/kubernetes/Clear_Space_in_an_etcd_Cluster_Database.md, operations/kubernetes/Report_the_Endpoint_Status_for_etcd_Clusters.md
Adding the container (-c etcd) when exec'ing into the etcd pods.
Not needed for csm 1.0 or 1.2.
=> CASMPET-5838-1.3 : Break/Fix: Etcd health checks failing - need to specify etcd container

operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
Adding to 1.0 for an CPU Throttling alert that was doc'ed in 1.2 but not in 1.0. Perlmutter noticed this during boot timing tests. 
=> CASMPET-5878-1.0 : Investigate Perlmutter alerts after boot timing test

operations/spire/Troubleshoot_Spire_Failing_to_Start_on_NCNs.md
This change switches the example from NCN_XNAME to NCN_HOSTNAME. This command takes the host name of the NCN and not the xname, causing confusion for the user.
=> CASMPET-5881 Fix incorrect renewncnjoin example

.spelling, operations/network/dns/DNS.md
The cray-powerdns-manager pod now creates and manages PTR records that correspond to ExternalDNS created A records.
=> CASMNET-1753 - Update documentation to reflect that cray-powerdns-manager now creates ExternalDNS PTR records

upgrade/scripts/common/ncn-common.sh
Bug fix: fixed ssh_keygen_keyscan function when removing old keys
=> CASMINST-5180 fixed ssh_keygen_keyscan function when removing old keys

install/pre-installation.md
This changes the `lsblk` command to only list block devices, while also excluding loop devices (`-e7`). The resulting disks are piped into `xargs` where they're compared aginst `/proc/mdstat`. If the disk doesn't exist in `/proc/mdstat`, then it isn't used in a RAID and it can be safely formatted and used as PITDATA.
=> CASMINST-5102 Do not use RAIDed disks

install/deploy_final_non-compute_node.md
Remove manual checks that are covered by Goss tests.
=> CASMINST-5188 - Should not be checking for can0 interfaces if CHN is configured

operations/kubernetes/Troubleshoot_Intermittent_503s.md, scripts/operations/known-issues.sh
While there is more it could and should still do, I'll leave other 503 istio issues for
future me to add in evolutionarily.
Note while for right now this is only finding a specific itio 503 I want to expand this beyond only istio to be more of a generic "if you find a thing and can fix it report what needs to happen" script. Hence why its not named say find-istio-503 errors. Simpler to have one script to rule them all that you run than N scripts that all could be run.
Add a script to find pods with envoy proxy issues and if so report back what kubectl delete commands need to be run to clear them.
I don't have any output at the moment to document them, but once we find another broken system I can update these docs with examples. Or I could contrive what it will output.
[1]: …
=> CASMPET-5686: mvp script for known 503 detection

workflows/ncn/worker/worker.wipe-and-reboot.yaml
- CASMINST-5192 fix syntax isisue
- CASMINST-5194 add missing force-ntp-setup step
=> CASMINST-5194 CASMINST-5192 fix syntax isisue

upgrade/scripts/common/upgrade-state.sh, upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Does not direct output to /dev/tty if unavailable. It is unavailable when using argo workflows.
Also fixes CASMINST-5133 - removes line setting target_ncn=ncn-s001
=> CASMINST-5143 does not direct output to /dev/tty if unavailable

install/install_csm_services.md, install/pre-installation.md, operations/hardware_state_manager/Set_BMC_Management_Role.md, upgrade/README.md, upgrade/Stage_0_Prerequisites.md, upgrade/Stage_2.md, upgrade/Stage_4.md, upgrade/Stage_5.md, upgrade/prepare_for_upgrade.md, upgrade/upgrade_ncn_nodes.md
Fixes, enhancements, and linting based on my recent installs and upgrades.
A lot of the changes to the 1.3 docs were removing things from 1.2 that no longer applied.
=> CASMINST-5205: Fixes, enhancements, and linting to install/upgrade docs

operations/CSM_product_management/Apply_Security_Hardening.md, operations/index.md, operations/kubernetes/Limit_Kubernetes_API_Audit_Log_Maxbackups.md
NCN Master disk space is being exhausted when customers enable K8S API Auditing, this as settings re: historical retention are not populated by our installer. This PR adds a procedure to correct this on running NCN K8S Master nodes as a stop gap measure. 
Due to potential conflict between kubeadm and the cloud-init scripts that establish K8S API auditing logging configuration, currently, will split the work out to make these settings persist. 
=> CASMINST-4795 - Add procedure to limit Kubernetes API Audit Log Retention

operations/index.md, operations/spire/Restore_Missing_Spire_Metadata.md
This adds a troubleshooting document on how to add the spire metadata to BSS if its not there.
=> CASMPET-5558 Add missing spire metadata fix

upgrade/scripts/common/ncn-common.sh, upgrade/scripts/common/ncn-rebuild-common.sh, upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Fix automation of setting ssh keys. ncn_upgrade_ceph_nodes.sh script will no longer need manual input to verify hostnames before ssh-ing to a node.
=> CASMINST-5110 fix automation of setting ssh keys

upgrade/scripts/upgrade/prerequisites.sh
This removes the spire-jwks anti-affinity prereq patch. This has been fixed in the helm chart and is no longer needed.
=> CASMPET-5884 Remove unneeded anti-affinity patch

install/livecd/Boot_LiveCD_USB.md
USB path does not need `CSM_PATH` set, the LiveCD should be available at the present working directory.
=> CASMINST-5204 Remove `CSM_PATH` from USB

upgrade/1.2/Stage_0_Prerequisites.md
It was discovered on `hela`, which does not have any CX-4 cards, that the blacklisting was still necessary.
=> MTL-1875: blacklisting `rpcrdma` is always required

upgrade/Stage_0_Prerequisites.md, upgrade/scripts/upgrade/prerequisites.sh
This adds in a check to the prerequisites.sh script to ensure the Nexus admin credentials are correct so the upgrade does not fail further down the line. This also update stage 0 to more accurately describe how the password is used in the upgrade.
=> CASMPET-5887: Update Nexus password check in prereqs

upgrade/scripts/upgrade/prerequisites.sh, upgrade/scripts/upgrade/util/upgrade-spire.sh
CSM 1.3 changes the location of the spire files from `/root/spire` to `/var/lib/spire`. The spire chart needs to be updated prior to NCNs being upgraded so that they can rejoin spire properly.
=> CASMINST-5206 Upgrade spire during prereq steps

operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System_Using_SAT.md, operations/node_management/Replace_a_Compute_Blade.md, operations/node_management/Replace_a_Compute_Blade_Using_SAT.md
* Make DVS reload optional on manual replacement procedure
* Add note making DVS over HSN prereq for SAT blade swap
The blade swap procedure using `sat` currently only supports DVS over HSN when swapping in a new replacement blade. This change documents that limitation and adds detail on when DVS should be reloaded when using the manual procedure, and also notes when the `--src-mapping` and `--dst-mapping` flags may be omitted
=> CRAYSAT-1495: Document limitations to `sat swap` blade replacement procedure

operations/network/Gateway_Testing.md, operations/network/management_network/generate_switch_configs.md, operations/network/management_network/validate_switch_configs.md
While validating some switch configs on jolt1, I found that the `canu generate` commands in the main branch were not correct.   While fixing that I also changed the 1.2 references to 1.3.  
I also found a 1.2 specific line in Gateway_Testing.md that needed to be removed since it is no longer true.
=> CASMNET-1777: Fix the canu generate commands

RELEASE_NOTES.md
Update RELEASE_NOTES.md to indicate `cray-powerdns-manager` bugfixes have been incorporated.
=> CASMNET-1779 - PowerDNS record generation bugfixes

upgrade/Stage_1.md, upgrade/Stage_2.md, upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh, workflows/ncn/worker/storage.rebuild.yaml
Automate stage 1 of upgrade using argo workflows. Also, adds automation for checking valid ceph ro key which implements CASMINST-4949. 
=> CASMISNT-4942 automate stage 1 using argo workflows

upgrade/Stage_0_Prerequisites.md, upgrade/scripts/upgrade/prerequisites.sh
This adds a step to the upgrade process for upgrading csm-config in order to work around a problem where old versions of csm-config were being applied during configuration of ncns
=> CASMTRIAGE-3889: Add upgrade step for csm-config

scripts/csm_rbd_tool.py
Last week, PR #2207 merged and created `scripts/csm_rbd_tool.py`. That script had an invalid shebang line, which in turn causes the docs-csm RPM to fail to install:
```text
Retrieving https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/docs-csm/1.3/noarch/docs-csm-latest.noarch.rpm
error: Failed dependencies:
/opt/cray/csm/scripts/csm_rbd_tool/bin/python is needed by docs-csm-1.3.32-1.noarch
```
I have confirmed that the RPMs worked prior to that PR, and failed starting with that PR. In addition, I have verified that the RPM generated by this PR (which fixes the shebang line) installs without a problem.
We should get this merged and tagged ASAP, since without it the latest 1.3 docs-csm RPM is not able to be installed (or not without having it ignore dependencies, …
=> CASMTRIAGE-3921: Fix shebang line in scripts/csm_rbd_tool.py

workflows/ncn/worker/worker.drain.yaml
CASMTRIAGE-3906 clear cfs state before boot so "wait for cfs after boot" will get the status from after boot instead of potentially getting it from the past which causes false negative  (race condition)
fanta
=> CASMTRIAGE-3906 clear cfs state before boot

scripts/operations/xnamevalidation.sh
This adds heartbeat to the xname filtering enable/disable piece.
=> CASMPET-5848 Enable heartbeat xname filtering

install/pre-installation.md
Remove manual step, force users to use the setup script.
=> CASMINST-5225 Remove manual redundancy

upgrade/scripts/k8s/upgrade_control_plane.sh
[# Description
Change for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5198 -- ensure auditing remains enabled after upgrade.
](https://github.com/Cray-HPE/docs-csm/pull/2246)
=> CASMINST-5198 Ensure auditing remains enabled during upgrade if configured

Jenkinsfile.github
Add slack notification to csm-release-alerts channel when/if build pipeline fails. Also removed some whitespace from stages section to line everything up.
=> CASMTRIAGE-3927: add slack alerts for build failures

Jenkinsfile.github
Add slack notification to csm-release-alerts channel when/if build pipeline fails. Also removed some whitespace from stages section to line everything up.
=> CASMINST-3927 add slack alerts for build failures

Jenkinsfile.github
Add slack notification to csm-release-alerts channel when/if build pipeline fails. Also removed some whitespace from stages section to line everything up.
=> CASMINST-3927: add slack alerts for build failures to release/1.3

Jenkinsfile.github
Add slack notification to csm-release-alerts channel when/if build pipeline fails. Also removed some whitespace from stages section to line everything up.
=> CASMTRIAGE-3927: add slack alerts for build failures for release/1.2

install/bootstrap_livecd_usb.md, install/wipe_ncn_disks_for_reinstallation.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, upgrade/1.2/README.md
Primarily a backport of the applicable parts of https://github.com/Cray-HPE/docs-csm/pull/2233, plus some 1.2-specific fixes.
=> CASMINST-5219: Corrections and improvements to install and upgrade documents

upgrade/scripts/upgrade/prepare-assets.sh
Also remove un-needed steps in stage 2
This solves an extra space check for getting the csm tarball before moving it to the rbd mount. This also removes a step to move the rbd mount that is no longer needed in stage 2. 
=> CASMINST-5245: Change download location of csm tarball

operations/firmware/FAS_Admin_Procedures.md, operations/firmware/FAS_CLI.md, operations/firmware/FAS_Recipes.md, operations/firmware/FAS_Use_Cases.md, operations/firmware/Update_Firmware_with_FAS.md, operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md, operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md
[CASMINST-4608](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4608) - cray-hmnfd-etcd instructions reference nonexistent service
[CASMINST-4838](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4838) - ServerTech PDU documentation incomplete
[CASMHMS-5598](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5598) - Clarify failures of firmware updates related to locking
[CASMHMS-5556](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5556)  - Explain Declarative vs Imperative FAS updates
=> CASMINST-4608 / CASMINST-4838 / CASMHMS-5598 / CASMHMS-5556 for v1.2

.spelling, install/livecd/Boot_LiveCD_USB.md, install/pre-installation.md
This uses more specific `tar` and `bsdtar` arguments to get the LiveCD and PIT into a more reliable path.
The user is expected NOT to change directories between extracting the RPMs and using the USB path.
=> CASMINST-5230 CASMINST-5229 LiveCD and CSI Path

operations/kubernetes/Rebuild_Unhealthy_etcd_Clusters.md, operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md, operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
Main - CASMPET-5905: Docs: Update docs for recent CASMPET-5531 changes to improve/fix etcd_restore_rebuild.sh script.
Update docs with etcd_restore_rebuild.sh script output changes.
Remove no longer supported "External DNS" cluster reference.
CASMPET-5905
Viewed changes.
Low
N/A
=> CASMPET-5905: Update docs for recent changes to improve/fix etcd_restore_rebuild.sh script

scripts/workarounds/boot-order/README.md, scripts/workarounds/boot-order/metal-lib.sh, scripts/workarounds/boot-order/run.sh, upgrade/1.2.1/README.md, upgrade/1.2/README.md, upgrade/1.2/Stage_1.md
Add a workaround for the boot-order fix from MTL-1909 so users have it prior to the upgrade. Users will receive this fix in the new 1.2.1 images.
This includes a known-issues update to the 1.2 and 1.2.1 `README.md`.
The workaround is invoked at the start of the upgrade, before any nodes are rebuilt.
=> MTL-1919 boot-order workaround

operations/network/dhcp/DHCP.md, operations/network/dhcp/Troubleshoot_DHCP_Issues.md
The implementation of `cray-dhcp-kea` currently does not store lease data in a Postgres database.
Removing reference to Postgres cluster from the documentation.
=> CASMNET-1815 - Remove reference to Kea postgres cluster from troubleshooting documentation

operations/boot_orchestration/Clean_Up_After_a_BOS-BOA_Job_is_Completed_or_Cancelled.md
Addresses customer concern regarding the name of a created configmap for how BOS v1 controller creates intermediate configmaps. This clarification allows customers to perform a more thorough clean-up job for boot sessions launched under BOS v1.
=> CASMCMS-8110: Clarify documentation regarding intermediate BOS datastructures

upgrade/prepare_for_upgrade.md
This removed the recommended step to take an export of the nexus data. This was found to be used on the in-house systems and would take much too long for testing. Another page is being created that should hold this information for use once it has been further polished. Read [CASMPET-5912](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5912) for more information on why the step should be removed.
=> CASMPET-5912: Remove Nexus Export Step

operations/package_repository_management/Nexus_Export_and_Restore.md
This adds in missing steps to recover nexus if the export procedure was ended early or stopped for any reason. This allows for simpler steps to recover from stopping the export due to time constraints.
=> CASMPET-5914: Add in steps to recover from a failed export

operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
The "Change NCN image root password and SSH keys" procedure has a step which involves updating the BSS bootparameters to point to the correct Kubernetes and Ceph image versions. This involves using a sed command to do string replacement. However, that sed command is not as precise as it ought to be. Specifically, it will replace some version strings even if they do not completely match the version being replaced (that is, if the old version is 1.2.3, then the sed command would replace all version strings that began with 1.2.3, even if they had additional characters.
The sed command does make a backup before doing the replacement, but the file names involved are hard-coded, so if the commands are run multiple times, the original backup will be lost.
This PR makes two changes two address …
=> CASMTRIAGE-3723: Be more careful when editing BSS boot parameters

background/README.md, background/ncn_images.md, install/deploy_final_non-compute_node.md, install/troubleshooting_pxe_boot.md, upgrade/scripts/upgrade/prerequisites.sh
This changes various pieces to support private S3 buckets. Namely replacing all usages of ncn-images with boot-images, and replacing `csi handoff` with `cray artifacts`.
This following pages, these are coming later via MTL-1874:
- `Change_NCN_Image_Root_Password_and_SSH_Keys.md`
- `Pre_Boot_NCN_Image_Configuration.md`
- `ceph-upload-file-public-read.py`
=> MTL-1876 NCN Images and Private S3 Buckets

upgrade/scripts/upgrade/prepare-assets.sh, upgrade/scripts/upgrade/prerequisites.sh
`csi handoff upload-utils` no longer exists, and the call itself was no longer necessary. Now that the function no longer exists this call fails, but since it is no longer necessary this call can be removed.
=> CASMTRIAGE-3993 Remove invalid `csi` call

background/ncn_boot_workflow.md
This is mentioned in the "Locating USB device" section, but not in
the "setting boot order" section.
=> MTL-1926: add a step to set the next boot device

upgrade/scripts/upgrade/prerequisites.sh
Upgrade BSS before rebuilding NCNs to bring in necessary BSS changes for pre-signed/private-S3-bucket support.
=> CASMINST-5274 Update prerequisites.sh

workflows/ncn/worker/storage.rebuild.yaml
…fore upgrade and print output
Edit storage rebuild workflow to check ceph health before upgrade
Print output of health checks in argo logs
=> CASMTRIAGE-3970 edit storage rebuild workflow to check ceph health prior to upgrade

operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md, operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System_Using_SAT.md, operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md, operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System_Using_SAT.md, operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
Clear out redfish event subscriptions when add or removing blades from the system. This will prevent BMCs from sending multiple events out that are associated with different xnames out, and causing power events to confusing HSM when trying to keep track of power status.
=> CASMHMS-5693: Clear out redfish event subscriptions when add or removing blades from the system.

operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md, operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md, operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
Clear out redfish event subscriptions when add or removing blades from the system. This will prevent BMCs from sending multiple events out that are associated with different xnames out, and causing power events to confusing HSM when trying to keep track of power status.
=> CASMHMS-5693: Clear out redfish event subscriptions when add or removing blades

upgrade/1.2.1/README.md
Fixes an issue where dhcp-manager could apply NIC data to the wrong reservation in Kea
Signed-off-by: Greg Baker <80114231+gbaker-hpe@users.noreply.github.com>
=> Added bug fix information about Kea changes.

operations/configuration_management/Troubleshoot_CFS_Sessions_Failing_to_Start.md, operations/index.md
Adds a procedure for purging CFS event queue to help when CFS is stuck handling old events.
=> CASMCMS-8194: Add procedure for purging CFS event queue (Backport to 1.2)

operations/README.md, operations/configuration_management/Troubleshoot_CFS_Sessions_Failing_to_Start.md
Adds a procedure for purging CFS event queue to help when CFS is stuck handling old events.
=> CASMCMS-8194: Add procedure for purging CFS event queue.

install/pre-installation.md
Currently the CSM install documentation provides default commands to run to set the SSH keys and root password inside the NCN images. There is a more detailed page that gives other options for this, including how to customize the time zone, but this is not linked from the install documents. This PR adds a link to that page, noting that the provided commands are reasonable defaults, but that the detailed page provides more advanced options if desired.
=> CASMINST-5092: Link to NCN image customization page as optional advanced procedure during install

workflows/ncn/worker/storage.rebuild.yaml
… in goss-testing
Storage upgrade workflow now uses ceph-service-status.sh in csm-testing.
Tested on Fanta upgrade to from 1.2.1 -> 1.3.
=> CASMPET-5918 storage upgrade workflow now uses ceph-service-status.sh in csm-testing

workflows/ncn/worker/storage.rebuild.yaml
Storage upgrade workflow now uses ceph-service-status.sh in csm-testing.
Tested on Fanta upgrade 1.2.1 -> 1.3.
=> CASMPET-5918-main storage upgrade workflow now uses ceph-service-status.sh in csm-testing

operations/validate_csm_health.md
Add an additional symptom of one of the already documented known issues with the internal SSH test. See [CASMINST-5208](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5208) for full details.
This does not need a backport to any other release branches -- the test did not exist in csm-1.0, and the underlying cause of the known issues is fixed in csm-1.3.
=> CASMINST-5208: Add CannotLoginException as known issue with SSH test

operations/system_layout_service/Dump_SLS_Information.md, operations/system_layout_service/Load_SLS_Database_with_Dump_File.md
This removes the part that saves vault information when saving the SLS data.
Using a private key allows one to the vault passwords in the SLS
dump. These changes simplify the procedure to save SLS's state,
by not including the vault data.
The backup of the data in Vault is left to the Vault specific
backup procedures.
=> CASMHMS-5569: Remove private key from SLS docs

workflows/ncn/worker/worker.drain.yaml, workflows/ncn/worker/worker.wipe-and-reboot.yaml
CASMINST-5278 force time sync should run before drain
=> CASMINST-5278 force time sync should run before drain

upgrade/Stage_2.md
Update the instructions to copy artifacts from ncn-m001 to ncn-m002 during the upgrade process to account for the rbd device being moved to ncn-m002 at this point in the upgrade instructions.
=> CASMINST-5284: Update Copy Artifacts instructions in Stage 2.3, step #5.

scripts/csm_rbd_tool.py
Fix missing dir when moving the rbd device to another master node
- [x ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.
=> CASMINST-5283 - Fix missing dir when moving csm rbd device

operations/kubernetes/Containerd.md
Add documentation for containerd restart slowness in CSM 1.2.
=> Add note about slow containerd startup and WAR for 1.2 (CASMTRIAGE-3997)

upgrade/1.2.1/README.md
The original text was a little confusing about whether the reference to a CSM 1.3 upgrade was a typo for 1.2 when instead it's about a future upgrade.
This change attempts to clarify that.
Signed-off-by: Chris Samuel (NERSC) <74568771+nerscchris@users.noreply.github.com>
A minor documentation change to clarify that the mention of CSM 1.3 is a reference to fixing a future upgrade, and not a typo for fixing upgrades to CSM 1.2.
=> Clarify text about istio containers & CSM 1.3 upgrades

troubleshooting/interpreting_hms_health_check_results.md
This PR documents a known issue for the HMS ComponentEndpoints test for HSM in CSM-1.2 where the names of certain EthernetInterfaces in Redfish change and become out-of-sync with HSM.
* Resolves CASMHMS-5690.
The remediation steps were tested on Frigg by rediscovering the BMC where the failure occurred, rerunning the HMS tests, and verifying that the previously failing test case began to pass.
Was a fresh Install tested? Y
Was an Upgrade tested? N
Was a Downgrade tested? N
Documents a known test issue, no risk.
=> CASMHMS-5690 Update HMS test known issues section with ComponentEndpoint EthernetInterfaces failure and remediation csm-1.2

upgrade/README.md, upgrade/Stage_0_Prerequisites.md, upgrade/Stage_1.md, upgrade/Stage_2.md, upgrade/Stage_3.md, upgrade/Stage_4.md, upgrade/Stage_5.md, upgrade/prepare_for_upgrade.md
This PR adds a step to start a typescript at the beginning of each section of the upgrade procedure, and to stop it at the end of the section. It also makes sure that these are copied over to ncn-m002 when the upgrade moves over to there. A final step is added to the upgrade procedure to back up all of the upgrade log files and typescript files into S3.
I also added a table of contents header to the files which lacked one.
=> CASMINST-5207: Add typescripts to upgrade procedure & back them up

scripts/workarounds/boot-order/run.sh, upgrade/scripts/common/ncn-rebuild-common.sh
This will allow failures from the `install_grub2` function, which should not be failing but is not the primary objective of the workaround. The primary objective of the bootorder workaround is to ensure that `setup_uefi_bootorder` is invoked.
=> CASMTRIAGE-4021 Fix call to `install_grub2` to allow failure

install/pre-installation.md
The current disk selection command was providing more than 1 device.
```bash
lsblk -l -o SIZE,NAME,TYPE,TRAN -e7 -d -n | sort -h | awk '{print $2}' | xargs -I {} bash -c "if ! grep -Fq {} /proc/mdstat; then echo {}; fi"
sr0
sdb
sde
sdd
```
The command was properly returning devices that are not included in the old RAID, but it would coincidentally return sr0 (the remoteISO) *first* in some cases. This command has previously not returned `sr0` first in other installs, in which case it has worked.
The multiple return is sloppy, but doesn't break the command. This change fixes the search command so that it ignores USBs and ROMs, preventing invalid devices like `sr0` from being used.
Before:
```bash
loki-ncn-m001-pit:~ # lsblk -l -o SIZE,NAME,TYPE,TRAN -e7 -d -n
447.1G sda  disk sata
447.1G …
```
=> CASMTRIAGE-4039 Fix disk selection

install/deploy_final_non-compute_node.md
The `bss-metadata` command was not updated with MTL-1876, this change addresses the update to the command to include the versioned squashFS files.
=> CASMINST-5290 Fix handoff command

operations/kubernetes/Restore_Postgres.md
Correct some minor issues with gitea restore procedure
=> CASMPET-5926 1.2 : DOCS: Restore Postgress for VCS need to be update for list.py

operations/kubernetes/Determine_if_Pods_are_Hitting_Resource_Limits.md
Remove script content for doc page and refer to the one installed by platform-utils.  Also add content for interpreting CPU results (https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5929).
=> Cleanup pod resource limits page and script reference (CASMPET-5929)

.github/workflows/stale.yml
Can't find an example of how to use `${expiration}`, so I am just
hardcoding it in like the examples on the plugin site.
Also updates plugin from 5.0.0 to 5.1.1.
=> Fixes #2388 by including the stale expiration

.github/workflows/cleanup.yml
The cron job is not actually deleting any branches. Looking more deeply, it seems that a checkout step is needed.
It is possible that this also doesn't work on `cron`, but I'd rather try this change first before looking at the source code.
=> Amends #2391

upgrade/scripts/upgrade/prerequisites.sh, upgrade/scripts/upgrade/util/extract_chart_manifest.py
During the CSM upgrade, in stage 0, the prerequisites.sh script deploys three helm charts ahead of when it normally would do so. However, the code to do this currently does not base its charts on the overall CSM manifest files. At least in the case of csm-config, this makes a difference. It also does not customize any of the charts, although it's less clear if that is a big problem. In any case, this PR modifies the prerequisites script so that these 3 charts (csm-config, cray-kyverno, and kyverno-policy) are deployed based on their CSM manifest entries, after being customized.
I tested this on mug and it works, but I had to jump through some hoops because of the bad state that mug is in. I'm going to open this for review, but I'd really like to be able to test this on an actual 1.2 …
=> CASMINST-5298: Deploy Helm charts properly in prerequisites script

scripts/operations/node_management/Add_Remove_Replace_NCNs/add_management_ncn.py
Properly generate NTP information for CSM 1.3 (and later) when adding a management NCN. Between CSM 1.2 and CSM 1.3 the format of the ntp.allow cloud-init data changed, and this PR aligns the `add_management_ncn.py` script to what CSI generates.
I took a capture of the SLS/HSM/BSS data from Surtur and loaded it into a local instance of the hms-simulation-environment. This is a similar test environment to how the `add_management_ncn.py`.
For the test scenario I removed ncn-w001/x3000c0s4b0n0 from SLS/BSS/HSM using the `./remove_management_ncn.py` script with the following command:
```bash
./remove_management_ncn.py --xname x3000c0s4b0n0 --test-urls --skip-kea --skip-etc-hosts
```
Then I added back in ncn-w001 with the modified version of `add_management_ncn.py` from this PR:
``` …
```
=> CASMINST-5299: Properly generate NTP information for CSM 1.3 when adding a management NCN

scripts/operations/node_management/Add_Remove_Replace_NCNs/add_management_ncn.py
Properly generate NTP information for CSM 1.3 (and later) when adding a management NCN. Between CSM 1.2 and CSM 1.3 the format of the ntp.allow cloud-init data changed, and this PR aligns the `add_management_ncn.py` script to what CSI generates.
I took a capture of the SLS/HSM/BSS data from Surtur and loaded it into a local instance of the hms-simulation-environment. This is a similar test environment to how the `add_management_ncn.py`.
For the test scenario I removed ncn-w001/x3000c0s4b0n0 from SLS/BSS/HSM using the `./remove_management_ncn.py` script with the following command:
```bash
./remove_management_ncn.py --xname x3000c0s4b0n0 --test-urls --skip-kea --skip-etc-hosts
```
Then I added back in ncn-w001 with the modified version of `add_management_ncn.py` from this PR:
``` …
```
=> CASMINST-5299: Properly generate NTP information for CSM 1.3

upgrade/scripts/common/ncn-common.sh
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4075 -- ensure myenv has been populated with env vars.
=> Add env var check in ncn-common.sh to halt upgrade if not set (CASMTRIAGE-4075)

workflows/ncn/worker/worker.drain.yaml, workflows/ncn/worker/worker.post-rebuild.yaml
CASMTRIAGE-4071 skip wait for cfs depends on cfs configurations
=> CASMTRIAGE-4071 skip wait for cfs depends on cfs configurations

install/prepare_site_init.md, upgrade/1.2/scripts/upgrade/util/update-customizations.sh
This backports the content of https://github.com/Cray-HPE/docs-csm/pull/2437 into csm-1.2. Unlike the case with csm-1.3, this patching is needed for both the install and upgrade path in csm-1.2. Therefore in addition to making the same script change as in the 1.3 PR, this PR also adds the same command as a new manual step during the fresh install when the installer is crafting their customizations.yaml file.
=> CASMTRIAGE-4098: Correct IMS customer_access.access_pool value in customizations.yaml during CSM install/upgrade

upgrade/scripts/upgrade/prerequisites.sh
When fixing a shell check error, I accidentally enclosed two whitespace-separated strings in a single set of double quotes, when they should have been separately enclosed. This problem only exists in main branch.
=> CASMINST-5305: Correct typo in prerequisites.sh upgrade script

operations/network/management_network/snmp_exporter_configs.md, upgrade/scripts/upgrade/util/update-customizations.sh
CASMMON-200: Documentation update for BREAK/FIX: CSM 1.3 Fresh install failure on loki - errors on prometheus-snmp-exporter serviceMonitor params error.
prometheus-snmp-exporter:
serviceMonitor:
enabled: true
params:
- name: snmp1
target: 127.0.0.1
- name: snmp2
target: 10.252.0.2
- name: snmp3
target: 10.252.0.3
- name: snmp4
target: 10
ncn-m001:~/ram # curl http://10.42.0.22:9116/snmp?target=10.254.0.3|less
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP ifAdminStatus The desired state of the interface - 1.3.6.1.2.1.2.2.1.7
ifAdminStatus{ifAlias="",ifDescr="1/1/2",ifIndex="2",ifName="1/1/2"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/20",ifIndex="20",ifName="1/1/20"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/21",ifIndex="21",ifName="1/1/21"} 2 …
=> CASMMON-200: Documentation update for BREAK/FIX: CSM 1.3 Fresh install service monitor failure on loki

troubleshooting/interpreting_hms_health_check_results.md
This change adds instructions to the Additional Troubleshooting section of the HMS test documentation with the steps to take if there is no discovered compute hardware in HSM.
* Resolves CASMHMS-5744 in CSM-1.2.
Steps have been tested across various systems when previous instances of these failures have occurred, such as in:
* [CASMTRIAGE-3863](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3863)
* [CASMTRIAGE-3544](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3544)
Was a fresh Install tested? Y
Was an Upgrade tested? N
Was a Downgrade tested? N
No risk, documents troubleshooting steps for certain test failures.
=> CASMHMS-5744 HMS test documentation for troubleshooting missing compute nodes CSM-1.2

troubleshooting/interpreting_hms_health_check_results.md
This change adds instructions to the Additional Troubleshooting section of the HMS test documentation with the steps to take if there is no discovered compute hardware in HSM.
* Resolves CASMHMS-5744 in main.
Steps have been tested across various systems when previous instances of these failures have occurred, such as in:
* [CASMTRIAGE-3863](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3863)
* [CASMTRIAGE-3544](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3544)
Was a fresh Install tested? Y
Was an Upgrade tested? N
Was a Downgrade tested? N
No risk, documents troubleshooting steps for certain test failures.
=> CASMHMS-5744 HMS test documentation for troubleshooting missing compute nodes Main

.spelling, install/configure_administrative_access.md, install/scripts/craycli_init.py, operations/artifact_management/Manage_Artifacts_with_the_Cray_CLI.md, operations/configure_cray_cli.md, operations/validate_csm_health.md
This creates a script that will generate a new Keycloak user with a random password, store that information in a k8s secret, then initialize and authorize cray cli on all NCN's using that temporary Keycloak user.  This allows the install to have a working cray cli even if Keycloak has not been populated with the correct end users.
The documentation has also been updated to show how to use the new script, or the regular way of authenticating against an existing Keycloak user.
NOTE: this only works on NCN's that have the correct python modules present to run the script (currently all master, worker, and storage nodes) and nodes that are set up with k8s (currently all master and worker nodes, but only ncn-s001 from the storage nodes).
https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7474
=> CASMCMS-7474 - create a script to automate cray cli auth.

install/pre-installation.md
Signed-off-by: Russell Bunch <doomslayer@hpe.com>
=> Use `-f` to provide non-zero return codes

upgrade/scripts/upgrade/prepare-assets.sh
Proposed solution to avoid using dummy value for CSM_ARTI_DIR variable. Making this PR for Di to consider as an alternative solution to [CASMINST-5327](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5327).
=> CASMINST-5327 Update prepare-assets.sh

background/ncn_kdump.md
This fixes things found in the `kdump` tech forum today held by metal internal.
The `-default` suffix needs to be stripped off when referring to the package version. The package is also called `kernel-default-debuginfo` not `kernel-default-debug`.
The `--plus-content debug` may or may not be needed but it doesn't hurt.
=> Tech Forum: Fix `KVER` usage

operations/security_and_authentication/Create_a_Backup_of_the_Keycloak_Postgres_Database.md, operations/spire/Create_a_backup_of_the_Spire_Postgres_Database.md
Adds service specific doc for manually backing up postgres for spire and keycloak.
This will be backported to release/1.3, release/1.2 and release/1.0 once the reviews for main are complete
=> CASMPET-5954-1.4 : Add docs for manual backups for keycloak and spire

operations/node_management/Reboot_NCNs.md
1.2 backport of https://github.com/Cray-HPE/docs-csm/pull/2468
=> CASMTRIAGE-4154 - DOCS: --format json missing when checking cray cfs component list

operations/README.md, operations/node_management/Add_a_Standard_Rack_Node.md, operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md, operations/node_management/Removing_a_Standard_Node_from_a_System.md, operations/node_management/Replace_a_Standard_Rack_Node.md, scripts/operations/node_management/Add_Remove_Replace_NCNs/add_management_ncn.py, scripts/operations/node_management/allocate_uan_ip.py, scripts/operations/node_management/remove_gigabyte_cmc.sh, scripts/operations/node_management/remove_standard_rack_node.sh
Tickets:
- [CASMHMS-5481](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5481)
- [CASMHMS-5491](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5491)
Add procedures to remove and replace standard rack nodes, and updates to the Add standard rack node procedure
The following are new procedures:
1. `Removing a Standard rack node from a System` was created for the process of removing a river node from a system. It does the following:
1. If an application node is being removed, deallocate an IP address from the CAN or CHN network. This is done via python script that reuses parts of the add_managmemnt_ncn.py script.
1. Remove node data from SLS hardware and HMS. This is scripted.
2. Remove a Gigabyte CMC if present
2. `Replace a Standard rack node from a System` procedure for …
=> CASMHMS-5481: Add procedures to remove and replace standard rack nodes, and updates to the Add standard rack node procedure

operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
Add the step to verify that the client service was created.
Will backport to release/1.2 and release/1.3
The change for release/1.0 has already merged.
=> CASMMON-138-main : DOCS: Update to the procedure for Restoring an etcd procedure from backup

operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
Add the step to verify that the client service was created.
=> CASMMON-138-1.2 : DOCS: Update to the procedure for Restoring an etcd procedure from backup

operations/argo/Using_Argo_Workflows.md
This file
- `operations/argo/Using_Argo_Workflows.md`
uses triple backticks in the running text to render command flag
arguments into teletype text.
Everywhere else (yes, I grep-ed it) within the documentation source,
just using a single backtick achieves the same thing, for example, in
- `operations/configure_cray_cli.md`
we read
```
At this point, the script may be re-run with the `--debug` flag added,
```
which renders as
> At this point, the script may be re-run with the `--debug` flag added,
The triple ticks, whilst not being incorrect, hinder attempts to
automatically handle triple-back-ticked code blocks that contain
characters that the Jekyll renderer considers special.
Any chance of some consistency in the running text sections?
This PR, should you choose to acceot it, applies …
=> Apply consistency to triple-backtick markup

upgrade/scripts/upgrade/prerequisites.sh
main backport for https://github.com/Cray-HPE/docs-csm/pull/2500, minus the part about upgrading cfs-operator in stage 0, since that is specifically to address a problem that exists in csm-1.2, and thus will not be needed in main branch.
=> CASMTRIAGE-4197: Create common function in prerequisites.sh for chart upgrades

.spelling, operations/multi_tenancy/Create_a_Tenant.md, operations/multi_tenancy/Modify_a_Tenant.md, operations/multi_tenancy/Overview.md, operations/multi_tenancy/Remove_a_Tenant.md, operations/multi_tenancy/SlurmOperator.md
* PE-40775 Document Slurm Operator
Since the CPE docs cannot reference unreleased software, document the Slurm operator here by filling in the placeholder sections. In the future, we can replace the content with references to CPE documentation.
* PE-40775 Follow command prompt conventions
Follow the command prompt conventions, and fix capitalization of Ansible.
* PE-40775 Fix spelling issues
Fix spelling issues in the Slurm Multi-Tenancy documentation found by the spell checker.
* PE-40775 Fix another spelling error
Fix another spelling error found by the spell checker.
=> PE-40775 Document Slurm Operator (#2470)

operations/CSM_product_management/Apply_Security_Hardening.md, operations/image_management/Update_IMS_Job_Access_Network.md
The CSM releases v1.2.0 and v1.2.1 contained an error in the ims configuration where the wrong metallb pool was used to create jobs. This prevents the network service from starting up so ssh access to the customize jobs might not work correctly.
This documents how to fix this on a running system with v1.2.0 or v1.2.1 installed. This does not impact new installs and upgrades as those are handled in the install documentation already.
=> CASMCMS-8213 - document fixing IMS metallb pool for running jobs.

install/deploy_non-compute_nodes.md, install/troubleshooting_ceph_csi.md, install/troubleshooting_unused_drives_on_storage_nodes.md
After deploying NCNs during a fresh install, a set of health checks are performed. Prior to csm-1.3, this included a manual check of the OSDs on utility storage nodes. In csm-1.3, this was replaced by a Goss test. However, the manual procedure (and associated remediation steps) should still be available in the documentation as a troubleshooting page. This PR creates that page, and links to it from the appropriate step during the install.
The content of the page is essentially copied from the 1.2 docs, fixing only linting-type issues.
=> CASMINST-5352: Create troubleshooting page for unused drives on storage NCNs

operations/kubernetes/Restore_Postgres.md
CASMINST-5363 Fix a typo on the unset command 
CASMPET-5933 Fix gitea replica on restart
=> CASMINST-5363 main : DOCS: unset command has typo in Restore Postgres doc

operations/firmware/Updating_Firmware_m001.md, operations/firmware/Updating_Firmware_without_FAS.md
Update to firmware update docs to include "content-type" header with curl commands
=> CASMTRIAGE-4240: Added content-type header to curl commands

operations/firmware/Updating_Firmware_m001.md, operations/firmware/Updating_Firmware_without_FAS.md
Update to firmware docs to include "content-type" headers with curl commands
Docs release/1.2
=> CASMTRIAGE-4240: Added content-type header to curl commands - release 1.2

operations/firmware/Updating_Firmware_m001.md, operations/firmware/Updating_Firmware_without_FAS.md
Update to firmware update docs to include "content-type" header with curl commands
=> CASMTRIAGE-4240: Added content-type header to curl commands - main

operations/firmware/Updating_Firmware_m001.md
Update to firmware update docs to include "content-type" header with curl commands
=> CASMTRIAGE-4240 Added content-type header to curl commands

operations/network/metallb_bgp/Check_BGP_Status_and_Reset_Sessions.md
The clear commands in Check_BGP_Status_and_Reset_Sessions.md only affect the default VRF.   Needed specify the clear commands that will work for each VRF.
Tested these commands on drax for mellanox and mug for Aruba.
- [  ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [  ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
=> CASMTRIAGE-4237:  Clarify the BGP reset procedures to make sure both VRFs are handled

troubleshooting/index.md, troubleshooting/known_issues/etcd_cluster_backup_timeout.md
Add a known issue about etcd cluster backups timing out if the creation time exceeds 1 minute and how to manually fix.
This has been addressed in the CSM 1.3 code, so the known issue doc is only needed for CSM 1.2
=> CASMPET-6011 1.2 : DOC : Add etcd backup timeout troubleshooting and WAR for CASMTRIAGE-4188

operations/image_management/Create_UAN_Boot_Images.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, operations/security_and_authentication/Update_NCN_Passwords.md
The extra hyphens in `tr -dc _A-Z-a-z-0-9` was enabling a chance that the generated salt would contain hyphens. Hyphens are not a viable character to be used in a salt, at least in this context where they could accidentally be interpreted by `openssl` as a parameter.
=> CASMTRIAGE-4241 Remove extra hypens (`-`)

operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
Fixing syntax errors and missing information in the "Change NCN image root password and SSH key" procedure. This change only applies to the `release/1.0` branch.
Resolves [STP-3339](https://jira-pro.its.hpecorp.net:8443/browse/STP-3339)
=> STP-3339: 1.0 bug fixes in change NCN image root password and SSH key procedure

operations/README.md, operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md, operations/utility_storage/Ceph_Deep_Scrubs.md
Add information about Ceph deep scrubbing and how to proceed when the
Ceph cluster is in a `HEALTH_WARN` state during the system power on
procedures.
When the worker nodes boot, they try to mount the boot-images bucket as
an s3fs mount. However, the Ceph cluster is not unfrozen yet, so this
mount will fail. After `sat bootsys boot --stage platform-services` is
executed, Ceph will be unfrozen, and at this point, it will be possible
to mount the `boot-images` filesystem. This filesystem is needed to
allow the cray-cps-cm pods to start successfully.
Add a manual workaround to mount this filesystem on worker nodes.
=> CASMPET-6002: Document Ceph workarounds for System Power On Procedures

runLint.sh
This commit fixes two issues in runLint.sh
* grep for both lefthand and righthand double quote characters instead of lefthand.
* change the glob pattern so that directories other than the top level are searched.
* Without applying this change, I made local changes to the docs:
* Added illegal double quote characters to a file in a directory other than the top-level directory of this repository.
* Added a righthand double quote character to a file at the top level of this repository.
* Ran the script without this change, which falsely reported no issues.
* After applying this change, the script correctly idenfitied the issues.
[2]: …
=> CRAYSAT-1571: Fix two issues in runLint.sh

operations/kubernetes/Restore_Postgres.md
Modify the steps to restore keycloak to setup the CRAY_CREDENTIALS
Minor formatting changes
Needs to be backported to release/1.2 and release/1.3
=> CASMINST-5362-1.2 : DOCS: Cray 403 error during keycloak restore/backup procedure

operations/kubernetes/Restore_Postgres.md
Modify the steps to restore keycloak to setup the CRAY_CREDENTIALS
Minor formatting changes
Needs to be backported to release/1.2 and release/1.3
=> CASMINST-5362-1.3 : DOCS: Cray 403 error during keycloak restore/backup procedure

.github/CODEOWNERS
I found a few items in CODEOWNERS that needed to have the trailing / added because the directory had subdirectories.   While doing that I also found a few directories that have been added to the repo that should have code owners specified. 
=> A few additions/adjustments to CODEOWNERS

troubleshooting/known_issues/velero_version_mismatch.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6013 -- add known issues doc that indicates how to get the velero client/server versions to match.
=> Add known issue for velero version mismatch (CASMPET-6013)

upgrade/1.0.11/Stage_0_Prerequisites.md
During the Pawsey 22.03 (CSM 1.0.11) upgrade the `K8sNEW` typo was noticed. This change just `s/s/S/` on the single instance of the typo.
=> Pawsey install noticed `s/s/S/` typo

scripts/operations/kubernetes/encryption.sh
The else clause can't address this variable as it was assigned in the if block. Move its scope to the function outside of the contditional.
=> CASMPET-6005: Fix variable scoping issue

operations/kubernetes/encryption/README.md, scripts/operations/kubernetes/encryption.sh, spec/encryption_spec.sh
This adds the ability for encryption.sh --enable/disable --aesgcm ... to validate the user input makes logical sense against what is found in the etcd database.
What this means is essentially if a user tries to setup encryption with a key that isn't found in etcd, the script will reject the update as being logically invalid.
This is to ensure that kubernetes secrets can always be read given a specific encryptionn configuration.
Also added switches --status to display the status of encryption.
And added a --restart switch to make restarting the daemonset easier to force updates.
Adds a layer of validation to prevent a user from setting up an encryption configuration that would be invalid or result in existing encrypted secrets from being readable by the kube api server.
[1]: …
=> CASMPET-6004: Add validation for checking the user input against etcd

.github/CODEOWNERS, .shellspec, install/README.md, operations/kubernetes/encryption/README.md, operations/kubernetes/encryption/index.md, scripts/operations/kubernetes/encryption.sh, spec/encryption_spec.sh, spec/spec_helper.sh
Backporting from 1.3 to main
* CASMPET-5846: Initial encryption.sh implementation
- [ x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.
=> CASMPET-5846 from 1.3 to main

.github/CODEOWNERS
Fix the missing leading `/` on `troubleshooting`. Add `Cray-HPE/metal` to `/operations/node_management` section. Include `Cray-HPE/ci` on all `.github/` items.
Attempt to fix CASMINST-5382 which seems fixed in `main` by using `main`'s formatting for some of the entries.
Add entries that exist in `main` that also exist in `release/1.3`.
Add LICENSE header.
This is related to #2561.
=> Add `@Cray-HPE/ssi-reviewers` as reviewers

operations/configuration_management/Management_Node_Image_Customization.md
Add a clarification about which target group to use when using CFS to modify an NCN image.
=> MTL-1970: add a clarification about --target-group for cfs session create

operations/configuration_management/Worker_Upgrade_Node_Personalization.md, upgrade/Stage_0_Prerequisites.md, upgrade/Stage_2.md, upgrade/scripts/upgrade/prerequisites.sh
This PR does 3 things (at Dennis's request)
1. Moves the NCN worker image customization steps from Stage 2.2 to Stage 0.3
2. Adds a first step to that procedure, indicating that the upgrader should read the relevant sections of the GSG.
3. Adds a stage to the end of prerequisites.sh in stage 0 that disables CFS on all NCNs
4. Minor doc linting.
There are still significant problems with the NCN worker image customization procedure. However, they are beyond the scope of this ticket, so please do not include them in the review of this PR. I will be opening another ticket to capture the work that I'm aware of that remains for this procedure. I'll comment [CASMINST-5390](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5390) with that ticket number, once I've opened it. Comments in that …
=> CASMINST-5390: Move worker NCN image customization steps back to stage 0; Linting; Disable CFS on all NCNs in prerequisites.sh

operations/CSM_product_management/Change_Passwords_and_Credentials.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, operations/security_and_authentication/Update_NCN_Passwords.md, scripts/ceph-upload-file-public-read.py
Backport root password/key docs from 1.0.
=>  CASMINST-5384: backport root password/key docs from 1.0

upgrade/Stage_0_Prerequisites.md, upgrade/scripts/k8s/create_new_postgres_backups.sh
Add a step 0.5 to the upgrade prereqs to regenerate the postgres backups.
This includes steps to copy the needed image to nexus (airgapped and non airgapped)
Tested on mug (1.3) and bradi (1.2).
The script takes about 2 minutes to run to re-create all the opt-in postgres backups
Usage
```
ncn-m001: # ./create_new_postgres_backups.sh -h
usage: create_new_postgres_backups.sh [-h] [-s <single_cluster>] [-i <image>]
A tool to recreate opt-in postgres backups using a patched cray-postgres-db-backup image.
create_new_postgres_backups.sh                     # Deletes & ReCreates postgres backups for all the opt-in postgres clusters.
create_new_postgres_backups.sh -s <single_cluster> # Delete & ReCreate postgres backup for a single opt-in postgres cluster.
select from one of: …
```
=> CASMPET-6029 1.3 : DOCS: Add Step in Stage0 of upgrade to remove old/bad pg backups & take new/good ones

operations/kubernetes/Restore_Postgres.md
Minor doc changes after regression testing of spire and keycloak restore from postgres backup
Also need to backport for release/1.3 and release/1.2
=> CASMPET-5990 main : Minor doc improvements

install/install_csm_services.md, scripts/operations/etcd/take-etcd-manual-backups.sh, upgrade/Stage_3.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5380 -- add script to take manual etcd backups, and point to it in the install docs after CSM services are installed (and settled).
```
ncn-m001:~/bklein/etcd # ./take-etcd-manual-backups.sh post.install
Creating manual etcd backup for 'cray-bos' named 'post.install.backup_2022-09-30-21:19:47'.
etcdbackup.etcd.database.coreos.com/cray-bos-etcd-cluster-manual-backup-3238 created
Creating manual etcd backup for 'cray-bss' named 'post.install.backup_2022-09-30-21:19:49'.
etcdbackup.etcd.database.coreos.com/cray-bss-etcd-cluster-manual-backup-30936 created
Creating manual etcd backup for 'cray-crus' named 'post.install.backup_2022-09-30-21:19:51'.
etcdbackup.etcd.database.coreos.com/cray-crus-etcd-cluster-manual-backup-4481 created …
```
=> Add script and doc note to take manual etcd backup after install/upgrade (CASMINST-5380)

troubleshooting/known_issues/issues_with_ncn_health_checks.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5965 -- add note about etcd backups resuming after 24 hours of a system being powered back up.
=> CASMPET-5965 Add note about etcd backups after system power up

upgrade/Stage_4.md
Add information to stage 4 about expected behavior during in family upgrades.
=> CASMPET-5977 stage4 Add note about 'in family' upgrades to stage 4

troubleshooting/known_issues/gitea_web_ui_requires_two_logins.md
Document known issue with logging into gitea web page where users are required to log in twice.
=> CASMCMS-8249: Document known issue with logging into gitea web page

RELEASE_NOTES.md
I'm adding a deadline for the removal of BOS V1.
=> BOS Deprecation: Attach a deadline to the removal of BOS V1

upgrade/Stage_1.md
Remove confusing step for normal Ceph upgrade in stage_1
=> CASMINST-5427 Remove confusing step for normal Ceph upgrade in stage_1

operations/image_management/Create_UAN_Boot_Images.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, operations/security_and_authentication/Update_NCN_Passwords.md
Per the `craypt(5)` manpage, the salt value must match the following
regex: `[./0-9A-Za-z]{1,16}`
=> CASMINST-5420: fix valid salt regex

operations/image_management/Create_UAN_Boot_Images.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, operations/security_and_authentication/Update_NCN_Passwords.md
Per the `craypt(5)` manpage, the salt value must match the following
regex: `[./0-9A-Za-z]{1,16}`
=> CASMINST-5420: fix salt regex

upgrade/Stage_0_Prerequisites.md
Cut and paste error in the docs.
Fixed the non airgapped case to skopeo copy from artifactory to the local (nexus) registry.
=> CASMTRIAGE-4320 1.3 : BREAK/FIX: /mnt/cray-postgres-db-backup.tar: no such file or directory

workflows/ncn/worker/worker.rebuild.yaml
fail if csi-install stage fails during worker upgrade 
=> CASMTRIAGE-4323 for csm-1.3: fail if csi-install stage fails during worker upgrade 

workflows/ncn/hooks/before-all/install-csi.yaml
during worker upgrade fail if csi-install stage fails
=> CASMTRIAGE-4323 during worker upgrade fail if csi-install stage fails

install/bootstrap_livecd_remote_iso.md, install/bootstrap_livecd_usb.md, install/deploy_final_ncn.md, operations/node_management/Updating_Cabinet_Routes_on_Management_NCNs.md
`cray-site-init` (`csi`) fails to print the `App. Version` field when `csi version` is invoked. This commit adds a note in every instance that `csi version` or `metalid.sh` are invoked, telling the user to observe the version information by another means.
=> MTL-1836 Add notice about missing `App. Version`

scripts/operations/gateway-test/gateway-test.py
We've found that a combination of CASMTRIAGE-4336 and CASMPET-6043 are what was causing the different behavior for APIs on the HMNLB.   With both of those fixed, the endpoints that are not on the HMNLB API gateway now return 404 instead of 403.   The special case in the test can be removed.
Tested on drax and mug.
```
------------- api.hmnlb.mug.dev.cray.com -------------------
api.hmnlb.mug.dev.cray.com is reachable
PASS - [cray-argo]: https://api.hmnlb.mug.dev.cray.com/apis/nls/v1/readiness - 404
PASS - [cray-bos]: https://api.hmnlb.mug.dev.cray.com/apis/bos/v1/session - 404
PASS - [cray-bss]: https://api.hmnlb.mug.dev.cray.com/apis/bss/boot/v1/bootparameters - 404
PASS - [cray-capmc]: https://api.hmnlb.mug.dev.cray.com/apis/capmc/capmc/v1/health - 404
PASS - [cray-cfs-api]: …
```
=> CASMPET-5853: Remove special case for hmnlb.  No longer needed.

troubleshooting/interpreting_hms_health_check_results.md
This change fixes a Cray CLI argument that needs to be capitalized in order to work, and adds additional information to the troubleshooting description for problems with leaf-bmc switches when no compute nodes are discovered in HSM.
* Resolves CASMHMS-5763 in CSM-1.2
Ran the updated Cray CLI command on Mug. Verified that it works as expected and fixes the failure that occurs with the previous command.
No risk, fixes a bug in documentation.
=> CASMHMS-5763 HMS test additional troubleshooting no computes CSM-1.2

troubleshooting/interpreting_hms_health_check_results.md
This change fixes a Cray CLI argument that needs to be capitalized in order to work, and adds additional information to the troubleshooting description for problems with leaf-bmc switches when no compute nodes are discovered in HSM.
* Resolves CASMHMS-5763 in CSM-1.3
Ran the updated Cray CLI command on Mug. Verified that it works as expected and fixes the failure that occurs with the previous command.
No risk, fixes a bug in documentation.
=> CASMHMS-5763 HMS test additional troubleshooting no computes CSM-1.3

troubleshooting/interpreting_hms_health_check_results.md
This change fixes a Cray CLI argument that needs to be capitalized in order to work, and adds additional information to the troubleshooting description for problems with leaf-bmc switches when no compute nodes are discovered in HSM.
* Resolves CASMHMS-5763 in Main
Ran the updated Cray CLI command on Mug. Verified that it works as expected and fixes the failure that occurs with the previous command.
No risk, fixes a bug in documentation.
=> CASMHMS-5763 HMS test additional troubleshooting no computes Main

scripts/workarounds/boot-order/run.sh, upgrade/1.2.1/README.md, upgrade/1.2/Stage_1.md, upgrade/1.2/Stage_3.md
This WAR was ran before the upgrade in order to facilitate PXE booting, but it is now known that it should also run _after_ the upgrade to fix disk boot entries.
Running this after the upgrade will ensure that disk boot entries will appear properly in the BIOS boot selection menu.
=> CASMINST-5434 Run MTL-1919 WAR after NCN Upgrade

operations/index.md, operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md, operations/node_management/Rebuild_NCNs/Validate_Boot_Loader.md, scripts/check_bootloader.sh, scripts/check_bootloader_all_ncns.sh, upgrade/1.2/scripts/upgrade/prerequisites.sh
This script will validate that the bootloader is correct on an NCN. The included `check_bootloader_all_ncns.sh` will copy the script `check_bootloader.sh` script to every pingable NCN before running it.
This is a backport of:
- #2444 
- #2445 
=> MTL-1954 Refactor to use `check_bootloader.sh`.

RELEASE_NOTES.md
[CASMUSER-3108](https://github.com/Cray-HPE/docs-csm/pull/new/CASMUSER-3108-uai-chn) Add known isssue for UAIs using a CMN default route.
=> CASMUSER-3108: Add a known issue to UAIs using a CMN default route

install/deploy_final_ncn.md, install/deploy_management_nodes.md
This applies the boot-order WAR to a fresh install.
We encountered a case on LANL where 2 systems fresh installed 1.2.0 and never ran the WAR (since they were never directed). This caused both systems to encounter the same problems NERSC encountered where nothing would disk boot on the power following up.
=> CASMTRIAGE-4351 Run the MTL-1919 WAR on installs

.spelling, operations/image_management/IMS_export_import.md, scripts/operations/system_recovery/ims-import-export.py
Adding documentation and script for IMS data import/export for disaster recovery.
=> CASMCMS-8257 - add IMS import/export documentation.

operations/security_and_authentication/Change_SNMP_Credentials_on_Leaf_BMC_Switches.md
New snmp configuration script no longer requires a user to delete. Remove it from the documentation.
Requires hpe-csm-scripts RPM v0.3.0
=> CASMHMS-5782 Don't require a user to delete when configuring Aruba switches

operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
Add rolling restart of request-ncn-join-token to power on. 
This was hit at LANL
Needs to be backported to CSM 1.0, 1.2 and 1.3
=> CASMPET-6070 : DOCS Add to Power On - Rolling restart of request-ncn-join-token

install/index.md, upgrade/1.2.2/README.md, upgrade/1.2.2/upgrade_network.md, upgrade/1.2/README.md, upgrade/1.2/Stage_0_Prerequisites.md, upgrade/1.2/Stage_2.md
This PR is for creating the initial CSM 122 patch instructions and ensuring we have updates in the release/1.2 branch of the 12 general upgrade instructions and fresh install instructions that refer to the 1.2.2 version as the latest CSM 1.2.x version to upgrade to or install.
I included a summary of the fixes that I found targeted (and already completed) in jira for the CSM 1.2.2 fix version.  I did NOT yet include any tickets that were marked with a fix version of CSM 1.2.2 but was not yet Done.   So all PRs that are incorporated into CSM 1.2.2 beyond the merge of this PR will need to also update the 1.2.2 patch instructions/README in order to contain a summary of the new issue under "Fixes included in 1.2.2".
=> CASMINST-5438 - create CSM 122 patch instructions

operations/image_management/Import_External_Image_to_IMS.md
This commit adds variable name consistency to "Import an External Image to IMS". In the event that the user is following "Management Node Image Customization," they will have already set the following three variables:
* IMS_ROOTFS_FILENAME
* IMS_KERNEL_FILENAME
* IMS_INITRD_FILENAME
This commit adds a reference to the "Management Node Image Customization" procedure in "Import an External Image to IMS", reminding the user that they may have already set these variables.
The variable is used in a slightly different way between the two procedures. In "Management Node Image Customization" it is assumed that the variables directly refer to filenames that exist locally. In "Import an External Image to IMS", this was not being assumed, and as a result a second variable called "ROOTFS_FILENAME" …
=> CASMINST-5470: Variable name and path consistency in IMS Image Import

operations/configuration_management/NCN_Node_Personalization.md, operations/configuration_management/Worker_Image_Customization.md
This commit provides more explicit instructions for setting up the CPE
and Analytics layers in NCN personalization in the case of an upgrade,
in which CPE and Analytics have not yet been installed. Prior to this
change, some knowledge was assumed about how to determine the current
playbook, commit hash and product values already in use. This commit
provides example output from `cray cfs components describe` as well
as explicit instructions on how to edit the bootprep file so that the
`playbook`, `url` and `commit` values are correct. It explicitly says
to use the `git` key in the bootprep layer definitions and provides
an example of what those layers should look like, based on the example
output of `cray cfs components describe`.
Finally, add optional steps to delete the temporary files, …
=> CASMINST-5474: Explicit instructions for setting layers

upgrade/Stage_0_Prerequisites.md
Instruct admins to cleanup myenv file if rbd device has been used in previous upgrade (https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5489).
=> Add note about myenv file if re-using rbd device (CASMINST-5489)

upgrade/Stage_0_Prerequisites.md
Instruct admins to cleanup myenv file if rbd device has been used in previous upgrade (https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5489).
=> Add note about myenv file if re-using rbd device (and update with recent 1.3 changes -- CASMINST-5489)

.github/config/markdown_link.json, install/README.md, introduction/scenarios.md, operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md, operations/CSM_product_management/Perform_NCN_Personalization.md, upgrade/README.md
The link to the GSG for Papaya and future releases will all use the same vanity URL (https://www.hpe.com/support/ex-S-8000), which will always points to the most current version of the GSG in HTML format. This PR replaces the old vanity URL.
This change is only needed in `release/1.3` and `main`.
**NOTE:** This link will not work until the GSG is published to the support center for the Papaya release.
=> STP-3355 : Update URL for GSG

operations/kubernetes/Restore_Bare-Metal_etcd_Clusters_from_an_S3_Snapshot.md
Main - CASMPET-6076: DOCS: Let user know that conjobs may need to be restarted after Bare-Metal etcd cluster restore.
Provide example checks that user can run after a Bare-Metal etcd cluster restore. 
CASMPET-6076
[1.3 PR 2672](https://github.com/Cray-HPE/docs-csm/pull/2672)
Tested on fanta, csm-1.3.0-rc.4.
Low
N/A
=> CASMPET-6076: DOCS: Let user know that `conjobs` may need to be restarted

operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Backporting the client secrets renewal steps to CSM 0.9 docs
=> CASMPET-6072 : DOCS: Backport cert renewal of client certs to 0.9 docs for CAST-31230

troubleshooting/known_issues/ncn_resource_checks.md
Add a statement to the ncnHealthCheck troubleshooting that postgressl-db-backup pods found in Error state can be ignored if the most recent cronjob pod Completed. Retries are expected if any intermediate issues are encountered.
=> CASMPET-6077 : DOCS: ncnHealthChecks add a note about postgresql-db-backup pods in Error

operations/validate_csm_health.md
Add a statement to the ncnHealthCheck troubleshooting that postgressl-db-backup pods found in Error state can be ignored if the most recent cronjob pod Completed. Retries are expected if any intermediate issues are encountered.
=> CASMPET-6077 : DOCS: ncnHealthChecks add a note about postgresql-db-bakcup pods in Error

operations/boot_orchestration/BOS_export_import.md, scripts/operations/system_recovery/export_bos_sessiontemplates.sh, scripts/operations/system_recovery/import_bos_sessiontemplates.sh
CASMCMS-8261: BOS session templates export/import
Provide scripts to automatically export and import BOS session templates
to support system recovery. Provide documentation mentioning these
scripts as well as manual ways to export and import session templates.
=> CASMCMS-8261 : BOS session templates export/import

operations/network/Gateway_Testing.md, operations/network/customer_accessible_networks/CHN_BGP_control_plane_over_CMN.md, operations/network/customer_accessible_networks/can_to_chn/README.md, operations/network/customer_accessible_networks/can_to_chn/network/chn_enable.md, operations/network/customer_accessible_networks/can_to_chn/network/network_upgrade_1.2_to_1.3.md
Minor corrections and linting of CHN cutover procedure and related documents, based on my testing of the procedure on surtur.
=> CASMINST-5507: Linting and corrections to CHN cutover procedure and related documents

operations/network/Gateway_Testing.md, operations/network/customer_accessible_networks/CHN_BGP_control_plane_over_CMN.md, operations/network/customer_accessible_networks/can_to_chn/README.md, operations/network/customer_accessible_networks/can_to_chn/network/chn_enable.md, operations/network/customer_accessible_networks/can_to_chn/network/network_upgrade_1.2_to_1.3.md, troubleshooting/dhcp_runbook.md, upgrade/Stage_0_Prerequisites.md, upgrade/scripts/k8s/create_new_postgres_backups.sh
Mostly this is linting-type changes to a couple of documents. One spelling error is also corrected in a script. Some of the commands on the DHCP troubleshooting page would not work as written, because of how they used Bash variables inside of single-quoted strings. This PR corrects that as well.
I also pulled in minor corrections and linting to the CHN cutover procedure and related documents, based on my testing of them on surtur.
=> CASMINST-5491/CASMINST-5507: Linting and command corrections

install/install_csm_services.md
Most chart release errors can be worked around by re-running the yapl command. Added this known issue to CSM install guide to make it clearer.
=> CASMINST-5510: add more known issues for CSM installation

install/index.md, upgrade/1.2/README.md, upgrade/1.2/Stage_0_Prerequisites.md, upgrade/1.2/Stage_2.md
I jumped the gun a bit with the CSM 1.2.2 patch instructions when I went ahead and updated the references in the csm-1.2 upgrade and fresh install docs to point to the 1.2.2 patch.   This PR will set it back to point to 1.2.1 until we are ready to ship 1.2.2, at which point, we'll need to change them back to point to 1.2.2.
=> CASMINST-5525 - change CSM 1.2 upgrade and install references to 1.2.2 once it's ready

.spelling, troubleshooting/README.md, troubleshooting/known_issues/antero_node_NID_allocation.md
Add known issue page for Antero node NID allocation issue. Add some example commands for an admin or user to determine the NIDs of an antero nodes in the system to workaround the non-contiguous NID ranges. 
Also add Antero to the list of allowed words as this is a new blade type, and the other blade types such as Windom and BardPeak have been perviously added to the list.
=> CASMHMS-5789: Add known issue page for Antero node NID allocation

operations/security_and_authentication/Keycloak_User_Management_with_Kcadm.md
One of the bulleted lists is not formatted correctly and ends up rendering all on one line.
Also had to make some changes to pass the spelling and style checks.
=> CASMINST-5511: Fix bulleted list formatting

operations/CSM_product_management/Perform_NCN_Personalization.md
Mistyped option in command needed a capitlization.
=> CASMTRIAGE-4425: Incorrect node command - Update the desired configuration for all NCNs.

operations/security_and_authentication/Update_NCN_Passwords.md
Changes a command to set the root password in vault because it was missing the container name in the exec command.
=> CASMTRIAGE-4424: Incorrect default container called in docs for vault

upgrade/Stage_1.md
DOCs change: add troubleshooting for ceph.ro.keyring file not existing during storage upgrade
=> CASMINST 5539: add troubleshooting for ceph.ro.keyring file not existing during storage upgrade

.spelling, background/ncn_kernel.md, install/pre-installation.md, operations/package_repository_management/Repair_Yum_Repository_Metadata.md, upgrade/Stage_0_Prerequisites.md, upgrade/Stage_1.md, upgrade/Upgrade_Management_Nodes_and_CSM_Services.md, upgrade/scripts/upgrade/prepare-assets.sh
This refactors all references with exception to a few (see exceptions below) of 1.3 and 1.3.0 to 1.4 and 1.4.0 (respectively). This also removes the boot-order workaround from the upgrade directions as it is already fixed, upgrades from 1.3 already have the fix in their 1.3 images and the fix also exists in the 1.4 images being upgraded to.
Exceptions:
- BOS/BOA references to cle-1.3.0 were left alone
- `canu` references to 1.3 were left alone, since `canu` does not support `1.4` CSM switch configs yet
=> CASMINST-5545 1.3 to 1.4 Refactor

upgrade/scripts/upgrade/prerequisites.sh
(cherry picked from commit 58d5a5c1c0f952e6d5d9267726cf7cdd54fec83a)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2708
The failure reported in CASMINST-5544 does not happen in csm-1.3, but that is just due to the fact that the variable is only dereferenced without double quotes. The variable itself still contains the extraneous whitespace. Therefore, it still makes sense to backport this fix so that the variable gets the correct value.
=> CASMINST-5544: Be more precise in setting postgres leader pod variable

operations/network/gateway_testing.md
This includes backports of [CASMINST-5491](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5491)/[CASMINST-5507](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5507) ([original PR link](https://github.com/Cray-HPE/docs-csm/pull/2668)) plus some additional linting for [CASMINST-5546](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5546). No content changes, just linting and corrections.
=> CASMINST-5491/CASMINST-5507/CASMINST-5546: Linting and corrections

workflows/ncn/storage/storage.rebuild.yaml
Export ceph.client.ro.keyring if file not present. This is done before storage upgrade starts.
Tested on surtur.
=> CASMTRIAGE-4413: export ceph.client.ro.keyring if file not present

scripts/workarounds/boot-order/lib.sh, scripts/workarounds/boot-order/run.sh
Systems upgrading from CSM 1.0.X to 1.2.2+ do not have the `lib.sh` dependency needed by the WAR `metal-lib.sh` library. This adds that dependency, enabling the WAR to be ran on CSM 1.0.X images.
When this WAR was originally added, it was intended to run on CSM 1.2.0 or CSM 1.2.1 systems upgrading to CSM 1.2.2 - CSM 1.2.X images include `lib.sh`, whereas CSM 1.0.X images do not have this file.
=> CASMINST-5552 Enable boot-order WAR for Upgrades from 1.0.X

operations/validate_csm_health.md
This adds a reference to SNMP configuration documentation in validate_csm_health.md for troubleshooting river discovery issues.
=> CASMINST-5366 Add reference to SNMP configuration to `validate_csm_health.md`

operations/validate_csm_health.md
This adds a reference to SNMP configuration documentation in validate_csm_health.md for troubleshooting river discovery issues.
=> CASMINST-5366: Add reference to SNMP configuration to validate_csm_health.md CSM 1.3

install/scripts/craycli_init.py, operations/configure_cray_cli.md
Changed 'ERROR' messages to 'WARNING' and updated the documentation to clarify that having some nodes not initialized can be OK. Also added a specific return code for k8s not configured on a node.
https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8277
=> CASMCMS-8277 - update cray cli auth script for clarity.

operations/kubernetes/encryption/README.md, upgrade/prepare_for_upgrade.md
Document and note that upgrades should be done with encryption off for 1.3.
While here note how to rotate encryption keys.
=> CASMPET-6031 Document encryption should be off during an upgrade

glossary.md
Removes the redundant LiveCD definition, and adds emphasis to the PIT's aliases.
Signed-off-by: Russell Bunch <doomslayer@hpe.com>
=> Remove Redundant LiveCD Definition

install/README.md, install/configure_administrative_access.md, operations/firmware/Update_Firmware_with_FAS.md
Move the section on Uploading Olympus BMC Recovery Firmware into TFTP Server to after HFP has been loaded on the system.
Release 1.3
=> CASMTRIAGE-4427 - Moved Upload of BMC Recover Images for rel 1.3

install/README.md, install/configure_administrative_access.md, operations/firmware/Update_Firmware_with_FAS.md
Move the section on Uploading Olympus BMC Recovery Firmware into TFTP Server to after HFP has been loaded on the system.
=> CASMTRIAGE-4427 - Moved Upload of BMC Recovery images

workflows/iuf/nexus-setup/README.md, workflows/iuf/nexus-setup/nexus-setup-template.yaml
This adds a new Argo workflow template to support the Install and Upgrade Framework (IUF) ability to create Nexus blob stores and repositories as required.
=> CASMPET-6010 Add IUF support for Nexus setup

operations/system_layout_service/Restore_SLS_Postgres_Database_from_Backup.md
=> CASMHMS-5676 Changed the validation step for SLS backup restore

install/install_csm_services.md, troubleshooting/known_issues/helm_chart_deploy_timeouts.md, upgrade/Upgrade_Management_Nodes_and_CSM_Services.md
Add note instructing users on how to increase a helm deploy timeout.
=> Add troubleshooting doc for helm charts that timeout (CASMPET-6114)

install/prepare_site_init.md, operations/security_and_authentication/Add_LDAP_User_Federation.md
Fix for the new dcldap cert.  The cert format changed so the older command would not result in fetching the cert
=> CASMTRIAGE-4475

operations/conman/ConMan.md, operations/conman/Troubleshoot_ConMan_Node_Pod_Stuck_Terminating.md
Add a console services troubleshooting page for how to manually move a cray-console-node pod that is stuck in 'Terminating' due to a worker node being shut down unexpectedly. Since this is a stateful set instead of a deployment it needs to be manually killed before it will move to another (healthy) worker.
=> CASMCMS-8311 - add console services troubleshooting page for stuck pods.

operations/configuration_management/NCN_Node_Personalization.md, operations/configuration_management/Worker_Image_Customization.md, upgrade/Stage_0_Prerequisites.md
Clarify that during upgrades, NCN image customizations is worker only, but personalization is for all management NCNs.
=> CASMINST-5485/CASMINST-5487: Clarify NCN personalization & image customization

operations/configuration_management/Management_Node_Image_Customization.md, operations/image_management/Import_External_Image_to_IMS.md
This ticket is specifically to make the interactions clearer between the NCN image customization procedure and the IMS image import procedures. Specifically, making it clear which steps in the latter procedure should be skipped when it is being done as part of the former procedure, while not unduly cluttering it as a standalone procedure.
In addition to the above, some small linting and reorganization was done, mostly to the IMS document.
This is not intended to correct all of the problems with the NCN image customization procedure. This is only trying to address the one specific issue described above. There are other open tickets being worked to fix other aspects of the procedure. I request that reviewers keep this in mind. If we try to fix the entire procedure with a single PR, it will …
=> CASMINST-5481: Clarify interaction between NCN image customization and IMS image import procedures; Reorganization; Linting

upgrade/Stage_2.md
Add note about how to reset cfs component state prior to worker upgrade if in error state.
=> Add note about resetting cfs component state prior to worker upgrade if in error state (CASMTRIAGE-4500)

upgrade/1.2/scripts/upgrade/prerequisites.sh
When upgrading from 1.0.x to 1.2.x, the worker upgrade script requires a shell script that is not installed on 1.0.x system but available from 1.2.x csm-testing rpm.
=> CASMTRIAGE-4497: install csm-testing rpm as prerequisites

operations/utility_storage/CSM_rbd_tool_Usage.md, upgrade/Stage_0_Prerequisites.md
Linting, but fairly extensive in terms of reorganizing and rewording content. No real content changes, but should still receive SME review from Craig or Lindsay, I think. Would be good to also get someone from SSI or an internal upgrader to take a gander, to make sure the changes to the stage 0 page in particular look okay to them.
=> CASMINST-5577: Linting of upgrade stage 0 and CSM RBD Tool info page

troubleshooting/known_issues/ims_image_creation_failure.md, upgrade/README.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4504 -- add troubleshooting for ims image creation failure.
=> CASMTRIAGE-4504 Add known issue for IMS image creation failures

operations/configuration_management/Management_Node_Image_Customization.md
Adds note to only modify worker boot images.
Signed-off-by: Dennis Walker <denniswalker@me.com>
=> CASMINST-5582 Update Management_Node_Image_Customization.md

operations/configuration_management/Management_Node_Image_Customization.md, operations/configuration_management/Worker_Image_Customization.md, scripts/operations/configuration/backup_cfs_config_comp.sh
This PR does some minor linting and reorganization, as well as including the detail on where to obtain the worker NCN artifact version that is needed during CSM upgrades.
This procedure is changing in 1.4 and will be handled by [MTL-1949](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1949),
However, in the interest of simplicity, I will backport these changes in the meantime (particularly since some are linting and not directly related to the primary changes).
This PR is against the CASMINST-5480-1.3 branch because it depends on commits that are in that PR but have not yet merged.
=> CASMINST-5482: Specify where to obtain artifact version for NCN image customization during CSM upgrades

.spelling, background/ncn_kdump.md, background/ncn_kernel.md, operations/configuration_management/Management_Node_Image_Customization.md, operations/configure_cray_cli.md, operations/firmware/FASUpdate_Script.md, operations/node_management/Add_a_Standard_Rack_Node.md, operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md, scripts/operations/configuration/apply_csm_configuration.sh, scripts/operations/firmware/FASUpdate.py, scripts/operations/kubernetes/encryption.sh, spec/encryption_spec.sh
Just linting. No content changes.
The changes to script files are only to comments or printed messages -- none to the code itself.
I don't know why the diff for operations/firmware/FASUpdate_Script.md shows so many changes, when only one string in the file was changed. It may be that it was checked in with weird line endings, and my PR stripped them. You can see that only one typoed string is actually changed.
=> CASMINST-5578: Linting

troubleshooting/README.md, troubleshooting/dns_runbook.md, troubleshooting/known_issues/unbound_airgap_forwarding.md
Document workaround for known issue where air-gapped Unbound DNS configuration causes forwarding of requests to PowerDNS to stop working.
=> CASMNET-1939 - Unbound forward to PowerDNS does not work in an air-gapped configuration.

operations/configuration_management/Management_Node_Image_Customization.md
Fix a command in the NCN image customization procedure so that it uses a legal CFS session name. The command currently uses a name which is illegal for two reasons -- too long (45 characters is the maximum) and containing an invalid character (underscores are verboten).
This PR:
- removes the invalid character and reduces the name length
- removes a redundant bit of text in the description of the command itself. 
- updates a later command in the procedure to use the correct CFS session name, rather than the old hardcoded one
If interested in the full details, see the description of [CASMINST-5590](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5590).
This should merge as soon as it gets approvals, to avoid more people hitting this problem when following the procedure.
[1]: …
=> CASMINST-5590: Use legal CFS session name during NCN image customization

operations/configuration_management/Create_an_Image_Customization_CFS_Session.md, operations/configuration_management/Management_Node_Image_Customization.md, operations/configuration_management/Track_the_Status_of_a_Session.md, operations/configuration_management/Troubleshoot_Ansible_Play_Failures_in_CFS_Sessions.md, scripts/operations/configuration/backup_cfs_config_comp.sh
The NCN image customization procedure is somewhat vague about the step where the CFS session is run. The command is given for how to run it, but no mention is made of how to monitor it while it runs, how to know when it is done, how to know if it was successful, and how to troubleshoot problems if they occur.
This PR modifies several documents to try and clarify that process. Other minor linting and reorganization is done around the image customization procedure.
=> CASMINST-5591: Elaborate on CFS image customization session procedure

operations/utility_storage/Troubleshoot_Ceph_MDS_reporting_slow_requests_and_failure_on_client.md, operations/utility_storage/Troubleshoot_Ceph_Services_Not_Starting.md, operations/utility_storage/Troubleshoot_Pools_Have_Many_More_Objects_Per_Pg_Than_Average.md
CASMINST-5543 - "more pgs than avg" warning
CASMPET-5963 - "ssh key distribution steps for ceph orchestrator"
CASMINST-5307 - "updated mds troubleshooting"
=> CASMINST-5307

troubleshooting/known_issues/kubectl_logs_no_space_left_on_device.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6140 -- indicate how to increase fs.inotify.max_user_watches if kubectl logs -f indicates no space left on device.
=> Add troubleshooting known issue for kubectl logs indicating no space left on device (CASMPET-6140)

scripts/operations/configuration/apply_csm_configuration.sh, scripts/operations/configuration/backup_cfs_config_comp.sh, scripts/operations/configuration/bash_lib/common.sh, scripts/operations/configuration/python_lib/common.py, scripts/operations/configuration/write_root_secrets_to_vault.py
This PR has no functional changes. It just reorganizes some of the scripts used in NCN personalization and Vault updates. This is to enable future work.
I tested the modified scripts on drax and ensured that they still work as before.
It would be fine backporting this to 1.3, but since it does involve script changes, it is fine if we keep it to the main branch. We can always backport it later, if desired.
=> CASM-3632: Move some common script functions into shared library

upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh, upgrade/1.2/scripts/upgrade/prerequisites.sh
Extract postgres healthcheck scripts from csm-testing 1.2 rpm and run them prior to ncn worker node upgrade.
=> CASMTRIAGE-4497: extract and run postgres health check script

install/pre-installation.md, operations/README.md, operations/security_and_authentication/Audit_Logs.md
Moving the procedure to enable audit logging to the CSM docs.
* Resolves [STP-3226](https://jira-pro.its.hpecorp.net:8443/browse/STP-3226)
* Change will also be needed in `release/1.2` and `release/1.0`
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1641 and https://github.com/Cray-HPE/docs-csm/pull/1642 
N/A
N/A
N/A
None
=> STP-3226 (main): Procedure to enable audit logging

install/pre-installation.md, operations/README.md, operations/security_and_authentication/Audit_Logs.md
Manual 1.3 backport.
Moving the procedure to enable audit logging to the CSM docs. Resolves [STP-3226](https://jira-pro.its.hpecorp.net:8443/browse/STP-3226).
=> STP-3226 (1.3): Procedure to enable audit logging

workflows/iuf/samples/example of global_params.json, workflows/iuf/samples/schema of global_params.yaml
IUF related:
Adds example and schema files for global parameters used as workflow inputs to operations and also as inputs to hook scripts.
=> CASM-3638 Add examples for global parameters

workflows/iuf/operations/nexus-setup/README.md, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
Add Install Upgrade Framework (IUF) support for loading one or more Nexus type 'yum' or 'raw' repositories.
=> CASMINST-5502 IUF: Add support for loading repositories 

scripts/operations/configuration/python_lib/api_requests.py, scripts/operations/configuration/python_lib/common.py, scripts/operations/configuration/python_lib/k8s.py, scripts/operations/configuration/python_lib/logger.py, scripts/operations/configuration/python_lib/vault.py, scripts/operations/configuration/write_root_secrets_to_vault.py
This PR modifies the write_root_secrets_to_vault.py script.
From a user perspective, the script is unchanged (beyond some minor changes to the printed output). The changes are primarily splitting it into a few library modules, adding logging, and adding type hinting. This is to enable upcoming work as part of [CASM-3367](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3367).
I tested the updated script on fanta and verified that it still works as it did prior to the changes.
=> CASM-3653: write_root_secrets_to_vault: Add logging, split into modules

workflows/iuf/stages.yaml
CASM-3665 IUF: Nexus operations paths are not correct in stages.yaml
=> CASM-3665 IUF: Nexus operations paths are not correct in stages.yaml

scripts/repair-ceph-latency.sh, troubleshooting/known_issues/ceph_osd_latency.md, upgrade/README.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6157 -- add repair script if ceph latency detected (and corresponding doc).
=> CASMPET-6157 Add script to repair ceph latency if detected

operations/power_management/Power_On_Compute_Cabinets.md
Document a workaround for a `sat bootsys` bug that occurs when waiting for the `hms-discovery` Kubernetes cronjob to be scheduled.
Based on my testing with a reproducer script on shandy, it seems that the issue occurs with the first time waiting on the hms-discovery cronjob to be scheduled after it is resumed (suspend set to false). The last schedule time reported by K8s for the cronjob is unreliable during that period. Afterwards, it seems to fix itself, so it should be fine to just run the `sat bootsys` command again.
=> CRAYSAT-1626: Document workaround for `sat bootsys` bug

workflows/iuf/operations/preflight-checks-for-services.yaml
Remove retryStrategy from preflight-checks-for-services.yaml. This can be removed because this stage references a different template that specifies the retryStrategy. 
Tested on Frigg.
=> CASMINST-5625 remove retryStrategy from preflight-checks-for-services.yaml

troubleshooting/index.md, troubleshooting/known_issues/hpe_systems_not_transitioning_power_state.md
HPE Systems impacted:
- DL385
- Apollo 6500
When HPE iLO systems are not properly transitioning power state in HMS/SAT this could indicate that Redfish events are not being received by the HMS HM-Collector. When this occurs, the HPE iLO receives an error back from its attempt to send events and will delete the subscription if there are enough failures.
This WAR provides a resolution until firmware updates are available.
=> CASMHMS-5839 HPE RF event WAR

workflows/iuf/operations/loftsman-manifest-deploy.yaml
Add IUF stage loftsman-manifest-deploy.yaml. This is an initial version. This stage will likely need revision based on the final draft of loftsman-manifest-upload as it is dependent on that stage.
=> CASMINST-5535 add IUF stage loftsman-manifest-deploy.yaml

install/prepare_site_init.md, troubleshooting/known_issues/spire_database_airgap_configuration.md
Modify air-gapped DNS procedure to forward the `"."` zone to PowerDNS so queries don't hang and timeout and apply required workaround to `spire-postgres-pooler` to prevent spire database lookup failures.
=> CASMTRIAGE-4577 - DNS hangs seen on airgapped system when host lookups fail

troubleshooting/interpreting_hms_health_check_results.md
This change adds troubleshooting documentation about handling test failures due to BMCs in unexpected states such as during system shutdown and power off testing.
* Partially resolves CASMHMS-5840 in Main.
No risks.
=> CASMHMS-5840 Add documentation for test failures due to unexpected BMC states Main

install/configure_administrative_access.md, operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md, operations/README.md, operations/configuration_management/NCN_Node_Personalization.md, scripts/operations/configuration/apply_csm_configuration.sh, upgrade/Stage_0_Prerequisites.md
[CASMINST-5609](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5609) was opened because for the CSM install case, the Getting Started Guide and the CSM docs were not synched up when it came to NCN personalization. There are some gaps and also some needless duplications. Other than some minor housekeeping tasks, this PR primarily does the following:
- Updates the Configure NCNs with CFS procedure to add language to cover both the install and upgrade cases, to make it clearer the different paths that may be followed.
- Same for NCN Node Personalization procedure.
- Removes a confusing callback to the GSG from stage 0.3 of the upgrade path, because there is nothing in the GSG that needs to be done at that point. The mention just adds confusion for no benefit.
This is not a thing of …
=> CASMINST-5609: Refine and clarify NCN personalization procedures

operations/validate_csm_health.md
Document that UAIs will not be accessible if the CHN is set in SLS, but the CHN has not been installed and configured.
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4499
=> CASMTRIAGE-4499 Add notice about UAIs if CHN is set but not installed and configured

install/install_csm_services.md
The order in which the `yapl` command line arguments must be specified is important and not entirely clear in the documentation.
The `--console-output` is a global option which must be specified before the `execute` command whereas the `--no-cache` option is a `execute` command argument and must be specified after it.
Added a note to clarify the order in which the options must be specified.
=> CASMINST-5595 - Clarify usage of --no-cache flag when resuming CSM services install

scripts/repair-ceph-latency.sh
After some soak testing, additional memory tuning to prevent ceph latency.  Tested on loki/shandy.
- [ x If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
=> Additional memory tuning for ceph latency script (CASMPET-6157)

scripts/repair-ceph-latency.sh
After some soak testing, additional memory tuning to prevent ceph latency.  Tested on loki/shandy.
- [ x If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
=> Additional memory tuning for ceph latency script

scripts/operations/gateway-test/gateway-test.py
Removing CHN test case from gateway tests. The CHN test case will fail install procedure as services are not installed in this point. 
=> CASMINST-5583 | Remove CHN test case from gateway test for 1.3

scripts/operations/gateway-test/gateway-test.py
Removes CHN test to avoid failure during install. Needs to be reworked in the future. 
=> CASMINST-5647 | 1.4 | CHN gw test removal

workflows/iuf/operations/extract-release-distributions.yaml, workflows/iuf/stages.yaml
=> CASM-3681 change extract-release-distrubition to a global stage

background/ncn_kernel.md, install/deploy_final_non-compute_node.md, operations/configuration_management/Management_Node_Image_Customization.md, operations/configuration_management/Worker_Image_Customization.md, scripts/operations/node_management/ncn-ims-image-upload.sh, upgrade/scripts/upgrade/prerequisites.sh
Prior to these changes, we were using craycli to update NCN artifacts, but they were unknown to IMS. This commit, paired with a change to CSI (https://github.com/Cray-HPE/cray-site-init/pull/273), associates the NCN boot artifacts with IMS immediately.  This will allow e.g. `sat` to work with the images.
=> MTL-1949: register NCN boot artifacts with IMS immediately

scripts/operations/configuration/python_lib/api_requests.py, scripts/operations/configuration/python_lib/args.py, scripts/operations/configuration/python_lib/k8s.py, scripts/operations/configuration/python_lib/types.py, scripts/operations/configuration/python_lib/vault.py, scripts/operations/configuration/write_root_secrets_to_vault.py
**NOTE**: This PR depends on changes in [this yet-to-be-merged PR](https://github.com/Cray-HPE/docs-csm/pull/2828). That is why the PR is against that branch instead of main. I will move this PR to be against main branch once that one merges.
The primary change in this PR is the addition of arguments to the write_root_secrets_to_vault.py script. Previously the script always set values for the password and both SSH keys. These new arguments add the following options:
- Delete field from root secret in Vault
- Retain current value (if any) from root secret in Vault
Each of those options can be specified independently for either SSH key or the root password hash, in addition to the previous options.
This now allows users to use the tool to make changes to just one of the fields, or to remove …
=> CASM-3635: write_root_secrets_to_vault.py: Add options to clear or retain root password and/or SSH keys in Vault

workflows/iuf/operations/ims-upload.yaml
This commit uses the update-product-catalog-template workflowtemplate to add updating the product catalog into the ims-upload operation of the deliver-product stage.
I used this version of ims-upload.yaml on frigg and ran the IUF CLI through the deliver-product stage.
=> CASM-3592: Add product catalog update to IMS upload

workflows/iuf/operations/vcs-upload-content.yaml, workflows/iuf/operations/vcs-upload/README.md, workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml, workflows/iuf/stages.yaml
Argo Workflow template following global_params.json example.
https://github.com/Cray-HPE/docs-csm/blob/a9ae6778ae529fe96cba9cb0a293ef9731e1351d/workflows/iuf/samples/example%20of%20global_params.json
Argo workflow template for VCS upload gitea operation. There are a few caveats with unknowns.
1. Clarification around the various products manifests `vcs.path`
2. Stable docker image for cf-gitea-import with argo entrypoint
=> CASMCMS-8255: Create an Argo template for VCS/gitea uploads

operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md, operations/system_layout_service/Add_Liquid-Cooled_Cabinets_To_SLS.md
CASMHMS-5855:
Updated PDU documentation to add command to manually update HSM record.
CASMTRIAGE-4603:
Fixed typo in command.
=> CASMTRIAGE-4603 / CASMHMS-5855 - release/1.2

operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md, operations/system_layout_service/Add_Liquid-Cooled_Cabinets_To_SLS.md
CASMHMS-5855:
Updated PDU documentation to add command to manually update HSM record.
CASMTRIAGE-4603:
Fixed typo in command.
=> CASMTRIAGE-4603 / CASMHMS-5855 - release/1.3

operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md, operations/system_layout_service/Add_Liquid-Cooled_Cabinets_To_SLS.md
CASMHMS-5855:
Updated PDU documentation to add command to manually update HSM record.
CASMTRIAGE-4603:
Fixed typo in command.
=> CASMTRIAGE-4603 / CASMHMS-5855 - main

update_product_stream/README.md, upgrade/Stage_0_Prerequisites.md, upgrade/scripts/upgrade/prerequisites.sh
1.4 upgrade instructions has a reference of docs-csm rpm link that points to sp2, which should be changed to sp3.
=> CASMTRIAGE-4674: fix the docs-csm rpm link

.github/workflows/license-check.yaml
The `artifactory.algol60.net/csm-docker` docker registry will become private since January 2023. This change is to provide authentication context for license checking github workflow, which is using container hosted in this registry.
Tested by temporarily adding `push:` event to the list of events which trigger workflow:
https://github.com/Cray-HPE/docs-csm/actions/runs/3633719040/jobs/6131051266
=> CASMINST-5440 Use license checker from private csm-docker [release/1.3]

.github/workflows/license-check.yaml
The `artifactory.algol60.net/csm-docker` docker registry will become private since January 2023. This change is to provide authentication context for license checking github workflow, which is using container hosted in this registry.
Tested by temporarily adding `push:` event to the list of events which trigger workflow:
https://github.com/Cray-HPE/docs-csm/actions/runs/3633719040/jobs/6131051266
=> CASMINST-5440 Use license checker from private csm-docker [release/1.2]

.github/workflows/license-check.yaml
The `artifactory.algol60.net/csm-docker` docker registry will become private since January 2023. This change is to provide authentication context for license checking github workflow, which is using container hosted in this registry.
Tested by temporarily adding `push:` event to the list of events which trigger workflow:
https://github.com/Cray-HPE/docs-csm/actions/runs/3633719040/jobs/6131051266
=> CASMINST-5440 Use license checker from private csm-docker [main]

scripts/operations/configuration/python_lib/api_requests.py, scripts/operations/configuration/python_lib/args.py, scripts/operations/configuration/python_lib/k8s.py, scripts/operations/configuration/python_lib/types.py, scripts/operations/configuration/python_lib/vault.py, scripts/operations/configuration/write_root_secrets_to_vault.py
This PR continues the modifications to the write_root_secrets_to_vault script. This PR contains changes for two tickets.
Until now, that script did not provide the user any options to govern how it behaved. Instead it would always read in the root password hash from the /etc/shadow file and it would read in the SSH keys from the /root/.ssh/id_rsa* files.
This PR adds options to:
1. Allow the user to specify the source file for the private SSH key
2. Allow the user to specify the source file for the public SSH key
3. Give the user other options to specify the root password -- provide the plaintext root password via environment variable, provide the hashed password string via environment variable, or be prompted to enter the plaintext root password.
In the case where a root password is …
=> CASM-3633/CASM-3635: write_root_secrets_to_vault.py: Additional options added

update_product_stream/index.md, upgrade/1.2/Stage_0_Prerequisites.md, upgrade/1.2/scripts/upgrade/prepare-assets.sh
This changes any of the instructions or scripts for downloading/installing the CSM tarball or the docs-csm rpm to use release.algol60.net instead of artifactory.algol60.net since we cannot use artifactory.algol60.net for public access to the artifacts.
Any references to docker images (e.g. artifactory.algol60.net/csm-docker/stable/docker.io/library/openjdk:11-jre-slim) were left as it is because they should be coming from the local repository and not from the external artifactory.algol60.net.
=> CASMINST-5517:  Change csm tarball and docs-csm rpm download instructions to use release.algol60.net

operations/firmware/FAS_Recipes.md
Improve the documentation for component power off when doing a FAS firmware update.
=> CASMHMS-5746 Update FAS procedures for component power off

update_product_stream/index.md, upgrade/1.2/Stage_0_Prerequisites.md
The link for the latest docs-csm rpm was changed last night to add in the "noarch" architecture.  Updating the docs accordingly.
=> CASMINST-5696: Adding noarch to the docs-csm-latest rpm name

background/ncn_kdump.md, install/pre-installation.md, update_product_stream/README.md, upgrade/Stage_0_Prerequisites.md
Add http_proxy verbiage for the purpose of downloading artifacts from external endpoints using a proxy
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5667
=> CASMINST-5667

workflows/iuf/stages.yaml
This is simply removing an attribute that we no longer use from IUF's stages.yaml. There are no doc changes.
=> CASMINST-5689 Remove local-path field from operations in Stages.yaml

operations/hardware_state_manager/Restore_HSM_Postgres_from_Backup.md, operations/system_layout_service/Restore_SLS_Postgres_Database_from_Backup.md
- SLS Postgres restore procedure
- Use correct CT test command for SLS.
- HSM Postgres restore procedure
- Wrong command prompt of ncn-w001# replaced with ncn#
- Changed the set of commands used to populate the database to one that is compatible with files with colons in the file name
- Added a WAR for properly repopulated ethernet interfaces for Intel Management NCNs.
Tested on Fanta with CSM 1.2.2
=> (CSM 1.2.2) CASMHMS-5866: Updates to the SLS and HSM postgres restore procedures.

operations/hardware_state_manager/Restore_HSM_Postgres_from_Backup.md
HSM Postgres restore procedure fixes
- Fixed command prompt  with ncn#
- Changed the set of commands used to populate the database to one that is compatible with files with colons in the file name 
- Added a WAR for properly repopulated ethernet interfaces for Intel Management NCNs.
- Appeased the markdown linter. 
=> (CSM 1.3) CASMHMS-5866: HSM Postgres restore procedure fixes

operations/hardware_state_manager/Restore_HSM_Postgres_from_Backup.md
HSM Postgres restore procedure fixes
- Fixed command prompt  with ncn#
- Changed the set of commands used to populate the database to one that is compatible with files with colons in the file name 
- Added a WAR for properly repopulated ethernet interfaces for Intel Management NCNs.
- Appeased the markdown linter. 
=> (CSM 1.4) CASMHMS-5866: HSM Postgres restore procedure fixes #2938

upgrade/scripts/upgrade/prerequisites.sh, upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
Deploy iuf and nls as prereq during upgrade. The new approach takes the iuf and nls chart spec directly from upgraded platform.yaml.
=> CASMINST-5669: deploy iuf and nls as prereq

workflows/iuf/operations/extract-release-distributions.yaml, workflows/iuf/operations/operation-record-time.yaml
argo_workflows_operation_time{opend="1671087764",opname="extract-release-distributions",opstart="1671087694",stage="global"} 70
=> CASMMON-247 : operations record timestamps for prometheus metrics

scripts/operations/gateway-test/gateway-test-defn.yaml, scripts/operations/gateway-test/gateway-test.py
Fixes whitespace issue that is causing gateway test failures on systems that don't have CHN.
This was introduced in https://github.com/Cray-HPE/docs-csm/pull/2871.
Tested on fanta (where the issue was found) with CAN and on wasp with CHN.
While testing on wasp, I found another case where the test fails if CHN is actually functional.
```
Getting token for chn
auth.chn.wasp.dev.cray.com is reachable
Token successfully retrieved at https://auth.chn.wasp.dev.cray.com/keycloak/realms/shasta/protocol/openid-connect/token
FAIL: Token retrieved for chn network which should be unreachable
```
The original fix was meant to disable CHN in the gateway tests because we cannot guarantee that it will be functional (i.e. if slingshot is not installed yet).   However, missed a place in …
=> CASMINST-5704: Fix whitespace issue in gateway test

workflows/iuf/operations/add-product-to-product-catalog.yaml, workflows/iuf/stages.yaml
This commit adds an operation in the deliver-product stage to insert the a product/version into the product catalog. This guarantees that even products that do not insert any VCS/IMS content will still be recorded in the product catalog.
Test Description: Ran this workflow on frigg.
=> CASM-3700: Add WorkflowTemplate to add product to catalog

workflows/iuf/operations/extract-release-distributions.yaml, workflows/iuf/operations/operation-record-time.yaml
CASMMON-247 : added csm arti docker iamges operations record timestamps for prometheus metrics
Test logs on frigg
ncn-m001:/usr/share/doc/csm/workflows/iuf/operations # curl 10.43.0.244:9090/metrics |grep operation_time
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP argo_workflows_operation_time Duration gauge by operation name in seconds
argo_workflows_operation_time{opend="1671087764",opname="extract-release-distributions",opstart="1671087694",stage="global"} 70
=> adding arti docker images

upgrade/Stage_0_Prerequisites.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5731 -- fix podman command and indicate not needed for CSM 1.3.1.
=> Fix pg backup step, indicate not needed in CSM 1.3.1 (CASMINST-5731)

background/ncn_kdump.md
Fixes `-bash: /srv/cray/scripts/metal/dracut-lib.sh: No such file or directory`.
=> `dracut-lib.sh` is in `common/` not `metal/`

workflows/iuf/operations/loftsman-manifest-deploy.yaml
Fix iuf stage: Loftsman Manifest Deploy.
Performed integration testing on frigg. 
=> CASMINST-5733 fix iuf stage: Loftsman Manifest Deploy

operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md, scripts/join_ceph_cluster.sh
Fix bug and refactor join_ceph_cluster.sh. Tested on fanta storage rebuild.
=> CASMINST-5651 fix bug and refactor join_ceph_cluster.sh

background/ncn_kernel.md
The 150400.24 patch kernel is running into kernel panics during the CSM 1.4 install. The cause is unknown, we have opened a SUSE case (SUSE Case #00502283) with dumps in order to help debug the problem. Internal debugging has been fruitless.
=> CASMTRIAGE-4697 Downgrade the kernel

background/ncn_images.md, install/pre-installation.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md, upgrade/scripts/upgrade/prerequisites.sh
In lieu of the upcoming aarch64 architecture, all artifacts built by the node-images repository will now denote their architecture. NCNs may never have aarch64 support, but their artifacts are built from the node-images repository.
This change modifies the usage of The NCN artifacts, referring to them with their new names that include their architecture. Without this change, none of the procedures that use the NCN artifacts will be usable.
=> MTL-2048 Account for `ARCH` in NCN artifacts

upgrade/scripts/upgrade/prerequisites.sh
Set `split_lock_detect=off` for upgrades to CSM 1.4.
=> DVS-2881 `split_lock_detect=off`

workflows/iuf/operations/ims-upload.yaml
This change removes the registry.local prefix from the image paths in the ims-upload workflow template.
Upload ims-load-artifacts images to Nexus on internal system, update workflow templates, and run IUF against a COS product distribution.
=> CASM-3718: Update ims-load-artifacts image path

upgrade/1.2/scripts/rebuild/ncn-rebuild-worker-nodes.sh
Skip caching images on (likely unhealthy) worker being rebuilt (https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6207)
=> Exclude worker being rebuilt from precache step (CASMPET-6207)

install/pre-installation.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
The MTL-2048 PR (#2964) updated the docs to account for the architecture inclusion in the image name, but failed to update the `awk` commands to handle the new location of the build ID.
=> CASMINST-5754 Fix `awk` command

workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
This commit uses the update-product-catalog-template workflowtemplate to add updating the product catalog into the vcs-upload-content operation of the deliver-product stage.
Test Description: I used this version of the vcs-upload-content workflowtemplate on frigg and ran the IUF CLI through the deliver-product stage.
=> CASM-3591: Add product catalog update to VCS upload

RELEASE_NOTES.md, introduction/deprecated_features/README.md, operations/system_layout_service/Dump_SLS_Information.md, operations/system_layout_service/Load_SLS_Database_with_Dump_File.md
Removed support for downloading and uploading credentials in SLS dumpstate and loadstate
[CASMHMS-5780](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5780)
=> CASMHMS-5780 SLS: removed private key option

operations/configuration_management/Ansible_Execution_Environments.md, operations/configuration_management/Configuration_Sessions.md, operations/configuration_management/Troubleshoot_Ansible_Play_Failures_in_CFS_Sessions.md, operations/configuration_management/View_Configuration_Session_Logs.md, operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md
Updates the CFS docs to reflect a 1.3.1 change to collapse all configuration layers into a single container.
=> CASMCMS-8335: Update CFS documentation to reflect container/layer changes (1.3)

scripts/operations/configuration/python_lib/api_requests.py, scripts/operations/configuration/python_lib/k8s.py, scripts/operations/configuration/python_lib/product_catalog.py, scripts/operations/configuration/python_lib/types.py, scripts/operations/configuration/python_lib/vault.py, scripts/operations/configuration/python_lib/vcs.py, scripts/operations/configuration/write_root_secrets_to_vault.py
Changes to enable upcoming work in [CASM-3714](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3714)
- Refactor some of the modules in `scripts/operations/configuration/python_lib`
- Add modules to obtain VCS credentials and to query the Cray product catalog configmap in Kubernetes
I tested this on frigg.
I regression tested by testing the `write_root_secrets_to_vault.py` script.
I tested the new features at the interactive console and verified that they worked as expected.
=> CASM-3699: Additions to scripts/operations/configuration/python_lib

operations/configuration_management/Ansible_Execution_Environments.md, operations/configuration_management/Configuration_Sessions.md, operations/configuration_management/Troubleshoot_Ansible_Play_Failures_in_CFS_Sessions.md, operations/configuration_management/View_Configuration_Session_Logs.md, operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md
Updates the CFS docs to reflect a 1.3.1 change to collapse all configuration layers into a single container.
=> CASMCMS-8335: Update CFS documentation to reflect container/layer changes

scripts/operations/pyscripts/pyscripts/core/ssh/ssh_targets.py
The `test_bican_internal` ssh test fails with a `KeyError` if an Application node exists in SLS that does not have a SubRole defined.
Testing
Baseline test with no SubRole defined
```
ncn-m001:~ # /usr/share/doc/csm/scripts/operations/pyscripts/start.py test_bican_internal
Going to test from node types ('ncn_master',) to node types ('ncn_master', 'spine_switch') on networks ('can', 'chn', 'cmn', 'nmn', 'nmnlb', 'hmn', 'hmnlb').
BICAN:CAN detected.
ncn-m002 password (leave blank and hit Enter if not using password):
ncn-m003 password (leave blank and hit Enter if not using password):
sw-spine-001 password (leave blank and hit Enter if not using password):
---snip---
Ran 14 tests in 239.383s. Overall status: PASSED (Passed: 14, Failed: 0)
```
UAN specific test with no SubRole defined …
=> CASMINST-5576 - Internal SSH test fails if an Application node has no SubRole

scripts/operations/configuration/python_lib/api_requests.py, scripts/operations/configuration/python_lib/hsm.py, scripts/operations/configuration/python_lib/vault.py
This adds a new Python module inside the scripts folder tree. Currently the module is not used, but it will enable future work. At present, the module consists primarily of a single function, which I tested in isolation on mug to verify that it worked as expected.
Some minor linting was also done to other files, to clean up a few minor linter complaints.
=> CASM-3711: Add function to return NCN xnames from HSM SMD

upgrade/scripts/upgrade/util/nls-keycloak-configure.py, upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
Update `upgrade-cray-nls.sh` and `nls-keycloak-configure.py` to use the CMN LB (e.g., `auth.cmn`) vs. NMN LB. This due to policy changes in OPA for Keycloak that block access the master realm OIDC endpoints and the keycloak admin API endpoints for the NMN LB. 
Tested on Wasp by executing the `upgrade-cray-nls.sh` twice, directly via shell. The first time after removing the WebOrigin and redirectUrls from the oauth2-proxy-customer-management client, and then verifying the script populated. The second execution verified idempotent behavior (did not set the additional URLs on the client if they existed).
=> CASMINST-5759: Use CMN LB for NLS Keycloak setup

workflows/iuf/operations/add-product-to-product-catalog.yaml, workflows/iuf/operations/extract-release-distributions.yaml
argo_workflows_operation_counter{opname="extract-release-distributions",pname="global",pversion="global",stage="process-media",status="Succeeded",type="global"}
argo_workflows_operation_time{opend="1673277775",opname="extract-release-distributions",opstart="1673277695",pdname="global",pdversion="global",stage="process-media",type="global"} 80
=> CASMMON-247 adding metrics

workflows/iuf/stages.yaml
This commit removes the 'set-product-active' operation from the IUF deploy-product stage.
=> CASM-3755: Remove set-product-active from stages.yaml

operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md, workflows/ncn/storage/common.bss-no-wipe.yaml, workflows/ncn/storage/common.envar.yaml, workflows/ncn/storage/common.reboot-node.yaml, workflows/ncn/storage/storage.common.parameters.yaml, workflows/ncn/storage/storage.rebuild.new.yaml, workflows/ncn/storage/storage.rebuild.yaml
Add storage node rebuild workflow. This will be used for IUF stage: management-node-rollout.
This procedure has been tested on Surtur and Frigg.
Example [rebuild on surtur](https://argo.cmn.surtur.hpc.amslabs.hpecorp.net/workflows/argo/ncn-lifecycle-rebuild-74rjp?tab=workflow)
=> CASMPET-5243 add storage node rebuild workflow

workflows/ncn/hooks/after-each/kernel-module-workaround.yaml
These kernel modules must be loaded for ceph-rbd pods to run properly on the new SP4 kernel.
=> CASMTRIAGE-4693 upgrades need to load kernel modules

workflows/iuf/operations/ims-upload.yaml, workflows/iuf/operations/loftsman-manifest-deploy.yaml, workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml, workflows/iuf/operations/preflight-checks-for-services.yaml, workflows/iuf/operations/s3-upload/s3-upload-template.yaml, workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
CASMMON-247 currently, iuf operation does not provide an inbuilt mechanism for r Prometheus metrics.
curl 10.43.0.244:9090/metrics |grep preflight-checks-for-services
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0argo_workflows_operation_counter{opname="preflight-checks-for-services",pname="global", …
=> CASMMON-247 adding deliver-product metrics

workflows/ncn/hooks/before-each/check-dvs-services.yaml
Adds a before-each hook to ensure that at least two other NCNs have DVS loaded and a running CPS pod before restarting a target NCN.
Adds a before-each hook to ensure that at least two other NCNs have DVS loaded and a running CPS pod before restarting a target NCN.
- [] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
=> DVS-2827: add DVS checks for NCN reboots

upgrade/scripts/upgrade/prerequisites.sh
The KUBERNETES_VERSION and CEPH_VERSION variables were mistakenly removed in a previous PR. They are still needed to ensure we collect the correct squashfs files out of the CSM tarball.
The ${arch} variable was missing in a conditional, causing the script to always invoke ncn-image-modification.sh even if it had already run successfully on a previous invocation.
If a non-relative path containing a file glob (*) is quoted, bash will add single quotes to the whole expression. This caused the path - with the glob - to be evaluated literally (without expanding the glob). This resulted in a path being "not found".
=> CASMINST-5767: fix variable construction, add missing vars

upgrade/Stage_1.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4793 -- make it clear we need to do the in family upgrade when upgrading from 1.3 to 1.4.
=> CASMTRIAGE-4793 Add note about in family ceph upgrade for 1.4 upgrades

scripts/operations/node_management/ncn-ims-image-upload.sh
IMS image customization breaks when run on IMS images with names that contain / characters. This PR modifies the CSM upgrade script responsible for create the NCN images in IMS, having it use the basename of the squashfs file, rather than its entire path.
The other small edits in the file were correcting inconsistent use of tabs and regular spaces, but have no functional impact.
I tested the commands manually on wasp to verify that they work as expected.
=> CASMINST-5801: Eschew / characters in NCN IMS image name

scripts/operations/configuration/python_lib/bss.py, scripts/operations/configuration/python_lib/cfs.py, scripts/operations/configuration/python_lib/hsm.py
This PR creates a few Python functions used to query and update BSS bootparameters, and to query and create CFS configurations and sessions. These functions are not currently used by any scripts, but will be used in upcoming PRs.
I tested the BSS functions on mug and validated that they worked as expected. 
I tested the CFS functions on fanta and validated that they worked as expected.
Of course, they will be tested further when they are integrated into other scripts in the future.
=> CASM-3712/CASM-3713: Create Python functions to get/update BSS bootparameters & CFS configs/sessions

operations/configuration_management/Create_an_Image_Customization_CFS_Session.md, operations/image_management/Create_UAN_Boot_Images.md
The primary purpose of this PR is to correct a CFS CLI command that is not valid. The `--image-map` argument should be `--target-image-map`. I also did some additional minor linting.
Backport PRs:
1.4: https://github.com/Cray-HPE/docs-csm/pull/3025
1.3: https://github.com/Cray-HPE/docs-csm/pull/3026
1.2: https://github.com/Cray-HPE/docs-csm/pull/3027
1.0: https://github.com/Cray-HPE/docs-csm/pull/3028
The 1.3 and earlier PRs only contain the linting changes, as the CLI error does not exist in those branches.
=> CASMCMS-8376: Correct CFS CLI command typo; minor linting

workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
The vcs-update-product-catalog step was mistakenly removed by the following commit: 9075f64bb9806c0712d0a091bbbad14f2b284cac.
This commit adds the missing step back into the workflowtemplate.
Test Description: On frigg, I manually modified the workflowtemplate with this step and ensured the VCS information was added to the catalog.
=> CASM-3768: Add workflowtemplate step that was mistakenly removed

operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md, workflows/ncn/hooks/before-each/check-dvs-services.yaml
Ports work for DVS-2827 currently in the main branch to release/1.4:  Adds a before-each hook to ensure that at least two other NCNs have DVS loaded and a running CPS pod before restarting a target NCN.  Handles a fresh install case where COS is not yet present by first checking whether the target is contributing to DVS HA before performing other checks.
- [] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
=> DVS-2827 dvs checks for ncn reboots 1.4

workflows/ncn/hooks/before-all/install-csi.yaml, workflows/ncn/storage/storage.rebuild.yaml
hardcode 15sp4 into install-csi stage of argo workflows. Tested on drax upgrade.
=> CASMTRIAGE-4806 hardcode 15sp4 into install-csi stage of argo workflows

upgrade/scripts/upgrade/prerequisites.sh
Update the cray-tftpd charts in stage 0 of CSM upgrades, so that NCN reboots will use the upgraded images.
=> CASMTRIAGE-4820: Update tftp charts in stage 0 of CSM ugprade

workflows/iuf/operations/ims-upload.yaml, workflows/iuf/operations/loftsman-manifest-deploy.yaml, workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml, workflows/iuf/operations/preflight-checks-for-services.yaml, workflows/iuf/operations/s3-upload/s3-upload-template.yaml, workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml, workflows/iuf/stages.yaml
This pull request cherry-picks changes for IUF into the release/1.4 branch.
=> CASM-3803: Backport IUF changes from main to release/1.4

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml, workflows/iuf/operations/s3-upload/s3-upload-template.yaml
=> CASMINST-5817: add error checking for template input

upgrade/scripts/upgrade/prepare-assets.sh
Remove the extra forward slack in the file path, as it should be consistent with what the instruction says, i.e., `${ENDPOINT}${CSM_REL_NAME}.tar.gz`
=> CASMINST-5800: remove extra forward slash

workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
This change is for IUF.
* Add product catalog updates to the following workflow templates
** nexus-helm-upload
** nexus-docker-load
* Update the version of cray-nexus-setup that is used in IUF
* For nexus-setup and nexus-docker-load, change the order of catalog updates such that they occur directly after the step producing the output
=> CASM-3588, CASM-3590, CASM-3758: (IUF) add product catalog updates to docker and helm uploads

workflows/iuf/operations/loftsman-manifest-deploy.yaml
add product version to path when pulling manifest for loftsman_manifest_deploy stage. This is necessary due to changes being made to the loftsman_manifest_upload stage.
This has not been tested because it cannot be tested on its own. But will be tested through IUF integration testing.
=> CASMINST-5762 add product version to path when pulling manifest for loftsman_manifest_deploy stage

workflows/iuf/stages.yaml
Split the `prepare-images` and `update-cfs-config` IUF stages into two operations, one for management nodes and one for managed nodes. The IUF CLI accepts separate options for specifying the bootprep file for the management nodes vs. the managed nodes. The `sat bootprep` command expects to receive only on input file per invocation. As such, we would already have to call it twice. Splitting the two invocations into separate operations will make it easier for the subsequent stages, `management_nodes_rollout` and `managed_nodes_rollout`, to obtain the output describing the CFS configurations, IMS images, and BOS session templates that were created for the type of nodes being rolled out.
Note that currently, the IUF runs operations serially within a stage. There is a Jira (CASMINST-5702) to …
=> CASMINST-5812: Split prepare-images and update-cfs-config IUF stages

install/deploy_final_non-compute_node.md, install/livecd/Boot_LiveCD_RemoteISO.md, install/livecd/Boot_LiveCD_USB.md, install/pre-installation.md
The new pre-install-toolkit ISO from node-images uses the "pre-install-toolkit" name, and now matches the same name format as the NCN image files.
=> MTL-1476 `s/cray-(pre-install-toolkit)/$1/`

operations/security_and_authentication/Access_the_Keycloak_User_Management_UI.md, operations/security_and_authentication/Change_Keycloak_Token_Lifetime.md, operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md, operations/security_and_authentication/Change_the_LDAP_Server_IP_Address_for_Existing_LDAP_Server_Content.md, operations/security_and_authentication/Create_a_Service_Account_in_Keycloak.md, operations/security_and_authentication/Remove_the_Email_Mapper_from_the_LDAP_User_Federation.md, operations/security_and_authentication/Remove_the_LDAP_User_Federation_from_Keycloak.md, operations/security_and_authentication/Retrieve_an_Authentication_Token.md
Update Keycloak operational documentation to use CMN vs NMN LB. This as the latter requests will now fail due to OPA policy restrictions put in place via [CASMSEC-371](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-371) in CSM 1.3.1 (also in 1.2.2 and 1.4.0, shortly main as well). See https://github.com/Cray-HPE/cray-opa/pull/77. 
The documentation is backward compatible with all 1.3 releases, as they all included the CMN LB and Keycloak access (virtual service) on the ingress path. 
Additional Detail:
* Did not update secret attributes for master admin auth re: internalTokenUrl.
* Use `jq` consistently where possible (vs. mixture of `jq`, and `python`)
* Added double-quotes to URLs for consistency
Also needed in 1.2 re: 1.2.2 patch …
=> CASMINST-5761: Update Keycloak Docs to use CMN LB

operations/hardware_state_manager/Component_Memberships.md, operations/hardware_state_manager/Restore_HSM_Postgres_from_Backup.md, operations/hardware_state_manager/Restore_HSM_Postgres_without_a_Backup.md, operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md, upgrade/scripts/cfs/wait_for_configuration.sh
This change fixes several Cray CLI calls for HSM that are broken in our documentation. In CSM-1.3 a change was made to switch the "type" field in HSM /State/Components from a string to an enum which now requires the argument to be capitalized to match the expected case.
* Resolves CASMHMS-5785 in CSM-1.3.
This change was tested by running the updated CLI calls for HSM on Drax running CSM-1.3 and verifying that they no longer failed and now return the expected data.
Low risk.
=> CASMHMS-5785 Fix HSM CLI calls in docs-csm CSM-1.3

operations/hardware_state_manager/Component_Memberships.md, operations/hardware_state_manager/Restore_HSM_Postgres_from_Backup.md, operations/hardware_state_manager/Restore_HSM_Postgres_without_a_Backup.md, operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md, upgrade/scripts/cfs/wait_for_configuration.sh
This change fixes several Cray CLI calls for HSM that are broken in our documentation. In CSM-1.3 a change was made to switch the "type" field in HSM /State/Components from a string to an enum which now requires the argument to be capitalized to match the expected case.
* Resolves CASMHMS-5785 in CSM-1.4.
This change was tested by running the updated CLI calls for HSM on Wasp running CSM-1.4 and verifying that they no longer failed and now return the expected data.
Low risk.
=> CASMHMS-5785 Fix HSM CLI calls in docs-csm CSM-1.4

operations/hardware_state_manager/Component_Memberships.md, operations/hardware_state_manager/Restore_HSM_Postgres_from_Backup.md, operations/hardware_state_manager/Restore_HSM_Postgres_without_a_Backup.md, operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md, upgrade/scripts/cfs/wait_for_configuration.sh
This change fixes several Cray CLI calls for HSM that are broken in our documentation. In CSM-1.3 a change was made to switch the "type" field in HSM /State/Components from a string to an enum which now requires the argument to be capitalized to match the expected case.
* Resolves CASMHMS-5785 in Main.
This change was tested by running the updated CLI calls for HSM on Wasp running CSM-1.4 and verifying that they no longer failed and now return the expected data.
Low risk.
=> CASMHMS-5785 Fix HSM CLI calls in docs-csm Main

workflows/iuf/hooks/master-host-hook-script.yaml, workflows/iuf/samples/global_params_example.json, workflows/iuf/stages.yaml, workflows/scripts/upload-rebuild-templates.sh
Implement the IUF hooks template.
1. Added a hooks section in stages.yaml, where each template is mapped to the execution context. This would allow us to add new execution contexts without waiting on the cray-nls server code.
2. The master_host template uses the existing ssh-template to ssh into m001 and run the specified hook script.
=> CASM-3717 implement hooks

workflows/iuf/hooks/master-host-hook-script.yaml, workflows/iuf/samples/global_params_example.json, workflows/iuf/stages.yaml, workflows/scripts/upload-rebuild-templates.sh
Implement the IUF hooks template (backport of https://github.com/Cray-HPE/docs-csm/pull/2954)
1. Added a hooks section in stages.yaml, where each template is mapped to the execution context. This would allow us to add new execution contexts without waiting on the cray-nls server code.
2. The master_host template uses the existing ssh-template to ssh into m001 and run the specified hook script.
=> CASM-3717 implement hooks for 1.4

workflows/iuf/samples/global_params_example.json, workflows/iuf/samples/global_params_schema.yaml
Small change mainly meant for IUF developers to update the schema of global params for bootprep config files.
=> CASMINST-5715 fix global params schema and example

operations/system_configuration_service/Configure_BMC_and_Controller_Parameters_with_scsd.md
Added a workaround for the set_ssh_keys.py script.
=> CASMHMS-5890 Add workaround for set_ssh_keys.py script

install/scripts/craycli_init.py, operations/configure_cray_cli.md
Add a `--keycloakHost` option to `craycli_init.py` script. Update documentation to source CMN LB and and use the new option. This as Keycloak administration must now use the CMN ingress path (when using an ingress...). 
Tested on Wasp, running 1.4.0-beta.36. Testing occurred from m002.
=> CASMINST-5837: Add keycloak host option to craycli_init.py, update docs to use CMN LB

workflows/iuf/operations/ims-upload.yaml, workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml, workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
For output parameters that are built from files expected to contain product catalog data, provide a default value. This protects against unexpected cases in which the results file was not written.
Test Description: I made the changes live on #frigg.
=> CASM-3811: Provide default values for outputs

operations/image_management/Import_External_Image_to_IMS.md, scripts/operations/node_management/ncn-ims-image-upload.sh
Add 'etag' information to the description of how to import a boot image into IMS.
=> CASMTRIAGE-4794 - add etag into IMS Image Import docs.

install/deploy_final_non-compute_node.md
=> CASMINST-5859 Remove erroneous `}`

workflows/ncn/hooks/after-each/update-node-label.yaml, workflows/ncn/worker/worker.drain.yaml
If a worker node had cps-pm-node label prior to rebuild, the PR adds it back after the node is rebuilt. 
=> CASMINST-5417: re-label previous CPS node

workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
Latest version of cf-gitea-import image to 1.8.0
[CASMINST-5816](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5816)
=> CASMINST-5816: Bumping cf-gitea-import image

operations/system_management_health/Prometheus_Kafka_Error.md
Description
Update documentation for the Prometheus log being flooded with Prometheus-Kafka-adapter errors during installation for CSM 1.4+.
[CASMMON-260](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-260)
=> CASMMON-260 Update prometheus-kafka-adapter error doc for CSM 1.4+

workflows/iuf/operations/update-cfs-config/update-managed-cfs-config.yaml, workflows/iuf/operations/update-cfs-config/update-management-cfs-config.yaml
This change adds the update-cfs-config-management and update-cfs-config-managed operations, and an overall update-cfs-config stage.
=> CASMINST-5674: Add update-cfs-config stage and operations

workflows/iuf/operations/prepare-images/prepare-managed-images-template.yaml, workflows/iuf/operations/prepare-images/prepare-management-images-template.yaml
Create two Argo workflow templates for the two operations in the
`prepare-images` IUF stage, `prepare-management-images` and
`prepare-managed-images`. The only difference between these two stages
is that they reerence a different bootprep input file from the input
parameters on the IUF Activity.
Note that currently these two operations will occur serially, which is
slower than if we did them concurrently. We could probably improve to
get them running concurrently, but it may not always be safe to run two
`sat bootprep` commands concurrently if they are trying to create items
with the same names.
Tested by running with a `sat bootprep` input file that defined a few
simple CFS configurations, an image built from the barebones recipe, a
customized version of that image, and …
=> CASMINST-5675: Create Argo workflow templates for prepare-images

workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml, workflows/ncn/worker/worker.rebuild.yaml
Worker node rebuild workflow had a regression in CSM 1.4 on where to move critical singleton pods. This PR fixes the regression.
=> CASMINST-5860: fix pod move logic

operations/system_layout_service/Add_Liquid-Cooled_Cabinets_To_SLS.md, scripts/operations/system_layout_service/add_liquid_cooled_cabinet.py
CASMHMS-5907: The proper cabinet class wasn't being set in SLS when adding a EX2500 cabinet to SLS. Replace SLS load state curl command with the appropriate craycli equivalent. 
Tested on Bradi when adding a EX2500 cabinet.
=> (CSM 1.3) CASMHMS-5907: The proper cabinet class wasn't being set in SLS when adding a EX2500 cabinet

operations/system_layout_service/Add_Liquid-Cooled_Cabinets_To_SLS.md, scripts/operations/system_layout_service/add_liquid_cooled_cabinet.py
CASMHMS-5907: The proper cabinet class wasn't being set in SLS when adding a EX2500 cabinet to SLS. Replace SLS load state curl command with the appropriate craycli equivalent. 
Tested on Bradi when adding a EX2500 cabinet.
=> CASMHMS-5907: The proper cabinet class wasn't being set in SLS when adding a EX2500 cabinet.

operations/validate_csm_health.md
Update the description for the verify_hsm_discovery.py script for changes related to the EX2500 cabinet in https://github.com/Cray-HPE/hpe-csm-scripts/pull/35
=> (CSM 1.4) CASMINST-5858: Update description for the verify_hsm_discovery.py script for changes related to the EX2500 cabinet

workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
The original code assumed a different format of targetNcns input. This PR handles the targetNcns input param correctly.
=> CASMTRIAGE-4867: correctly handle the targetNcns input

upgrade/scripts/upgrade/prerequisites.sh
During the upgrade to CSM 1.6, if cray-crus is installed, then uninstall it.
=> CASMINST-5875: Remove CRUS during upgrade to CSM 1.6

.github/CODEOWNERS, .spelling, install/pre-installation.md, operations/README.md, operations/iuf/IUF.md, operations/iuf/examples/iuf_abort.md, operations/iuf/examples/iuf_activity.md, operations/iuf/examples/iuf_list_stages.md, operations/iuf/examples/iuf_restart.md, operations/iuf/examples/iuf_resume.md, operations/iuf/examples/iuf_run.md, operations/iuf/stages/deliver_product.md, operations/iuf/stages/deploy_product.md, operations/iuf/stages/managed_nodes_rollout.md, operations/iuf/stages/management_nodes_rollout.md, operations/iuf/stages/post_install_check.md, operations/iuf/stages/post_install_service_check.md, operations/iuf/stages/pre_install_check.md, operations/iuf/stages/prepare_images.md, operations/iuf/stages/process_media.md, operations/iuf/stages/update_cfs_config.md, operations/iuf/stages/update_vcs_config.md, operations/iuf/workflows/upgrade_all_products.md
* CASMINST-5618 initial IUF content
Add initial IUF content within the operations section. Additional changes and additions are required in this section and none of the other sections of the documentation have been updated to refer to it yet.
* CASMINST-5618 initial IUF content
Add detailed documentation for the update-vcs-config IUF stage.
* CASMINST-5618 initial IUF content
Add an IUF workflow example of upgrading all products in a recipe release without upgrading CSM itself.
* CASMINST-5618 initial IUF content
This commit futher fleshes out IUF details, including:
- fixing the format of session IDs in examples
- including updated help text for multiple commands
- adding details about the IUF CLI output
- adding initial troubleshooting information
- changing the username in example …
=> CASMINST 5618 initial IUF content (#3056)

workflows/iuf/operations/prepare-images/prepare-managed-images-template.yaml, workflows/iuf/operations/prepare-images/prepare-management-images-template.yaml, workflows/iuf/operations/update-cfs-config/update-managed-cfs-config.yaml, workflows/iuf/operations/update-cfs-config/update-management-cfs-config.yaml
Added stub operations to get prom-metrics for update-cfs-config prepare-images stages 
iuf -a ram-1  -m /opt/cray/iuf/rambabu  run --site-vars /opt/cray/iuf/site_vars.yaml --bootprep-config-dir /etc/cray/upgrade/csm/iuf/hpc-csm-software-recipe-23.1.18/vcs -b  prepare-images -e prepare-images
INFO All logs will be stored in …
=> CASMMON-257 adding metrics for update-cfs-config prepare-images stages 

workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml
Added metrics management-nodes-rollout get prom-metrics for update-cfs-config prepare-images stages
=> CASMMON-257 adding metrics for management-nodes-rollout

workflows/iuf/operations/managed-nodes/managed-nodes-rollout.yaml
Added metrics  managed-nodes-rolloutget prom-metrics for update-cfs-config prepare-images stages
=> CASMMON-257 adding metrics for managed-nodes-rollout metrics

workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
Bumping cf-gitea-import image to latest, contains IUF required fixes regarding logging.
[CASMINST-5866](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5866)
=> CASMINST-5866: Bumping version cf-gitea-import 1.8.1

workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
Adding in bumped version change from `main`
Also adds IUF logging formatting
=> CASMINST-5866: Bumping gitea upload to version 1.8.1

workflows/iuf/operations/managed-nodes/managed-nodes-rollout.yaml, workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
Abstracts SAT and BOS V2 staged rebooting of managed compute and application nodes. This workflow wraps SAT and does preprocessing of IUF stage data to forward the requests to BOS V2.
JIRA https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5691
Needed for IUF code feature freeze.
=> CASMINST-5691: Adds managed nodes rollout IUF operation

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml
Update the product catalog with Loftsman manifest data.
=> CASM-3727: Update product catalog with loftsman information

workflows/iuf/operations/extract-release-distributions.yaml, workflows/iuf/operations/ims-upload.yaml
This change bumps the container image versions for the following
containers:
- cray-ims-load-artifacts
- iuf
- cf-gitea-import
Also needs to be backported to `release/1.4`.
=> CASMINST-5818: Bump container image versions

workflows/iuf/operations/loftsman-manifest-deploy.yaml
allow IUF-stage: loftsman_manifest_deploy to accept `*.yaml` files when looking for loftsman manifests
=> CASMINST-5848-release-1.4 allow IUF-stage: loftsman_manifest_deploy to accept `*.yaml` files when looking for loftsman manifests

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh, workflows/ncn/worker/worker.common.parameters.yaml, workflows/ncn/worker/worker.drain.yaml, workflows/ncn/worker/worker.rebuild.yaml
add ability to use image-id in worker rebuild workflow. This has not been tested and is just an example of how to add this functionality.
=> CASMPET-6034 add ability to use image-id in worker rebuild workflow

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/rfe.md, .github/PULL_REQUEST_TEMPLATE.md
Implementing some more explicit instructions in the PR template after receiving copious feedback on:
- checkboxes
- premature merge
- dependent/required/related content
This also includes an issue template to assist with external users making Github Issues.
=> More explicit instructions for PRs

install/deploy_final_non-compute_node.md
=> CASMINST-5894: hex-aware unix-fu for setting efibootmgr nextboot

scripts/operations/node_management/ncn-ims-image-upload.sh, upgrade/scripts/upgrade/prerequisites.sh
When the code to update the cray product catalog with NCN image info was added, the output for the `podman` call was not redirected to /dev/null. As a result, that output was processed by `prerequisites.sh`, which lead to other problems downstream.
This commit does two things:
1. Redirects stdout from the podman call to /dev/null
2. Adds a regex check on the output from the script to ensure the only thing we're getting is a valid UUID.
=> CASMINST-5900: direct cray-product-catalog-update output to /dev/null

workflows/iuf/stages.yaml
[CASMINST-5746](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5746)
Summary: IUF operator should conditionally include operations based IUF product manifest contents
As a product developer, I want the IUF to skip operations that do not apply to my product based on the contents of my IUF product manifest, so that unnecessary operations are not executed and misleading information is not presented to the user through logs or product catalog.
The stages.yaml needs to be updated to add a JSON path expression that indicates the property it consumes from the IUF Product Manifest.
If the property specified for a given operation in stages.yaml is not present in the IUF product manifest for a given product, then the IUF operator should omit the operation for that product entirely from the …
=> CASMINST-5746

workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
This commit updates all references to cray-nexus-setup from 0.9.0 to 0.9.1 to include bug fixes required for IUF.
=> CASM-3859: Use cray-nexus-setup 0.9.1 in IUF

operations/security_and_authentication/Change_Air-Cooled_Node_BMC_Credentials.md
CRAYSAT-1617: Further expand on River BMC password configuration doc
* Provide more reference information on `sat bmccreds`, specifically linking to the more complete procedure found in the "system_configuration_service" directory as well as the `sat-bmccreds` man page.
* Reiterate what exactly this procedure does by adding a sentence more in the step that runs `sat bmccreds`.
* Add optional step to view the generated password in vault, and confirm that the `sat bmccreds` command itself is not supposed to echo the password.
* Ensure command prompts follow the documented convention.
=> CRAYSAT-1617: Further expand on River BMC password configuration doc

workflows/iuf/operations/ims-upload.yaml, workflows/iuf/operations/vcs-update/vcs-update-working-branch.yaml, workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
Adds changes to the following templates:
- ims-upload
- vcs-upload
- vcs-update-working-branch
Required to mount certs via a configMap instead of hostPath due to storage issues from IUF
Update the Argo workflow template that implements the `update-vcs-config` stage of the IUF to properly handle a product that doesn't have a `working_branch` in the site parameters. This requires a corresponding update to the cf-gitea-update image to handle an empty string value for the CUSTOMER_BRANCH environment variable.
Update the Argo workflow templates that implement the `vcs-upload` and `update-vcs-config` stages of the IUF, so that they can create repos named according to the new `content.vcs.repo_name` property which was added in the IUF Product Manifest schema.
This requires changes to the …
=> CASMINST-5843, CASMINST-5902, CASMINST-5876: Fix bugs in ims-upload, vcs-upload, and update-vcs-config IUF stages

operations/validate_csm_health.md
Some of the CSM health validation tests require the Cray CLI to be configured. The procedure for doing this varies slightly based on whether it is being done during an install versus being done later. This PR modifies the instructions and links accordingly.
=> CASMINST-3950: Provide more precise and appropriate links for configuring the Cray CLI before validating CSM health

.github/workflows/license-check.yaml
License check sporadically fails to determine the list of changed files. This seems to be happening due to a bug in `tj-actions/changed-files@v34`, which does not filter out temporary merge commits, created by Github to assess mergeability of PR. The `tj-actions/changed-files@v34` has this problem addressed.
=> CASMINST-5921 License check sporadically fails

workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
=> CASMINST-5920: Use new version of cray-nexus-setup in IUF

scripts/operations/node_management/ncn-ims-image-upload.sh
The escaped quotes needed for the remove execution of the command cause problem when run locally.
=> CASMINST-5928: run unquoted command when running locally

.spelling, operations/validate_csm_health.md, troubleshooting/interpreting_hms_health_check_results.md, troubleshooting/known_issues/issues_with_ncn_health_checks.md, troubleshooting/known_issues/sms_health_check.md
The Cray CLI being configured is mentioned at the top of the CSM health checks page, but it is not mentioned in most of the troubleshooting sections for the tests which require it to be configured. This PR corrects that. It also clarifies the actual CLI requirements for HMS tests.
=> CASMINST-3943: Update CSM health check troubleshooting information, specifically for issues related to unconfigured CLI

operations/firmware/Updating_Firmware_m001.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/3239
=> CASMINST-4654: Add warning about updating ncn-m001 firmware when booted from remote ISO

workflows/iuf/operations/prepare-images/prepare-managed-images-template.yaml, workflows/iuf/operations/prepare-images/prepare-management-images-template.yaml, workflows/iuf/operations/update-cfs-config/update-managed-cfs-config.yaml, workflows/iuf/operations/update-cfs-config/update-management-cfs-config.yaml
Use INFO prefix on messages for skipped bootprep stages
Use the "INFO " prefix in the messages printed by the operations in the
"update-cfs-config" and "prepare-images" stages when no bootprep file is
provided to the operations in those stages.
This will ensure these messages are displayed to the end user at INFO
level.
Tested in combination with CASMINST-5936 on frigg by running the
update-cfs-config and prepare-images stages without passing in bootprep
files for either management or managed nodes and confirmed that the
INFO-level messages were logged to stdout by the CLI.
Use BOS v2 in prepare-images stage
For consistency with the managed-nodes-rollout stage, use BOS v2 when
creating BOS session templates in the prepare-images stage. Although
only the …
=> CASMINST-5936, CASMINST-5885: Small fixes to update-cfs-config and prepare-images IUF stages

.github/CODEOWNERS
ssi-reviewers is constantly the only team being queried for reviews.
=> Explicitly add docs-csm-reviewers

workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml, workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
=> CASMINST-5944: (IUF): Use new version of cray-nexus-setup in IUF

RELEASE_NOTES.md, glossary.md, introduction/deprecated_features/README.md, operations/README.md, operations/boot_orchestration/Rolling_Upgrades.md, operations/compute_rolling_upgrades/CRUS_Workflow.md, operations/compute_rolling_upgrades/Compute_Rolling_Upgrades.md, operations/compute_rolling_upgrades/Troubleshoot_Nodes_Failing_to_Upgrade_in_a_CRUS_Session.md, operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Bad_Parameters.md, operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Unmet_Conditions.md, operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md, operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md, troubleshooting/README.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/3274
=> CASMINST-5957: Replace CSM 1.6 references with CSM 1.5

workflows/iuf/operations/extract-release-distributions.yaml
CASMINST-5967 BREAK/FIX: IUF process-media doesn't extract full tarball when previous run is aborted halfway through
Unfortunately, an optimization that was made to process-media is now causing a critical issue whereby an IUF run is aborted during process-media, and the next run assumes the extraction was successful, and hence doesn't re-extract fully.
We need to either remove this optimization or insert a file containing the md5 sum of tarball when extract is complete in order to skip.
=> CASMINST-5967

operations/sat/sat_in_csm.md
Some sections in the SAT documentation were renamed and moved because of recent changes for IUF. References to these sections in docs-csm need to be updated.
Relates to:
- [STP-3525](https://jira-pro.its.hpecorp.net:8443/browse/STP-3525)
=> STP-3525: Update references to docs-sat

workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
- https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5954 Resolves git error not exiting gracefully.
=> CASMINST-5954: bump cf-gitea-import to 1.9.1

operations/configuration_management/Management_Node_Image_Customization.md, operations/image_management/Import_External_Image_to_IMS.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/3265
(note that this is actually a smaller set of changes for 1.4 and main, because in those releases the S3 path will always be an IMS image ID -- these changes just carry forward some of the linting / quality of life improvements from the original PR)
=> CASMINST-5942: Modify NCN image customization procedure to be more flexible

operations/iuf/IUF.md, operations/iuf/examples/iuf_restart.md, operations/iuf/examples/iuf_resume.md, operations/iuf/stages/update_vcs_config.md
Address IUF doc issues CASMINST-5935 and CASMINST-5904. 
=> CASMINST-5935 / CASMINST-5904

upgrade/scripts/upgrade/prerequisites.sh
Explicitly disable `rd.live.overlay.thin` to prevent the extraneous error messages from printing.
Based on the feedback we received from the dracut developers, a thin overlay can not be used with a read-only squashFS image like ours. Therefore enabling a thin overlay has no effect, and we can mitigate the errors by not requesting a thin overlay.
https://github.com/dracutdevs/dracut/issues/2198#issuecomment-1432471630
=> MTL-2085 Fix extraneous dracut messages on boot

operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Update the "kubeadm [alpha] kubeconfig user" command to use the --config argument.  The --apiserver-advertise-address and --apiserver-bind-port arguments are no longer supported.  In CSM 1.3+ the 'alpha' portion of the 'kubeadm' command is optional so this is being removed in the CSM 1.3+ versions of the doc.
Resolves [CASMPET-6315](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6315) for CSM 1.3
Backports of this change for CSM 1.4 and main branch are in progress.
=> CASMPET-6315 : DOCS : Cert renewal - update kubeadm [alpha] kubeconifg user

operations/utility_storage/Troubleshoot_ceph_image_with_none_tag.md
CASMPET-6332- replace less than and greater than signs with HTML entities
=> CASMPET-6332 replace less than and greater than signs with HTML entities

workflows/ncn/hooks/before-all/install-csi.yaml
Make install_csi hook more robust. It will check both sp3 and sp4 for link to install csi and will only fail if unable to install csi, independent of installing other repositories. Provides an error message if nexus appears to be down.
=> CASMTRIAGE-4824 make install_csi hook more robust

operations/README.md, operations/configuration_management/Management_Node_Image_Customization.md, operations/image_management/Import_External_Image_to_IMS.md, operations/image_management/Import_NCN_Image_to_IMS.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, scripts/operations/node_management/ncn-image-modification.sh, scripts/operations/node_management/ncn-ims-image-upload.sh
Backport of https://github.com/Cray-HPE/docs-csm/pull/3299
This includes backporting just the IMS upload portion of the ncn-ims-image-upload.sh script (and not the cray-product-catalog part of it), so that it can be used to simplify some of the procedures.
=> CASMINST-5979: Correct some NCN customization procedures

operations/README.md, operations/configuration_management/Management_Node_Image_Customization.md, operations/image_management/Import_External_Image_to_IMS.md, operations/image_management/Import_NCN_Image_to_IMS.md, operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md, scripts/operations/node_management/ncn-image-modification.sh, scripts/operations/node_management/ncn-ims-image-upload.sh
The procedure to update NCN timezones has a few errors in it. In addition, after the CSM install is done, it really should only be used just for timezones, and passwords/SSH keys should be handled using CFS. This PR overhauls that procedure (and makes some small script tweaks) to accomplish the above. While writing and testing these changes, I found other odds and ends in related procedures that I also cleaned up with this PR.
I tested this on fanta except for actually updating the entries in BSS (but I did test the commands to do that -- I just had them echo rather than run the final command to do the update).
- [1.4 backport PR](https://github.com/Cray-HPE/docs-csm/pull/3310)
- [1.3 backport PR](https://github.com/Cray-HPE/docs-csm/pull/3311)
The PRs should be reviewed by at least one …
=> CASMINST-5979: Correct procedures for customizing NCN image timezone post-install

operations/boot_orchestration/Stage_Changes_with_BOS.md
Fixes a typo in the command to stage a boot with BOS v2
Relates to: CAST-32234
=> CAST-32234: Fix typo in BOS staging docs

workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml
CASMINST-5994 create new loop for rebuild-worker-nodes due to argo bug.
This prevents the workflow getting into a bad state if a step was to fail.
This has been tested on Gamora.
=> CASMINST-5994 create new loop for rebuild-worker-nodes due to argo bug

operations/node_management/Rebuild_NCNs/Final_Validation_Steps.md, operations/node_management/Rebuild_NCNs/Identify_Nodes_and_Update_Metadata.md, operations/node_management/Rebuild_NCNs/Post_Rebuild_Storage_Node_Validation.md, operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md, operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md, operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md, operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md, operations/node_management/Rebuild_NCNs/Validate_Boot_Loader.md
Redirect back to main rebuild page instead of directly to next step.
Resolves [CASMINST-6001](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6001)
=> Refactor rebuild links to avoid following next step if not rebuilding (CASMINST-6001)

scripts/operations/node_management/ncn-ims-image-upload.sh
$PITDATA should only be set if /etc/pit-release exists. This commit fixes inverted and/or logic.
=> CASMINST-6018: fix $PITDATA handling

upgrade/Stage_0_Prerequisites.md
Clarify which cephfs share steps are required for upgrade
Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6029
=> Clarify which cephfs share steps are required for upgrade (CASMINST-6029)

upgrade/scripts/upgrade/prerequisites.sh
Relates to:
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5006
- [ x ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.
=> CASMTRIAGE-5006: Add trustedcerts-operator to prerequisite upgrades

workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml
When doing a csm upgrade, ncn-m002 and ncn-m003 need to be upgraded before the worker nodes are upgraded. The order is corrected in this PR.
Master nodes should not be 'rebuilt' as part of IUF but they should be 'upgraded'. If no CSM upgrade is happening, then the master nodes are configured with CFS. This is correct in the IUF documentation.
=> CASMINST-6032 change management-nodes-rollout to upgrade master nodes before rebuilding workers

scripts/operations/node_management/ncn-ims-image-upload.sh
The previous fix to this conditional missed changing `-n` (variable set) to `-z` (variable empty) when the logic was restructured.
=> CASMINST-6039: fix PITDATA logic. Again.

install/deploy_final_non-compute_node.md, operations/kubernetes/Fix_Failed_to_start_etcd_on_Master.md
Add procedure to correct master nod not joining cluster.
Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6049
=> Add procedure for correcting etcd not starting on master (CASMINST-6049)

troubleshooting/interpreting_hms_health_check_results.md
There is a situation where PCS does not have any information in its ETCD cluster and won't have any until PCS is restarted. This is documented in the tavern tests in understanding tavern failures. Once PCS has been restarted following the WAR instructions, PCS will contain the proper information.
- CASMHMS-5937
=> CASMHMS-5937 Add PCS WAR to tavern documentation CSM-1.4

.spelling, operations/image_management/IMS_export_import.md
In upcoming work for [CASMINST-6054](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6054), there will be a number of changes made to the IMS import/export procedure. In order to make those changes easier to review, I've tried to do as much of my usual linting as possible up front. That is what is being done in this PR. It is not intending to make true content changes to the page -- it is just correcting some issues, making minor improvements, and doing some minor reorganization.
- [1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3411)
- [1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3412)
Backports to earlier releases are not needed, as the IMS import/export procedure does not exist in them.
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documenta …
=> CASMINST-6056: Linting of IMS import/export procedure

RELEASE_NOTES.md
Add a known issue to match what was included in CSM 1.3* as this is still relevant to UAIs in CSM 1.4.
=> CASMUSER-3175: Add known issue for default route use in UAIs

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
=> CASMINST-5981 add log headers so IUF cli can show progress

scripts/mount-cephfs-share.sh
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6385
surtur:
```
ncn-m001:~ # /usr/share/doc/csm/scripts/mount-cephfs-share.sh
Didn't find previous CSM release rbd mount, proceeding...
Didn't find s3fs mount at /var/lib/admin-tools, proceeding...
Creating admin-tools ceph fs share...
Sleeping for five seconds waiting for 3 running mds.admin-tools daemons...
Sleeping for five seconds waiting for 3 running mds.admin-tools daemons...
Sleeping for five seconds waiting for 3 running mds.admin-tools daemons...
Found 3 running mds.admin-tools daemons -- continuing...
Creating admin-tools keyring...
[client.admin-tools]
key = AQAfnQdkPM0iLBAAE8aYOsH8aLMc1w5xOtuCuA==
export auth(key=AQAfnQdkPM0iLBAAE8aYOsH8aLMc1w5xOtuCuA==)
fstab entry for cephfs already present...
Done! …
```
=> Add call to set enable_multiple to true for cephfs share (CASMPET-6385)

upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
=> CASMINST-6064 Ceph upgrade missing step

operations/package_repository_management/Nexus_Import_Embedded_Repo.md
This commit amends Nexus_Import_Embedded_Repo.md to include adding the embedded repo to the list of repos csm-config-management adds via ansible during image customization and/or node personalization.
=> CASMINST-6060: add the embedded repo to csm-config-management

operations/System_Recovery.md
Resolves [CASMINST-6073](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6073) DOCS: Typo system recovery procedure for keycloak for main
Backport to release/1.4
=> CASMINST-6073 main : DOCS: Typo system recovery procedure for keycloak

operations/kubernetes/Restore_Postgres.md
This issue was fixed previously in CASMINST-5362 but later removed as part of lint cleanup (CASMINST-5663)
This resolves [CASMINST-6074](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6074) Backup and Restore: Drax - No LDAP users after backup and restore for main
Backport to 1.4, 1.3 and 1.2
- [ x If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
=> CASMINST-6074 main : Backup and Restore: Drax - No LDAP users after backup and restore

upgrade/scripts/upgrade/util/update-customizations.sh
Update the update-customizations.sh script to change the values for keycloak from keycloak to keycloakx to adjust for new values in updated chart.
=> CASMPET-6400: Update update-customizations.sh for keycloak 20.0.5

install/scripts/csm_services/steps/7.docs_csm_upload_rebuild_templates.yaml
IUF workflows are not starting up
IUF workflow templates are not uploaded
The root cause here is that the fresh-install path does not ever install the Argo workflow templates from docs-csm (using the script in /usr/share/doc/csm/workflows/script/upload-rebuild-templates.sh) 
Note that for the upgrade path, it does this through the prerequisites.sh, but we never run prerequisites.sh on a fresh install.
One solution here is to add an instruction to run upload-rebuild-templates.sh once kubernetes is up and running.
Note that we want to move away from having these templates part of docs-csm for 1.6.0 so this is a temporary measure (i.e. IUF backend will install these templates itself when it boots up).
Tested on gamora
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentat …
=> CASMTRIAGE-5069 add upload-rebuild-templates.sh to install workflow

.github/workflows/link-checker.yaml
Backport of https://github.com/Cray-HPE/docs-csm/pull/3468 to `release/1.4`.
=> CASMINST-6062 Do a full link-checker scan if files were deleted/renamed [release/1.4]

.github/workflows/link-checker.yaml
If one or more `*.md` files were deleted or renamed, references to these files may have not been updated. Currently, link checker does not catch such errors, because it only verifies changed files, and the files where reference are originating from may be unchanged. To catch this type of issue, full re-scan (all `*.md` files) is needed.
This PR also adds `workflow_dispatch` trigger to `Check Links` workflow, with optional `Enforce Full Scan` flag. This allows to run full scan manually.
Temporarily renamed one file to trigger full re-scan. It was successfully triggered, and uncovered the following broken links (filtered for readility, and removing temporary filename change):
https://github.com/Cray-HPE/docs-csm/actions/runs/4449788607/jobs/7814442768
FILE: …
=> CASMINST-6062 Do a full link-checker scan if files were deleted/renamed [main]

troubleshooting/known_issues/sms_health_check.md
Add a short note in the `cmsdev` test details page explaining that the tftp file transfer subtest is omitted on master nodes, but that it's run automatically on a worker node as part of the Goss tests.
- Resolves [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
- Problem created by the change made in [CASMCMS-8450](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8450)
- Problem reported by [CASMTRIAGE-5071](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5071)
- [cmsdev test tool PR](https://github.com/Cray-HPE/cms-tools/pull/73)
- [csm-testing PR](https://github.com/Cray-HPE/csm-testing/pull/458)
=> CASMCMS-8473: Add note to cmsdev test details page about tftp file transfer subtest

operations/power_management/Cray_Advanced_Platform_Monitoring_and_Control_CAPMC.md
The deprecated interfaces of CAPMC were not under the deprecation heading. Moved the heading to include the deprecated interfaces.
- [CASMHMS-5956](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5956)
=> CASMHMS-5956 CAPMC deprecation update

RELEASE_NOTES.md, operations/boot_orchestration/BOS_API_Versions.md, operations/boot_orchestration/Boot_Orchestration.md
When no version is specified for a cray bos <command>, the default BOS version is V2. Previously, it was V1.
=> CASMCMS-8481: Make BOS V2 the default

update_product_stream/README.md
The consolidation of the RPM fetching step in the upgrade into caused a gap where the fetched RPMs are not available for the `prereqs` script.
There also was some duplication of steps in fetch RPM steps.
=> CASMINST-6128 Copy the RPMs to `/root`

operations/README.md, operations/node_management/Defragment_NID_Numbering.md, scripts/operations/node_management/defragment_nids.py, troubleshooting/known_issues/antero_node_NID_allocation.md
This adds the defragment_nids.py script and the `Defragment NID Numbering` procedure to docs-csm for CSM 1.3.
=> CASMHMS-5565: Add NID defragmentation script and procedure CSM 1.3

operations/README.md, operations/node_management/Defragment_NID_Numbering.md, scripts/operations/node_management/defragment_nids.py, troubleshooting/known_issues/antero_node_NID_allocation.md
This adds the defragment_nids.py script and the `Defragment NID Numbering` procedure to docs-csm for CSM 1.4.
=> CASMHMS-5565: Add NID defragmentation script and procedure CSM 1.4

upgrade/scripts/k8s/tds_lower_cpu_requests.sh, upgrade/scripts/upgrade/prerequisites.sh
Cleanup tds script for metallb daemonset and run on new PoR systems with 4 workers.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5110
* frigg
Prior to running three workers were at 99%:
```
Resource           Requests            Limits
--------           --------            ------
cpu                43749m (68%)        596250m (931%)
memory             161364476672 (59%)  811658718464 (301%)
Resource           Requests           Limits
--------           --------           ------
cpu                41774m (65%)       609850m (952%)
memory             96787884288 (35%)  758387690752 (281%)
Resource           Requests         Limits
--------           --------         ------
cpu                4936m (7%)       71600m (111%)
memory             7817211136 (2%)  130756455680 (48%) …
```
=> Updates to TDS settings and run on 4 worker node systems (CASMTRIAGE-5110)

upgrade/scripts/upgrade/prerequisites.sh
Updates the upgrade prerequisistes script for csm-1.4 to include a step updating the cfs-operator configmap.  This updates the image CFS uses to build Ansible inventory early in the upgrade because some csm-config Ansible code in csm-1.4 requires a change made to the way we build inventory.
- Relates to: CASMTRIAGE-5115
=> CASMTRIAGE-5115: Add cfs-operator config change to upgrade prerequisites

operations/image_management/IMS_export_import.md, scripts/operations/system_recovery/ims-import-export.py
When importing IMS images and recipes, not only does the IMS ID change, but the etag will change as well. For images in particular, BOS session templates may refer to these etag values for the image manifest. Accordingly, the import procedure needs to record these changes just as it does for the IMS IDs.
This PR just adds that data to what is collected during the IMS import procedure. I tested this on wasp and verified that the information is correctly recorded. 
- [1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3533)
- [1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3532)
No backports needed for pre-1.3 as the procedure did not exist then.
[2]: …
=> CASMINST-6135: IMS import/export: Record S3 etag changes on import

workflows/ncn/hooks/after-each/update-node-label.yaml
=>  CASMTRIAGE-5131 force cpm label in case the label has applied

scripts/repair-ceph-latency.sh
Refactor latency script to simply set rocksdb options and restart osds without checking if the cluster is currently exhibiting latency.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5138
* `ashton`
```
ncn-m002:~/brad # ./repair-ceph-latency.sh
Ceph is healthy -- continuing...
INFO: beginning restart of daemons on ncn-s001.
INFO: failing active manager to another node (from ncn-s001).
Sleeping for 30 seconds waiting for mgr to fail over...
noout is set
norecover is set
nobackfill is set
Daemons for Ceph cluster 7dd7193a-cb42-11ed-af07-42010afc0104 stopped on host ncn-s001. Host ncn-s001 moved to maintenance mode
Sleeping for ten seconds waiting for daemons to stop...
All daemons stopped, continuing...
Ceph cluster 7dd7193a-cb42-11ed-af07-42010afc0104 on ncn-s001 has exited …
```
=> Change ceph latency script to always restart osds (CASMTRIAGE-5138)

upgrade/scripts/upgrade/csm-upgrade.sh
Add pool fix to csi script if pulling from older version.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5144
* `tyr`
Kurt is re-running with this change on tyr.
Low
* Nothing
=> Fix cephfs storage class config map for add'l pool (CASMTRIAGE-5144)

upgrade/1.3.2/README.md
Add guidance to 1.3.2 patch release to upgrade CANU to 1.7.1.
Relates to:
- CASMNET-2056
=> CASMNET-2056 Update CANU in 1.3.2 Patch Docs

upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh, workflows/ncn/storage/storage.upgrade.yaml
The storage node upgrade previously was performing the following steps:
1. push local running ceph container images to nexus
2. point ceph daemons to use nexus image by doing a ceph orch upgrade nexus_image 
3. reboot node to upgrade node image
4. redeploy daemons
The upgrade was having trouble with step 2.
This PR changes the storage node upgrade to do the following steps:
1. push local running ceph container images to nexus
2. reboot node to upgrade node image
3. redeploy daemons explicitly telling them to use the nexus_image
Note: this new upgrade will not run pre-load-images.sh once the node has been upgraded. This makes it so after the upgrade, the ceph daemons will be running off of the ceph container images in nexus and do not need to have any local containers.
This has been tested …
=> CASMPET-6440 change storage upgrade to deploy daemons with nexus image after node reboots

scripts/operations/configuration/python_lib/product_catalog.py, scripts/operations/configuration/update_product_catalog_ims_ids.py, scripts/operations/system_recovery/ims-import-export.py
Starting in CSM 1.4, the Cray Product Catalog contained pointers to IMS image and recipe IDs. This PR modifies the IMS import script so that after import, if any IDs have changed, the Product Catalog will be updated if necessary.
I also provide a standalone script that will just update a specified IMS ID in the Cray Product Catalog. It uses the same backend code, but is intended for use in the docs when a user is manually importing just a single image or recipe, and wants to update the product catalog with the changed ID.
This involved writing code to find the latest version of the product catalog updater image. Code had already been written for parsing the product catalog. This makes use of that, searching each entry in the product catalog for images and recipes. And then if there are …
=> CASMINST-6150: Update Cray Product Catalog after IMS import

workflows/ncn/worker/worker.post-rebuild.yaml, workflows/ncn/worker/worker.wipe-and-reboot.yaml
Change bgp test when run after worker rebuild to only check that worker.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5164
* `surtur`
```
ncn-w003:~ # TARGET_NCN=ncn-w003 GOSS_BASE=/opt/cray/tests/install/ncn SW_ADMIN_PASSWORD='!nitial0' /opt/cray/tests/install/ncn/scripts/check_bgp_neighbors_established_brad.sh
NAME      DATA   AGE
metallb   1      3d5h
CAN
Running: canu validate network bgp --verbose --network all --password XXXXXXXX
PASS
```
Low
* Nothing
=> Add success output to validate-bss-ntp (CASMTRIAGE-5164)

workflows/ncn/worker/worker.post-rebuild.yaml, workflows/ncn/worker/worker.wipe-and-reboot.yaml
Change bgp test when run after worker rebuild to only check that worker.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5164
* `surtur`
```
ncn-w003:~ # TARGET_NCN=ncn-w003 GOSS_BASE=/opt/cray/tests/install/ncn SW_ADMIN_PASSWORD='!nitial0' /opt/cray/tests/install/ncn/scripts/check_bgp_neighbors_established_brad.sh
NAME      DATA   AGE
metallb   1      3d5h
CAN
Running: canu validate network bgp --verbose --network all --password XXXXXXXX
PASS
```
Low
* Nothing
=> Change bgp test to test only the worker being rebuilt (CASMTRIAGE-5164)

operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md, operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md
This is necessary because for CSM-1.4 we are using the sp3 version of storage nodes. So storage nodes will not have the latest scripts in their image so they should be copied from ncn-m001.
=> CASMINST-6196-1.4 copy latest files for storage rebuild from ncn-m001 before executing

troubleshooting/known_issues/sms_health_check.md
Main backport of https://github.com/Cray-HPE/docs-csm/pull/3604
=> CASMCMS-8529: Note new log location for cmsdev test tool

upgrade/scripts/upgrade/prerequisites.sh
This toggle is handled by various scripts (argo and otherwise) at the time of the individual/group NCN upgrade(s). There is no need to set it at the time we associate images with IMS and update the boot parameters.
- [ x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.
=> CASMINST-6209: don't toggle metal.no-wipe when associating new images with IMS

install/install_csm_services.md
Adds a note that the user may be prompted for a password during the execution of the `yapl execute`, to indicate that this will be a prompt for the password of the `pit` nodes (`ncn-m001`)
=> CASMTRIAGE-5102: Add note for password prompt during the yapl execute command

install/pre-installation.md
In CSM-1.4 (only), we have SLES SP3 images on storage nodes and SP4 images on kubernets nodes. As a result, the kernels do not match. Add a note saying the message emitted by set-sqfs-links.sh bout mismatched kernels can be ignored.
=> CASMTRIAGE-5197: add note about mismatched kernels

troubleshooting/interpreting_hms_health_check_results.md
This change adds an explicit output example to the HMS test documentation for when hardware problems on nodes cause flags to be set in HSM and result in CSM validation test failures. Previously these types of cases were addressed in plain text but did not include an example.
* Resolves CASMHMS-5976 in CSM-1.4
No risks.
=> CASMHMS-5976 Add test failure output example for Warning flag in HSM CSM-1.4

troubleshooting/interpreting_hms_health_check_results.md
This change adds an explicit output example to the HMS test documentation for when hardware problems on nodes cause flags to be set in HSM and result in CSM validation test failures. Previously these types of cases were addressed in plain text but did not include an example.
* Resolves CASMHMS-5976 in CSM-1.3
No risks.
=> CASMHMS-5976 Add test failure output example for Warning flag in HSM CSM-1.3

troubleshooting/interpreting_hms_health_check_results.md
This change adds an explicit output example to the HMS test documentation for when hardware problems on nodes cause flags to be set in HSM and result in CSM validation test failures. Previously these types of cases were addressed in plain text but did not include an example.
* Resolves CASMHMS-5976 in CSM-1.2
No risks.
=> CASMHMS-5976 Add test failure output example for Warning flag in HSM CSM-1.2

troubleshooting/README.md, troubleshooting/known_issues/HSM_Discovery_StoreFailed_Error.md
This adds a section to Known Issues for workarounds to [CASMTRIAGE-5190](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5190) - HSM Discovery StoreFailed.
This page is only needed for CSM 1.3 at this time.
=> CASMHMS-5975: Add known issues page for HSM Discovery StoreFailed

workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml
Get CFS configs for specific management node types
=> CASMINST-6233 get CFS configs for specific management node types

operations/power_management/Recover_from_a_Liquid_Cooled_Cabinet_EPO_Event.md
Documentation for recovery from EPO indicated a need to bring up the Slingshot fabric. That is not needed as the Slingshot fabric will automatically come up after hms-discovery powers the Colorado switches back On. The step has been reworked to indicate the admin needs to validate the health of the fabric instead.
Relates to:
- CASMTRIAGE-5114
=> CASMTRIAGE-5114 Update Slingshot fabric step after EPO event

operations/iuf/workflows/configuration_of_SFM.md
The section of the IUF docs that refered to the Slingshot Fabric Manager instructions had some copy/paste issues that this resolves.
=> CASMINST-6242 Fix Slingshot Fabric Manager IUF documentation

operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
Instructions for restarting the cray-orca system daemon were including nodes that did not run the cray-orca system daemon. Cleaned up the verbiage and commands to execute.
Relates to:
- [CASMHMS-5968](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5968)
=> CASMHMS-5968 Improve verbiage for restarting orca when recovering HMNFD ETCD

upgrade/Stage_2.md
Added text to Stage 2 to refer the reader back to IUF when appropriate.
=> CASMINST-6249 Correct management rollout procedure

workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml
Remove check to make sure master nodes is in k8s cluster in management-nodes-rollout. This check creates a bug when a master node has been partially upgraded. For example, if a master node has been removed from the cluster and power cycled and the workflow has been stopped. Then, if the workflow is restarted, this check will fail because the node is not part of the cluster and it will prevent the workflow from continuing.
=> CASMINST-6257 remove check to make sure master node is in k8s cluster in management-nodes-rollout

.spelling, operations/iuf/workflows/managed_rollout.md
Document a way to detect a hang in the IUF managed-nodes-rollout workflow.
=> CASMTRIAGE-5255: Document managed-nodes-rollout work-around

operations/kubernetes/Kyverno.md
The documentation change will be used by HPE internally and customers. This helps to identify the policy violations. There is no functionality impact with this documentation change.
=> CASMSEC-388: Document Kyverno Tooling to Report Audit Violations

operations/package_repository_management/Nexus_Export_and_Restore.md, scripts/nexus-export.sh
This updates the nexus export script to check for space in all of the cluster rather than one pool. The change fixes the issue where there could be multiple pools with the same name but checking a pool is not needed as the export can take up any amount of space in the cluster not just the pool. This will be backported to 1.3 and 1.4
=> CASMPET-6511: Update nexus export script with better data

workflows/iuf/operations/ims-upload.yaml
Update ims-load-artifacts image version to resolve CASM-3868.
=> CASM-3868: Update ims-load-artifacts container version

scripts/upload_ceph_images_to_nexus.sh
Add function to check if ceph daemons are currently running the image in nexus. The ceph_upload_image_to_nexus script restarts all ceph daemons so that they use the image in nexus. This can take 40 minutes and the script will do this even if the daemons are already running the image in nexus. This PR adds a function to check if the daemons are already running the image in nexus and it doesn't restart them unless necessary.
Tested on Beau.
=> CASMPET-6524 add function to check if ceph daemons are currently running the image in nexus

operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md
Add instructions on how to query the state manager for the lock state of the management nodes and their BMCs.
Relates to:
- [CASMHMS-5727](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5727)
=> CASMHMS-5727 Add command to get node lock status to docs

introduction/deprecated_features/README.md, operations/UAS_user_and_admin_topics/Customize_End-User_UAI_Images.md, operations/UAS_user_and_admin_topics/Troubleshoot_Common_Mistakes_when_Creating_a_Custom_End-User_UAI_Image.md, operations/boot_orchestration/Check_the_Progress_of_BOS_Session_Operations.md, operations/boot_orchestration/Clean_Up_After_a_BOS-BOA_Job_is_Completed_or_Cancelled.md, operations/boot_orchestration/Manage_a_BOS_Session.md, operations/image_management/Create_UAN_Boot_Images.md, operations/node_management/Add_a_Standard_Rack_Node.md, operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md, operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System_Using_SAT.md, operations/node_management/Move_a_Standard_Rack_Node_SameRack_SameHSNPorts.md, operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md, operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System_Using_SAT.md, operations/node_management/Removing_a_Standard_Node_from_a_System.md, operations/node_management/Replace_a_Compute_Blade.md, operations/node_management/Replace_a_Compute_Blade_Using_SAT.md, operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md, operations/node_management/Swap_a_Compute_Blade_with_a_Different_System_Using_SAT.md, operations/node_management/Update_Compute_Node_Mellanox_HSN_NIC_Firmware.md, operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md, operations/power_management/Prepare_the_System_for_Power_Off.md, operations/power_management/Shut_Down_and_Power_Off_Compute_and_User_Access_Nodes.md, operations/resiliency/Resiliency_Testing_Procedure.md, operations/security_and_authentication/Add_LDAP_User_Federation.md, operations/security_and_authentication/Resync_Keycloak_Users_to_Compute_Nodes.md, troubleshooting/cms_barebones_image_boot.md
- Update the deprecations page to specify the removal of BOSv1 in CSM 1.6.
- Since the CLI default is changed to BOS v2 in CSM 1.4, update all of the commands in the docs that were relying on v1 as the default, instead having them explicitly specify the version.
- Linting unrelated to this PR to fix pre-existing problems on the pages being edited.
Backports:
- [1.4](https://github.com/Cray-HPE/docs-csm/pull/3747)
- [1.3](https://github.com/Cray-HPE/docs-csm/pull/3748)
- [1.2](https://github.com/Cray-HPE/docs-csm/pull/3749) -- just the linting part
- [1.0](https://github.com/Cray-HPE/docs-csm/pull/3750) -- just the linting part
=> CASMCMS-8593: Update to reflect BOS v1 removal in CSM 1.6, BOS CLI default change in CSM 1.4

troubleshooting/known_issues/CRUS_Subcommands_Missing_From_Cray_CLI.md
Now that the API docs are being auto-generated and included in this repository, this PR updates the "CRUS CLI is missing" workaround doc to link to the CRUS API doc inside the docs-csm repository, rather than an external repository. That way on the off chance that the 1.4 CRUS API spec does end up changing, we won't have to update the link, because the auto-generation will take care of it for us.
No backports are needed. This is specific to 1.4 only.
=> CASMCMS-8608: Update link in CRUS CLI known issue to use API spec inside this repo

glossary.md, index.md, operations/index.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/3777
=> CASMINST-6338: Add missing terms to glossary; add missing links to operations index

operations/multi-tenancy/Create_a_Tenant.md, operations/multi-tenancy/Tapms.md
Add support for UAN resources in tapms
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6316
```
{
"childnamespaces": [
"vcluster-green-user",
"vcluster-green-slurm"
],
"tenantresources": [
{
"enforceexclusivehsmgroups": true,
"hsmgrouplabel": "green",
"type": "application",
"xnames": [
"x3000c0s32b0n0"
]
},
{
"enforceexclusivehsmgroups": true,
"hsmgrouplabel": "green",
"type": "compute",
"xnames": [
"x3000c0s19b1n0",
"x3000c0s19b3n0"
]
}
],
"uuid": "a81e4206-02ed-4ec8-b6fc-512bb67cfdf0"
}
Deployed
label = "green"
description = ""
exclusiveGroup = "tapms-exclusive-group-label"
tags = [ "vcluster-green",]
[members]
ids = [ "x3000c0s19b3n0", "x3000c0s32b0n0", "x3000c0s19b1n0",]
```
If …
=> Doc changes for adding UAN support for tapms (CASMPET-6316)

upgrade/Stage_1.md, upgrade/Stage_3.md, upgrade/Stage_4.md, upgrade/Upgrade_Management_Nodes_and_CSM_Services.md
Upload_ceph_images_to_nexus script to only run when staying in CSM release version
Detailed description:
Original problem was upload_ceph_images_to_nexus script was added to the 1.3 storage upgrade. This script does not work when upgrade from CSM-1.2 to CSM-1.3 because of the Ceph version. Ticket to track this was CASMINST-6268. What should have been done here is move that script to only run during upgrades staying within the 1.3 release version.
Instead, CASMINST-6268 moved the Ceph upgrade from Stage_4 of the upgrade to Stage_1. This was done to avoid sha issues that might occur because upload_ceph_images_to_nexus was not being run. However, this change failed because the Ceph upgrade cannot be completed on CSM-1.2 storage nodes because the Ceph upgrade requires images to be pullable …
=> CASMTRIAGE-5324-revert revert changes from CASMINST-6286

upgrade/scripts/upgrade/util/update-customizations.sh
Replace all occurrences of Prometheus-operator to kube-prometheus-operator as part of version update from 9.3.1 to 45.1.1.
Note: Here using sed instead of yq calls since this is simply a string search/replace.
Relates to:
- https://github.com/Cray-HPE/csm/pull/1913/files
Tested on 
- Gamora
cat customizations.yaml | grep kube-prometheus-stack
- '{{ kubernetes.services[''cray-sysmgmt-health''][''kube-prometheus-stack''].prometheus.prometheusSpec.externalAuthority }}'
- '{{ kubernetes.services[''cray-sysmgmt-health''][''kube-prometheus-stack''].alertmanager.alertmanagerSpec.externalAuthority }}'
- '{{ kubernetes.services[''cray-sysmgmt-health''][''kube-prometheus-stack''].grafana.externalAuthority }}'
url: https://{{ kubernetes.services['cray-sysmgmt-health']['kube-prometheus-stack'].grafana …
=> CASMINST-6346: UPGRADE: cray-sysmgmt-health upgrade error

upgrade/scripts/upgrade/prerequisites.sh
These are changes to allow prerequisites to run properly on vshasta.   vshasta currently cannot deploy m001 so we need to run prerequisites.sh from m002.    However, most of the stages in prerequisites are skipped if it is not run on m001.
This introduces a --primary-node option to allow specifying a different primary node.   Otherwise, it defaults the primary node to m001 to allow it to run the same way on baremetal systems.
This also now detects if it is running on vshasta and 
* sets the vshasta goss variable to true to skip tests that are not relevent to (and will fail on) vshasta.   
* skips m001 in REPAIR_AND_VERIFY_CHRONY_CONFIG
* skips stages UPLOAD_NEW_NCN_IMAGE, CHECK_BMC_NCN_LOCKS, DISABLE_CFS_ON_NCNS, and TDS_LOWER_CPU_REQUEST
Finally, I pulled out a couple of redundant token …
=> CASMINST-6354:  Adjustments to run on vshasta

operations/kubernetes/Disaster_Recovery_Postgres.md
Updated the restart of the ingress gateway to the oauth2-proxies.
TBD : Backport to 1.3, 1.4 and 1.5
=> CASMPET-6594 1.2 : Update Disaster Recovery Postgres for keycloak oath2 change

operations/kubernetes/Disaster_Recovery_Postgres.md
Updated the restart of the ingress gateway to the oauth2-proxies.
=> CASMPET-6594 1.3 : Update Disaster Recovery Postgres for keycloak oath2 change

workflows/iuf/operations/management-nodes-rollout/info-to-read.yaml, workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml, workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml, workflows/iuf/operations/management-nodes-rollout/verify-images-and-configuration.yaml
Improve contextual logging information for management-nodes-rollout operation
Changes in this PR address the following use cases for IUF -
As an admin, I want to have more contextual information from the result of prepare-images stage so I can do deployments manually
As an admin, I want to have better logging information about what failed and what I need to fix
=> CASM-4137 Improving iuf messages for management-nodes-rollout stage

upgrade/scripts/upgrade/util/update-customizations.sh
yq4 to handle handle when there is no kube-prometheus-stack section in customizations.yaml in case of bare-metal systems. 
Relates to:
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6399
Tested:
Mug
=> CASMINST-6399: UPGRADE: update_customization error for sysmgmt-health

Jenkinsfile.github, Makefile
Reduce amount of Google Compute VMs needed to build docs-csm RPMs down to 1. Currently, it takes 3 VMs for each build. It takes a lot of time and resources to spin up all 3 VMs and do a fresh git clone onto each of them. This change uses docker container with mounted cone directory instead of 2 VMs.
=> CASMINST-6403 Avoid creating new VMs for each Jenkinsfile matrix axis

install/scripts/craycli_init.py, operations/configure_cray_cli.md
Add a --keycloakHost option to craycli_init.py script. Update documentation to source CMN LB and and use the new option. This as Keycloak administration must now use the CMN ingress path (when using an ingress...).
Forward port of https://github.com/Cray-HPE/docs-csm/pull/3075. 
Needed in CSM 1.5.0 and main. 
(cherry picked from commit 82f840e85cc2fe1474b463697d5180afab63f73f)
=> CASMINST-5848: Add keycloak host option to craycli_init.py, update docs to use CMN LB

.github/workflows/link-check.yaml, .github/workflows/shellcheck.yaml, .github/workflows/spellcheck.yaml, .github/workflows/style-check.yaml
Sometimes files in `api/` are listed as changed in the PR (when last commit in the PR is a rebase, for example: https://github.com/Cray-HPE/docs-csm/pull/3820). Spell and style checking is applied to these files and causes confusion. These files are very specific and should not undergo style/spell checks.
=> CASMINST-6431 Ignore spell and style checks in docs-csm api/ folder

scripts/operations/configuration/import_cfs_data.py
CFS doesn't let you create a configuration layer that has both a branch and a commit field. However, configurations with such layers can exist in CFS. This is because when creating a configuration layer that has a branch field, CFS automatically populates the commit field (and can later be told to update it, if desired). 
The import tool did not take this into account, and tries to create layers with both fields. This PR modifies it so that for layers with both fields, the commit field is deleted, allowing CFS to repopulate it on import.
I found this bug during the import testing on wasp, and I also tested this PR fix on there to verify that it solved the problem.
[1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3861)
[1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3862) …
=> CASMCMS-8660: Make CFS import tool able to handle layers with branch field

upgrade/scripts/upgrade/util/update-customizations.sh
This updates the [update-customizations.sh](https://github.com/Cray-HPE/docs-csm/blob/main/upgrade/scripts/upgrade/util/update-customizations.sh) to remove extra issuers from opa-ingressgateway during upgrade as it will be separated to only allow nmn access and no longer allows cmn access.  
This should be merged when https://github.com/Cray-HPE/csm/pull/2329 is merged to CSM.
=> CASMPET-5797: Remove extra issuers from opa on upgrade

upgrade/scripts/upgrade/ncn-upgrade-master-nodes.sh
Uninstall the old etcd-operator on upgrade (after new charts have been installed).
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6608
Fearne (Mitch manually ran the helm uninstall command) to get things going
Low
* Nothing
=> Uninstall etcd-operator after new charts are installed (CASMPET-6608)

operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
Update management plane startup procedure to rejoin storage nodes to spire.
=> CASMINST-6475 - Power on procedure should rejoin storage nodes to spire

scripts/upload_ceph_images_to_nexus.sh
Addressed:
- disable docker registry on each storage node that is used for ceph bootstrap
- fix podman registries.conf to a post internal build version
To do:
- Add a check and restart for any containers that did not restart (typically node-exporter)
Refactor the here file and shellcheck cleanup
One shot health_check near the beginning
Create description and function(){} cleanup
Flesh out description
CASMPET-6348 style ceph mgr fail to force service movement
Add --host_pattern  in more recent versions of ceph
1.4 based version of CASMPET-6516 to address insecure registry on utility storage nodes
=> CASMPET-6516 - disable registry and fix podman aliases on ncn-s nodes

scripts/upload_ceph_images_to_nexus.sh
This addresses insecure registry running on the utility storage nodes. It moves those images to Nexus and disables the service running the registry.
=> CASMPET-6516

workflows/ncn/storage/storage.upgrade.yaml, workflows/templates/drain-worker.yaml, workflows/templates/set-bss-images-cfs-config.yaml, workflows/templates/storage.before-each.yaml
A workflow template was created to set CFS configuration and BSS image. Worker workflows already had this capability but this change makes it reusable so that it can be used by the storage upgrade workflow. This is necessary now that IUF will run storage node upgrades, IUF will provide the image and CFS config to storage node upgrade the nodes will be rebuilt into that image.
This was tested on Surtur in the storage node upgrade on 6/13/23. A dry-run of a worker rebuild was performed to make sure the worker node workflow changes work as well.
=> CASMINST-6283 make template to set NCN image and CFS config. Run template in storage node upgrade

upgrade/scripts/upgrade/util/update-customizations.sh
This PR includes Prometheus scalability and high availability with Thanos.  It has several components such as Querier, Compactor, StoreAPI, Ruler, etc.
_List and characterize the relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASM-3496
Gamora
Mug
Starlord
ncn-m001:~ # kubectl get pods -n sysmgmt-health | grep prom-
prometheus-cray-sysmgmt-health-kube-p-prom-0                    3/3     Running             0          2d23h
prometheus-cray-sysmgmt-health-kube-p-prom-1                    3/3     Running             0          2d23h
prometheus-cray-sysmgmt-health-kube-p-prom-shard-1-0            3/3     Running             0          2d23h
prometheus-cray-sysmgmt-health-kube-p-prom-shard-1-1 …
=> CASM-3496: Highly available Prometheus setup with long term storage with Thanos

upgrade/scripts/upgrade/prerequisites.sh
Update certmanager upgrade logic to backup specific certmanager objects into a temporary k8s secret.
This is then restored *after* the new certmanager is installed. Once restored the secret is removed.
=> CASMPET-6634: Save cert-manager data in a secret in prereq upgrade

operations/configuration_management/Track_the_Status_of_a_Session.md
Fixes an issue with a link in the CFS troubleshooting docs that was introduced by a a backport.
=> CASMTRIAGE-5542: Fix CFS troubleshooting docs link for failed sessions

upgrade/scripts/upgrade/util/update-customizations.sh
_List and characterize the relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves - [CASMPET-6651](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6651)
Frigg
Mug
```
kube-prometheus-stack:
kubeEtcd:
endpoints: '{{ network.netstaticips.nmn_ncn_masters }}'
prometheus:
prometheusSpec:
externalAuthority: prometheus.cmn.{{ network.dns.external }}
externalUrl: https://{{ kubernetes.services['cray-sysmgmt-health']['kube-prometheus-stack'].prometheus.prometheusSpec.externalAuthority }}/
alertmanager:
alertmanagerSpec:
externalAuthority: alertmanager.cmn.{{ network.dns.external }}
externalUrl: https://{{ kubernetes.services['cray-sysmgmt-health']['kube-prometheus-stack'].alertmanager.alertmanagerSpec.externalAuthority }}/
grafana:
externalAuthority: …
```
=> CASMMON-325 thanos breaks csm service upgrade

workflows/iuf/operations/extract-release-distributions.yaml
Corresponding csm PR: https://github.com/Cray-HPE/csm/pull/2382
Remove installation of dependencies using zypper entirely to rely upon the host for dependencies.
We are removing these because the dependencies in the host are more up-to-date, as opposed to the embedding them within this container which doesn't get updated often.
Yes
* Resolves [CASM-4352](https://jira-pro.it.hpe.com:8443/browse/CASM-4352)
* Merged code PR: https://github.com/Cray-HPE/iuf-containers/pull/18
Drax
Removed internally embedded dependencies from the image, volume mounted the host /usr/bin directory, …
=> CASM-4352 Backport to release/1.4

workflows/iuf/operations/extract-release-distributions.yaml
Corresponding csm PR: https://github.com/Cray-HPE/csm/pull/2380
Remove installation of dependencies using zypper entirely to rely upon the host for dependencies.
We are removing these because the dependencies in the host are more up-to-date, as opposed to the embedding them within this container which doesn't get updated often.
Yes
* Resolves [CASM-4352](https://jira-pro.it.hpe.com:8443/browse/CASM-4352)
* Merged code PR: https://github.com/Cray-HPE/iuf-containers/pull/18
Drax
Removed internally embedded dependencies from the image, volume mounted the host /usr/bin directory, …
=> CASM-4352 Remove installation of dependencies using zypper entirely to rely upon the host for dependencies

.spelling, operations/CSM_product_management/Post_Install_Customizations.md, operations/CSM_product_management/Redeploying_a_Chart.md, operations/configuration_management/Version_Control_Service_VCS.md, operations/hmcollector/adjust_hmcollector_resource_limits_requests.md, operations/node_management/Add_Remove_Replace_NCNs/Redeploy_Services.md, operations/node_management/Add_TLS_Certificates_to_BMCs.md, operations/package_repository_management/Nexus_Service_Recovery.md, operations/security_and_authentication/Add_LDAP_User_Federation.md, operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md, operations/security_and_authentication/Keycloak_Service_Recovery.md, operations/security_and_authentication/Update_Default_Air-Cooled_BMC_and_Leaf_BMC_Switch_SNMP_Credentials.md, operations/security_and_authentication/Update_Default_ServerTech_PDU_Credentials_used_by_the_Redfish_Translation_Service.md, operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md, operations/security_and_authentication/Vault_Service_Recovery.md, operations/spire/Restore_Spire_Postgres_without_a_Backup.md, operations/spire/Spire_Service_Recovery.md, scripts/operations/kubernetes/latest_chart_manifest.sh
In a number of places in the docs we have administrators redeploy charts, for a variety of reasons. These are not done in a uniform way. Many of them assume that the loftsman manifest from the CSM install/upgrade will exist unchanged in the loftsman Kubernetes configmap, while others overwrite it, in some cases overwriting it with most of the charts removed.
I raised this issue in a Slack DM and there has been much discussion about what we should be doing. I am not an expert on this, but I do know we need to make some change to the docs to at least make sure we aren't overwriting things, or having customers regress product versions inadvertently.
This PR updates chart redeploy procedure to prevent overwriting existing manifests while still using correct versions and customizations. It is …
=> CASMINST-6470: Update chart redeploy procedure

upgrade/scripts/common/ncn-common.sh
Do `set -o pipefail` in ncn-common.sh in order to stop masking command failures.  This file is included by several other files, so this change is more far-reaching than it initially seems.
=> CASMINST-6244: set `pipefail`

workflows/iuf/operations/ims-upload.yaml
Latest version `2.6.0` of ims-load-artifacts is required for arch IUF manifest changes to process correctly.
Must merge with:
https://github.com/Cray-HPE/cray-nls/pull/181 - [CASMCMS-8623](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8623)
=> CASMCMS-8623: Updating latest ims-load-artifacts for arch

upgrade/scripts/upgrade/util/update-customizations.sh
The current method to update proxied urls for the change to prometheus-operator to kube-prometheus-stack there is hard coded indexes to choose which lines to update, however there is never a guarantee for order or location of urls. This change updates that logic to remove old urls and re-add the important URLs to the end of the proxied hosts.
=> CASMTRIAGE-5584: Change update-customization for smarter url updates

.editorconfig
Restores `.editorconfig` to align bash editing with #3846 .
=> Add editor config to match shfmt

.spelling, operations/power_management/Power_On_Compute_Cabinets.md, operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
SAT now re-creates cronjobs automatically, so this is now noted.
=> CRAYSAT-1728: Update cronjob re-creation documentation

operations/configure_cray_cli.md, operations/multi-tenancy/TenantAdminConfig.md
Add some content for the cray cli for scoping to a tenant.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6649
Tested on ashton:
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: vshasta
Password:
Success!
Initialization complete.
ncn-m003:~/.config/cray/configurations # cat default
[core]
hostname = "https://api-gw-service-nmn.local"
tenant = ""
[auth.login]
username = "vshasta"
```
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local --tenant vcluster-blue
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: vshasta
Password:
Success!
Initialization …
```
=> Add content for multi-tenancy related to cray cli (CASMPET-6649)

scripts/operations/gateway-test/gateway-test.py
Change to the gateway-test.py  because the nmn and cmn have been separated in 1.5 meaning tokens from the nmn will not work on the cmn and vice versa. This is now expected behavior in 1.5 so the test should be updated from the expected behavior from 1.2-1.4.
Running the test post change on drax:
```/usr/share/doc/csm/scripts/operations/gateway-test/ncn-gateway-test.sh
System domain is drax.hpc.amslabs.hpecorp.net
Running tests on the NCN
auth.cmn.drax.hpc.amslabs.hpecorp.net is reachable
Token successfully retrieved at https://auth.cmn.drax.hpc.amslabs.hpecorp.net/keycloak/realms/shasta/protocol/openid-connect/token
Reachable networks: ['can', …
```
=> CASMTRIAGE-5639: Update the gateway-test.py for cmn nmn seperation.

operations/CSM_product_management/Redeploying_a_Chart.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/3964
=> CASMINST-6534: Remove chart source fields from manifest, to force it to use the source specified on the loftsman command line

workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
Critical singleton pods are moved before a worker rebuild is done. This will move pods even if they are on a node that is not being rebuilt by the worker rebuild workflow. This means that the pod may have to move more times than necessary which is not ideal especially for pods like nexus. This change doesn't move a pod if it is not necessary.
=> CASMINST-6533 Don't move critical pod if node is not being rebuilt

workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
Critical singleton pods are moved before a worker rebuild is done. This will move pods even if they are on a node that is not being rebuilt by the worker rebuild workflow. This means that the pod may have to move more times than necessary which is not ideal especially for pods like nexus. This change doesn't move a pod if it is not necessary.
=> CASMINST-6533-csm-1.4 Don't move critical singleton pod if node is not being rebuilt

operations/iuf/IUF.md, operations/iuf/stages/prepare_images.md, operations/iuf/workflows/image_preparation.md
Update installation procedures that use IUF. Mention that if you have ARM nodes on your system that you should uncomment the ARM section of the sat bootprep input file, so that the ARM images are built. This section is commented out by default, so that systems must opt-in. You do not want to accidentally build ARM images if your system does not contain ARM nodes.
[CASMCMS-8672](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8672)
=> CASMCMS-8672: ARM image sat bootprep documentation

install/pre-installation.md, operations/iuf/IUF.md, operations/iuf/stages/management_nodes_rollout.md, operations/iuf/workflows/managed_rollout.md, operations/iuf/workflows/management_rollout.md
CASMINST-6208 and CASMPET-6610 adjusted the functionality of IUF stage management-nodes-rollout. These changes include automating the storage node rollouts with IUF and being able to specify an NCN hostname to rebuild through IUF. These changes are documented by this PR. 
=> CASMINST-6429 update management-node-rollout docs for CSM 1.5

upgrade/1.4.1/README.md, upgrade/scripts/upgrade/upload-ncn-images.sh
Fix variables needed in 1.4.1 patch when running upload ncn-images to edit the cray-product-catalog for the patch version.
Earlier steps in the patch use CSM_RELEASE_VERSION instead of CSM_RELEASE. A script called in ncn-image-modification.sh requires CSM_RELEASE. Instead of having the user export this variable, the script will export it.
=> CASMINST-6519 use CSM_RELEASE_VERSION variable in 1.4.1 patch when uploading ncn-images

operations/validate_csm_health.md, troubleshooting/interpreting_hms_health_check_results.md
The following `csm-testing` PR modified the Goss suites so that the CMS and HMS CT tests are now executed as part of the main Goss suite:
https://github.com/Cray-HPE/csm-testing/pull/509
This `docs-csm` PR modifies the CSM health validation procedure to remove the now superfluous manual execution of those steps. Some of the information from the HMS CT test section was added to the "Interpreting HMS test results" page instead, since that is where people are directed if there are failures.
This change is only for CSM 1.5 -- no backports are needed.
[ ] This PR should ideally not merge until the csm-testing PR has been in a few builds, so that people don't stop manually running the CMS/HMS tests prematurely.
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conven …
=> CASMINST-6538: Update CSM health validation procedure to reflect that the CMS, HMS tests are part of the main Goss suite

operations/configuration_management/Exporting_and_Importing_CFS_Data.md, scripts/operations/configuration/import_cfs_data.py, scripts/operations/configuration/import_cfs_data.sh, scripts/operations/configuration/python_lib/cfs.py
One disaster recovery scenario that we are testing involves reinstalling CSM, then restoring the VCS data from the prior install. This means that things like git commit IDs will no longer match what is in CFS for the new install. So for this scenario specifically, we want an option in the CFS import tool which will clear the existing data before importing the backed up data. This is because by default the CFS import tool does not overwrite existing data. Making this change will ensure that CFS will only reference valid git data (or anyway, it will assuming that this was the case when the exports were made).
Specifically, the new clear option on the import tool:
* Deletes all configurations
* Clears all desired configurations, states, and error counts for components
This PR implements that …
=> CASMINST-6524: Update CFS import tool and documentation with clear option

workflows/templates/base/echo.template.argo.yaml, workflows/templates/base/iufBase.template.argo.yaml, workflows/templates/base/kubectlAndCurl.template.argo.yaml, workflows/templates/base/sat-general-iuf.template.argo.yaml, workflows/templates/base/ssh.template.argo.yaml, workflows/templates/base/update-product-catalog.template.argo.yaml, workflows/templates/wipe-and-reboot-worker.yaml
=> CASMINST-6540 fix copyright header to use # instead of {}
