operations/network/management_network/1.2_to_1.3_upgrade.md
operations/network/management_network/README.md
operations/network/management_network/generate_switch_configs.md

Updating CANU related commannds and release notes locations

CASMNET-1805 | network upgrades for CANU specific things main

---

operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
operations/configuration_management/Write_Ansible_Code_for_CFS.md

This updates and improves recommendations for writing Ansible code for CFS

CASMCMS-7326: Improve CFS Ansible Recommendations

---

operations/firmware/FAS_Admin_Procedures.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md
operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md

This PR adds the updates made in v1.2 branch to main branch.

CASMINST-4608 CASMINST-4838 CASMHMS-5598 CASMHMS-5556  Changes from 1.2 into main

---

operations/firmware/FAS_Admin_Procedures.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md
operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md

Push changes into release/1.3
for
CASMINST-4608
CASMINST-4838
CASMHMS-5598
CASMHMS-5556

CASMINST-4608 CASMINST-4838 CASMHMS-5598 CASMHMS-5556 Changes from v1.2 into v1.3

---

operations/system_management_health/Remove_Kiali.md

Add instructions for kiali-operator removal for CVE remediation if customers choose to do so.

CASMPET-5902: add instructions for kiali-operator removal

---

operations/node_management/Add_Remove_Replace_NCNs/Add_NCN_Data.md

Various linting with some opinionated formatting for the new/alpha "Add NCN Data page."

CASMINST-5258 Linting/formatting

---

scripts/workarounds/boot-order/README.md
scripts/workarounds/boot-order/metal-lib.sh
scripts/workarounds/boot-order/run.sh
upgrade/README.md
upgrade/Stage_1.md

MTL-1919 boot-order workaround

---

scripts/ceph-upload-file-public-read.py

Increase read timeout for ceph upload script.

CASMINST-5263 Increase read timeout for ceph upload script

---

operations/boot_orchestration/Clean_Up_After_a_BOS-BOA_Job_is_Completed_or_Cancelled.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2272

CASMCMS-8110: Clarify documentation regarding intermediate BOS datastructures

---

install/README.md
install/pre-installation.md

CASMINST-5262 Remove TODOs

---

operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2300

CASMTRIAGE-3723: Be more careful when editing BSS boot parameters

---

upgrade/README.md
upgrade/Stage_0_Prerequisites.md

CASMNET-1809 remove mgmt net upgrade docs

---

.spelling
operations/firmware/FAS_Use_Cases.md
operations/kubernetes/Restore_Postgres.md
operations/node_management/Add_Remove_Replace_NCNs/Collect_NCN_MAC_Addresses.md
operations/security_and_authentication/Default_Keycloak_Realms_Accounts_and_Clients.md
scripts/operations/node_management/Add_Remove_Replace_NCNs/add_management_ncn.py

Backport of https://github.com/Cray-HPE/docs-csm/pull/2310

CASMINST-5272: Linting

---

operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System_Using_SAT.md
operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md
operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System_Using_SAT.md
operations/node_management/Replace_a_Compute_Blade.md
operations/node_management/Replace_a_Compute_Blade_Using_SAT.md
operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
scripts/operations/node_management/delete_bmc_subscriptions.py

Apply linking changes from: https://github.com/Cray-HPE/docs-csm/pull/2324

CASMHMS-5693: Apply suggestions from code review from CSM 1.3 PR

---

workflows/ncn/worker/worker.drain.yaml
workflows/ncn/worker/worker.wipe-and-reboot.yaml

CASMINST-5278 1.3

---

operations/kubernetes/Containerd.md

Backport of just the linting from https://github.com/Cray-HPE/docs-csm/pull/2355

CASMTRIAGE-3997: Linting

---

operations/kubernetes/Containerd.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2355

CASMTRIAGE-3997: Add note about slow containerd startup and WAR

---

upgrade/README.md
upgrade/Stage_0_Prerequisites.md
upgrade/Stage_1.md
upgrade/Stage_2.md
upgrade/Stage_3.md
upgrade/Stage_4.md
upgrade/Stage_5.md
upgrade/prepare_for_upgrade.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2348

CASMINST-5207: Add typescripts to upgrade procedure & back them up

---

install/deploy_final_non-compute_node.md

Removed backup to m003 commands as they are  not restored from there. Added commands to make a copy of the backups to the config-data bucket in our local s3 to ensure they can be restored later. Also set a variable for the pit backup date time and changed the filenames to uses that variable. After review, we had to retain the rsync of the ISO, and the prep/ folder to /metal/boostrap as the prep/ folder and ifcfg-lan0 site NIC file has to be instantiated on ncn-m001 after reboot and that occurs before the **_Cray Configure Administrative Access_** step is performed, thus no S3 credentials are functional at this point.
Output from test execution …

CASMINST-5216 - Ensure backup of pit data gets uploaded to S3

---

scripts/workarounds/boot-order/run.sh

This will allow failures from the `install_grub2` function, which should not be failing but is not the primary objective of the workaround. The primary objective of the bootorder workaround is to ensure that `setup_uefi_bootorder` is invoked.
Backport: https://github.com/Cray-HPE/docs-csm/pull/2361

CASMTRIAGE-4021 Fix call to `install_grub2` to allow failure

---

workflows/ncn/worker/worker.drain.yaml

add a check for pg operator after drain

CASMINST-5292 1.3

---

workflows/ncn/worker/worker.drain.yaml

CASMINST-5292 backport to main

---

operations/kubernetes/Restore_Postgres.md

Correct some minor issues with gitea restore procedure

CASMPET-5926 main: DOCS: Restore Postgress for VCS need to be update for list.py

---

.github/CODEOWNERS
.github/delete-merged-branch-config.yml
.github/workflows/cleanup.yml
.github/workflows/stale.yml
.gitignore
.spelling
docs-csm.spec

Auto-removes branches linked to merged or closed pull-requests on a cron.

Fixes #2391 cleanup merged closed prs

---

RELEASE_NOTES.md
install/pre-installation.md
update_product_stream/README.md

Update specific 1.3 refs to 1.4

---

upgrade/Stage_4.md

update Docs for stage 4 of the upgrade

CASMINST-5259 update Docs for stage 4 upgrade

---

operations/argo/Using_Argo_Workflows.md
operations/argo/Using_the_Argo_UI.md
upgrade/Stage_1.md
upgrade/Stage_2.md

Adding doc for using argo workflows and linking it in stage 1 and 2 of the upgrade

CASMTRIAGE-4055 adding doc for using argo workflows

---

upgrade/Stage_0_Prerequisites.md

Reverts Cray-HPE/docs-csm#2407

Revert "CASMTRIAGE-4044"

---

upgrade/Stage_0_Prerequisites.md

Signed-off-by: Dennis Walker <denniswalker@me.com>

CASMTRIAGE-4044

---

upgrade/Stage_0_Prerequisites.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2406

CASMTRIAGE-4044 1.4

---

upgrade/Stage_0_Prerequisites.md

CASMTRIAGE-4044 link text

---

upgrade/scripts/upgrade/prerequisites.sh
upgrade/scripts/upgrade/util/extract_chart_manifest.py

Backport of https://github.com/Cray-HPE/docs-csm/pull/2398

CASMINST-5298: Deploy Helm charts properly in prerequisites script

---

install/pre-installation.md

CASMINST-5306 updating pitdata location

---

workflows/ncn/worker/worker.drain.yaml
workflows/ncn/worker/worker.post-rebuild.yaml

CASMTRIAGE-4071 

---

workflows/ncn/worker/worker.drain.yaml
workflows/ncn/worker/worker.post-rebuild.yaml

[fix path in cfs api call](https://github.com/Cray-HPE/docs-csm/commit/842ff56bc2c306c3b1fb4986071c2f1dc54721d0)

CASMINST-5315 fix path in cfs api call

---

workflows/ncn/worker/worker.drain.yaml
workflows/ncn/worker/worker.post-rebuild.yaml

[BACKPORT] CASMINST-5315 fix path in cfs api call

---

background/README.md
background/ncn_kdump.md

This provides a new section that describes `kdump`, its usage, and various test plans to use against it.

CASMREL-1046 `kdump` overview

---

.spelling
install/index.md
operations/CSM_product_management/Configure_CSM_Packages_with_CFS.md
operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
upgrade/1.2.1/README.md
upgrade/1.2/README.md
upgrade/1.2/Stage_0_Prerequisites.md
upgrade/1.2/Stage_2.md
upgrade/1.2/Stage_5.md

CASMINST-5265

---

.github/CODEOWNERS
RELEASE_NOTES.md
operations/README.md
operations/sat/sat_in_csm.md

Document SAT inclusion in CSM 1.3

CRAYSAT-1549: Document SAT inclusion in CSM

---

RELEASE_NOTES.md
operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md

Updates to the CSM 1.3 release notes - following sections were changed:
* Monitoring
* Automation Improvements
* Platform Component upgrades
* Security Improvements
* Customer-requested enhancements
* Security Vulnerability Exceptions

CASMPET-5300-release-notes and CASMTRIAGE-4127

---

install/prepare_site_init.md

Signed-off-by: Russell Bunch <doomslayer@hpe.com>

Output is combined with input command

---

install/pre-installation.md
install/prepare_site_init.md

CASMINST-5334: Linting

---

upgrade/scripts/upgrade/prepare-assets.sh

CASMINST-5327 war var that is not set yet

---

operations/kubernetes/Restore_Postgres.md

Fixes CASMPET-5935
Adds steps to rename the .psql file to workaround a `kubectl cp` bug
Other minor cleanup
Removes capsules which was deprecated in csm 1.2
Replaces python scripts to list and download s3 files with `cray artifacts`
TBD : Backport to release/1.3 and release/1.2

CASMPET-5935 : DOCS: "Copy the database dump file to the postgres member " results error

---

operations/kubernetes/Restore_Postgres.md

Cherry pick https://github.com/Cray-HPE/docs-csm/pull/2466 commit to release/1.2

CASMPET-5935 : DOCS: "Copy the database dump file to the postgres member" results error

---

upgrade/Stage_1.md

This has the blurb about in-family ceph upgrades and the process invovled.
- [ x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

CASMTRIAGE-4052 Docs PR

---

operations/node_management/Add_additional_Liquid-Cooled_Cabinets_to_a_System.md
operations/system_configuration_service/Configure_BMC_and_Controller_Parameters_with_scsd.md

When adding a liquid-cooled cabinet follow the procedure to configure BMCs with SCSD.
Also in the automated procedure, add a link the manual procedure in the the troubleshooting steps.

CASMTRIAGE-4067: When adding a liquid-cooled cabinet follow the procedure to configure BMCs with SCSD.

---

upgrade/scripts/upgrade/prerequisites.sh

This PR does two main things:
1. Adds cray-cfs-operator to the charts that are upgraded when prerequisites.sh is run during stage 0 of the upgrade. This is to avoid hitting a known bug in CFS during the upgrade process.
2. Now that there are several stanzas in prerequisites.sh which are just upgrading CSM charts, it made sense to just make a common function that they could each call to do that, rather than repeating the same code in so many stanzas. So this PR does that as well.
I do not have a system where I can readily test this, but it is mostly just reusing code that was already there.

CASMTRIAGE-4197: Upgrade cfs-operator in stage 0; Create common function to upgrade CSM charts in prerequisites.sh

---

RELEASE_NOTES.md

Added Networking, DNS, and DHCP entries to the release notes

CASMINST-5302: Added Networking, User, and Metal release notes for Papaya

---

.spelling
operations/multi-tenancy/Create_a_Tenant.md
operations/multi-tenancy/Modify_a_Tenant.md
operations/multi-tenancy/Overview.md
operations/multi-tenancy/Remove_a_Tenant.md
operations/multi-tenancy/SlurmOperator.md

Since the CPE docs cannot reference unreleased software, document the Slurm operator here by filling in the placeholder sections. In the future, we can replace the content with references to CPE documentation.

PE-40775 Document Slurm Operator

---

operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
operations/configuration_management/Write_Ansible_Code_for_CFS.md

Casmcms 8236 jasons

---

operations/configuration_management/Configuration_Management.md
operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
operations/configuration_management/Write_Ansible_Code_for_CFS.md

This updates the recommendations for how to write Ansible playbooks for image customization, including adding sample templates that can be used as a starting point.

CASMCMS-8236: Update documentation for image customization, including examples

---

upgrade/Stage_1.md

Signed-off-by: cdelatte-hpe <77167617+cdelatte-hpe@users.noreply.github.com>
Removing trailing slash

CASMINST-5376 Removing trailing slash

---

operations/conman/Log_in_to_a_Node_Using_ConMan.md
operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md

Small changes to storage node rebuild procedure.

CASMPET-5984 edit storage node rebuild procedure

---

operations/index.md
operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
operations/utility_storage/Ceph_Deep_Scrubs.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2508

CASMPET-6002: Document Ceph workarounds for System Power On Procedures

---

operations/configuration_management/Configuration_Management.md
operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
operations/configuration_management/Write_Ansible_Code_for_CFS.md

This updates the recommendations for writing Ansible targeting image customization.  This is slightly different than the recommendations for CASMCMS-8236, as 1.3 will not have a feature that we are recommending going forward.

CASMCMS-8244: Update recommendations for image customization Ansible

---

workflows/ncn/worker/worker.drain.yaml

CASMTRIAGE-4256 remove wait for cfs

---

workflows/ncn/worker/worker.drain.yaml

CASMTRIAGE-4256 remove cfs before upgrade

---

workflows/ncn/worker/worker.drain.yaml

Reverts Cray-HPE/docs-csm#2553

Revert "CASMTRIAGE-4256 remove cfs before upgrade"

---

operations/README.md
operations/boot_orchestration/Rolling_Upgrades.md
operations/boot_orchestration/Stage_Changes_with_BOS.md
operations/compute_rolling_upgrades/CRUS_Workflow.md
operations/compute_rolling_upgrades/Compute_Rolling_Upgrades.md
operations/compute_rolling_upgrades/Troubleshoot_Nodes_Failing_to_Upgrade_in_a_CRUS_Session.md
operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Bad_Parameters.md
operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Unmet_Conditions.md
operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md

Adds new docs describing how BOS v2 can be used to perform rolling upgrades

CASMCMS-7677: Write new documentation for using BOS to apply rolling upgrades (1.3)

---

upgrade/scripts/upgrade/util/nls-keycloak-configure.py

This file did not contain a python shebang, leaving it at the mercy of whatever the default python interpreter may be.  This PR adds a shebang for python3.

CASMTRIAGE-4162: add a python3 shebang

---

.spelling
operations/configuration_management/Accessing_Sat_Bootprep_Files.md
operations/configuration_management/Worker_Upgrade_Image_Customization.md
operations/configuration_management/Worker_Upgrade_Node_Personalization.md
upgrade/Stage_0_Prerequisites.md

This pull request addresses the simpler items to fix in the upgrade procedure. See commit messages for details.

CASMINST-5424: Upgrade Procedure Fixes

---

operations/utility_storage/CSM_rbd_tool_Usage.md

Add troubleshooting info for csm_rbd_tool.py. 

CASMTRIAGE-4302 add troubleshooting info for `csm_rbd_tool.py`

---

operations/CSM_product_management/Post_Install_Customizations.md

Add a link to the Post Install Customizations document for the HM Collector.

CASMHMS-5777 Add HM Collector customization link

---

troubleshooting/README.md
troubleshooting/dhcp_runbook.md
troubleshooting/dns_runbook.md
troubleshooting/kea_unbound_check.sh

Adding DHCP and DNS troubleshooting run books

CASMNET-1875 | 1.3 | dhcp and dns run book

---

Jenkinsfile.github

add Jenkinsfile logic to prevent overwriting latest RPM when tag doesn't point to hea

CASMINST-5432

---

Jenkinsfile.github
upgrade/Stage_0_Prerequisites.md

Docs change. Update upgrade docs to check if csm-rbd-mount already exists before creating it.

CASMTRIAGE-4334 update upgrade docs to check if csm-rbd-mount already exists before creating it

---

operations/utility_storage/Utility_Storage.md
upgrade/Stage_1.md

Add ceph troubleshooting reference area. Reference this in stage 1 of the upgrade.

CASMPET-6058 make ceph trouble shooting page

---

.spelling
operations/image_management/IMS_export_import.md
scripts/operations/system_recovery/ims-import-export.py

Adding documentation and script for IMS data import/export for disaster recovery.

CASMCMS-8257 - add IMS import/export documentation.

---

operations/network/customer_accessible_networks/can_to_chn/scripts/util/update-customizations-network.sh

Fix clean up customizations script.

CASMINST-5477

---

operations/CSM_product_management/Post_Install_Customizations.md

CASMMON-230/231: Documentation update for Prometheus OOM and PVC fill 100%.
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-230
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-231

CASMMON-230/231: Documentation update for Prometheus OOM and PVC fill 100%.

---

workflows/iuf/install.yaml
workflows/iuf/operations/extract-release-distributions.yaml
workflows/iuf/samples/session.yml
workflows/iuf/stages/deliver-product.yaml
workflows/iuf/stages/deploy-product.yaml
workflows/iuf/stages/post-install-check.yaml
workflows/iuf/stages/pre-install-check.yaml
workflows/iuf/stages/process-media.yaml
workflows/iuf/stages/rolling-reboot.yaml
workflows/iuf/stages/sat-bootprep.yaml
workflows/iuf/stages/update-config.yaml
workflows/scripts/upload-rebuild-templates.sh

CASM-3517 separate stages/operations from giant `install.yaml`

---

operations/multi-tenancy/Modify_a_Tenant.md

Add a section with instructions for how to modify the Slurm configuration for a tenant after it has been deployed. This is necessary when the tenant's node list is changed.

PE-43420 Multi-Tenancy: modify the Slurm config

---

scripts/operations/node_management/ncn-image-modification.sh

There's no reason to do this. It was overly complicated and made error handling problematic. Just invoke `mksquashfs` directly, there's no reason to do the mounts in the chroot.

MTL-1987: don't chroot to create a new squashfs

---

upgrade/scripts/upgrade/util/upgrade-cray-nls.sh

CASMPET-6093 deploy iuf before nls

---

workflows/ncn/hooks/after-each/ensure-csm-rpms-installed.yaml
workflows/ncn/hooks/after-each/update-bss-no-wipe.yaml
workflows/ncn/hooks/after-each/wait-for-cfs-after-rebuild.yaml
workflows/ncn/hooks/before-each/force-time-sync.yaml

Fix a couple of 1.4 ncn upgrade issues in CASMPET-6099.  

CASMPET-6099: fix ncn rebuild upgrade issues

---

operations/network/Gateway_Testing.md

Minor linting. No content changes.

CASMINST-5546: Linting

---

operations/utility_storage/Ceph_Deep_Scrubs.md

(cherry picked from commit 7b23c6a43b9672cd41649bb5e40a42d6e1730882)
1.2 backport of https://github.com/Cray-HPE/docs-csm/pull/2715

CASMINST-5555: Linting and minor corrections

---

operations/firmware/FASUpdate_Script.md
operations/firmware/FAS_Admin_Procedures.md
operations/firmware/FAS_CLI.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md
scripts/operations/firmware/FASUpdate.py
scripts/operations/firmware/recipes/cray_chassisBMC_BMC.json
scripts/operations/firmware/recipes/cray_nodeBMC_BMC.json
scripts/operations/firmware/recipes/cray_nodeBMC_node0AccFPGA0.json
scripts/operations/firmware/recipes/cray_nodeBMC_node0BIOS.json
scripts/operations/firmware/recipes/cray_nodeBMC_node1AccFPGA0.json
scripts/operations/firmware/recipes/cray_nodeBMC_node1BIOS.json
scripts/operations/firmware/recipes/cray_nodeBMC_nodeAccFPGA0.json
scripts/operations/firmware/recipes/cray_nodeBMC_nodeBIOS.json
scripts/operations/firmware/recipes/cray_routerBMC_BMC.json
scripts/operations/firmware/recipes/gigabyte_nodeBMC_BIOS.json
scripts/operations/firmware/recipes/gigabyte_nodeBMC_BMC.json
scripts/operations/firmware/recipes/hpe_nodeBMC_iLO5.json
scripts/operations/firmware/recipes/hpe_nodeBMC_systemRom.json

CASMHMS-5243: Added script for FAS updates and documentation for the script.
CASMHMS-5692: CMM Shutdown updates
CASMHMS-5761: Documentation to exclude xnames from actions

CASMHMS-5692 / CASMHMS-5243 / CASMHMS-5761 - FAS Update Script

---

operations/hardware_state_manager/Add_a_Switch_to_the_HSM_Database.md
operations/hardware_state_manager/Add_an_NCN_to_the_HSM_Database.md
operations/network/external_dns/External_DNS_Failing_to_Discover_Services_Workaround.md
troubleshooting/kubernetes/Troubleshoot_Kubernetes_Node_NotReady.md
troubleshooting/kubernetes/Troubleshoot_Liveliness_Readiness_Probe_Failures.md

(cherry picked from commit c5ca88e827db1c44e720213303a83326e531f8d2)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2727

CASMINST-5557: Linting

---

operations/CSM_product_management/Validate_Signed_RPMs.md
operations/security_and_authentication/Backup_and_Restore_Vault_Clusters.md
operations/security_and_authentication/Change_Root_Passwords_for_Compute_Nodes.md
operations/security_and_authentication/Create_Internal_Groups_in_the_Keycloak_Shasta_Realm.md
operations/security_and_authentication/Create_Internal_User_Accounts_in_the_Keycloak_Shasta_Realm.md
operations/security_and_authentication/Make_HTTPS_Requests_from_Sources_Outside_the_Management_Kubernetes_Cluster.md
operations/security_and_authentication/Remove_the_LDAP_User_Federation_from_Keycloak.md

Just linting. No content changes.

CASMINST-5560: Linting

---

operations/artifact_management/Generate_Temporary_S3_Credentials.md
operations/package_repository_management/Repair_Yum_Repository_Metadata.md
operations/package_repository_management/Restrict_Admin_Privileges_in_Nexus.md
operations/security_and_authentication/Change_the_LDAP_Server_IP_Address_for_New_LDAP_Server_Content.md
operations/security_and_authentication/Get_a_Long-lived_Token_for_a_Service_Account.md
operations/security_and_authentication/Resync_Keycloak_Users_to_Compute_Nodes.md

Just linting. No real content changes.

CASMINST-5562: Linting

---

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh

Before what would happen is if you did:
./script ncn-w001,ncn-w002 ncn-w003
Only ncn-w003 would be updated as it was the last thing to update the vars.
So instead once the first arg with ncn-... is found, consider that the terminal case and then if more args matching it are found, exit with a warning message to stdout and do no work.
Ideally we should make this script just accept the following: ./script ncn-w001 ncn-w002 etc...
so we can just have users do
./script $(kubectl get nodes ... some selector)
Instead of forcing callers of the script to join arguments with a comma. That steps largely unnecessary and error prone.

CASMPET-6111: Update arg parsing of this script to be more strict

---

operations/system_layout_service/Restore_SLS_Postgres_Database_from_Backup.md

The SLS database restore steps were out of date, and contained a broken link.

CASMHMS-5676 SLS database restore validation steps

---

operations/system_layout_service/Restore_SLS_Postgres_Database_from_Backup.md

Jira: CASMHMS-5676
Jira: CASMHMS-5773
Co-authored-by: Nathan Rockershousen <nathan.rockershousen@hpe.com>
Signed-off-by: Shane Unruh <87081771+shunr-hpe@users.noreply.github.com>

CASMHMS-5676 Changed the validation step for SLS backup restore

---

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh

Reverts Cray-HPE/docs-csm#2750

Revert "CASMPET-6111: Update arg parsing of this script to be more strict"

---

operations/configuration_management/NCN_Worker_Image_Customization.md
operations/image_management/Import_External_Image_to_IMS.md

(cherry picked from commit bded0d56924f5239504abd3d2225a25101e197f9)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2763

CASMINST-5481: Clarify interaction between NCN image customization and IMS image import procedures; Reorganization; Linting

---

install/prepare_site_init.md
operations/security_and_authentication/Add_LDAP_User_Federation.md

CASMPET-6118: Update LDAP information for keycloak

---

operations/utility_storage/CSM_rbd_tool_Usage.md
upgrade/Stage_0_Prerequisites.md

(cherry picked from commit 0e5e52ddf4b171abe25ac2873e00cca7ef3b869a)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2773

CASMINST-5577: Linting of upgrade stage 0 and CSM RBD Tool info page

---

operations/configuration_management/Management_Node_Image_Customization.md

Provide guidance on determining NCN xnames

CASMISNT-5486: provide guidance on determining NCN xnames

---

scripts/operations/configuration/apply_csm_configuration.sh

(cherry picked from commit 3d7ee014c3691ac2d8773e49bca714c2837f92db)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2792

CASMINST-5578: Linting

---

operations/configuration_management/Create_an_Image_Customization_CFS_Session.md
operations/configuration_management/Track_the_Status_of_a_Session.md
operations/configuration_management/Troubleshoot_Ansible_Play_Failures_in_CFS_Sessions.md

(cherry picked from commit b54811eefdea690d56283d711534a3a757c6fecc)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2802

CASMINST-5591: Elaborate on CFS image customization session procedure

---

operations/security_and_authentication/Troubleshoot_Kyverno_Configuration_manually.md
troubleshooting/README.md

Kyverno is a new introduction for this release. Incase customer encounters any issue the steps mentioned here helps for debugging manually.

CASMINST-5088 : Documentation for troubleshooting kyverno

---

troubleshooting/known_issues/issues_with_ncn_health_checks.md

Provide path to script if "Validate PodSecurityPolicy is enabled" goss test fails. Instructions are added to "issues_with_ncn_health_checks.md".

CASMTRIAGE-4568

---

operations/security_and_authentication/Add_LDAP_User_Federation.md

CASMTRIAGE-4540: Update locations needed for cert change

---

install/prepare_configuration_payload.md
operations/index.md
operations/security_and_authentication/Audit_Logs.md

Moving the procedure to enable audit logging to the CSM docs.
* Resolves [STP-3226](https://jira-pro.its.hpecorp.net:8443/browse/STP-3226)
N/A
N/A
N/A
None

STP-3226 (1.0): Procedure to enable audit logging

---

install/prepare_configuration_payload.md
operations/index.md
operations/security_and_authentication/Audit_Logs.md

Moving the procedure to enable audit logging to the CSM docs.
* Resolves [STP-3226](https://jira-pro.its.hpecorp.net:8443/browse/STP-3226)
N/A
N/A
N/A
None

STP-3226 (1.2): Procedure to enable audit logging

---

.github/CODEOWNERS
Jenkinsfile.github
Makefile
docs-csm.spec

Minor `Jenkinsfile` and license updates. This simplifies some things in the `Jenkinsfile`, and conforms to my current template I'm using for several RPMs used in the PIT and NCN images.

Updating template for `Jenkinsfile`

---

operations/System_Recovery.md

Add steps to confirm that an export of the data or a backup exists before proceeding with uninstalling the chart
Also correct the location in the nexus manifest to pull from argo.

CASMPET-6144 main : Add checks for backups and update the nexus steps to create the manifest

---

RELEASE_NOTES.md
scripts/repair-ceph-latency.sh
troubleshooting/known_issues/ceph_osd_latency.md
upgrade/README.md

Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6157 -- add repair script if ceph latency detected (and corresponding doc).

Add script to repair ceph latency if detected (CASMPET-6157)

---

operations/README.md
operations/power_management/Power_Off_Compute_Cabinets.md
operations/power_management/Power_Off_the_External_Lustre_File_System.md
operations/power_management/Power_On_Compute_Cabinets.md
operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md
operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
operations/power_management/Prepare_the_System_for_Power_Off.md
operations/power_management/Shut_Down_and_Power_Off_the_Management_Kubernetes_Cluster.md
operations/power_management/System_Power_Off_Procedures.md
operations/power_management/System_Power_On_Procedures.md

Covers CASMPET-6148 and CASMPET-6162
TBD : backport the release/1.3 changes to main

CASMPET-6148 & CASMPET-6162 Changes from papaya shutdown test on shandy

---

workflows/iuf/operations/extract-release-distributions.yaml
workflows/iuf/stages.yaml

CASM-3644 add output of process media stage

---

workflows/iuf/operations/s3-upload/s3-upload-template.yaml

Pairs with: https://github.com/Cray-HPE/iuf-containers/pull/2
Requires: https://github.com/Cray-HPE/cray-nls/pull/94
This was not tested within the context of an operational IUF installation.  Happy to do so if someone can clue me in regarding how to do so.  (The script associated with this template _was_ tested.)

CASMINST-5584: add s3-upload-template.yaml

---

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml

Pairs with https://github.com/Cray-HPE/iuf-containers/pull/6
Requires: https://github.com/Cray-HPE/cray-nls/pull/94
This was not tested within the context of an operational IUF installation.  Happy to do so if someone can clue me in regarding how to do so.  (The script associated with this template _was_ tested.)

CASMINST-5585: provide loftsman-manifest-upload-template.yaml

---

workflows/iuf/operations/s3-upload/s3-upload-template.yaml

CASMINST-5584: indentation fixup

---

operations/configuration_management/Management_Node_Image_Customization.md

Fix the steps to prepare for customizing an ncn image using CFS/IMS.

CASMINST-5599 - update steps to customize an ncn image.

---

operations/security_and_authentication/Update_Default_ServerTech_PDU_Credentials_used_by_the_Redfish_Translation_Service.md

* Incorrect instructions to get RTS version number ([CASMHMS-5783](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5783))

CASMHMS-5783

---

operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md

(cherry picked from commit b97a1f73d71fa0be1184825dae5c2a33c0f3638b)
Backport of just the linting stuff from https://github.com/Cray-HPE/docs-csm/pull/2853

CASMINST-5609: Linting of NCN personalization procedures

---

upgrade/1.2/scripts/upgrade/files/goss-check-clock-skew.yaml
upgrade/1.2/scripts/upgrade/prerequisites.sh

The new snippet was tested on drax.

MTL-2030: update clock skew test during upgrade

---

upgrade/Upgrade_Management_Nodes_and_CSM_Services.md

add Docs for running a step of the upgrade procedure manually

CASMTRIAGE-4659-release1.3 add Docs for running a step of the upgrade procedure manually

---

upgrade/Upgrade_Management_Nodes_and_CSM_Services.md

Add Docs for running a step of the upgrade procedure manually.

CASMTRIAGE-4659 add Docs for running a step of the upgrade procedure manually

---

workflows/iuf/operations/preflight-checks-for-services.yaml

edit output messaging from IUF stage: pre_fligth_checks

CASMPET-6187 edit output messaging from IUF stage: pre_fligth_checks

---

background/ncn_kernel.md

Updates the docs to match the new kernel version for SLES15SP4.

MTL-1708 New kernel version

---

install/prepare_site_init.md
operations/conman/Establish_a_Serial_Connection_to_NCNs.md
operations/firmware/FAS_Recipes.md
operations/kubernetes/Restore_Postgres.md
operations/spire/Restore_Missing_Spire_Metadata.md

(cherry picked from commit 6f4f0bc93d1d6aef4d03da27dbabd0ffe81d5a61)
Backport of https://github.com/Cray-HPE/docs-csm/pull/2893

CASMINST-5663: Linting

---

install/deploy_non-compute_nodes.md
upgrade/Stage_1.md

Add some pointers during install and upgrade to run ceph latency repair script.

Update docs to instruct admins to run ceph repair latency script (CASMPET-6188)

---

upgrade/1.2.2/README.md

There was a request to review all changes that went into 1.2.2 in order to update the list of issues that are included in the 1.2.2 patch (in the readme file).

CASMINST-5684 Updating list of issues fixed in the 1.2.2 readme file

---

background/ncn_kdump.md
install/pre-installation.md
update_product_stream/README.md
upgrade/Stage_0_Prerequisites.md

Add http_proxy verbiage for the purpose of downloading artifacts from external endpoints using a proxy
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5667

CASMINST-5667 Alice

---

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml
workflows/iuf/operations/s3-upload/s3-upload-template.yaml

CASMINST-5661: adjust parameter handling

---

workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
workflows/iuf/stages.yaml

Complete the Install and Upgrade Framework (IUF) Nexus Helm template. Update other templates as required to work with the expected IUF framework global parameters (global_params).
These IUF workflows have all been verified to work as expected on Frigg with the IUF environment installed there. 

CASMINST-5501 IUF Nexus template updates

---

install/README.md
upgrade/prepare_for_upgrade.md

CASMPET-6154: Add Nexus Export to upgrade and install

---

.spelling
operations/image_management/Configure_IMS_to_Use_DKMS.md

Documentation on the new IMS feature to enable DKMS inside of IMS jobs.

CASM-2374 - enable DKMS within IMS jobs on demand.

---

install/install_csm_services.md
install/prepare_site_init.md

Fix broken links in `prepare_site_init.md` for skipping the LDAP section.
Add a segue in the CSM service install page to route users to the validation page.

Fix broken links and add segue

---

operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md

Add link in rebuild doc for how to restart a workflow if needed (https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4752).

Add note to rebuild doc indicating how to restart argo workflow (CASMTRIAGE-4752)

---

update_product_stream/README.md
upgrade/Stage_0_Prerequisites.md

add noarch to docs-csm-latest.noarch.rpm refs

---

install/pre-installation.md
operations/image_management/Upload_and_Register_an_Image_Recipe.md
workflows/ncn/hooks/before-all/install-csi.yaml
workflows/ncn/storage/storage.rebuild.yaml

CASMINST-5791 Auto-resolve SLES version. Also fix other `15sp3` references.

CASMINST-5791

---

workflows/iuf/operations/ims-upload.yaml
workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
workflows/iuf/stages.yaml

* Add product catalog update to nexus-setup
* Temporarily change cray-nexus-setup image used
* Remove unnecessary "default" values from output parameters in vcs and ims templates

CASM-3589 Add product catalog updates to nexus-setup

---

upgrade/scripts/upgrade/prerequisites.sh

CASMINST-5767: fix extra parens

---

install/pre-installation.md
update_product_stream/README.md

CASMINST-5799 remove refs to artifactory in download URLs

---

operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
workflows/ncn/hooks/before-each/check-dvs-services.yaml

The original PR for this feature was prematurely merged.  This PR contains responses to code reviews for the first PR.  Some of the code reviews are occurring offline, as not everyone on our team is set up to interact with CSM repos.
- [] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].

DVS-2827 dvs checks for ncn reboots

---

operations/README.md
operations/boot_orchestration/Options.md
operations/network/management_network/bican_switch_configuration.md
operations/security_and_authentication/Troubleshoot_Kyverno_Configuration_manually.md
operations/system_management_health/Prometheus_Kafka_Error.md
operations/utility_storage/Troubleshoot_S3FS_Mounts.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/2928 and https://github.com/Cray-HPE/docs-csm/pull/3029

CASMINST-5809/CASMMON-257: Linting and backport of CASMMON-245

---

operations/utility_storage/Troubleshoot_S3FS_Mounts.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3029

CASMINST-5809: Linting

---

workflows/iuf/operations/loftsman-manifest-deploy.yaml

CASMINST-5762-csm1.4 add versioned path to loftsman manifest deploy

---

workflows/iuf/operations/loftsman-manifest-deploy.yaml

CASMINST-5762: add versioned path to loftsman manifest deploy

---

workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml

CASM-3588 CASM-3590 Add catalog to docker and helm uploads (release 1.4)

---

install/deploy_final_non-compute_node.md

CASMINST-5550: restart chronyd after modfying chrony.conf

---

scripts/operations/node_management/ncn-image-modification.sh

`ntp-upgrade-config.sh` was removed in CSM 1.3. A reference to this script was not removed from `ncn-image-modification.sh`. This commit sets the timezone directly instead of trying to use a non-existent script.

CASMINST-5853: set timezone directly

---

workflows/iuf/operations/ims-upload.yaml
workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml

CASM-3811: Provide default values for outputs

---

scripts/cubs_tool.py
upgrade/Stage_1.md

When we enter our in_family check function, a variable was not getting set properly causing the noted error.
Since this was adding the whole script I put comments on what changed in comparison to the one that would be in the image.  

CASMINST-5855 - Fix UnboundLocalError in cubs_tool.py

---

workflows/iuf/operations/post-install-check-end.yaml
workflows/iuf/operations/post-install-check-start.yaml
workflows/iuf/operations/post-install-service-check-end.yaml
workflows/iuf/operations/post-install-service-check-start.yaml
workflows/iuf/stages.yaml

Added stub operations to get prom-metrics for post-install-service-check and post-install-check stages
curl 10.43.0.244:9090/metrics |grep post-install-check
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- …

CASMMON-247 adding metrics for web hook stages 

---

scripts/operations/node_management/ncn-ims-image-upload.sh

CASMINST-5815: add NCN IMS image name and id to Cray Product Catalog

---

glossary.md
introduction/differences.md
operations/README.md
operations/boot_orchestration/Rolling_Upgrades.md
operations/compute_rolling_upgrades/CRUS_Workflow.md
operations/compute_rolling_upgrades/Compute_Rolling_Upgrades.md
operations/compute_rolling_upgrades/Troubleshoot_Nodes_Failing_to_Upgrade_in_a_CRUS_Session.md
operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Bad_Parameters.md
operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Unmet_Conditions.md
operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md
operations/kubernetes/Backups_for_etcd-operator_Clusters.md
operations/kubernetes/Check_for_and_Clear_etcd_Cluster_Alarms.md
operations/kubernetes/Check_the_Health_and_Balance_of_etcd_Clusters.md
operations/kubernetes/Clear_Space_in_an_etcd_Cluster_Database.md
operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
troubleshooting/README.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3108

CASMCMS-8394: Document CRUS removal in CSM 1.6.0

---

workflows/iuf/operations/extract-release-distributions.yaml
workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml

Update the rbd mount in extract media operation for IUF

CASMINST-5620 change `/opt/cray/iuf` to `/etc/cray/upgrade/csm`

---

workflows/iuf/operations/managed-nodes/managed-nodes-rollout.yaml

Porting IUF operation managed nodes rollout to release/1.4

CASMINST-5691: Adding IUF operation managed nodes rollout to 1.4

---

workflows/iuf/operations/vcs-update/vcs-update-working-branch.yaml

Adds IUF operation update working branch to release/1.4

CASMCMS-8329: Update working branch to 1.4

---

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml

Update the product catalog with Loftsman manifest data.

CASM-3727: Update the product catalog

---

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml

Reverts Cray-HPE/docs-csm#3135

Revert "CASM-3727: Update product catalog with loftsman information"

---

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml

Reverts Cray-HPE/docs-csm#3134

Revert "CASM-3727: Update the product catalog"

---

workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml

This reverts commit e05c86428076b2fa805c846330793bb8d20d0a42.

Revert "Revert "CASM-3727: Update the product catalog" (#3149)"

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/docs.md
.github/ISSUE_TEMPLATE/rfe.md
.github/PULL_REQUEST_TEMPLATE.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3158

More explicit instructions for PRs

---

operations/hardware_state_manager/HSM_Roles_and_Subroles.md
operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_from_Role.md
operations/package_repository_management/Nexus_Space_Cleanup.md

(cherry picked from commit 8c40953673eb55720003511eb7dfd9d0b5a7eacb)
Backport of https://github.com/Cray-HPE/docs-csm/pull/3155

CASMINST-5884: Linting

---

troubleshooting/kubernetes/Kubernetes_Troubleshooting_Information.md

CASMINST-5903: Linting

---

workflows/iuf/operations/vcs-update/vcs-update-working-branch.yaml
workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml

This change adds a `cf_update_gitea_repo` parameter to the `gitea-update-content` step of the `vcs-update-working-branch` workflow template, as well as to the `gitea-upload-content` step of the `vcs-upload-content` workflow template. This allows products to specify a name which does not conform to the `<product>-config-management` default.
Test `vcs-update` and `vcs-upload` operations of IUF.

CASMINST-5876: Add support for `CF_*_GITEA_REPO` env var

---

install/deploy_final_non-compute_node.md

Handle fetching CSI from the new LiveCD ISO structure.

CASMTRIAGE-4892

---

scripts/operations/node_management/ncn-ims-image-upload.sh

Add `registry.local` to the image path.

CASMINST-5907: don't reach out to the interwebs, eh?

---

install/pre-installation.md

CASMINST-5886: Update docs to display csm-1.4 in github install docs

---

scripts/operations/node_management/ncn-ims-image-upload.sh

This temporary band-aid change will allow fresh install to skip updating the product catalog and avoid the errors described in CASMINST-5912.  It should only be merged if we are testing fresh install of `CSM-1.4` over the weekend

CASMINST-5912: fresh-install band-aid

---

workflows/iuf/operations/ims-upload.yaml

Update `cray-ims-load-artifacts` Docker image version used in ims-upload operation for IUF.
This will need to be backported to the 1.4 release branch.

CASM-3760: Update ims-load-artifacts image version

---

operations/CSM_product_management/Post_Install_Customizations.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3222

CAST-32117 Typos in loftsman ship parameters

---

scripts/operations/node_management/ncn-ims-image-upload.sh

This is not the greatest solution, IMO. However, it is the simplest. (So much for Occam's Razor.)

CASMINST-5912: if running on the pit, ship the command over to ncn-m002

---

.spelling
operations/validate_csm_health.md
troubleshooting/interpreting_hms_health_check_results.md
troubleshooting/known_issues/issues_with_ncn_health_checks.md
troubleshooting/known_issues/sms_health_check.md

(cherry picked from commit 6c47c1ae81fd8f9028293e564442dafbd9e909ee)
Backport of https://github.com/Cray-HPE/docs-csm/pull/3205

CASMINST-3943: Update CSM health check troubleshooting information, specifically for issues related to unconfigured CLI

---

operations/node_management/Add_a_Standard_Rack_Node.md
operations/node_management/Add_additional_Air-Cooled_Cabinets_to_a_System.md

CASMHMS-5914
- Update procedure for changes made to the hardware-topology-assistant: https://github.com/Cray-HPE/hardware-topology-assistant/pull/2
- Fix typos in script paths used by this procedure. 
- Describe advanced options for the hardware topology 
CASMHMS-5860: Fixed typos in `Add a Standard Rack Node` procedure to remove references to a liquid-cooled blade.
assistant.

(CSM 1.3) CASMHMS-5914/CASMHMS-5860: Updates to add river cabinet procedure and fix typo when adding a river node.

---

operations/firmware/Updating_Firmware_m001.md
operations/firmware/Updating_Firmware_without_FAS.md

Adds a warning not to update the firmware and BIOS of ncn-m001 while it is booted as the PIT node from a remote ISO image, because it will break the remote ISO mount. Also does some linting of a couple of the non-FAS FW/BIOS update pages.

CASMINST-4654: Add warning about updating ncn-m001 firmware when booted from remote ISO

---

operations/node_management/Add_a_Standard_Rack_Node.md
operations/node_management/Add_additional_Air-Cooled_Cabinets_to_a_System.md

CASMHMS-5914
- Update procedure for changes made to the hardware-topology-assistant: https://github.com/Cray-HPE/hardware-topology-assistant/pull/2
- Fix typos in script paths used by this procedure. 
- Describe advanced options for the hardware topology 
CASMHMS-5860: Fixed typos in `Add a Standard Rack Node` procedure to remove references to a liquid-cooled blade.
assistant.

(main) CASMHMS-5914/CASMHMS-5860: Updates to add river cabinet procedure and fix typo when adding a river node.

---

operations/node_management/Add_a_Standard_Rack_Node.md
operations/node_management/Add_additional_Air-Cooled_Cabinets_to_a_System.md

CASMHMS-5914
- Update procedure for changes made to the hardware-topology-assistant: https://github.com/Cray-HPE/hardware-topology-assistant/pull/2
- Fix typos in script paths used by this procedure. 
- Describe advanced options for the hardware topology 
CASMHMS-5860: Fixed typos in `Add a Standard Rack Node` procedure to remove references to a liquid-cooled blade.
assistant.

(CSM 1.4) CASMHMS-5914/CASMHMS-5860: Updates to add river cabinet procedure and fix typo when adding a river node.

---

workflows/iuf/operations/ims-upload.yaml

Update the `cray-ims-load-artifacts` image version to fix a bug in the ims-upload IUF operation.

CASMINST-5926: Update cray-ims-load-artifacts image version

---

operations/configuration_management/Worker_Image_Customization.md

Fix misspelled command argument.

CASMTRIAGE-4868: Correct typo in command

---

.github/CODEOWNERS

Backport of https://github.com/Cray-HPE/docs-csm/pull/3271

Explicitly add docs-csm-reviewers

---

workflows/iuf/operations/extract-release-distributions.yaml

CASMINST-5939: Use the latest version of iuf-container

---

workflows/iuf/operations/extract-release-distributions.yaml

CASMINST-5939: Pull in latest iuf-container

---

glossary.md
introduction/differences.md
operations/compute_rolling_upgrades/CRUS_Workflow.md
operations/compute_rolling_upgrades/Compute_Rolling_Upgrades.md
operations/compute_rolling_upgrades/Troubleshoot_Nodes_Failing_to_Upgrade_in_a_CRUS_Session.md
operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Bad_Parameters.md
operations/compute_rolling_upgrades/Troubleshoot_a_Failed_CRUS_Session_Due_to_Unmet_Conditions.md
operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md
operations/index.md
operations/kubernetes/Repopulate_Data_in_etcd_Clusters_When_Rebuilding_Them.md
troubleshooting/index.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3274

CASMINST-5957: Replace CSM 1.6 references with CSM 1.5

---

workflows/iuf/operations/vcs-update/vcs-update-working-branch.yaml

1.0.4 fixes two release critical bugs.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5955 Race condition for slingshot repo connections when merging branches.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5956 git checkout was being used with incorrect flag causing branch history resets thus some files missing after merge.

CASMINST-5955-5956: backport to main bumping version to 1.0.4 cf-gitea-update

---

workflows/iuf/operations/vcs-update/vcs-update-working-branch.yaml

1.0.4 fixes two release critical bugs.
- https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5955 Race condition for slingshot repo connections when merging branches.
- https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5956 git checkout was being used with incorrect flag causing branch history resets thus some files missing after merge.

CASMINST-5955-5956: 1.0.4 cf-gitea-update bump

---

operations/configuration_management/Management_Node_Image_Customization.md

The 1.3 procedure for customizing NCN images is written assuming that the S3 paths for the images will always be of the form `k8s/<version>/<artifact>` or `ceph/<version>/<artifact>`. However, that will only be the case the first time the images are customized. As part of the customization process, the new images being used will have their S3 paths of the form `<IMS ID>/<artifact>`. Because of this, the procedures as written do not work for those re-customizations of images that had been previously customized.
This PR modifies the procedures to be more general, not making an assumption about which form the S3 path must take. Almost all of this involves just changing the initial step to identify and download the NCN image artifacts. Minor changes are needed to other parts of the procedure …

CASMINST-5942: Modify NCN image customization procedure to be more flexible

---

.github/workflows/markdown-lint.yaml

Updates to markdown-lint 0.32.0 from 0.31.1.

Update to markdownlint-cli 0.32.0

---

operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md

Update the "kubeadm [alpha] kubeconfig user" command to use the --config argument.  The --apiserver-advertise-address and --apiserver-bind-port arguments are no longer supported.
Resolves [CASMPET-6315](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6315) for CSM 1.2.
A slightly different change for CSM 1.3 and backports to CSM 1.4 and main branch are in progress.

CASMPET-6315 : DOCS : Cert renewal - update kubeadm [alpha] kubeconfig user

---

.spelling
operations/network/management_network/edge_switch_cabling_guide.md

Edge switch Cabling guide
Relates to:
[CASMNET-1915](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1915)

CASMNET-1915 | edge switch cabling guide

---

operations/iuf/workflows/upgrade_all_products.md

CSAMINST-5919-managment-rollout-update make corrections for management-nodes-rollout-stage

---

operations/node_management/Updating_Cabinet_Routes_on_Management_NCNs.md

Add absolute path to ifroute-bond0 file paths

CASMNET-2052 Add absolute path to ifroute-bond0 file paths

---

operations/node_management/Updating_Cabinet_Routes_on_Management_NCNs.md

Add absolute path to ifroute-bond0 file paths

CASMNET-2052 Add absolute file path to ifroute-bond0 files

---

operations/boot_orchestration/Rolling_Upgrades.md

Adds examples to the session on using BOS staged sessions with Slurm
Relates to:
CASMCMS-8417

CASMCMS-8417: Improve BOS docs on using staged sessions with Slurm

---

operations/node_management/Rebuild_NCNs/Final_Validation_Steps.md
operations/node_management/Rebuild_NCNs/Identify_Nodes_and_Update_Metadata.md
operations/node_management/Rebuild_NCNs/Post_Rebuild_Storage_Node_Validation.md
operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md
operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
operations/node_management/Rebuild_NCNs/Validate_Boot_Loader.md

Redirect back to main rebuild page instead of directly to next step.
Resolves [CASMINST-6001](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6001)

Refactor rebuild links to avoid following next step if not rebuilding (CASMINST-6001)

---

.spelling
operations/network/management_network/README.md
operations/network/management_network/aruba_split_cables.md

Adding  Aruba splitter cable document and updating readme.
Relates to:
- [CASM-3166](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3166)

CASM-3166 | aruba split cables rel/1.4

---

.spelling
operations/network/management_network/README.md
operations/network/management_network/aruba_split_cables.md

Adding  Aruba splitter cable document and updating readme.
Relates to:
- [CASM-3166](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3166)

CASM-3166 | aruba split cables rel/main

---

operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
upgrade/Stage_2.md

CASMPET-6287 add comment about not restarting DVS clients and servers at the same time

CASMPET-6287 add comment about not restarting DVS clients and servers at the same time

---

workflows/iuf/stages.yaml

The operation name needs to match the Argo WorkflowTemplate name. The workflow template name is vcs-update-working-branch. Fix this in `stages.yaml`.
This change is only needed on the release/1.4 branch. It is already correct on the main branch.

CASMINST-6023: Fix operation name in update-vcs-config stage of IUF

---

upgrade/scripts/upgrade/prerequisites.sh

When upgrading to CSM 1.4, the rebuild workflow templates need to be uploaded as a prerequisite.

CASMTRIAGE-5002 & CASMPET-6357: upload rebuild templates and install iuf-cli

---

operations/security_and_authentication/Resync_Keycloak_Users_to_Compute_Nodes.md

The keycloak sync ansible plays have changed since this procedure was written:
- They moved to the Slurm/PBS config management VCS repos
- They have been enabled by default
- They sync periodically (daily)
- There's now a script that can be run to sync without rebooting
Update the documentation for this procedure to reflect the above changes.

ALT-180 Fix keycloak sync procedure

---

install/configure_administrative_access.md
operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md
operations/hardware_state_manager/Set_BMC_Management_Role.md
upgrade/Stage_3.md
upgrade/prepare_for_upgrade.md

These pages have broken links
- 'Upgrade Management Nodes and CSM Services' on https://github.com/Cray-HPE/docs-csm/blob/main/upgrade/prepare_for_upgrade.md#preparation-completed
- 'Validate CSM health' on https://github.com/Cray-HPE/docs-csm/blob/main/upgrade/Stage_3.md#stage-completed
- 'Manual configuration' on https://github.com/Cray-HPE/docs-csm/blob/main/install/configure_administrative_access.md#1-configure-the-cray-command-line-interface
- 'Ignore Node within FAS' on https://github.com/Cray-HPE/docs-csm/blob/main/operations/hardware_state_manager/Set_BMC_Management_Role.md
- 'Ignore Node within FAS' on https://github.com/Cray-HPE/docs-csm/blob/main/operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md
[1]: …

CASMINST-6016 Fixed broken internal links

---

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml

CASMINST-5982 add labels for iuf session and activity to worker rebuild workflow

CASMINST-5982 add labels for iuf session and activity to worker rebuild workflow

---

operations/iuf/stages/management_nodes_rollout.md
operations/iuf/workflows/upgrade_all_products.md

CASMINST-6024 add ncn-boot image instructions for management-nodes-rollout stage

---

operations/kubernetes/Backups_for_etcd-operator_Clusters.md
operations/kubernetes/Check_for_and_Clear_etcd_Cluster_Alarms.md
operations/kubernetes/Check_the_Health_and_Balance_of_etcd_Clusters.md
operations/kubernetes/Clear_Space_in_an_etcd_Cluster_Database.md
operations/kubernetes/Determine_if_Pods_are_Hitting_Resource_Limits.md
operations/network/dns/DNS.md
operations/network/external_dns/Troubleshoot_DNS_Configuration_Issues.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3384

CASMINST-6036: Remove references to external DNS etcd cluster

---

operations/iuf/stages/managed_nodes_rollout.md

Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5990

CASMINST-5990: 1.4 Documentation for IUF managed nodes rollout

---

upgrade/scripts/upgrade/prerequisites.sh

After cray-nls chart is upgraded, it takes some time for hooks crd to be created. This PR adds a 90 second wait for hooks crd to be created before uploading workflow rebuild templates.

CASMINST-6040: add wait for hooks crd

---

.spelling
operations/image_management/IMS_export_import.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3410

CASMINST-6056: Linting of IMS import/export procedure

---

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh

CASMINST-5981

---

.spelling
operations/iuf/IUF.md
operations/iuf/examples/iuf_list_stages.md
operations/iuf/examples/iuf_restart.md
operations/iuf/stages/management_nodes_rollout.md
operations/iuf/workflows/upgrade_all_products.md
operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md

More IUF install workflow improvements based on experiences on loki and odin installs.

CASMINST-6024

---

upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh

CASMINST-6076 1.4

---

upgrade/scripts/upgrade/util/update-customizations.sh

This is a small fix for the update-customizations.sh found while looking to do the next change. The current script does not work and will not do anything so this change will actually put the change into the correct place in the customziations.yaml for keycloak. This wont need to be back-ported to 1.5, I am doing more changes to 1.5 and will have a seperate PR.

CASMPET-6401: Fix update-customizations.sh for keycloak upgrade

---

upgrade/Upgrade_Management_Nodes_and_CSM_Services.md

Stage_4 was removed from the csm-upgrade procedure because no ceph upgrade is performed in the 1.3 to 1.4 upgrade. This change is removing a broken link which was still referencing stage_4.

CASMPET-6394 remove broken link referencing stage_4 of upgrade

---

.spelling
operations/CSM_product_management/Post_Install_Customizations.md
operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
operations/network/external_dns/External_DNS_Failing_to_Discover_Services_Workaround.md
operations/network/external_dns/Ingress_Routing.md
operations/network/external_dns/Troubleshoot_Systems_Not_Provisioned_with_External_IP_Addresses.md
operations/node_management/Add_Remove_Replace_NCNs/Redeploy_Services.md
operations/resiliency/Recreate_StatefulSet_Pods_on_Another_Node.md
operations/system_management_health/Access_System_Management_Health_Services.md
operations/system_management_health/Configure_Prometheus_Alerta_Alert_Notifications.md
operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
operations/system_management_health/System_Management_Health.md
operations/system_management_health/System_Management_Health_Checks_and_Alerts.md

Resolves:
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-287

CASMMON-287: Update csm documentation

---

install/deploy_final_non-compute_node.md

https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5025
- remove instructions regarding NMN DNS
- add code snippet to handle single and multiple HMN DNS servers

CASMTRIAGE-5025 (1.3 backport)

---

install/deploy_final_ncn.md

https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5025
- remove instructions regarding NMN DNS
- add code snippet to handle single and multiple HMN DNS servers

CASMTRIAGE-5025 (1.2 backport)

---

operations/node_management/Configure_NTP_on_NCNs.md

 CASMINST-6079: clarify that time.nist.gov is an example

---

.spelling
operations/boot_orchestration/BOS_export_import.md

Linting (and other minor improvements) of the BOS import/export procedure, ahead of more substantial changes, so that the upcoming PRs can be focused just on the technical changes to the procedures.
Note that I've talked with @jsollom-hpe and we've also identified some problems with the current BOS import/export procedure and scripts. However, I still want to keep this PR to just be linting, without addressing those issues. I will address those issues in a subsequent PR.
Backports:
- [1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3432)
- [1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3433)
No backports needed for earlier than 1.3
[2]: …

CASMINST-6066: BOS export/import: Linting

---

introduction/documentation_conventions.md
introduction/templates/disclaimers.md

By popular request, add a template for draft pages.

Add a disclaimer for draft

---

upgrade/Stage_0_Prerequisites.md

Fix formatting, unterminated triple astrick.

Broken Markdown

---

install/README.md
operations/boot_orchestration/Limitations_for_Gigabyte_BMC_Hardware.md
operations/boot_orchestration/Troubleshoot_Compute_Node_Boot_Issues_Related_to_Slow_Boot_Times.md
operations/kubernetes/Determine_if_Pods_are_Hitting_Resource_Limits.md
operations/network/management_network/snmp_exporter_configs.md
operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
upgrade/prepare_for_upgrade.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3470

CASMINST-6094: Linting

---

operations/configuration_management/Version_Control_Service_VCS.md

Mostly linting. Also added a table of contents to the page, and modified one set of commands to avoid the user having to manually edit the backed-up manifest files. I tested this last procedure on wasp.

CASMINST-6099: VCS backup/restore: Linting and minor improvements

---

operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md

This adds a note in the Kubernetes and Bare Metal etcd documentation that you will also want to look at the spire certificate information. At the moment I don't believe we'd want to merge the two documents, but if someone needs to renew the kubernetes certificates on a CSM 1.2 system then they'll most likely also need to renew the spire certificate. This makes it easier to find that information and hopefully will let them know that they should check that as well.
[CASMTRIAGE-5089](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5089)

CASMTRIAGE-5089 Add a link to spire cert renewal

---

RELEASE_NOTES.md
operations/boot_orchestration/BOS_API_Versions.md
operations/boot_orchestration/Boot_Orchestration.md

CASMCMS-8481 release 1.4: Make BOS V2 the default for the Cray CLI

---

install/deploy_non-compute_nodes.md
install/pre-installation.md
operations/network/Gateway_Testing.md
operations/validate_csm_health.md
update_product_stream/README.md
upgrade/Stage_0_Prerequisites.md
upgrade/Stage_2.md

This installs `libcsm` in the installation and upgrade workflows.
`libcsm` will start providing dependencies for `docs-csm`, so it should be installed at the same time.
This will need to be backported to release/1.3 and release/1.4 once reviews and feedback are incorporated.

MTL-2112 Install `libcsm` with `docs-csm`

---

install/pre-installation.md

Ensure installations pull the latest docs, and from our desired endpoints.

CASMINST-6127 Ensure installs fetch latest docs

---

update_product_stream/README.md

The consolidation of the RPM fetching step in the upgrade into caused a gap where the fetched RPMs are not available for the `prereqs` script.

CASMINST-6128 Copy the RPMs to `/root`

---

operations/README.md
operations/node_management/Defragment_NID_Numbering.md
scripts/operations/node_management/defragment_nids.py
troubleshooting/known_issues/antero_node_NID_allocation.md

This adds the defragment_nids.py script and the `Defragment NID Numbering` procedure to docs-csm.

CASMHMS-5565: Add NID defragmentation script and procedure

---

operations/kubernetes/Troubleshoot_Postgres_Database.md

Based on CAST-32596 - tweak the example in the docs to note that the service that is being scaled could be a deployment or a statefulset

CASMPET-6449 1.5 : DOCs: Small improvement to Postgres SyncFailed troubleshooting

---

operations/firmware/FASUpdate_Script.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Update_iLO5_2.78.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md
scripts/operations/firmware/FASUpdate.py
scripts/operations/firmware/recipes/cray_nodeBMC_node0AccVBIOS.json
scripts/operations/firmware/recipes/cray_nodeBMC_node0ManagementEthernet.json
scripts/operations/firmware/recipes/cray_nodeBMC_node1ManagementEthernet.json
scripts/operations/firmware/recipes/cray_nodeBMC_nodeManagementEthernet.json

Added AccVBOIS and Management Ethernet FAS documentation
Added documentation to upgrade iLO 5 to version 2.78 when required to upgrade to versions > 2.78
Updated FAS Update Script to add image ID

CASMHMS-5936 / CASMHMS-5957

---

.github/dependabot.yml
.github/workflows/link-check.yaml
.github/workflows/shellcheck.yaml
.github/workflows/spellcheck.yaml
.github/workflows/stale.yml
.github/workflows/style-check.yaml

Workflow update 1.3

---

scripts/mount-cephfs-share.sh

Exit mount script if unable to unmount old rbd device
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5109
* ashton
Testing exit when mountpoint is busy:
```
ncn-m003:/etc/cray/upgrade/csm # ~/brad/mount-cephfs-share.sh
Found previous CSM release rbd mount, moving to /mnt/csm-1.3-rbd...
Unmounting /etc/cray/upgrade/csm...
umount: /etc/cray/upgrade/csm: target is busy.
ERROR: CSM rbd device failed to unmount!
```
Testing exit when mountpoint is not busy:
```
ncn-m003:/etc/cray/upgrade # ~/brad/mount-cephfs-share.sh
Found previous CSM release rbd mount, moving to /mnt/csm-1.3-rbd...
Unmounting /etc/cray/upgrade/csm...
Replacing /etc/cray/upgrade/csm with /mnt/csm-1.3-rbd in /etc/fstab...
Mounting /mnt/csm-1.3-rbd to preserve previous upgrade content...
Didn't find s3fs mount at …
```

Exit mount script if unable to unmount old rbd device (CASMTRIAGE-5109)

---

operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Update_iLO5_2.78.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md

Added AccVBOIS and Management Ethernet FAS documentation
Added documentation to upgrade iLO 5 to version 2.78 when required to upgrade to versions > 2.78
CASMHMS-5936 / CASMHMS-5957

CASMHMS-5936 / CASMHMS-5957 for 1.3 branch

---

operations/firmware/FASUpdate_Script.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Update_iLO5_2.78.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md
scripts/operations/firmware/FASUpdate.py
scripts/operations/firmware/recipes/cray_nodeBMC_node0AccVBIOS.json
scripts/operations/firmware/recipes/cray_nodeBMC_node0ManagementEthernet.json
scripts/operations/firmware/recipes/cray_nodeBMC_node1ManagementEthernet.json
scripts/operations/firmware/recipes/cray_nodeBMC_nodeManagementEthernet.json

Added AccVBOIS and Management Ethernet FAS documentation
Added documentation to upgrade iLO 5 to version 2.78 when required to upgrade to versions > 2.78
Updated FAS Update Script to add image ID
CASMHMS-5936 / CASMHMS-5957

CASMHMS-5936 / CASMHMS-5957 main

---

operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
operations/node_management/Removing_a_Standard_Node_from_a_System.md

`s/Perquisites/Prerequisites/`
merge with https://github.com/Cray-HPE/docs-csm/pull/3538
merge with https://github.com/Cray-HPE/docs-csm/pull/3539

fix spelling error in remove standard node pro

---

install/install_csm_services.md
operations/network/management_network/README.md
operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
operations/security_and_authentication/Change_SNMP_Credentials_on_Leaf_BMC_Switches.md
update_product_stream/README.md
upgrade/Stage_0_Prerequisites.md
upgrade/Stage_2.md
upgrade/prepare_for_upgrade.md
upgrade/scripts/common/ncn-common.sh

This covers:
- CASMINST-6140
- CASMINST-6141
- CASMINST-6142
Provides UX fixes for docs.

CASMINST-6140 CASMINST-6141 CASMINST-6142

---

update_product_stream/README.md

The `https_proxy` var needs to be exported the way it is currently used, which we want to avoid as it can break other commands if `https_proxy` is left set.
This merges it back into one line while keeping the code-snippets separate for facilitating copy-paste. Using this in one line avoids the need to `export`, while allowing `wget` to find `https_proxy`.

CASMINST-6142 Fix unexported variable

---

upgrade/scripts/upgrade/util/upgrade-cray-nls.sh

When upgrading argo server to v3.4.5, we need to label and annotate existing argo crds so that helm can manage them during the upgrade.

CASM-3813: upgrade argo server to v3.4.5

---

operations/network/management_network/bonded_uan.md

CASMUSER-3183 bonded uan 1.4

---

operations/network/management_network/bonded_uan.md

CASMUSER-3183 Bonded UAN net DOCS

---

upgrade/Stage_3.md

CASMINST-6140 tweak for more friendly copy-paste.

CASMINST-6140 adjustment

---

.spelling
operations/network/management_network/bonded_uan.md
operations/network/management_network/canu/custom_config.md

CASMUSER-3183 bonded uan 1.3

---

update_product_stream/README.md
upgrade/Stage_2.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3555

MTL-2112 Handle service pack changes

---

upgrade/Stage_2.md

The CSM repos are not added to the NCN at this point in time, short of adding the repos the user can just follow the check-for-latest documentation guide again.
```bash
root@ncn-m002 2023-04-01 01:53:37 ~ # zypper --plus-repo="/etc/cray/upgrade/csm/csm-${CSM_RELEASE}/tarball/${CSM_RELEASE}/rpm/cray/csm/sle-$(awk -F= '/VERSION=/{gsub(/["-]/, "") ; print tolower($NF)}' /etc/os-release)" --no-gpg-checks install -y cray-site-init
Specified local path does not exist or is not accessible.
root@ncn-m002 2023-04-01 01:53:47 ~ # scp ncn-m001:/root/*.noarch.rpm /root/
docs-csm-latest.noarch.rpm                                                                                100%   30MB 282.8MB/s   00:00
libcsm-latest.noarch.rpm …
```

MTL-2112 csm repo is not available at this point

---

upgrade/Stage_2.md

The URL for installing `cray-site-init` on ncn-m002 during upgrades is missing the prefix from the CASMINST-6142 fixes in #3540.
Fixes this command:
```bash
zypper --plus-repo="/etc/cray/upgrade/csm/csm-${CSM_RELEASE}/tarball/${CSM_RELEASE}/rpm/cray/csm/sle-$(awk -F= '/VERSION=/{gsub(/["-]/, "") ; print tolower($NF)}' /etc/os-release)" --no-gpg-checks install -y cray-site-init
Specified local path does not exist or is not accessible.
```

CASMINST-6142 Fix `csm-` prefix on URL

---

scripts/repair-ceph-latency.sh

Refactor latency script to simply set rocksdb options and restart osds without checking if the cluster is currently exhibiting latency.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5138
* `ashton`
```
ncn-m002:~/brad # ./repair-ceph-latency.sh
Ceph is healthy -- continuing...
INFO: beginning restart of daemons on ncn-s001.
INFO: failing active manager to another node (from ncn-s001).
Sleeping for 30 seconds waiting for mgr to fail over...
noout is set
norecover is set
nobackfill is set
Daemons for Ceph cluster 7dd7193a-cb42-11ed-af07-42010afc0104 stopped on host ncn-s001. Host ncn-s001 moved to maintenance mode
Sleeping for ten seconds waiting for daemons to stop...
All daemons stopped, continuing...
Ceph cluster 7dd7193a-cb42-11ed-af07-42010afc0104 on ncn-s001 has exited …
```

Change ceph latency script to always restart osds (CASMTRIAGE-5138)

---

upgrade/1.3.1/README.md
upgrade/1.3.2/README.md

Allow customers to simply run an auto-expanding `pdsh` command vs. manually adjusting BASH ranges.

Remove manual labor

---

upgrade/1.3.2/README.md

CASMNET-2056

---

install/deploy_non-compute_nodes.md
upgrade/Stage_1.md

Include instructions for ceph latency repair (CASMINST-6175)

---

upgrade/scripts/upgrade/prerequisites.sh

In the prerequisites step, kyverno is upgraded with reference to the newly added dvs namespace. This PR upgrades cray-drydock to add the dvs namespace prior to kyverno upgrade.

CASMINST-6152: upgrade drydock prior to kyverno in prereq

---

install/install_csm_services.md
operations/System_Recovery.md
operations/image_management/IMS_export_import.md
operations/network/management_network/README.md
operations/network/management_network/bonded_uan.md
operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
operations/node_management/Removing_a_Standard_Node_from_a_System.md
operations/security_and_authentication/Change_SNMP_Credentials_on_Leaf_BMC_Switches.md
scripts/operations/system_recovery/ims-import-export.py
scripts/repair-ceph-latency.sh
update_product_stream/README.md
upgrade/Stage_0_Prerequisites.md
upgrade/Stage_2.md
upgrade/Stage_3.md
upgrade/prepare_for_upgrade.md
upgrade/scripts/common/ncn-common.sh
upgrade/scripts/k8s/tds_lower_cpu_requests.sh
upgrade/scripts/upgrade/csm-upgrade.sh
upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
upgrade/scripts/upgrade/prerequisites.sh
upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
workflows/ncn/hooks/after-each/update-node-label.yaml
workflows/ncn/storage/storage.upgrade.yaml

Add references to the WLM restore procedures from the CPE installation guide.

ALT-194 Add references to WLM recovery procedures

---

.spelling
operations/iuf/workflows/management_rollout.md
upgrade/Stage_2.md

Instruct user to stop before rebuilding m001 in IUF documentation. It was unclear how many steps in a specific document should be followed, it is to clarify where the user should stop.

CASMINST-6156 instruct user to stop before rebuilding m001 in IUF documentation

---

install/deploy_non-compute_nodes.md
install/troubleshooting_installation.md
install/troubleshooting_utility_storage_node_installation.md

Add troubleshooting doc for storage install failing due to ceph pool app not enabled.

CASMINST-6149 add troubleshooting doc for storage install failing due to ceph pool app not enabled

---

operations/node_management/Rebuild_NCNs/Validate_Boot_Loader.md

Add troubleshooting to validate_bool_loader doc for applying root ssh keys 

CASMISNT-6184 add troubleshooting to validate_bool_loader doc for applying root ssh keys 

---

upgrade/scripts/upgrade/prerequisites.sh

Backport of: https://github.com/Cray-HPE/docs-csm/pull/3606

MTL-2112 Include `libcsm`

---

operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md

CASMINST-6196-main copy file  upload_ceph_images_to_nexus.sh from m001 before executing it

---

operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md

CASMINST-6196-1.3 copy file  upload_ceph_images_to_nexus.sh from m001 before executing it

---

operations/node_management/Build_NCN_Images_Locally.md

Backport of the linting to one of the pages in https://github.com/Cray-HPE/docs-csm/pull/3615

CASMCMS-8530: Fix broken links. do minor linting

---

operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
scripts/upload_ceph_images_to_nexus.sh

CASMTRIAGE-5107-1.3

---

operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md
scripts/upload_ceph_images_to_nexus.sh

Backport of CASMTRIAGE-5107 into CSM 1.4.
Fixing the ceph image issue occuring during node image upgrades

CASMTRIAGE-5107-1.4

---

background/ncn_firmware.md

Updates our minimum version to `C37`.

MTL-2075 C37 BIOS

---

.spelling
operations/iuf/workflows/managed_rollout.md

The documentation now links to an explanation for configuring the Slurm workload manager to enable 'rolling updates' which the managed node rollout functionality uses. Further, it lists the command to Slurm to execute the reboot through BOS.

CASM-4072:  Improve IUF documentation for managed nodes rollout

---

.spelling
operations/iuf/workflows/managed_rollout.md

The documentation now links to an explanation for configuring the Slurm workload manager to enable 'rolling updates' which the managed node rollout functionality uses. Further, it lists the command to Slurm to execute the reboot through BOS.

CASM-4072: Improve IUF documentation for managed nodes rollout

---

scripts/operations/configuration/apply_csm_configuration.sh

When applying CFS configurations, the CFS API can only handle a certain number of xnames as query parameters. This is due to the buffer size of uwsgi. The default buffer size is too small to handle more than 34 xnames per request and sometimes fewer.
This mod breaks up requests into twenty xnames or fewer. The CFS API can handle this many.
This is a workaround for the CSM-1.3.2 release. In later releases, uwsgi's buffer size was increased.
I tested this on both Frigg and the Crossroads system.

CASMTRIAGE-5113: Chunk up xnames in requests to CFS

---

operations/iuf/IUF.md
operations/iuf/workflows/configuration.md
operations/iuf/workflows/management_rollout.md
operations/iuf/workflows/upgrade_csm_and_additional_products_with_iuf.md
upgrade/Stage_0_Prerequisites.md
upgrade/Stage_1.md

CASMINST-6147 Add note after Stage 0.4
CASMINST-6151 misc IUF doc updates

CASMINST-6147 / CASMINST-6151

---

operations/iuf/IUF.md
operations/iuf/workflows/configuration.md
operations/iuf/workflows/management_rollout.md
operations/iuf/workflows/upgrade_csm_and_additional_products_with_iuf.md
upgrade/Stage_0_Prerequisites.md

CASMINST-6147 Add note after Stage 0.4
CASMINST-6151 misc IUF doc updates

CASMINST-6147 / CASMINST-6151 1.4

---

.spelling
operations/README.md
operations/node_management/Add_additional_Air-Cooled_Cabinets_to_a_System.md
operations/node_management/Add_additional_Liquid-Cooled_Cabinets_to_a_System.md

Some pages in the CSM docs are orphaned, in that they are not linked to from any other pages in the docs. This makes them mostly invisible to people who are navigating through the docs in the intended way (following links, using the provided index pages, etc).
This PR corrects some of the low hanging fruit examples of these. I'll open additional tickets for others that I find.
Backports:
- [1.4](https://github.com/Cray-HPE/docs-csm/pull/3627)
- [1.3](https://github.com/Cray-HPE/docs-csm/pull/3629)
- [1.2](https://github.com/Cray-HPE/docs-csm/pull/3630)
- [1.0](https://github.com/Cray-HPE/docs-csm/pull/3631)

CASMINST-6212: Fix orphaned links, create backup/restore section of operations index

---

scripts/operations/etcd/take-etcd-manual-backups.sh

Refactor etcd script for taking manual backup of all clusters for bitnami chart changes.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6418
* `ashton`
```
/tmp/take-etcd-manual-backups.sh post_install
Creating manual etcd backup for 'cray-bos' named 'post_install.backup_2023-04-13-13:56:24'.
Taking snapshot from cray-bos-bitnami-etcd-1...
Pushing newly created snapshot /snapshots/cray-bos-bitnami-etcd/db-2023-04-13_13-56 to S3 as post_install.backup_2023-04-13-13:56:24 for cray-bos
upload: snapshots/cray-bos-bitnami-etcd/db-2023-04-13_13-56 to s3://etcd-backup/cray-bos/post_install.backup_2023-04-13-13:56:24
Creating manual etcd backup for 'cray-power-control' named 'post_install.backup_2023-04-13-13:56:26'.
Taking snapshot from cray-power-control-bitnami-etcd-2...
Pushing newly …
```

Bitnami chart changes for script taking manual etcd backup (CASMPET-6418)

---

operations/configuration_management/Enable_Ansible_Profiling.md

CASMCMS-8312: Add info on Ansible memory profiling for CFS

---

operations/README.md
operations/System_Recovery/System_Recovery.md
operations/kubernetes/Restore_Postgres.md
operations/package_repository_management/Nexus_Service_Recovery.md
operations/security_and_authentication/Keycloak_Service_Recovery.md
operations/security_and_authentication/Vault_Service_Recovery.md
operations/spire/Spire_Service_Recovery.md

Fixing up some links that broke with a recent PR, and doing other minor linting.
[1.4 backport PR](https://github.com/Cray-HPE/docs-csm/pull/3647)
No earlier backports needed.

CASMINST-6222: System recovery-related linting and link fixing

---

scripts/operations/system_recovery/import_bos_sessiontemplates.py

Small adjustment to the BOS import tool so that it will not overwrite existing session templates on the live system. Instead it will print a message explaining the situation and skip the import of that template.

CASMCMS-8538: BOS import tool: Do not overwrite existing templates

---

install/pre-installation.md
update_product_stream/README.md

Add a docs solution for copying CANU into the sp3 directory.
Relates to: https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5206

CASMTRIAGE-5206 add instructions for updating canu RPM for sle-15sp3 repository

---

install/pre-installation.md
update_product_stream/README.md

Reverts Cray-HPE/docs-csm#3660

Revert "CASMTRIAGE-5206 add instructions for updating canu RPM for sle-15sp3 repository"

---

install/scripts/csm_services/steps/5.setup_nexus.yaml
upgrade/Stage_0_Prerequisites.md

Relates to: https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5206

update locations of canu cp instructions

---

operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md

The 'Delete the NMN MAC and IP addresses each node in the blade from the HSM.' step in the 'Removing a Liquid-cooled blade from a System' procedure doesn't actually do anything.
Updated embedded script to include the step to actually delete the record from SMD ethernetInterfaces.

CASMINST-6237 - Fix error in the liquid cooled blade removal procedure

---

operations/iuf/workflows/configuration.md
operations/iuf/workflows/deploy_product.md
operations/iuf/workflows/image_preparation.md
operations/iuf/workflows/managed_rollout.md
operations/iuf/workflows/management_rollout.md
operations/iuf/workflows/product_delivery.md
operations/iuf/workflows/validate_deployment.md

CASMINST-6230 Refer admins to the new Software Stack Guide

CASMINST-6230 Refer admins to the new Software Stack Guide

---

install/common-pre-install/hpcm_installation-cpi.md
install/install_csm_services.md
install/scripts/craycli_init.py
operations/network/management_network/README.md
operations/network/management_network/transceiver_cable_guide.md
operations/node_management/Defragment_NID_Numbering.md
scripts/cubs_tool.py
scripts/operations/system_recovery/import_cfs_data.py
upgrade/Stage_0_Prerequisites.md
upgrade/scripts/common/ncn-rebuild-common.sh
upgrade/scripts/sls/csm_1_2_upgrade/sls_updates.py
upgrade/scripts/sls/expert_mode.md
upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
workflows/iuf/operations/management-nodes-rollout/management-nodes-rollout.yaml
workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml

Just good old-fashioned linting. 
[1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3673)
[1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3674)
No earlier backports needed (the content being fixed either did not exist or did not have the problems in prior versions).

CASMINST-6234: Correcting typos and other linting

---

operations/CSM_product_management/Post_Install_Customizations.md

The current post-install customization process would override existing cached manifest configmap. This PR preserves existing configmap during post-install customization.

CASMTRIAGE-5234: preserve existing configmap during customization

---

update_product_stream/README.md
upgrade/Stage_0_Prerequisites.md
upgrade/scripts/upgrade/prepare-assets.sh

Relates to: https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5240

changes to copy the canu rpm into the correct place

---

upgrade/scripts/k8s/tds_lower_cpu_requests.sh

Added sma-dashbaords to upgrade script. 
https://github.hpe.com/hpe/hpc-car-sma-opensearch/pull/12

CASMSMF-7177 added sma-dashboards settings

---

operations/iuf/stages/management_nodes_rollout.md
operations/iuf/workflows/management_rollout.md

Fix IUF management-nodes-rollout doc links to Kubernetes (stage_1) upgrade docs. The links broke when the storage node upgrade was removed from CSM 1.4 upgrade and the Kubernetes upgrade moved to stage_1. These links were referencing the incorrect location.

CASMINST-6252 fix IUF management-nodes-rollout doc links to Kubernetes (stage_1) upgrade docs

---

operations/firmware/FASUpdate_Script.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md

Update to token code plus added more references to the new FAS Update Script and revised some output
Resolves:
CASMTRIAGE-5248

CASMTRIAGE-5248 - FAS Update Script - release 1.4

---

operations/firmware/FASUpdate_Script.md
operations/firmware/FAS_Recipes.md
operations/firmware/FAS_Use_Cases.md
operations/firmware/Update_Firmware_with_FAS.md

Update to token code plus added more references to the new FAS Update Script and revised some output
Resolves:
CASMTRIAGE-5248

CASMTRIAGE-5248 - FAS Update Script - main

---

operations/bare_metal/Change_River_BMC_Credentials.md

CASMINST-6255 Update Change_River_BMC_Credentials.md

---

background/ncn_kernel.md

New kernel for 1.5.
Also fix incorrect major/minor. 5.5.14.21 is not a version.

MTL-2144 New kernel

---

operations/README.md

I noticed that the VCS backup/restore procedure was not included in the list of system restore procedures. This adds it.
[1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3724)
[1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3725)
No earlier backports needed as the system restore procedure list did not exist in previous versions.

CASMCMS-8569: Add link to VCS backup/restore to system restore link list

---

workflows/ncn/hooks/after-each/ensure-csm-rpms-installed.yaml
workflows/ncn/hooks/after-each/update-bss-no-wipe.yaml
workflows/ncn/hooks/after-each/update-node-label.yaml
workflows/ncn/hooks/after-each/wait-for-cfs-after-rebuild.yaml
workflows/ncn/hooks/before-all/install-csi.yaml
workflows/ncn/hooks/before-all/move-critical-singleton-pods.yaml
workflows/ncn/hooks/before-each/cos-prechecks-for-worker-reboots.yaml
workflows/ncn/hooks/before-each/ensure-critical-pods-are-running.yaml
workflows/ncn/hooks/before-each/ensure-etcd-pods-are-healthy.yaml
workflows/ncn/hooks/before-each/ensure-pg-pods-are-healthy.yaml
workflows/ncn/hooks/before-each/force-time-sync.yaml
workflows/templates/after-all-hooks.yaml
workflows/templates/after-each-hooks.yaml
workflows/templates/before-all-hooks.yaml
workflows/templates/before-each-hooks.yaml
workflows/templates/drain-worker.yaml

1. there are some TOKEN missing
2. the step name used to be:
now it is:

CASM-4204 fix-pack

---

operations/system_management_health/Grafana_Dashboards_by_Component.md

CASMMON-298 SMF Kafka server and zookeeper grafana dashboards - release/1.4 branch

---

operations/system_management_health/Grafana_Dashboards_by_Component.md

CASMMON-298 SMF Kafka server and zookeeper grafana dashboards

---

operations/system_management_health/Grafana_Dashboards_by_Component.md

CASMMON-298 SMF Kafka server and zookeeper grafana dashboards - release/1.3 branch

---

upgrade/scripts/common/upgrade-state.sh
upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh

NOTE: we don't need to backport this to main/1.5 branch cause we won't need this script there

CASMTRIAGE-5281 make sure we remove temp files

---

RELEASE_NOTES.md

Document the WLM workarounds needed for Alice IUF installation.

ALT-307 Add WLM workarounds for Alice

---

troubleshooting/README.md
troubleshooting/known_issues/sms_health_check.md

Minor linting and adding a link to the page to the troubleshooting index.
The 1.4 backport PR for this is going to be combined with the PR for [CASMTRIAGE-5317](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5317), since it is editing the same page.

CASMINST-6294: Linting of and linking to SMS health check troubleshooting page

---

troubleshooting/index.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3755 (for the parts that apply to the 1.2 branch)

CASMINST-6294: Linting of troubleshooting index

---

operations/UAS_user_and_admin_topics/Troubleshoot_Common_Mistakes_when_Creating_a_Custom_End-User_UAI_Image.md
operations/node_management/Move_a_Standard_Rack_Node_SameRack_SameHSNPorts.md
operations/node_management/Update_Compute_Node_Mellanox_HSN_NIC_Firmware.md
operations/resiliency/Resiliency_Testing_Procedure.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3746
(but just the linting part)

CASMCMS-8593: Linting

---

introduction/deprecated_features/README.md
operations/UAS_user_and_admin_topics/Customize_End-User_UAI_Images.md
operations/UAS_user_and_admin_topics/Troubleshoot_Common_Mistakes_when_Creating_a_Custom_End-User_UAI_Image.md
operations/boot_orchestration/Check_the_Progress_of_BOS_Session_Operations.md
operations/boot_orchestration/Clean_Up_After_a_BOS-BOA_Job_is_Completed_or_Cancelled.md
operations/boot_orchestration/Manage_a_BOS_Session.md
operations/image_management/Create_UAN_Boot_Images.md
operations/node_management/Add_a_Standard_Rack_Node.md
operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System_Using_SAT.md
operations/node_management/Move_a_Standard_Rack_Node_SameRack_SameHSNPorts.md
operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System.md
operations/node_management/Removing_a_Liquid-cooled_blade_from_a_System_Using_SAT.md
operations/node_management/Removing_a_Standard_Node_from_a_System.md
operations/node_management/Replace_a_Compute_Blade.md
operations/node_management/Replace_a_Compute_Blade_Using_SAT.md
operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
operations/node_management/Swap_a_Compute_Blade_with_a_Different_System_Using_SAT.md
operations/node_management/Update_Compute_Node_Mellanox_HSN_NIC_Firmware.md
operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md
operations/power_management/Prepare_the_System_for_Power_Off.md
operations/power_management/Shut_Down_and_Power_Off_Compute_and_User_Access_Nodes.md
operations/resiliency/Resiliency_Testing_Procedure.md
operations/security_and_authentication/Add_LDAP_User_Federation.md
operations/security_and_authentication/Resync_Keycloak_Users_to_Compute_Nodes.md
troubleshooting/cms_barebones_image_boot.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3746

CASMCMS-8593: Update to reflect BOS v1 removal in CSM 1.6, BOS CLI default change in CSM 1.4

---

operations/multi-tenancy/Modify_a_Tenant.md

Adds a section to "Modifying a Tenant" docs to include the steps that should be taken in BOS when moving a component from one tenant to another.
Relates to:
- CASMCMS-8453

CASMCMS-8453: Add procedure for changing node tenant's in BOS

---

workflows/iuf/operations/ims-upload.yaml

This reverts commit ab78e5bf62142c580ea19b2969119273fa16ceee.

Revert "CASM-3868: Update ims-load-artifacts container version (#3722)"

---

glossary.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3763

CASMINST-6300: Linting & glossary improvements

---

update_product_stream/README.md
upgrade/scripts/upgrade/prepare-assets.sh

Conditionally cp canu RPM from sle-15sp4 to sle-15sp3 only during CSM 1.3.2 install/upgrade.
Relates to CASMINST-6307 
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6307

CASMINST-6307

---

upgrade/1.4.1/README.md
upgrade/scripts/upgrade/upload-ncn-images.sh

This is the initial draft of 1.4.1 patch instructions. These are the same as 1.3.1 patch instructions except there is an added step to upload ncn images and update the cray-product-catalog. This is necessary in order for IUF to be able to find the images it should customize for product updates/upgrades. Without uploading the images and editing the product-catalog, IUF does not know which images it should use.

CASMTRIAGE-5330 make initial 1.4.1 patch instructions, add step to upload-ncn-images

---

workflows/iuf/operations/extract-release-distributions.yaml
workflows/iuf/operations/ims-upload.yaml
workflows/iuf/operations/loftsman-manifest-deploy.yaml
workflows/iuf/operations/loftsman-manifest-upload/loftsman-manifest-upload-template.yaml
workflows/iuf/operations/managed-nodes/managed-nodes-rollout.yaml
workflows/iuf/operations/nexus-setup/nexus-docker-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-helm-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-rpm-upload-template.yaml
workflows/iuf/operations/nexus-setup/nexus-setup-template.yaml
workflows/iuf/operations/preflight-checks-for-services.yaml
workflows/iuf/operations/prepare-images/prepare-managed-images-template.yaml
workflows/iuf/operations/prepare-images/prepare-management-images-template.yaml
workflows/iuf/operations/s3-upload/s3-upload-template.yaml
workflows/iuf/operations/update-cfs-config/update-managed-cfs-config.yaml
workflows/iuf/operations/update-cfs-config/update-management-cfs-config.yaml
workflows/iuf/operations/vcs-update/vcs-update-working-branch.yaml
workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml

[CASM-3946](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3946)
Automation: IUF error messages must clearly provide root causes and context information
Changes in this PR address the following use cases for IUF - 
- As an admin, I want to have more contextual information from the result of prepare-images stage so I can do deployments manually
- As an admin, I want to have better logging information about what failed and what I need to fix
- [] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
[2]: …

CASM-3946 improving iuf messages

---

README.md
glossary.md
operations/README.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3777

CASMINST-6338: Add missing terms to glossary; add missing links to operations index

---

README.md
glossary.md
operations/README.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3777

CASMINST-6338: Add missing terms to glossary; add missing links to operations index; add links to auto-generated API docs

---

background/ncn_kernel.md

Updates ncn_kernel.md with latest kernel for 1.5 development.

MTL-2154: Update ncn_kernel.md

---

install/common-pre-install/hpcm_installation-cpi.md
operations/network/management_network/aruba_split_cables.md

Minor MitchLint.
1.4 backport: https://github.com/Cray-HPE/docs-csm/pull/3792
No others needed -- the pages being fixed only exist in 1.4 and main.

CASMINST-6343: Linting

---

operations/README.md

I found more pages which are missing from the operations index page. This PR adds them to the appropriate sections of the index.
Backports:
- [1.4](https://github.com/Cray-HPE/docs-csm/pull/3785)
- [1.3](https://github.com/Cray-HPE/docs-csm/pull/3786)
- [1.2](https://github.com/Cray-HPE/docs-csm/pull/3787)
- [1.0](https://github.com/Cray-HPE/docs-csm/pull/3788)

CASMINST-6340: Add missing links to operations index

---

operations/power_management/Prepare_the_System_for_Power_Off.md

Remove the references to CRUS session checks from sections regarding `sat bootsys`. The CRUS session checker functionality has been removed from SAT since CRUS is deprecated.

CRAYSAT-1671: Remove references to CRUS from SAT sections

---

upgrade/1.3.2/README.md

Update patch README.md to include 1.3.0 as a patch source for 1.3.2.

---

workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml
workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml
workflows/iuf/operations/management-nodes-rollout/verify-images-and-configuration.yaml

our refactoring introduced some non-exist dep and this PR is removing those

CASMINST-6351

---

upgrade/scripts/upgrade/prerequisites.sh
upgrade/scripts/upgrade/util/upgrade-cray-nls.sh

In CSM 1.4.1, argo server versions were upgraded for CVE remediation; however, crds during the upgrade need to re-labeled so that helm can manage the upgrade. In addition, the wait time needs to be increased as it seemed to take longer than 90 seconds when upgrading argo in fanta.

CASMINST-6375: fix upgrade_nls errors

---

operations/iuf/IUF.md
operations/iuf/examples/iuf_abort.md
operations/iuf/examples/iuf_activity.md
operations/iuf/examples/iuf_restart.md
operations/iuf/examples/iuf_resume.md
operations/iuf/examples/iuf_workflow.md

Several changes have been made to IUF since the docs were last updated, so reflect the changes in the documentation.

SCICD-711: Reflect Recent IUF Changes

---

operations/iuf/examples/iuf_workflow.md

Reflect the addition of script_stdout to the workflow output.

SCICD-732: Workflow Output

---

upgrade/scripts/upgrade/util/upgrade-cray-nls.sh

cray-nls upgrade in 1.5 involves new postgres operator, which requires cray-psp to be upgraded first. This PR includes cray-psp when upgrading cray-nls charts.

CASMPET-6599: add cray-psp chart dependency for nls upgrade

---

upgrade/scripts/upgrade/prerequisites.sh

CASMPET-6173: Updates to prerequisites.sh to aide cert-manager changes

---

install/deploy_non-compute_nodes.md

CASMINST-6419 Update deploy_non-compute_nodes.md

---

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
workflows/iuf/hooks/master-host-hook-script.yaml

[CASM-4313](https://jira-pro.it.hpe.com:8443/browse/CASM-4313)
From the output of IUF commands, John has suggested some changes that would improve messages that user sees on screen. Out of this some changes needs to be done in docs-csm templates and scripts. This JIRA is to handle those changes.
https://rndwiki-pro.its.hpecorp.net/display/~john.navitsky@hpe.com/IUF+Stage+Output#IUFStageOutput

CASM-4313 Improve logging based on IUF stage output

---

upgrade/scripts/upgrade/prerequisites.sh

After postgres operator is upgraded, it takes quite some time for postgres pods to be ready. This PR works around the issue by forcing the rollout of cray-nls-postgres statefulset, and then validate the readiness toward the end.

CASMPET-6602: postgres upgrade timing

---

workflows/iuf/operations/management-nodes-rollout/management-storage-nodes-rollout.yaml
workflows/iuf/operations/management-nodes-rollout/management-two-master-nodes-rollout.yaml
workflows/iuf/operations/management-nodes-rollout/management-worker-nodes-rollout.yaml

Management-nodes-rollout now takes HSM role_subroles or hostnames. This PR adds logic to storage and master rollouts to make sure the correct nodes are rolled out depending on input.
This PR also adds logic for calling the storage node upgrade workflow.
The logic for rebuilding hostnames was tested on Mug.

CASMPET-6610 add logic for rolling out hostnames in management-nodes-rollout

---

upgrade/scripts/upgrade/prerequisites.sh

CASMPET-6616: helm remove/list check bugfix

---

upgrade/scripts/upgrade/prerequisites.sh

Added a few clean-ups to prerequisites script:
- Remove spire upgrade
- Remove VCS backup
- Consistent logging for cert-manager & cray-nls upgrade
- Install platform-utils, goss-servers rpms and restart goss-servers service

CASMPET-6619: prereqs script cleanup

---

upgrade/scripts/upgrade/prerequisites.sh

Install csm-testing, platform-utils, goss-servers RPMs on ncn-w001, so that health check tests running from w001 will not fail before NCN node images are upgraded.

CASMPET-6635: install RPMs on ncn-w001

---

install/install_csm_services.md

Update the name of the spire-update-bss job to cray-spire-update-bss in the documentation.

CASMINST-6442: Update spire-update-bss job name to cray-spire-update-bss

---

upgrade/scripts/upgrade/upload-ncn-images.sh

upload-ncn-images.sh is run as part of 1.4.1 patch. This script will run for many minutes before exiting if CSM_RELEASE variable is not set. This adds an early exit to the script if CSM_RELEASE is not set.

CASMTRIAGE-5504 exit upload-ncn-images.sh if CSM_RELEASE is not set

---

upgrade/scripts/upgrade/prerequisites.sh

This PR enables goss-servers after upgrading them on the primary node and ncn-w001 so that goss-servers will auto restart after node rebooting.

CASMPET-6644: enable goss-servers for auto-restart

---

operations/package_repository_management/Manage_Repositories_with_Nexus.md
operations/package_repository_management/Nexus_Configuration.md
operations/package_repository_management/Package_Repository_Management.md
operations/package_repository_management/Package_Repository_Management_with_Nexus.md
operations/package_repository_management/Repair_Yum_Repository_Metadata.md
operations/package_repository_management/Troubleshoot_Nexus.md

(cherry picked from commit 636f4344f5f7e503b2442042b80d579175f9f33f)
Backport of https://github.com/Cray-HPE/docs-csm/pull/3872

CASMINST-6468: Linting and minor corrections

---

operations/CSM_product_management/Post_Install_Customizations.md
operations/configuration_management/Version_Control_Service_VCS.md
operations/conman/Access_Console_Log_Data_Via_the_System_Monitoring_Framework_SMF.md
operations/kubernetes/Restore_Postgres.md
operations/package_repository_management/Nexus_Deployment.md
operations/security_and_authentication/Add_LDAP_User_Federation.md
operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
operations/system_management_health/Access_System_Management_Health_Services.md
operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md

(cherry picked from commit b926fc86aa5939c9dbe6fcf905323f350569297a)
Backport of https://github.com/Cray-HPE/docs-csm/pull/3864

CASMINST-6465: Linting and corrections

---

operations/node_management/Enable_ipmi_access_on_HPE_iLO_BMCs.md

Correcting the output in the step to show that IPMI is enabled.
[CASMINST-6482](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6482)
Relates to:
- https://github.com/Cray-HPE/docs-csm/pull/3896

CASMINST-6482: fixed protocolenabled parameter value in output

---

operations/configuration_management/Track_the_Status_of_a_Session.md
upgrade/1.4.1/README.md

Populate the "Bug Fixes and Improvements" section within the 1.4.1 release notes.

CASMINST-6480 - listing of the fixes included in the 141 release notes

---

upgrade/scripts/upgrade/prerequisites.sh

spire-postgres is in a SyncFailed state by this point. It needs to be rolled to resolve the issue.

CASMINST-6484 Restart spire-postgres

---

.spelling
operations/CSM_product_management/Post_Install_Customizations.md
operations/CSM_product_management/Redeploying_a_Chart.md
operations/configuration_management/Version_Control_Service_VCS.md
operations/hmcollector/adjust_hmcollector_resource_limits_requests.md
operations/node_management/Add_Remove_Replace_NCNs/Redeploy_Services.md
operations/node_management/Add_TLS_Certificates_to_BMCs.md
operations/package_repository_management/Nexus_Service_Recovery.md
operations/security_and_authentication/Add_LDAP_User_Federation.md
operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
operations/security_and_authentication/Keycloak_Service_Recovery.md
operations/security_and_authentication/Update_Default_Air-Cooled_BMC_and_Leaf_BMC_Switch_SNMP_Credentials.md
operations/security_and_authentication/Update_Default_ServerTech_PDU_Credentials_used_by_the_Redfish_Translation_Service.md
operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md
operations/security_and_authentication/Vault_Service_Recovery.md
operations/spire/Restore_Spire_Postgres_without_a_Backup.md
operations/spire/Spire_Service_Recovery.md
scripts/operations/kubernetes/latest_chart_manifest.sh

backport of https://github.com/Cray-HPE/docs-csm/pull/3880

CASMINST-6470: Update chart redeploy procedure to prevent overwriting existing manifests while still using correct versions and customizations

---

.spelling
operations/network/management_network/firmware/update_management_network_firmware.md

Upgrade Aruba firmware instructions and add current levels of sw to the table showing the supported sw versions.
Relates to: https://jira-pro.it.hpe.com:8443/browse/CASMNET-2114

CASMNET-2114 | main | upgrade aruba switch firmware instructions

---

operations/kubernetes/Restore_Postgres.md
update_product_stream/README.md

As always, I noticed minor doc problems when working on the latest runthrough of the disaster recovery procedure on wasp. This PR corrects them.
Backport PRs:
* [1.4](https://github.com/Cray-HPE/docs-csm/pull/3908)
* 1.3 (no backport PR because I accidentally pushed the commit directly to the release/1.3 branch -- I am surprised it didn't balk)
* [1.2](https://github.com/Cray-HPE/docs-csm/pull/3909)
* [1.0](https://github.com/Cray-HPE/docs-csm/pull/3910)

CASMINST-6503: Linting

---

upgrade/1.3.4/README.md

Update the yq4 command as the eval was missing for the yq4 version of yq
This command is used as part of updating of customizations.yaml.

CASMTRIAGE-5551: Update yq4 command for 1.3.4 upgrade

---

operations/multi-tenancy/Overview.md

Update 'feature preview' language regarding use of multi-tenancy features.

CASMINST-6301: Update 'feature preview' banner for CSM multi-tenancy

---

upgrade/scripts/ceph/create_rgw_buckets.sh
upgrade/scripts/ceph/csm-1.5-new-buckets.yml
upgrade/scripts/upgrade/csm-upgrade.sh

Add step to add new buckets for CSM 1.5 prior to services upgrade
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6665
Tested on starlord:
```
ncn-m001:~/brad # > /etc/cray/upgrade/csm/csm-/ncn-m001/state; ./foo.sh
************
*** NOTE ***
************
LOG_FILE is not specified; use default location: /root/brad/output.log
====> PRE_CSM_SERVICES_UPGRADE_BUCKETS ...
====> PRE_CSM_SERVICES_UPGRADE_BUCKETS has been completed
```
```
ncn-s001 IP address is 10.252.1.10
Host ncn-s001 not found in /root/.ssh/known_hosts
Host 10.252.1.10 not found in /root/.ssh/known_hosts
ncn-s001.nmn IP address is 10.252.1.10
Host ncn-s001.nmn not found in /root/.ssh/known_hosts
/root/.ssh/known_hosts updated.
Original contents retained as /root/.ssh/known_hosts.old
ncn-s002 IP address is 10.252.1.11
Host …
```

Add step to create new buckets on upgrade (CASMPET-6665)

---

workflows/ncn/worker/worker.drain.yaml

After a change to iuf-base-template that this the update bss and cfs step were using, these steps no longer worked. As this workflow is sometime run outside of IUF, it would be good for it to reference a different workflowTemplate. It now uses ssh-template and the steps run successfully. This was tested on Fanta during management-nodes-rollout.

CASMINST-6486 have update-bss and update-cfs use ssh-template

---

upgrade/Stage_1.md
upgrade/Stage_2.md
upgrade/Stage_3.md

CASMTRIAGE-5585 put csm validation step at the end of upgrade

---

operations/UAS_user_and_admin_topics/Troubleshoot_Common_Mistakes_when_Creating_a_Custom_End-User_UAI_Image.md

Fixing a couple of minor typos for [CASMINST-6502](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6502).
Relates to:
-https://github.com/Cray-HPE/docs-csm/pull/3925

CASMINST-6502: Minor typos

---

upgrade/1.3.4/README.md

CASMTRIAGE-5607:  add a note about zypper output

---

troubleshooting/known_issues/qlogic_driver_crash.md

Mention the `pcie` ports, and include some extra examples and notes.

CASMNET-2127 Amendment

---

operations/power_management/Prepare_the_System_for_Power_Off.md

Use `canu` by default to check if switches are reachable. If `canu` isn't available, fix and update the manual process given in the procedure.
We may want to get a CANU/network person on this PR to review it as well.

CRAYSAT-1712: Update switch checking in power off procedure

---

operations/multi-tenancy/Create_a_Tenant.md
operations/multi-tenancy/Modify_a_Tenant.md
operations/multi-tenancy/Tapms.md

Add documentation for tapms' new forcepoweroff field.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6667
N/A
Low
* Nothing

Add documentation about forcepoweroff behavior in tapms (CASMPET-6667)

---

operations/multi-tenancy/Overview.md
operations/multi-tenancy/Tapms.md
operations/multi-tenancy/Vault.md

CASMPET-6568 Add TAPMS Vault integration documentation.

---

operations/README.md
operations/boot_orchestration/Multi_tenancy_with_BOS.md

Adds BOS documentation on the impacts of multi-tenancy
Relates to:
- CASMCMS-8547

CASMCMS-8547: Add documentation for BOS multi-tenancy

---

background/ncn_kernel.md

Relates to:
- https://jira-pro.it.hpe.com:8443/browse/MTL-2159
- https://github.com/Cray-HPE/metal-provision/pull/234
- https://github.com/Cray-HPE/node-images/pull/804

MTL-2159 kernel update

---

install/common-pre-install/hpcm_installation-cpi.md
install/common-pre-install/pre-installation-cpi.md

To replace the static username and password reference - "initial0"
JIRA: [CASMTRIAGE-5609](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5609)

CASMTRIAGE-5609: Replace static password references

---

install/pre-installation.md

Upload images into pit-nexus before booting management-nodes. This allows storage nodes to use container images in pit-nexus when bringing up the ceph cluster. 
This was tested on Redbull and Vshasta2- caleb.

CASMPET-6650 MTL-2032 Add Step to Upload Images and RPMs to PIT Nexus

---

upgrade/scripts/k8s/upgrade_control_plane.sh

Fix coredns IPBO issue on upgrade, re-tag to former image path to support master node upgrade prior to execution of upgrade_control_plane.sh.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5632
drax:
```
ncn-m002:~/brad # kubectl get configmap kubeadm-config -n kube-system -o yaml
apiVersion: v1
data:
ClusterConfiguration: |
apiServer:
certSANs:
- 10.252.1.2
- 10.252.1.5
extraArgs:
api-audiences: api,istio-ca
authorization-mode: Node,RBAC
encryption-provider-config: /etc/cray/kubernetes/encryption/current.yaml
oidc-ca-file: /etc/kubernetes/pki/oidc.pem
oidc-client-id: kubernetes-api-oidc-client
oidc-groups-claim: groups
oidc-issuer-url: https://api-gw-service-nmn.local/keycloak/realms/shasta
oidc-username-claim: name
runtime-config: …
```

Edit kubeadm config with coredns image repo on upgrade (CASMTRIAGE-5632)

---

install/pre-installation.md

Reverts Cray-HPE/docs-csm#3939

Revert "CASMPET-6650 MTL-2032 Add Step to Upload Images and RPMs to PIT Nexus"

---

workflows/ncn/worker/worker.drain.yaml

Export TOKEN before running csi command. This was not done in during the worker node rebuild when updating bss parameters with csi and it stopped the argo workflow.

CASMTRAIGE-5643 export token before running csi command

---

operations/CSM_product_management/Redeploying_a_Chart.md

A problem was found with the chart redeploy procedure in cases where the manifest obtained from Loftsman specifies a nonexistent chart location (even if a good location is specified on the deploy command line). This PR updates the relevant procedure to remove the chart sources from the manifest being deployed, forcing it to only consider the source specified on the command line.
- Resolves [CASMINST-6534](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6534)
- [1.4 backport](https://github.com/Cray-HPE/docs-csm/pull/3965)
- [1.3 backport](https://github.com/Cray-HPE/docs-csm/pull/3966)
- [1.2 backport](https://github.com/Cray-HPE/docs-csm/pull/3967)
- [1.0 backport](https://github.com/Cray-HPE/docs-csm/pull/3968)
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentati …

CASMINST-6534: Remove chart source fields from manifest, to force it to use the source specified on the loftsman command line

---

install/scripts/craycli_init.py

This changes the logic in the get sls portion of the craycli_init.py so the token it gets is for the nmn gateway and not for the cmn gateway. This should allow for the keycloak user to be setup using the cmn but then also allow the section to get sls to fuction.

CASMTRIAGE-5626: Change logic in craycli_init.py for cmn/nmn seperation

---

upgrade/scripts/upgrade/prerequisites.sh

cray-cmstools-crayctldeploy rpm needs to be updated on both primary node and ncn-w001 to run updated 1.5 CMS tests.

CASMINST-6517: update cray-cmstools-crayctldeploy rpm

---

install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml

CASMTRIAGE-5650

---

install/configure_administrative_access.md
install/deploy_final_non-compute_node.md
install/deploy_non-compute_nodes.md
install/pre-installation.md
install/prepare_compute_nodes.md
install/re-installation.md

Several links for the `install/csm-install/README.md` file are broken. This fixes the links in the `install/` folder.

CASMINST-6536 Fix links

---

upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
workflows/base/echo.template.argo.yaml
workflows/base/iufBase.template.argo.yaml
workflows/base/kubectlAndCurl.template.argo.yaml
workflows/base/sat-general-iuf.template.argo.yaml
workflows/base/ssh.template.argo.yaml
workflows/base/update-product-catalog.template.argo.yaml
workflows/ncn/worker/worker.rebuild.yaml
workflows/templates/base/echo.template.argo.yaml
workflows/templates/base/iufBase.template.argo.yaml
workflows/templates/base/kubectlAndCurl.template.argo.yaml
workflows/templates/base/sat-general-iuf.template.argo.yaml
workflows/templates/base/ssh.template.argo.yaml
workflows/templates/base/update-product-catalog.template.argo.yaml
workflows/templates/wipe-and-reboot-worker.yaml

CASMPET-6671 move base templates from nls

---

install/csm-install/README.md
install/pre-installation.md

Upload RPMs and container images to pit nexus.
This sets the stage for image changes that pull RPMs and images instead of baking them in.
This new script must be invoked after `pit-init`, specifically after the `customizations.yaml` file has been generated and modified by the user.

CASMPET-6650 MTL-2032

---

background/ncn_networking.md
install/deploy_final_non-compute_node.md
operations/hardware_state_manager/Set_BMC_Management_Role.md
operations/node_management/Set_Gigabyte_Node_BMC_to_Factory_Defaults.md
operations/security_and_authentication/Update_Default_Air-Cooled_BMC_and_Leaf_BMC_Switch_SNMP_Credentials.md
operations/system_configuration_service/Configure_BMC_and_Controller_Parameters_with_scsd.md
operations/validate_csm_health.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3978

CASMINST-6539: Linting and minor corrections

---

upgrade/Stage_0_Prerequisites.md
upgrade/scripts/common/ncn-rebuild-common.sh
upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
workflows/ncn/storage/common.reboot-node.yaml
workflows/ncn/worker/worker.wipe-and-reboot.yaml

CAST-33404

---

operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md

This mod adds an additional section that describes additional context variables that are exposed by IMS during image customization that pertain to DKMS and multi-arch support.
Documentation changes herein correspond to:
- (CASMCMS-8519)[https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8519]

CASMCMS-8519 Add additional help section for IMS image passthrough variables and how to use them

---

glossary.md
operations/boot_orchestration/BOS_Services.md
operations/boot_orchestration/BOS_Workflows.md
operations/boot_orchestration/Clean_Up_After_a_BOS-BOA_Job_is_Completed_or_Cancelled.md
operations/boot_orchestration/Clean_Up_Logs_After_a_BOA_Kubernetes_Job.md
operations/boot_orchestration/Component_Status.md
operations/boot_orchestration/Components.md
operations/boot_orchestration/Configure_the_BOS_Timeout_When_Booting_Nodes.md
operations/boot_orchestration/Limitations_for_Gigabyte_BMC_Hardware.md
operations/boot_orchestration/Manage_a_BOS_Session.md
operations/boot_orchestration/Manage_a_Session_Template.md
operations/boot_orchestration/Multi_tenancy_with_BOS.md
operations/boot_orchestration/Options.md
operations/boot_orchestration/Rolling_Upgrades.md
operations/boot_orchestration/Session_Templates.md
operations/boot_orchestration/Sessions.md
operations/boot_orchestration/Stage_Changes_with_BOS.md
operations/boot_orchestration/Troubleshoot_Booting_Nodes_with_Hardware_Issues.md
operations/boot_orchestration/Troubleshoot_Compute_Node_Boot_Issues_Related_to_Slow_Boot_Times.md
operations/boot_orchestration/View_the_Status_of_a_BOS_Session.md
operations/hardware_state_manager/Manage_Component_Groups.md

Mostly boring linting, plus added a few entries to the glossary. Finally, backports the content of [CASMCMS-8231](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8231), which was accidentally only added to the 1.3 release branch (I verified with Jason S that this was indeed a mistake).
* [CASMINST-6545](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6545)
* [CASMCMS-8231](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8231)
Backports
* [1.4](https://github.com/Cray-HPE/docs-csm/pull/3995)
* [1.3](https://github.com/Cray-HPE/docs-csm/pull/3996)
* [1.2](https://github.com/Cray-HPE/docs-csm/pull/3997)
* [1.0](https://github.com/Cray-HPE/docs-csm/pull/3998)
[2]: …

CASMINST-6545: Linting + a couple new glossary entries + CASMCMS-8231 backport

---

glossary.md
operations/boot_orchestration/BOS_Services.md
operations/boot_orchestration/BOS_Workflows.md
operations/boot_orchestration/Clean_Up_After_a_BOS-BOA_Job_is_Completed_or_Cancelled.md
operations/boot_orchestration/Clean_Up_Logs_After_a_BOA_Kubernetes_Job.md
operations/boot_orchestration/Component_Status.md
operations/boot_orchestration/Components.md
operations/boot_orchestration/Configure_the_BOS_Timeout_When_Booting_Nodes.md
operations/boot_orchestration/Limitations_for_Gigabyte_BMC_Hardware.md
operations/boot_orchestration/Manage_a_BOS_Session.md
operations/boot_orchestration/Manage_a_Session_Template.md
operations/boot_orchestration/Options.md
operations/boot_orchestration/Rolling_Upgrades.md
operations/boot_orchestration/Session_Templates.md
operations/boot_orchestration/Sessions.md
operations/boot_orchestration/Stage_Changes_with_BOS.md
operations/boot_orchestration/Troubleshoot_Booting_Nodes_with_Hardware_Issues.md
operations/boot_orchestration/Troubleshoot_Compute_Node_Boot_Issues_Related_to_Slow_Boot_Times.md
operations/boot_orchestration/View_the_Status_of_a_BOS_Session.md
operations/hardware_state_manager/Manage_Component_Groups.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3994

CASMINST-6545: Linting + a couple new glossary entries

---

operations/configuration_management/Write_Ansible_Code_for_CFS.md
operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
operations/utility_storage/Troubleshoot_S3FS_Mounts.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/3989

CASMINST-6543: Linting

---

.spelling
background/certificate_authority.md
background/index.md
background/ncn_bios.md
background/ncn_boot_workflow.md
background/ncn_images.md
background/ncn_mounts_and_file_systems.md
background/ncn_networking.md
background/ncn_operating_system_releases.md
background/ncn_plan_of_record.md
operations/UAS_user_and_admin_topics/Troubleshoot_UAIs_with_Administrative_Access.md
operations/firmware/FAS_Admin_Procedures.md
operations/network/Default_IP_Address_Ranges.md
operations/network/customer_accessible_networks/Customer_Accessible_Networks.md
operations/network/management_network/canu_install_update.md
operations/network/metallb_bgp/MetalLB_in_BGP-Mode.md
operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_from_Role.md
operations/node_management/Rebuild_NCNs/Final_Validation_Steps.md
operations/node_management/Rebuild_NCNs/Identify_Nodes_and_Update_Metadata.md
operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
operations/package_repository_management/Nexus_Export_and_Restore.md
operations/package_repository_management/Nexus_Space_Cleanup.md
operations/power_management/Cray_Advanced_Platform_Monitoring_and_Control_CAPMC.md
operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md
upgrade/index.md

Backport of https://github.com/Cray-HPE/docs-csm/pull/4001

CASMINST-6548: Linting
