Cray-HPE/docs-csm

- upgrade/1.0/scripts/upgrade/ncn-upgrade-common.sh
- upgrade/1.0/scripts/upgrade/prerequisites.sh
CASMPET-3025
CASMPET-3060
CASMPET-3065
CASMPET-3066
> Multiple fixes

- operations/node_management/Rebuild_NCNs.md
(cherry picked from commit e1747e43ed7872863aed54b391aeffa39b9b1f36)
> CASMINST-3056 - Update to rebuild doc for ceph nodes

- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
Adding CephNetworkPacketsDropped  alerts as know issues
https://connect.us.cray.com/jira/browse/CASMPET-4917
> CASMPET-4917 CephNetworkPacketsDropped known issue

- upgrade/0.9/csm-0.9.6.md
- upgrade/0.9/csm-0.9.6/README.md
First draft of 0.9.6 doc containing information mostly specific to the application of the Unbound fix.
> 0.9.6 Patch

- background/ncn_boot_workflow.md
- install/redeploy_pit_node.md
- operations/CSM_product_management/Manage_a_Configuration_with_CFS.md
- operations/validate_csm_health.md
This is the csm-1.1 version of this PR: https://github.com/Cray-HPE/docs-csm/pull/49
> CASMINST-3109: Fix broken commands; restore previous commits that were overwritten; linting

- 101-NCN-BOOTING.md
> Revert "CASMINST-3109: Update boot order set instructions"

- operations/security_and_authentication/Add_LDAP_User_Federation.md
Updates to the "Add LDAP User Federation" procedure per CAST-27279 and STP-2890.
> STP-2890: Add LDAP User Federation

- upgrade/1.0/scripts/upgrade/ncn-upgrade-common.sh
- upgrade/1.0/scripts/upgrade/ncn-upgrade-k8s-worker.sh
- upgrade/1.0/scripts/upgrade/prerequisites.sh
CASMPET-4888
CASMINST-3115
CASMINST-3105
CASMINST-3107
> Casminst 3107

- install/deploy_management_nodes.md
Remove unnecessary instructions related to BGP that may cause confusion.
> CASMINST-3004

- Jenkinfile.github
updates for organization of RPMs in artifactory by release version
> updates for organization of RPMs in artifactory by release version

- operations/power_management/Cray_Advanced_Platform_Monitoring_and_Control_CAPMC.md
- operations/power_management/Power_On_Compute_and_IO_Cabinets.md
- operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md
- operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
- operations/power_management/Prepare_the_System_for_Power_Off.md
- operations/power_management/Shut_Down_and_Power_Off_the_Management_Kubernetes_Cluster.md
- operations/power_management/User_Access_to_Compute_Node_Power_Data.md
In operations/power_management topics.
> STP-2897: Changed instances of "Shasta Admin Tookit (SAT) to System Admin Toolkit 

- upgrade/update_management_network.md
Add additional clarification to BGP docs.
> CASMINST-3143

- operations/FAS_Loader/FAS_Loader_Fails.md
Document of steps to fix FAS Loader if it fails on repomd.xml - Added to operations directory
Resolves:
CAST-27463
CASMHMS-5179
> CASMHMS-5179 - FAS Loader Fails

- introduction/PowerDNS_migration.md
- introduction/differences.md
Document introduction of PowerDNS, upcoming DNS record naming changes, and upcoming deprecation of cray-dns-unbound-manager job.
> CASM-2656 - DNS deprecation notice

- upgrade/1.0/scripts/upgrade/ncn-upgrade-ceph-initial.sh
- upgrade/1.0/scripts/upgrade/prerequisites.sh
skip stage1.1 for 10210 upgrade
> Casminst 3195

- upgrade/1.0/scripts/upgrade/prerequisites.sh
> CASMINST-3203 suppress inode xattr messages

- operations/node_management/Rebuild_NCNs.md
This is the csm-1.1 version of this PR: https://github.com/Cray-HPE/docs-csm/pull/155
This is ready for merge pending approvals.
> CASMINST-3198: Corrections and improvements to NCN rebuild procedure

- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
Add specific Shasta v1.3 information to the Cert Renewal docs for Reboot and Vault/Etcd
Resolves
* CASMPET-4962 for 0.9
Cert Renewal doc on release/0.9 branch will cover Shasta v1.4+ and Shasta v1.3
> CASMPET-4962 0.9 : Add Shasta v1.3 NCN Reboot info to cert renewal process and vault check

- operations/image_management/Customize_an_Image_Root_to_Install_Singularity.md
- troubleshooting/index.md
- troubleshooting/pxe_runbook.md
- upgrade/1.0/scripts/upgrade/CASMINST-2689-lib.sh
- upgrade/1.0/scripts/upgrade/prerequisites.sh
Just basic Mitch-lint(TM). No content changes.
> CASMINST-3209: Minor corrections and linting

- install/configure_aruba_aggregation_switch.md
- operations/system_configuration_service/Configure_BMC_and_Controller_Parameters_with_scsd.md
- operations/validate_csm_health.md
- troubleshooting/known_issues/discovery_aruba_snmp_issue.md
Removed manual steps if HMS automation scripts fail.
> Removed manual steps if HMS automation scripts fail.

- install/deploy_management_nodes.md
Clarifying the add unused drive procedure
> CASMINST-3137 Clarify Add Unused Drives to ceph

- install/redeploy_pit_node.md
- operations/node_management/Rebuild_NCNs.md
This should merge the same time as: https://github.com/Cray-HPE/csm-testing/pull/69
> CASMINST-3211, CASMINST-3217 run the renamed CASMINST-2689 script

- operations/system_management_health/Grafterm.md
This change is needed for: https://connect.us.cray.com/jira/browse/CASMMON-98
> CASM-2423 Add documentation for Grafterm tool

- upgrade/index.md
- upgrade/prepare_for_upgrade.md
Change ordering of install so MGMT net is upgraded after RPMs get installed. This will ensure that CANU is available to use.
> Casminst 3233

- install/deploy_management_nodes.md
- operations/network/metallb_bgp/Update_BGP_Neighbors.md
Update path of mellanox_set_bgp_peers.py script to the correct location
> CASMINST-3229 - Update location of the Mellanox BGP script in the docs

- .github/workflows/backport.yaml
This Github action simplifies spawning PR's for release branches. When creating a PR for main branch, assign label(s) such as "backport release/1.0", "release/1.1", etc to the PR:
Once PR for main branch is merged, this action will spawn additional PR's against selected branches:
> CASMINST-3116 Automatic backport of closed PRs to selected branches (main)

- upgrade/1.2/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
This is the 1.2 version of this PR: https://github.com/Cray-HPE/docs-csm/pull/253
> CASMINST-3285: Make upgrade more sophisticated about vault

- RELEASE_NOTES.md
- background/ncn_boot_workflow.md
- install/collecting_ncn_mac_addresses.md
- install/deploy_management_nodes.md
- operations/configuration_management/Version_Control_Service_VCS.md
- operations/firmware/Update_Firmware_with_FAS.md
- operations/kubernetes/Cert_Renewal_for_Kubernetes_and_Bare_Metal_EtcD.md
- operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
- operations/security_and_authentication/Update_NCN_Passwords.md
- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
- operations/utility_storage/Ceph_Daemon_Memory_Profiling.md
- operations/utility_storage/Ceph_Orchestrator_Usage.md
- operations/utility_storage/Troubleshoot_Ceph_MDS_reporting_slow_requests_and_failure_on_client.md
- troubleshooting/known_issues/cfs_sessions_stuck_in_pending.md
- troubleshooting/known_issues/craycli_403_forbidden_errors.md
- upgrade/1.0/Stage_1.md
No content changes -- just classic MitchLint(TM).
> CASMINST-3290: Linting of formatting, spelling, grammar, style, etc.

- glossary.md
- operations/spire/Restore_Spire_Postgres_without_a_Backup.md
- operations/validate_csm_health.md
CASMTRIAGE-2096: Clarify Kubernetes NCNs in topics and add glossary entry csm main
> CASMTRIAGE-2096: Clarify Kubernetes NCNs in topics and add glossary entry csm main

- install/collecting_bmc_mac_addresses.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/393. Cherry-picked from  for branch main.
> [Backport main] CASMTRIAGE-2549

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/ceph/lib/ceph-service-status.sh
- ensure storage cloud init is not in runcmds
- ensure the ceph service enable script is run via runcmds
> CASMINST-3463 - Update storage node runcmds

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/ceph/lib/ceph-service-status.sh
- ensure storage cloud init is not in runcmds
- ensure that the ceph service enable script is run.
> CASMINST-3464 - Update storage node runcmds

- upgrade/1.2/scripts/ceph/lib/ceph-service-status.sh
- fixes a variable in a loop for a known_hosts issue
> CASMINST-3465 - ceph service check script fix

- upgrade/1.2/scripts/ceph/lib/ceph-service-status.sh
- fixes issue with varable and known_hosts
> CASMINST-3465 - Ceph service check fix

- 008-CSM-VALIDATION.md
No real content changes in this PR -- it is typical MitchLint. It corrects several issues noted during the creek upgrade from csm-0.9 to csm-1.0, as well as various other issues I found while making those edits. But these are all issues of formatting, clarification, grammar, organization, etc -- not content issues.
> CASMINST-3445: Minor linting and enhancements to health validation

- upgrade/1.2/Stage_2.md
> port fix to 1.2

- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
Need steps to repair these alerts (fixed in 1.2)
https://connect.us.cray.com/jira/browse/CASMINST-3502
hela
* hela
Alerts cleared after running these documented steps.
No
> Add troubleshooting for CephMgrIsAbsent and CephMgrIsMissingReplicas alerts

- operations/node_management/Build_NCN_Images_Locally.md
This change adds documentation specific to building NCN images locally.
* Related to root work in MTL-1512
* Documentation changes required in MTL-1551
> MTL-1512: Add documentation for building NCN images locally

- upgrade/index.md
CASMINST-3403: Adjust upgrade workflow to reference Getting Started Guide for HFP and then FAS update
> CASMINST-3403: Adjust upgrade workflow to reference Getting Started Guide for HFP and then FAS update

- operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
Add note to rebuild doc indicating how to handle re-running cloud-init if custom keys need to be added after rebuild.
* Resolves [CASMPET-4963](https://connect.us.cray.com/jira/browse/CASMPET-4963)
N/A
N/A
N/A
Low
> Add note to rebuild doc indicating how to handle modified ssh keys

- scripts/operations/configuration/apply_csm_configuration.sh
Fixes three issues with the apply_csm_configuration script
- No longer prints usage message when running without arguments
- No longer requests git credentials when running outside the home directory
- No longer breaks when the cli format is not set to json
* Resolves CASMTRIAGE-2736
* Wasp
Successfully ran the script using a setup that was hitting all three of these issues.
None
> CASMTRIAGE-2736: Fix apply_csm_configuration json parsing and git auth

- operations/validate_csm_health.md
ncnhealth check script name should be updated correctly .https://github.com/Cray-HPE/docs-csm/blob/release/1.2/operations/validate_csm_health.md --> 1.2 OPTIONAL Check of ncnHealthChecks Resources
ncn# /opt/cray/platform-utils/ncnHealthCheck.sh -s ncn_uptimes
ncn# /opt/cray/platform-utils/ncnHealthCheck.sh -s node_resource_consumption
ncn# /opt/cray/platform-utils/ncnHealthCheck.sh -s pods_not_running
It should be updated with correct name ncnHealthChecks.sh .
* Merge …
> Casminst 3552

- install/redeploy_pit_node.md
- scripts/cc_ntp.py
- scripts/chrony.conf.cray.tmpl
> CASMINST-3489 keep ntp template local and copy into place

- upgrade/1.0.1/README.md
fixes for storage nodes' ssh key is not included in the doc. This is required for systems upgraded from 0.9 to 1.0. fresh install of 1.0 should be fine.
* `fanta`
- Were the install/upgrade-based validation checks/tests …
> add missing steps in 1.0.1 patch upgrade

- upgrade/1.0/scripts/ceph/ceph-upgrade.sh
Add step to detect active cephfs clients before mds upgrade.
* Resolves [CASMINST-3618](https://connect.us.cray.com/jira/browse/CASMINST-3618)
script contents tested on pepsi
pepsi
```
ncn-s001:~/bklein # ./foo.sh
ERROR: The following CephFS pvcs currently have active clients and those clients
MUST be scaled down in order to continue with this upgrade without data
corruption:
ldms-sms-smpl-pvc
cray-tftp-shared-pvc
ldms-sms-aggr-mellanox-pvc
ldms-sms-aggr-pvc
ldms-compute-aggr-pvc
ldms-compute-aggr-pvc
ldms-sms-aggr-pvc
slingshot-fabric-manager-data-claim
slurmdb-backup
ldms-compute-aggr-mellanox-pvc
slurmdb-data
ldms-compute-smpl-pvc
cray-ims-data-claim
cfs-db
slurm-data-pvc
cray-conman-data-claim
capsules-warehouse-server-fs-claim
capsules-dispatch-server-fs-claim
nexus-data …
```
> Add check to halt upgrade if active CephFS clients

- upgrade/1.2/scripts/upgrade/ncn-upgrade-cloud-init.sh
* Add routing for the MTL and K8s networks.
* Resolves [MTL-1564](https://connect.us.cray.com/jira/browse/MTL-1564)
Tested on fanta
> MTL-1564: adjust routes for 1.0 -> 1.2 upgrade

- install/bootstrap_livecd_remote_iso.md
Reference : https://github.com/Cray-HPE/docs-csm/blob/release/1.2/install/bootstrap_livecd_remote_iso.md --> Subsection 3 after applying CSI workaround 
bond0.cmn0 need to be add into the list of below command .
wicked show bond0 bond0.nmn0 bond0.hmn0 bond0.can0 
_How were the changes tested and …
> Add bond0.cmn0 to the list of ip address being checked

- upgrade/1.2/scripts/upgrade/update-customizations.sh
This updates the cray-opa customizations to support custom issuers per
opa policy (CASMPET-5150)
* Resolves [CASMINST-3636](https://connect.us.cray.com/jira/browse/CASMINST-3636)
This change needs to be tested on an upgrade.
> CASMINST-3636 Update cray-opa customizations

- install/prepare_site_init.md
When prepping site-init the fact that the DCLDAP group criemp has been renamed to employee needs to be taken into account
Link to docs:
CSM 1.0 https://github.com/Cray-HPE/docs-csm/blob/release/1.0/install/prepare_site_init.md#create-baseline-system-customizations
linux# yq write -s - -i /mnt/pitdata/prep/site-init/customizations.yaml <<EOF
command: update
path: spec.kubernetes.services.cray-keycloak-users-localize.localRoleAssignments
value:
{"group": "employee", "role": "admin", "client": "shasta"}
{"group": "employee", "role": "admin", "client": "cray"}
{"group": "craydev", "role": "admin", "client": "shasta"}
{"group": "craydev", "role": "admin", "client": "cray"}
{"group": "shasta_admins", "role": "admin", "client": "shasta"}
{"group": "shasta_admins", "role": "admin", "client": …
> Change the DCLDAP group name from criemp to employee (1.0)

- install/prepare_site_init.md
> Change the DCLDAP group name from criemp to employee (1.2)

- troubleshooting/index.md
- troubleshooting/known_issues/wait_for_unbound_hang.md
- Add troubleshooting documentation when verify unbound hangs.
- updated and added docs
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ yes
* Resolves 
CASMINST-3477
- they are doc changes
- Was upgrade …
> CASMINST-3477 - trouble shooting steps adding when verify unbound hangs

- operations/system_management_health/Access_System_Management_Health_Services.md
- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
- operations/validate_csm_health.md
CASMINST-3495: Update info about troubleshooting Prometheus alerts
Documentation only change.
> CASMINST-3495: Update info about troubleshooting Prometheus alerts

- operations/node_management/Configure_NTP_on_NCNs.md
Adds updated NTP quick fixes and general troubleshooting.
* Resolves MTL-1575
* 
Low
> MTL-1575 add update NTP troubleshooting and quick fixes

- upgrade/1.0/scripts/ceph/lib/k8s-scale-utils.sh
Add better idempotency to scale down script, add logic to wait for deployments and statefulsets to scale down before proceeding.
* Resolves [CASMINST-3644](https://connect.us.cray.com/jira/browse/CASMINST-3644)
vshasta
* `vshasta`
```
ncn-m001-23bf8b92:/home/bklein # ./k8s-scale-utils.sh
Taking a snapshot of nexus pvc (20:13:17_12-01-2021-snapshot)
Did not find nexus pod to take snapshot from -- continuing...
Ensuring cray-cfs-api-db deployment in namespace services is scaled from 1 to zero
deployment.apps/cray-cfs-api-db scaled
Ensuring cray-console-node statefulset in namespace services is scaled from 2 to zero
statefulset.apps/cray-console-node scaled
Ensuring cray-console-operator deployment in namespace services is scaled from 1 to zero
deployment.apps/cray-console-operator scaled …
```
> Improve cephfs scale down idempotency with logic to wait for pods to scale down

- install/scripts/csm_services/steps/1.initialize_bootstrap_registry.yaml
> let's hope we don't keep changing/breaking path every other day

- operations/node_management/Rebuild_NCNs/Prepare_Master_Nodes.md
Fix a couple of issues with the rebuild doc when promoting new master
* Resolves [CASMINST-3678](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3678)
N/A
Low risk, already broken
> Fix BSS PUT command and promote script EOF indentation issue

- operations/node_management/Dump_a_Non-Compute_Node.md
- operations/power_management/Prepare_the_System_for_Power_Off.md
- upgrade/prepare_for_upgrade.md
The System Dump Utility (SDU) name is changing to the System Diagnostic Utility (SDU).
* Resolves [STP-3071](https://jira-pro.its.hpecorp.net:8443/browse/STP-3071)
N/A
N/A
N/A
None.
> STP-3071: Updated SDU references

- operations/security_and_authentication/Change_SMNP_Credentials_on_Leaf_Switches.md
- operations/security_and_authentication/Manage_System_Passwords.md
- operations/security_and_authentication/Update_Default_Air-Cooled_BMC_and_Leaf_Switch_SNMP_Credentials.md
- operations/security_and_authentication/Update_NCN_Passwords.md
Adding more information to the "Manage System Passwords" to incorporate newer credential changing procedures and add missing information. More improvements will be required in the future in the Jiras indicated below.
* Resolves [STP-3073](https://jira-pro.its.hpecorp.net:8443/browse/STP-3073)
* Future work required by [CASMNET-979](https://connect.us.cray.com/jira/browse/CASMNET-979) and [CASMHMS-4817](https://connect.us.cray.com/jira/browse/CASMHMS-4817)
* Merge with: https://github.com/Cray-HPE/docs-csm/pull/666
N/A
N/A
N/A
None.
> STP-3073: Updates to password changing procedures

- operations/security_and_authentication/Change_SMNP_Credentials_on_Leaf_Switches.md
- operations/security_and_authentication/Manage_System_Passwords.md
- operations/security_and_authentication/Update_Default_Air-Cooled_BMC_and_Leaf_Switch_SNMP_Credentials.md
- operations/security_and_authentication/Update_NCN_Passwords.md
Adding more information to the "Manage System Passwords" to incorporate newer credential changing procedures and add missing information. More improvements will be required in the future in the Jiras indicated below.
* Resolves [STP-3073](https://jira-pro.its.hpecorp.net:8443/browse/STP-3073)
* Future work required by [CASMNET-979](https://connect.us.cray.com/jira/browse/CASMNET-979) and [CASMHMS-4817](https://connect.us.cray.com/jira/browse/CASMHMS-4817)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/624
N/A
N/A
N/A
None.
> STP-3073: Updates to password changing procedures (1.2)

- install/deploy_final_ncn.md
This is the 1.2 branch version of this 1.0 PR:
https://github.com/Cray-HPE/docs-csm/pull/674
> CASMINST-3714: Linting of redeploy pit node / deploy final NCN page

- upgrade/1.2/scripts/upgrade/update-customizations.sh
When upgrading from 1.0 to 1.2, we need to add the metallb configuration information to customizations.yaml.   This requires a bunch of information about the network configuration.  That information is gathered from SLS which will be required to be updated prior to running this script.
Example of what will be added to customizations.yaml:
```
metallb:
peers:
- peer-address: 10.252.0.2
peer-asn: 65533
my-asn: 65533
- peer-address: 10.252.0.3
peer-asn: 65533
my-asn: 65533
- peer-address: 10.103.0.2
peer-asn: 65533
my-asn: 65536
- peer-address: 10.103.0.3
peer-asn: 65533
my-asn: 65536
address-pools:
- name: hardware-management
protocol: bgp
addresses:
- 10.94.100.0/24
- name: customer-access
protocol: bgp
addresses:
- 10.103.0.160/27
- name: customer-management-static
protocol: bgp …
```
> CASMINST-3617: Add metallb configuration to update-customizations.sh

- install/prepare_site_init.md
* Corrected section formatting 
* Clarified when this procedure should be run
* Added procedure to check current site DNS setting
* Resolves [CASMINST-3412](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3412)
* N/A
> CASMINST-3412 - Correct formatting issue in DNS section of install/prepare_site_init.md

- operations/network/index.md
Fixed the mellanox mgmt switch f/w in docs.
CASMNET-1081
> fix mellanox switch f/w version

- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-worker.sh
* `pepsi`
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
> wait for CPS to come back online instead of failing upgrade script

- upgrade/1.2/Stage_1.md
- upgrade/1.2/scripts/k8s/upgrade_control_plane.sh
Add some error checking during the final upgrade step where we update control plane pods with their new images.
* Resolves [CASMINST-3705](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3705)
* `craystack`
Ran the script in both error and success cases.
N/A
> Improve the control plane pod upgrade step to stop if any errors

- operations/security_and_authentication/Manage_System_Passwords.md
Update switch names and add aruba switches to Management_System_Passwords.md
Casmnet -979
> Casmnet -979

- install/create_application_node_config_yaml.md
CASMINST-3018: Stress SHCD example before hmn_connections.json example in install/create_application_node_config_yaml.md
> CASMINST-3018-1.2 Stress SHCD example before hmn_connections.json example

- install/create_application_node_config_yaml.md
CASMINST-3018: Stress SHCD example before hmn_connections.json example in install/create_application_node_config_yaml.md
> CASMINST-3018-main Stress SHCD example before hmn_connections.json example

- upgrade/1.2/scripts/k8s/tds_lower_cpu_requests.sh
- upgrade/1.2/scripts/upgrade/tds_cpu_requests.yaml
- upgrade/1.2/scripts/upgrade/update-customizations.sh
Edit customizations.yaml during upgrade to permanently apply lower CPU requests for some services requests larger than needed on TDS/3 worker systems.
* Partially Resolves [CASMINST-3688](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3688)
Validated the merge of yaml looks correct (craystack)
* `craystack`
Yaml looks good, will need to validate final chart impacts on an upgraded 1.2 system (with SMA installed)
None
> Changes to reduce CPU requests for TDS systems

- operations/index.md
- operations/node_management/Change_Java_Security_Settings.md
- operations/node_management/Launch_a_Virtual_KVM_on_Intel_Nodes.md
CASMINST-3570 Change more Gigabyte servers or Intel servers to be nodes instead of servers
> CASMINST-3570 Change more Gigabyte servers or Intel servers to be nodes instead of servers

- install/prepare_site_init.md
CASMINST-3053: Remove minor typo with dangling See word
> CASMINST-3053: Remove minor typo with dangling See word

- LICENSE
- docs-csm.spec
- index.md
- runLint.sh
- toc.sh
CASMINST-3738: Update copyright to 2022
> CASMINST-3738: Update copyright to 2022

- install/prepare_site_init.md
CASMINST-3740: Correct broken link to Decrypt Sealed Secrets for Review
> CASMINST-3740: Correct broken link to Decrypt Sealed Secrets for Review

- install/install_csm_services.md
- upgrade/1.2/README.md
Add doc note about changes to customizations for TDS systems on install/upgrade
* Resolves [CASMINST-3739](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3739)
N/A
N/A
N/A
Low
> Add doc note about changes to customizations for TDS systems on install/upgrade

- operations/firmware/FAS_Use_Cases.md
- operations/power_management/Power_On_Compute_and_IO_Cabinets.md
- operations/power_management/Power_On_and_Boot_Compute_Nodes_and_User_Access_Nodes.md
- operations/power_management/Recover_from_a_Liquid_Cooled_Cabinet_EPO_Event.md
Update to documentation to include steps for configuring the high speed network after powering on components but before booting nodes.
* Resolves [CASMHMS-5285](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5285)
NA
NA
NA
None
> Update documentation for Slingshot switch config

- install/prepare_site_init.md
CASMINST-2951:1.2 Clarify LDAP setting examples and change bullets to numbered tasks
> CASMINST-2951:1.2 Clarify LDAP setting examples and change bullets to numbered tasks

- install/prepare_site_init.md
CASMINST-2951:main Clarify LDAP setting examples and change bullets to numbered tasks
> CASMINST-2951:main Clarify LDAP setting examples and change bullets to numbered tasks

- operations/image_management/Build_an_Image_Using_IMS_REST_Service.md
- operations/image_management/Customize_an_Image_Root_Using_IMS.md
Update IMS docs for SP2 barebones recipe. NOTE: There are additional references to SP1 that still need to be fixed by the UAN team. 
Yes
* Resolves [issue id](issue link) CASMCMS-3646
Not tested. Just docs.
> CASMCMS-3646 Update docs for SLE15SP2

- operations/image_management/Build_an_Image_Using_IMS_REST_Service.md
- operations/image_management/Customize_an_Image_Root_Using_IMS.md
Update docs to change from SP2 to SP3
Yes
* Resolves [CASMCMS-7758](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7758)
No testing. Just docs.
None
> CASMCMS-7758 Update barebones image service pack to SP3

- install/prepare_site_init.md
CASMINST-2951-1.2b Correct large DNS and FIXME sections which were mistakenly removed
The previous mod to CASMINST-2951 mistakenly removed major DNS and FIXME sections and had used the old dtr.dev.cray.com URL in many places.
> CASMINST-2951-1.2b Correct large DNS and FIXME sections which were mistakenly removed

- upgrade/1.2/scripts/upgrade/prerequisites.sh
This updates kea in stage 0 because the new kea chart is needed to boot the NCNs in stage 1.
Also updates a couple of minor bugs that I saw during the upgrade on drax.
* Resolves CASMINST-3778
* `drax`
Updated prerequisites.sh on drax before running it for the latest 1.2 upgrade.
No known issues.
> CASMINST-3778:  Upgrade Kea before Stage 1 of upgrade

- operations/index.md
- operations/node_management/Add_additional_Liquid-Cooled_Cabinets_to_a_System.md
Adds the top level procedure for adding additional liquid-cooled cabinets to a system. Which makes calls out to other procedures to support adding cabinets.
backwards compatible
* Partially resolves [CASMINST-3690](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3690)
Currently 2 steps are stubbed out which required content from:
* Reconfigure management network: …
> CASMINST-3690: Add initial top level procedure for adding cabinets

- operations/index.md
- operations/node_management/Add_additional_Liquid-Cooled_Cabinets_to_a_System.md
Adds the top level procedure for adding additional liquid-cooled cabinets to a system. Which makes calls out to other procedures to support adding cabinets.
backwards compatible
* Partially resolves [CASMINST-3690](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3690)
Currently 2 steps are stubbed out which required content from:
* Reconfigure management network: …
> (main) CASMINST-3690: Add initial top level procedure for adding cabinets

- install/bootstrap_livecd_remote_iso.md
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_ This is a simple addition to add the exported SYSTEM_NAME variable to /etc/environment so it persists similar to the CSM_RELEASE variable.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ : Should be backwards compatible.
* Resolves [CASMINST-3746](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3746)
* Change will also be needed in `N/A`
* Future work required by `N/A`
* Documentation changes required in `These are the doc changes`
* Merge with/before/after `N/A`
_List the environments in which …
> CAMSINST-3746 - updated /etc/environment persist command to include SYSTEM_NAME

- index.md
In the https://github.com/Cray-HPE/docs-csm/blob/release/1.2/index.md index page, link to "pre-install steps" is not working.
The URL https://github.com/Cray-HPE/docs-csm/blob/release/1.2/operations/install/Preinstall.md is not found.
I think the issue is that install folder from operations directory is removed and the preinstall files are moved to:
https://github.com/Cray-HPE/docs-csm/tree/release/1.2/operations/preinstall
No, preinstall folder was moved.
UNK
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list …
> changed pre-install link location to point to new folder

- upgrade/1.2/scripts/upgrade/prerequisites.sh
> install testing rpm before using it

- operations/kubernetes/TDS_Lower_CPU_Requests.md
- upgrade/1.0.1/README.md
Based on feedback when upgrading lumi TDS system, we need to make it clear that the CPU limits need to be lowered in order for the upgrade to succeed.
* Resolves [CASMINST-3840](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3840)
N/A
N/A
N/A
N/A
> Strengthen wording about lowering CPU limits on TDS systems during upgrade

- install/deploy_final_ncn.md
> Revert "CASMINST-3807: Manually install/upgrade RPMs on ncn-m001 after PIT redeploy"

- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
> remove scary error messages

- upgrade/1.2/scripts/upgrade/update-customizations.sh
Fix case problem preventing config map for metallb to be created.
* Resolves [CASMPET-5276](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5276)
drax
* `drax`
Fixed customizations on drax and the config map gets created.
None
> Fix case problem for metallb config map values

- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-worker.sh
> fix goss test bgp password var name change

- introduction/differences.md
Updated deprecating/deprecated terminology to better describe the state of the features under each heading. A sentence was also added under each heading to add more clarity.
Changes needed in 1.0 and 1.2.
* Resolves [STP-3104](https://jira-pro.its.hpecorp.net:8443/browse/STP-3104)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/801
N/A
N/A
N/A
None.
> STP-3104: clarify confusing terminology in differences.md

- install/configure_management_network.md
Added notes that Canu does not automatically create site connections and simple instructions on how to.
yes
* Resolves [issue id](issue link) Casmnet-1107
* …
> Casmnet 1107

- upgrade/1.2/scripts/upgrade/prerequisites.sh
> CASMINST-3929

- upgrade/update_management_network.md
https://cray-hpe.github.io/docs-csm/en-10/upgrade/update_management_network/
has an incorrect path in:
Next step is to re-run the BGP script.
It is located at /opt/cray/csm/scripts/networking/BG/Aruba_BGP_Peers.py <-- !
This is documented on this page Update BGP Neighbors
The correct path is:
/opt/cray/csm/scripts/networking/BGP/Aruba_BGP_Peers.py
Solution: added P.
https://jira-pro.its.hpecorp.net:8443/browse/CAST-28970
* …
> fixed typo

- operations/network/network_management_install_guide/aruba/index_aruba.md
- operations/network/network_management_install_guide/dell/index_dell.md
- operations/network/network_management_install_guide/mellanox/index_mellanox.md
Fixed headers in index files (incorrect rendering that was not caught my macdown).
Was displaying headers as ###example where as it should have displayed bold header. 
No change in content
yes
n/a
_List the …
> Casmnet 1111

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Adding to the Troubleshoot Postgres a case where after the reinit (to fix lag), the member remains stopped. 
In Pawsey prod environment this was seen and was a result of one member running out of disk space prior to the reinit.
The reinit did cleanup the WAL files but there were remaining pg_internal.init.* files that were truncated when the file system filled up; these needed to be cleaned up so that the stopped member would restart.
This change also includes a minor change to remove lag number from Leader line in patronictl list output.
This change also pulls in some formatting changes that were done on the release/1.2 branch to improve readability.
Is this change is backwards compatible
* Resolves [CASMPET-5292](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5292) for CAST-28984 …
> CASMPET-5292 main : DOCS: Add case for postgres cluster member stopped after reinit

- install/bootstrap_livecd_remote_iso.md
Simple minor typing correction to append new line
* surtur
_How were the changes tested and success …
> CASMINST-3953 minor correction to $CSM_PATH var

- operations/resiliency/Resiliency_Testing_Procedure.md
The Resiliency_Testing_Procedure.md file has several issues that need to be addressed. Here are a couple for context:
- Acronyms are not properly capitalized
- Third party terms are not properly capitalized
- Redundant use of "NCN node"
- Large bulleted lists with the tasks buried in the text
- Spelling and formatting
* Merge with [799](https://github.com/Cray-HPE/docs-csm/pull/799) + [837](https://github.com/Cray-HPE/docs-csm/pull/837)
* Resolves [STP-3102](https://jira-pro.its.hpecorp.net:8443/browse/STP-3102)
N/A
N/A
N/A
N/A
> STP-3102: Improvements to resiliency testing procedures (1.0)

- operations/resiliency/Resiliency_Testing_Procedure.md
The Resiliency_Testing_Procedure.md file has several issues that need to be addressed. Here are a couple for context:
- Acronyms are not properly capitalized
- Third party terms are not properly capitalized
- Redundant use of "NCN node"
- Large bulleted lists with the tasks buried in the text
- Spelling and formatting
* Merge with [799](https://github.com/Cray-HPE/docs-csm/pull/799) + [836](https://github.com/Cray-HPE/docs-csm/pull/836)
* Resolves [STP-3102](https://jira-pro.its.hpecorp.net:8443/browse/STP-3102)
N/A
N/A
N/A
N/A
> STP-3102: Improvements to resiliency testing procedures (main)

- upgrade/1.2/Stage_3.md
- upgrade/1.2/scripts/upgrade/csm-service-upgrade.sh
Update to the documents for the ceph csi change and disclaimer of limited pvc movement.
Includes execution of prerequisite functions to ensure the proper csi components are created prior to the chart deployment.
* Resolves CASMINST-3857
* To be tested on metal - not testable elsewhere
> Casminst 3857 update

- operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
Update final step to set no wipe flag to include complete set of steps.
* Resolves [CASMINST-3969](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3969)
N/A
N/A
N/A
Low -- same steps used before wipe.
> Add missing steps to update bss data after rebuild

- operations/kubernetes/Containerd.md
Add procedure for addressing /var/lib/containerd filling up
* Resolves [CASMINST-3989](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3989)
N/A
N/A
N/A
Low
> Add procedure for addressing /var/lib/containerd filling up

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/scripts/upgrade/prerequisites.sh
Cleanup process for installing latest docs rpm in an air gapped system
* Resolves [CASMINST-3990](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3990)
N/A
N/A
N/A
N/A
Low
> Cleanup docs rpm install location for air gapped

- upgrade/1.0.1/scripts/upgrade/create_rgw_buckets.sh
- upgrade/1.0.11/scripts/upgrade/create_rgw_buckets.sh
Update known hosts files on storage nodes after ncn-s001 is re-imaged prior to running ansible.
* Resolves [CASMINST-3994](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3994)
Wasp
* `wasp`
Ran script with changes, saw it succeed updating known hosts and successfully ran bucket play.
Low
> Add ssh key scan prior to running rgw ansible play on upgrade

- upgrade/1.0.1/scripts/upgrade/ncn-upgrade-k8s-worker.sh
- upgrade/1.0.11/scripts/upgrade/ncn-upgrade-k8s-worker.sh
[CAST-28901](https://jira-pro.its.hpecorp.net:8443/browse/CAST-28901) and [CASMINST-3703](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3703) both noted that the 1.0 ncn-upgrade-k8s-worker.sh uses a curl command (curl -s http://localhost:8008/cluster) rather than the patronictl list command to determine postgres health. We have found that these two different methods do not alway report consistent information especially when the clusters are not healthy.
Changing the csm 1.0 ncn-upgrade-k8s-worker.sh to run patronictl list from the leader pod to determine if there is lag, missing members, etc
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? yes
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure …
> CASMPET-5311 1.0 : Modify postgres health check in csm 1.0 ncn-upgrade-k8s-worker.sh

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-worker.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
> Multiple fixes for upgrade automation

- upgrade/1.2/README.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/scripts/upgrade/csm-service-upgrade.sh
- upgrade/1.2/scripts/upgrade/enable-psp.sh
- CASMINST-4034
- CASMINST-4028
- Remove an unnecessary retry we had in 1.0
- Was downgrade tested? …
> Upgrade mega fix

- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
Cleaned up the Add a liquid-cooled blade procedure. There were some inconstancies related to ordering of when the chassis BMC got discovered and when the chassis slot was powered on. Some of the DNS/DHCP/IP checks needed to be refined and/or replaced. This commit shows what I changed from CSM 1.2: https://github.com/Cray-HPE/docs-csm/commit/8652e6dabe0578031c16ee8fff757bc06e7cf40c
* Partially Resolves …
> CASMHMS-5386 Add Blade add/remove procedures to CSM 1.0

- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
Cleaned up the Add a liquid-cooled blade procedure. There were some inconstancies related to ordering of when the chassis BMC got discovered and when the chassis slot was powered on. Some of the DNS/DHCP/IP checks needed to be refined and/or replaced.
* Partially Resolves [CASMHMS-5386](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5386)
* Local development …
> Clean up the Add a liquid-cooled blade procedure.

- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
Cleaned up the Add a liquid-cooled blade procedure. There were some inconstancies related to ordering of when the chassis BMC got discovered and when the chassis slot was powered on. Some of the DNS/DHCP/IP checks needed to be refined and/or replaced.
* Partially Resolves [CASMHMS-5386](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5386)
* Local development …
> Cleaned up the Add a liquid-cooled blade procedure.

- RELEASE_NOTES.md
- operations/firmware/Updating_Firmware_m001.md
- operations/power_management/Prepare_the_System_for_Power_Off.md
- operations/validate_csm_health.md
- troubleshooting/known_issues/craycli_403_forbidden_errors.md
Fix some of the special characters that snuck into the docs.
> CASMINST-4070: Convert 'fancy' quotes to regular ones

- introduction/csm_overview.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/CSM_product_management/Remove_Artifacts_from_Product_Installations.md
- operations/kubernetes/Kubernetes_Networking.md
- operations/network/external_dns/External_DNS_Failing_to_Discover_Services_Workaround.md
- operations/network/external_dns/Ingress_Routing.md
- operations/network/external_dns/Troubleshoot_DNS_Configuration_Issues.md
- operations/network/external_dns/Troubleshoot_Systems_Not_Provisioned_with_External_IP_Addresses.md
- operations/network/metallb_bgp/Troubleshoot_Services_without_an_Allocated_IP_Address.md
- operations/package_repository_management/Restrict_Admin_Privileges_in_Nexus.md
- operations/security_and_authentication/Access_the_Keycloak_User_Management_UI.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
- operations/security_and_authentication/Configure_the_RSA_Plugin_in_Keycloak.md
- operations/security_and_authentication/Make_HTTPS_Requests_from_Sources_Outside_the_Management_Kubernetes_Cluster.md
- operations/security_and_authentication/Retrieve_an_Authentication_Token.md
Update docs that reference DNS names and talk about ingress gateways to include the network name and reference the new gateways in 1.2.
* Resolves CASMNET-867
Tested commands that were updated as appropriate on fanta or hela.
Very low risk.
> CASMNET-867:  Update docs for multiple gateways

- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-master.sh
Typo in introduction of new step to update kubeapi issuer
* Resolves [CASMINST-4096](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4096)
Manually made change on drax
* `drax`
Manually made change on drax
Low
> Fix typo in upgrade-k8s-master script

- operations/utility_storage/Ceph_Orchestrator_Usage.md
- upgrade/1.2/Stage_4.md
- upgrade/1.2/scripts/ceph/lib/ceph-service-status.sh
* Utility storage doc fixes
* Adding ceph upgrade to stage4
* Resolves CASMPET-4858
* craystack
> Casmpet 4858 1.2

- upgrade/1.2/scripts/k8s/upgrade_control_plane.sh
The kubeadm upgrade step doesn't honor current args in the static manifests, so we need to load the configmap with the settings that will be used during the upgrade step and restart of the containers.  Need to add back the bind-address so kube scheduler and controller-manager prometheus alerts aren't down.
* Resolves [CASMINST-4107](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4107)
Ran the new code and applied to the configmap on drax
* `drax`
Alerts cleared after the manifests were updated
Low
> Add extraArgs for kube alerts prior to calling kubeadm upgrade

- operations/network/management_network/index.md
Move index.md back to management_network folder.
CASMNET-1175
> CASMNET-1175

- operations/conman/Access_Compute_Node_Logs.md
- operations/conman/Access_Console_Log_Data_Via_the_System_Monitoring_Framework_SMF.md
- operations/conman/Disable_ConMan_After_System_Software_Installation.md
- operations/conman/Establish_a_Serial_Connection_to_NCNs.md
- operations/conman/Log_in_to_a_Node_Using_ConMan.md
- operations/conman/Manage_Node_Consoles.md
- operations/conman/Troubleshoot_ConMan_Asking_for_Password_on_SSH_Connection.md
- operations/conman/Troubleshoot_ConMan_Blocking_Access_to_a_Node_BMC.md
- operations/conman/Troubleshoot_ConMan_Failing_to_Connect_to_a_Console.md
- operations/firmware/FAS_Use_Cases.md
- operations/utility_storage/Troubleshoot_System_Clock_Skew.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/Stage_4.md
- upgrade/1.2/scripts/upgrade/ncn-upgrade-k8s-worker.sh
- upgrade/prepare_for_upgrade.md
This is the 1.2 version of this 1.0 PR:
https://github.com/Cray-HPE/docs-csm/pull/976
> CASMINST-4115 Linting of install and upgrade docs; Improve k8s worker script handling of CPS

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
This is to support a 1.2 to 1.2 upgrade
Logic tested on craystack
> CASMINST-4121 - Add container image check before removing

- operations/network/management_network/index.md
- operations/network/management_network/upgrade.md
- troubleshooting/known_issues/mellanox_lacp_individual.md
rename 1.0 preconfig > 1.2 preconfig
add lacp-individual limitations to known_issues page.
CASMNET-1176
CASMNET-1177
> CASMNET-1176

- operations/utility_storage/Troubleshoot_Ceph_FS_Client_Connectivity_issues.md
This adds additional troubleshooting documentation for Ceph filesystem/MDS
* Resolves CASMTRIAGE-3003
* N/A
> CASMTRIAGE-3003 - Add step to diagnose and failover MDS

- upgrade/1.2/Stage_1.md
this is to cover the case of services not starting post image upgrade
* Resolves CASMTRIAGE-3004
* Linking to existing procedures
> CASMTRIAGE-3004 - link stage 1 upgrade to utility storage operations

- operations/image_management/Customize_an_Image_Root_Using_IMS.md
> CASMCMS-7868 Remove references to Singularity and Compute Kubernetes

- upgrade/1.2/scripts/upgrade/csm-service-upgrade.sh
> CASMINST-4027

- operations/firmware/FAS_Recipes.md
- operations/firmware/FAS_Use_Cases.md
- operations/network/management_network/apply_custom_config_1.0.md
- operations/network/management_network/apply_custom_config_1.2.md
- operations/network/management_network/fresh_install.md
Fix last few links to make markdown link checker happy.
> Last few links fixed

- upgrade/1.0.11/Stage_5.md
This updates the kafka image names to match the ones in the new operator update.
> CASMPET-5363 Update kafka image names

- upgrade/1.2/scripts/strimzi/kafka-prereq.sh
There will be multiple helm secrets when a upgrade is done to the
cray-kafka-operator helm chart. This change will delete all the helm
secrets instead of a single secret.
* Resolves [CASMINST-4140](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4140) 
Validated script deleted all helm secrets for the cray-kafka-operator chart.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A 
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? N/A
- Were new tests (or test issues/Jiras) created for this change? N
> CASMINST-4140 Fix issue with deleting helm secrets

- operations/utility_storage/Add_Ceph_Node.md
- operations/utility_storage/Remove_Ceph_Node.md
Minor changes to existing docs for ceph add/remove node
> minor-fix main : Noted after add/remove s004 storage integration testing

- operations/utility_storage/Add_Ceph_Node.md
- operations/utility_storage/Remove_Ceph_Node.md
Minor changes to existing docs for ceph add/remove node
> minor-fix 1.2 : Noted after add/remove s004 storage integration testing

- operations/node_management/Add_Remove_Replace_NCNs.md
- operations/node_management/Add_Remove_Replace_NCNs/Add_NCN_Data.md
- operations/node_management/Add_Remove_Replace_NCNs/Boot_NCN.md
- operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_Data.md
- operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_from_Role.md
- operations/utility_storage/Add_Ceph_Node.md
- operations/utility_storage/Remove_Ceph_Node.md
More changes and filling out of the Add/Remove/Replace docs based on initial integration testing for storage node
> CASMPET-5341c 1.0 : Updates after s004 integration testing

- operations/network/management_network/collect_data.md
Show admins how to run `canu backup network`
CASMNET-4051
virtual env
hela
> CASMINST-4051

- upgrade/1.2/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
The wipe commands don't care if a device is mounted or not. They
will wipe it regardless.
Modify the code so the list of devices to wipe doesn't include the
USB. This borrows code that is in dracut for the same reason.
While here, reduce the number of lines needed to figure out which
device is the USB device. (IMO, this code doesn't need to care about
whether the USB device is mounted or not, but it's a smaller code
change to leave that logic in place. And it's harmless.)
* Resolves [CASMINST-4149](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4149)
* `redbull`
Tested the snippets on redbull, but echoing the …
> CASMINST-4149: never wipe USB devices

- upgrade/1.2/scripts/k8s/tds_lower_cpu_requests.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-wipe-rebuild.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
> CASMINST-4133

- operations/configuration_management/Version_Control_Service_VCS.md
- upgrade/1.0.1/README.md
- upgrade/1.0.1/Stage_0_Prerequisites.md
- upgrade/1.0.11/README.md
- upgrade/1.0.11/Stage_0_Prerequisites.md
- upgrade/prepare_for_upgrade.md
This backports the relevant changes from this 1.2 PR into the 1.0 docs:
https://github.com/Cray-HPE/docs-csm/pull/1036/files
> Minor linting, fixes, and enhancements

- glossary.md
- operations/configuration_management/Configuration_Management.md
CASMINST-3510-1.0 Update glossary entries with new terms
Many new terms have been added to the glossary based on feedback from documentation readers.
> CASMINST-3510-1.0 Update glossary entries with new terms

- glossary.md
- operations/configuration_management/Configuration_Management.md
CASMINST-3510-main Update glossary entries with new terms
Many new terms have been added to the glossary based on feedback from documentation readers.
> CASMINST-3510-main Update glossary entries with new terms

- operations/validate_csm_health.md
The 1.2 version of this PR:
https://github.com/Cray-HPE/docs-csm/pull/1060
> Fix formatting issue in Velero remediation instructions

- upgrade/1.2/scripts/upgrade/prerequisites.sh
- upgrade/1.2/scripts/upgrade/util/update-customizations.sh
> fix import path issue

- operations/network/management_network/fresh_install.md
- operations/network/management_network/upgrade.md
- operations/network/management_network/validate_cabling.md
Adding cable validation step to both upgrade and install scenarios. 
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4193
Testing done in Fanta.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4175
* Fanta
Cabling issue detected and physical action taken to correct cabling. Re-run of Canu cable validation showed the issue as fixed. 
N/A
- [ x] Version number(s) incremented, if applicable
- [ x ] Copyrights updated
- [ x ] License file intact
- [ x ] Target branch correct
- [ x ] CHANGELOG.md updated
- [ x ] Testing is appropriate and complete, if applicable
- [ x ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
> validate cabling documentation added for both upgrade/install documents

- install/prepare_site_init.md
- operations/network/management_network/snmp_exporter_configs.md
Change order to update Prometheus SNMP Exporter Deployment values.yaml
* Resolves [iCASMMON-111](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-111)
*
No new code, just documentation
-NA
> Casmmon 111 snmp-exporter documentation

- operations/node_management/Reboot_NCNs.md
> CASMINST 4201

- operations/node_management/Reboot_NCNs.md
> CASMINST 4202

- operations/node_management/Reboot_NCNs.md
- upgrade/1.2/scripts/common/ncn-common.sh
- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
- upgrade/1.2/scripts/common/upgrade-state.sh
- upgrade/1.2/scripts/k8s/promote-initial-master.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
> Refactoring fix pack

- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
This change clarifies how to change the keycloak password and make sure that the sealed secret and customizations.yaml are updated properly.
> CASMPET-5263 Update keycloak password process

- .vscode/settings.json
- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
This adds the documentation on how to change the keycloak admin password.
> CASMPET-5263 Add keycloak admin password change doc

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
This is to fix container image corruption of cached images
* Resolves CASMINST-4239
* surtur
Performed a boot loop with this change overnight.  we hit first try success 88% of the time and the additional 12% were boot based issues that resolved on the second boot.
> Fixes to the ceph node image upgrade

- operations/firmware/Updating_Firmware_m001.md
Update to the "Updating Firmware on m001" guide with command and wording changes.
CASMHMS-5437
CASMHMS-5438
> Firmware updates to m001 docs wording and command changes - 1.0

- operations/firmware/Updating_Firmware_m001.md
Update to the "Updating Firmware on m001" guide with command and wording changes.
CASMHMS-5437
CASMHMS-5438
> Firmware updates to m001 docs wording and command changes - 1.2

- upgrade/1.2/scripts/upgrade/prerequisites.sh
> make sure podman is configured properly

- operations/power_management/Cray_Advanced_Platform_Monitoring_and_Control_CAPMC.md
- operations/power_management/Liquid_Cooled_Node_Card_Power_Management.md
- operations/power_management/Standard_Rack_Node_Power_Management.md
Update power capping documentation.
* Resolves [CASMHMS-5253](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5253)
Verified output on River Gigabyte nodes and Olympus nodes.
Executed power capping command to verify they worked and output was as expected.
None
> CASMHMS-5253 Power capping documentation updates

- RELEASE_NOTES.md
> CASMINST-4267 Update RELEASE_NOTES.md for 1.0.11

- RELEASE_NOTES.md
> CASMINST-4268 RELEASE_NOTES.md

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Removing ||true  testing work around
* Resolves CASMINST-4240
> CASMINST-4240 - remove true on the goss testing

- upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
Removing ||true  testing work around
* Resolves CASMINST-4240
> Casminst 4240 main

- install/ceph_csi_troubleshooting.md
- install/configure_administrative_access.md
- install/configure_management_network.md
- install/create_ncn_metadata_csv.md
- install/create_switch_metadata_csv.md
- install/deploy_management_nodes.md
- install/prepare_compute_nodes.md
- install/prepare_configuration_payload.md
- install/prepare_management_nodes.md
- install/prepare_site_init.md
- install/pxe_boot_troubleshooting.md
- install/shcd_hmn_connections_rules.md
No major content changes. Minor cleanup of grammar, formatting, and wording.
* Resolves [STP-3123](https://jira-pro.its.hpecorp.net:8443/browse/STP-3123)
N/A
N/A
N/A
None.
> STP-3123: minor grammar and formatting changes

- operations/node_management/Configure_NTP_on_NCNs.md
- upgrade/scripts/upgrade_ntp_timezone_metadata.sh
Add documentation that helps a user restore NTP data to BSS if it is missing.
* Resolves [CASMINST-4256](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4256)
* `Rocket`
> CASMINST-4256: Add documentation for restoring NTP data in BSS

- install/bootstrap_livecd_remote_iso.md
> Added admin directory to fix script issue

- operations/index.md
- operations/spire/xname_validation.md
This adds documentation on how to enable/disable xname validation.
> CASMINST-3774 Add xname validation docs

- operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
reordering the steps
* Resolves CASMPET-5436
> CASMPET-5436 - fix prepare storage node for rebuild

- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/prepare-assets.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
- Integrate ncn-image-modification to customize password/ssh keys
- automate more manual steps in prereq
- use xname instead of hostname in bss_ntp validation
- use preprare-asset.sh to install canu and extract tarball (de-couple from prepreq)
- change m001 upgrade procedure to remove time consuming but unnecessary steps
_List the …
> Casminst 4370

- install/troubleshooting_installation.md
- operations/node_management/Configure_NTP_on_NCNs.md
- operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
- operations/node_management/Updating_Cabinet_Routes_on_Management_NCNs.md
- operations/resiliency/NTP_Resiliency.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys_on_PIT_Node.md
- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
- operations/utility_storage/Ceph_Service_Check_Script_Usage.md
- operations/utility_storage/Troubleshoot_an_Unresponsive_S3_Endpoint.md
- upgrade/1.0.1/scripts/ceph/lib/ceph-service-status.sh
- upgrade/1.0.11/Stage_1.md
Basic MitchLint of spelling, formatting, etc.
> CASMINST-4386: Linting

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Add to postgres troubleshooting to cover the case where reinit fails and leader pod needs to be restarted.
* Resolves [CASMINST-4390](DOCS: K8s upgrade on w001 throws error)
This issue was seen on drax where 0.1.11 to 1.2.0 beta 96 upgrade was occurring.
In the past this procedure has been used instead of waiting 45m for the lag to resolve.
Low
> CASMINST-4390 1.2 : DOCS: K8s upgrade on w001 throws error

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Add to postgres troubleshooting to cover the case where reinit fails and leader pod needs to be restarted.
* Resolves [CASMINST-4390](DOCS: K8s upgrade on w001 throws error)
This issue was seen on drax where 0.1.11 to 1.2.0 beta 96 upgrade was occurring.
In the past this procedure has been used instead of waiting 45m for the lag to resolve.
Low
> CASMINST-4390 1.2.5 : DOCS: K8s upgrade on w001 throws error

- upgrade/1.2/Stage_1.md
CASMINST-4325 - adding retry note for rare error during storage node upgrade
I was not able to reproduce the error to locate the source and it is very rare that we come across this.
* Resolves CASMINST-4325
> Casminst 4325

- .github/workflows/markdown-lint.yaml
- .markdownlint.yaml
[## Summary and Scope
_How were the changes tested and success verified? If …
> CASMINST-4387 Add markdown linter to docs-csm [1.2.5]

- .github/workflows/markdown-lint.yaml
- .markdownlint.yaml
- operations/firmware/FAS_Use_Cases.md
[[## Summary and Scope
_How were the changes tested and success verified? …
> CASMINST-4387 Add markdown linter to docs-csm [1.1]

- operations/index.md
- operations/node_management/Rebuild_NCNs/Final_Validation_Steps.md
- operations/node_management/Rebuild_NCNs/Identify_Nodes_and_Update_Metadata.md
- operations/node_management/Rebuild_NCNs/Post_Rebuild_Storage_Node_Validation.md
- operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
- operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
- operations/node_management/Rebuild_NCNs/Re-add_Storage_Node_to_Ceph.md
- operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
- operations/node_management/Rebuild_NCNs/Validate_Boot_Raid.md
- operations/node_management/Rebuild_NCNs/Wipe_Drives.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
Updates to the NCN rebuild procedures to improve workflow, wording, and formatting.
This change can be applied to release/1.2.5 and main as well.
* Resolves [STP-3163](https://jira-pro.its.hpecorp.net:8443/browse/STP-3163)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1213 and https://github.com/Cray-HPE/docs-csm/pull/1214
N/A
N/A
N/A
None.
> STP-3163: NCN rebuild improvements

- operations/firmware/FAS_Use_Cases.md
- operations/kubernetes/TDS_Lower_CPU_Requests.md
- operations/node_management/Reboot_NCNs.md
- operations/security_and_authentication/Update_NCN_Passwords.md
- operations/utility_storage/Ceph_Service_Check_Script_Usage.md
Linting of grammar, formatting, spelling, consistency, etc. No content changes.
> CASMINST-4401: Linting

- operations/power_management/Cray_Advanced_Platform_Monitoring_and_Control_CAPMC.md
Update internal doc link
* Resolves [CASMHMS-5254](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5254)
> CASMHMS-5254 Fix internal link

- upgrade/1.0.1/scripts/upgrade/add_pod_priority.sh
- upgrade/1.0.11/scripts/upgrade/add_pod_priority.sh
The pod priority script needs to interrogate the cluster state a bit better before restarting pods, it looks like there is a timing issue of the charts being deployed and the cluster not being fully up.  This PR makes sure the operator sees three healthy members before starting -- in the same way it does during the actual restarts of etcd pods.
* Resolves [CASMINST-4364](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4364)
drax (healthy and unhealthy cluster)
* `drax`
Tested on both bss (unhealthy -- it waited) and bos (healthy -- marched on)
Low
> Improve pod priority script pre-req check for healthy cluster before restarts

- upgrade/1.2/scripts/common/upgrade-state.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
add a white list in trap function to suppress certain errors
- CASMINST-4388
- CASMINST-4389
- Was upgrade …
> CASMINST-4388

- operations/node_management/Add_Remove_Replace_NCNs/Add_NCN_Data.md
Query kea instead of HMS to get the current BMC IP as this requires less possible troubleshooting.
* Resolves [CASMPET-5447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5447)
* fanta
Tested during storage NCN replace (ncn-s001<->ncn-s004) on fanta.
Very …
> CASMPET-5447 1.0 : Use kea lease to determine current BMC IP and fix md formatting

- upgrade/1.2/README.md
- upgrade/1.2/Stage_0_Prerequisites.md
This step is confusing in its current stage, so after discussion we'll move to to the main page for later refactoring into an abstract section.
* Resolves [CASMINST-4420](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4420)
N/A
N/A
N/A
Low
> Move info about TDS CPU request lowering to abstract section

- upgrade/1.2/scripts/common/upgrade-state.sh
- remove expected error from console
CASMINST-4419
- Was downgrade …
> ignore expected error in prepare etcd

- upgrade/1.2/Stage_1.md
Adding a note that this can occur and link to the documentation around this.
* Resolves CASMINST-4411
> CASMINST-4411 - add note for ceph crash

- install/bootstrap_livecd_usb.md
- install/create_application_node_config_yaml.md
- install/create_hmn_connections_json.md
- install/deploy_final_ncn.md
- operations/Access_LiveCD_USB_Device_After_Reboot.md
- operations/Component_Names_xnames.md
- operations/firmware/FAS_Admin_Procedures.md
- operations/firmware/FAS_CLI.md
- operations/firmware/Update_Firmware_with_FAS.md
- operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md
- operations/image_management/Image_Management_Workflows.md
- operations/node_management/Access_and_Update_the_Settings_for_Replacement_NCNs.md
- operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
- operations/power_management/Bring_up_the_Slingshot_Fabric.md
- operations/utility_storage/Add_Ceph_Node.md
- operations/utility_storage/Remove_Ceph_Node.md
- operations/utility_storage/Troubleshoot_Ceph_OSDs_Reporting_Full.md
- scripts/operations/system_layout_service/restore_sls_postgres_from_backup.sh
- upgrade/1.2/scripts/k8s/failover-leader.sh
- upgrade/1.2/scripts/sls/sls_utils/README.md
Ready for review.
Usual linting of spelling, formatting, style, grammar, clarity, and consistency issues. No content changes, only linting.
> CASMINST-4408: Linting of formatting, spelling, style, consistency, grammar, and clarity

- upgrade/1.2/scripts/common/ncn-common.sh
Do a cluster-wide remove of the old host key entry after a node is rebuilt/upgraded.
> CASMINST-4392: remove old host keys after NCN is re-imaged

- operations/node_management/Add_Remove_Replace_NCNs/Boot_NCN.md
- operations/node_management/Add_Remove_Replace_NCNs/Validate_NCN.md
- operations/utility_storage/Add_Ceph_Node.md
- scripts/join_ceph_cluster.sh
Fix join script, update docs for minor tweaks
* Resolves [CASMPET-5449](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5449)
* fanta
Tested during storage NCN replace (ncn-s001<->ncn-s004) on fanta.
Very low
> CASMPET-5449 : NCN Storage replace updates to docs and scripts

- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
set default value of LOG_FILE in csm service upgrade script
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4424
- Were continuous integration tests run? If …
> add missing variable check with a default value

- upgrade/1.2/Stage_4.md
add command to check for older versions of ceph.  also adding link to ceph orchestrator usage page for additional troubleshooting.
* Resolves CASMINST-4429
> Casminst 4429 1.2.5

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/deploy_management_nodes.md
- install/redeploy_pit_node.md
Backports documentation from current branches to help prevent NTP issues during deployment/uograde.
* Relates to CASMINST-4421
* Backports #1249 
* Backports #1247 
Tested in original PRs
Low.
> MTL-1664 CASMINST-4421 converge NTP documenation

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Adds another case seen only during 1.0 -> 1.2 upgrade where postgres lag requires a reinit, but reinit fails and needs manual remediation
* Resolves [CASMINST-4412](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4412)
* Change will also be needed in `main, 1.2.5, 1.0`
surtur
Resolved the issues on surtur using the additional troubleshooting procedure
> CASMINST-4412 1.2 : DOCS: Troubleshoot Postgres needs additional details when TL is different

- operations/kubernetes/Troubleshoot_Postgres_Database.md
Adds another case seen only during 1.0 -> 1.2 upgrade where postgres lag requires a reinit, but reinit fails and needs manual remediation
* Resolves [CASMINST-4412](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4412)
* Change will also be needed in `main, 1.2, 1.0`
surtur
Resolved the issues on surtur using the additional troubleshooting procedure
> CASMIMST-4412 1.2.5 : DOCS: Troubleshoot Postgres needs additional details when TL is different

- background/ncn_plan_of_record.md
- operations/node_management/customize_pcie_hardware.md
There were 3 broken links introduced in this PR.
https://github.com/Cray-HPE/docs-csm/pull/1240
They were fixed in 1.2 and 1.2.5 branches but still need to be fixed in main.
> Fixed broken links that came in on a previous PR

- upgrade/1.2/scripts/common/upgrade-state.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
ignore another expected error found during upgrade
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …
> CASMINST-4443 ignore another expected error

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/collect_mac_addresses_for_ncns.md
- install/deploy_management_nodes.md
- install/index.md
- operations/kubernetes/Recover_from_Postgres_WAL_Event.md
- operations/kubernetes/Troubleshoot_Postgres_Database.md
- operations/node_management/Check_the_BMC_Failover_Mode.md
- operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- operations/security_and_authentication/Change_NCN_Image_Root_Password_and_SSH_Keys.md
- operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
- operations/utility_storage/Identify_Ceph_Latency_Issues.md
- upgrade/1.0.11/Stage_1.md
Ready for review:
Minor linting -- no real content changes
> CASMINST-4423: Linting

- operations/index.md
- operations/kubernetes/CronJobs.md
Add info about verifying the cronjob-kicker schedule if cronjobs not running.
* Resolves [CASMPET-5184](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5184)
N/A
N/A
N/A
Low
> Add doc about cronjob-kicker schedule

- operations/image_management/Build_a_New_UAN_Image_Using_the_Default_Recipe.md
- operations/image_management/Build_an_Image_Using_IMS_REST_Service.md
- operations/image_management/Configure_IMS_to_validate_rpms.md
- operations/image_management/Convert_TGZ_Archives_to_SquashFS_Images.md
- operations/image_management/Create_UAN_Boot_Images.md
- operations/image_management/Customize_an_Image_Root_Using_IMS.md
- operations/image_management/Delete_or_Recover_Deleted_IMS_Content.md
- operations/image_management/Image_Management.md
- operations/image_management/Image_Management_Workflows.md
- operations/image_management/Upload_and_Register_an_Image_Recipe.md
No major changes. Edits for markdown formatting, grammar, and consistency. 
* Resolves [STP-3183](https://jira-pro.its.hpecorp.net:8443/browse/STP-3183)
* Change will also be needed in `release/1.2.5` and `release/1.2`
N/A
N/A
N/A
None.
> STP-3183: IMS formatting and grammar edits

- upgrade/1.0.11/Stage_3.md
* Surtur
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
> Casmtriage 3226

- upgrade/1.2/scripts/upgrade/prerequisites.sh
During testing the nexus repo providing the RPMs from the tarball existed on the system, but in reality this is false. This change simply adds the repo for a one-time-use in the CASMINST-4458 function.
The fix allowed the failing step to continue:
```bash
====> UPDATE_SSH_KEYS has been completed
====> CHECK_CLOUD_INIT_PREREQ has been completed
====> UPDATE_DOC_RPM has been completed
====> UPDATE_CUSTOMIZATIONS has been completed
====> SETUP_NEXUS has been completed
====> DISABLE_SERVICE_REPOS has been completed
====> REMOVE_DUPLICATE_BMC_DNS_RECORDS ...
====> REMOVE_DUPLICATE_BMC_DNS_RECORDS has been completed
====> UPGRADE_BSS ...
====> UPGRADE_BSS has been …
```
> CASMTRIAGE-3225 Nexus repo does not exist

- install/deploy_management_nodes.md
See main branch PR for details:
https://github.com/Cray-HPE/docs-csm/pull/1360
> CASMINST-4464: Modify pdsh command to avoid authentication errors

- install/redeploy_pit_node.md
Basic linting of deploy final NCN procedure. No content changes.
Cherry-picked from https://github.com/Cray-HPE/docs-csm/pull/1342
> CASMINST-4460: Linting of deploy final NCN procedure

- operations/system_management_health/Access_System_Management_Health_Services.md
Fix kubectl command used to show the systems' FQDN from the CAN.
* Resolves [CASMINST-4474](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4474)
* Change will also be needed in release/1.2 and release/1.0 (backport)
fanta
- Were new tests (or …
> CASMINST-4474 main : DOCS: Access_System_Management_Health_Services.md correct example

- operations/image_management/Customize_an_Image_Root_Using_IMS.md
- operations/image_management/Import_External_Image_to_IMS.md
- operations/index.md
Create explicit workflow to import external image to IMS
Yes
* Resolves [CASMCMS-7980](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7980)
None
> CASMCMS-7980 Workflow to import external image to IMS

- upgrade/1.2/scripts/rebuild/ncn-rebuild-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh
> CASMINST-4478 upgrade script is putting csi into wrong folder

- RELEASE_NOTES.md
- operations/network/management_network/backup_custom_config.md
- operations/network/management_network/config_management.md
Correct a couple of typos and remove a contraction (per the HPE style guide).
csm-1.2 backport PR: https://github.com/Cray-HPE/docs-csm/pull/1406
N/A
Nope
> CASMINST-4489: Spelling and style linting

- operations/network/gateway_testing.md
Just linting and some minor rewording of the document. No content changes.
1.2 backport PR: https://github.com/Cray-HPE/docs-csm/pull/1412
N/A
Nope
> CASMINST-4491: Linting of operations/network/gateway_testing.md

- operations/image_management/Customize_an_Image_Root_Using_IMS.md
- operations/image_management/Import_External_Image_to_IMS.md
- operations/index.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1396
Also pulled in linting commits from this PR:
https://github.com/Cray-HPE/docs-csm/pull/1417
> [Backport release/1.0] CASMCMS-7980 Workflow to import external image to IMS

- upgrade/1.2/scripts/k8s/enable-psp.sh
CASMINST-4495 fixed ssh from failing upon seeing unknown host key signature by adding -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null on line 32 of enable.psp.sh
* Resolves [CASMINST-4495](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4495)
* Change will also be needed in `release/1.2.5`
Verified got past the issue on surtur
LOG_FILE is not …
> CASMINST-4495 fixed ssh from failing upon seeing unknown host key signature

- install/prepare_configuration_payload.md
- troubleshooting/index.md
- troubleshooting/known_issues/initrd.img.zx_not_found.md
See main PR for details:
https://github.com/Cray-HPE/docs-csm/pull/1422
> CASMINST-4496: release/1.2 backport

- install/prepare_configuration_payload.md
- troubleshooting/index.md
- troubleshooting/known_issues/initrd.img.zx_not_found.md
Linting -- no content changes. Linting was of 3 files:
* troubleshooting/index.md
* install/prepare_configuration_payload.md
* troubleshooting/known_issues/initrd.img.zx_not_found.md
* csm-1.0 PR: https://github.com/Cray-HPE/docs-csm/pull/1424
* csm-1.2 PR: https://github.com/Cray-HPE/docs-csm/pull/1423
N/A
N/A
> CASMINST-4496: Linting: troubleshooting, prepare configuration payload

- install/prepare_configuration_payload.md
- troubleshooting/index.md
- troubleshooting/known_issues/initrd.img.zx_not_found.md
See main PR for details:
https://github.com/Cray-HPE/docs-csm/pull/1422
> CASMINST-4496: release/1.0 backport

- install/prepare_site_init.md
> CASMINST-4499: Added \ to encrypt certs.jks.b64 into customizations.yaml

- operations/hardware_state_manager/Set_BMC_Management_Role.md
- operations/index.md
- operations/node_management/Add_Remove_Replace_NCNs.md
- operations/node_management/Add_Remove_Replace_NCNs/Boot_NCN.md
- operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_from_Role.md
Added step to set the BMC management role to Add/Remove/Replace NCN procedure
Also added a link for latest 1.0 csm-docs RPM
Also added cron-job kicker fix (CASMINST-4217)
* Resolves [CASMPET-5557](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5557)
* Change will also be needed in `1.2 change is included in work being done on the CASM-2787-add-remove-ncns-1.2 branch`
fanta
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
> CASMPET-5557 1.0 : Add Set_BMC_Management_Role to Add/Remove/Replace NCN procedure

- install/bootstrap_livecd_usb.md
Install the latest docs after rebooting into the new LiveCD.
No.
* Resolves [CASMINST-4501](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4501)
None.
> CASMINST-4501

- upgrade/1.2/scripts/upgrade/prepare-assets.sh
uninstall canu before we instll a new version
- …
> uninstall canu before we instll a new version

- operations/network/metallb_bgp/Check_BGP_Status_and_Reset_Sessions.md
Fix clear bgp command
CASMTRIAGE-3262
> CASMTRIAGE-3262 Update clear bgp command

- operations/firmware/FAS_Admin_Procedures.md
- operations/firmware/FAS_CLI.md
- operations/firmware/FAS_Filters.md
- operations/firmware/FAS_Recipes.md
- operations/firmware/FAS_Use_Cases.md
- operations/firmware/Update_Firmware_with_FAS.md
- operations/firmware/Updating_Firmware_m001.md
- operations/firmware/Upload_Olympus_BMC_Recovery_Firmware_into_TFTP_Server.md
General linting of FAS topics:
- Corrected formatting of headers and code blocks
- Grammar, wording, and consistency edits
- Removed unnecessary duplicate information
- Minor re-organization of content
* Resolves [STP-3192](https://jira-pro.its.hpecorp.net:8443/browse/STP-3192)
N/A
N/A
N/A
None
> STP-3192 (1.0): organization and linting of FAS topics

- scripts/operations/configuration/apply_csm_configuration.sh
If you run the apply_csm_configuration script with a file named ncn-personalization.json in your current directory, the script will assume this contains an existing CFS configuration that you want to apply the new CSM configuration layer on top of. The script has a flag which allows the user to specify such a file, but even if the flag is not specified, if that file exists in the directory, the script will slurp it up. This behavior is not something a user would guess and caused the problem documented in [CASMINST-4511](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4511). This PR modifies the script so that it will only consume a script as the basis for the new configuration if the user explicitly specifies it on the command line. 
* Would have prevented …
> CASMINST-4520: Only use existing NCN configuration file at user request

- operations/firmware/FAS_Admin_Procedures.md
- operations/firmware/FAS_CLI.md
- operations/firmware/FAS_Filters.md
- operations/firmware/FAS_Recipes.md
- operations/firmware/FAS_Use_Cases.md
- operations/firmware/Update_Firmware_with_FAS.md
- operations/firmware/Updating_Firmware_m001.md
- operations/firmware/Upload_Olympus_BMC_Recovery_Firmware_into_TFTP_Server.md
Manually pulling in the changes that merge in `main` and `release/1.0`.
General linting of FAS topics:
- Corrected formatting of headers and code blocks
- Grammar, wording, and consistency edits
- Removed unnecessary duplicate information
- Minor re-organization of content
* Resolves [STP-3192](https://jira-pro.its.hpecorp.net:8443/browse/STP-3192)
N/A
N/A
N/A
None
> STP-3192-1.2: organization and linting of FAS topics

- install/deploy_management_nodes.md
- install/redeploy_pit_node.md
This is the csm-1.0 backport PR of this PR:
https://github.com/Cray-HPE/docs-csm/pull/1511
EXCEPT it only contains the linting bits -- not the csm-1.2+ specific changes.
> CASMINST-4538: Linting and linter appeasement

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Ensure all images in the precache configmap are cached before we upgrade services.  We've realized that if opa can't pull his image, nothing can pull from nexus.
* Resolves [CASMINST-4550](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4550)
```
====> PRECACHE_EXISTING_NEXUS_IMAGES ...
====> PRECACHE_EXISTING_NEXUS_IMAGES has been completed
====> UPGRADE_PRECACHE_CHART ...
====> UPGRADE_PRECACHE_CHART has been completed
====> PRECACHE_NEW_IMAGES ...
====> PRECACHE_NEW_IMAGES has been completed
```
* `surtur`
Ran the new subset of prerequisites on surtur.
Low
> Ensure new pre-cached images have been cached in addition to existing

- upgrade/1.2/scripts/upgrade/prerequisites.sh
catch EXIT in bash trap
* Resolves [CASMINST-4569](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4569)
> catch EXIT in prereq error handling

- upgrade/1.2/scripts/upgrade/prerequisites.sh
> backport attempt 6

- .spelling
Neither of these are the correct spelling.
> Remove misspelled words

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Use loftsman and section of platform manifest when installing new cray-precache-images chart.  For safety, also remove the old chart first.
* Resolves [CASMINST-4588](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4588)
```
ncn-m001:/usr/share/doc/csm/upgrade/1.2/scripts/upgrade # /usr/share/doc/csm/upgrade/1.2/scripts/upgrade/prerequisites_brad.sh
************
*** NOTE ***
************
LOG_FILE is not specified; use default location: /usr/share/doc/csm/upgrade/1.2/scripts/upgrade/output.log
====> UPGRADE_PRECACHE_CHART ...
====> UPGRADE_PRECACHE_CHART has been completed
[OK] - Successfully completed
```
```
ncn-m001:/usr/share/doc/csm/upgrade/1.2/scripts/upgrade # cat /usr/share/doc/csm/upgrade/1.2/scripts/upgrade/output.log
release "cray-precache-images" uninstalled …
```
> Fix UPGRADE_PRECACHE_CHART step to use loftsman/manifest

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Remove old precache step that staged 1.x nexus images, instead on upgrade include in the configmap so a new NCN that comes up can host nexus.
* Resolves [CASMINST-4595](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4595)
```
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
configmap/cray-precache-images configured
ncn-w002: Warning: Permanently added 'ncn-w002,10.252.1.8' (ECDSA) to the list of known hosts.
ncn-w001: Warning: Permanently added 'ncn-w001,10.252.1.7' (ECDSA) to the list of known hosts.
ncn-w003: Warning: Permanently added 'ncn-w003,10.252.1.9' (ECDSA) to the list of known hosts.
ncn-w002: Image is up to date for sha256:b25d788808d84488e6c297ef69505933726f988f666f77265121e3f13ed33a1a
ncn-w002: Image is …
```
> Ensure images needed by pre-upgraded nexus are in precache configmap

- .spelling
- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- operations/configuration_management/VCS_Branching_Strategy.md
- operations/image_management/Customize_an_Image_Root_Using_IMS.md
- operations/kubernetes/Kubernetes_Storage.md
- operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
- operations/power_management/Liquid_Cooled_Node_Card_Power_Management.md
- operations/power_management/Power_On_Compute_and_IO_Cabinets.md
- operations/security_and_authentication/Manage_Sealed_Secrets.md
- troubleshooting/known_issues/component_power_state_mismatch.md
- troubleshooting/known_issues/discovery_job_not_creating_redfish_endpoints.md
csm-1.0 backport of this PR:
https://github.com/Cray-HPE/docs-csm/pull/1520
> csm-1.0 backport: CASMINST-4552: Linting / CASMINST-4582: Remove csi init example from bootstrap docs

- .spelling
- operations/network/management_network/1.0_to_1.2_upgrade.md
- operations/network/management_network/aruba/index.md
- operations/network/management_network/canu/canu_verify_generate_compare_switch_configuration.md
- operations/network/management_network/canu/quick_start_guide_to_canu.md
- operations/network/management_network/dell/index.md
- operations/network/management_network/generate_switch_configs.md
- operations/network/management_network/index.md
- operations/network/management_network/mellanox/index.md
- operations/network/management_network/network_tests.md
- operations/network/management_network/validate_shcd.md
- operations/network/management_network/validate_switch_configs.md
Fixing the spelling errors from the main PR which were made moments too late for the original PR merge:
https://github.com/Cray-HPE/docs-csm/pull/1489
> CASMINST-4531: More linting

- .spelling
Backport of https://github.com/Cray-HPE/docs-csm/pull/1578
> csm-1.0 backport: CASMINST-4531: More linting

- .spelling
- operations/network/management_network/1.0_to_1.2_upgrade.md
- operations/network/management_network/aruba/index.md
- operations/network/management_network/canu/canu_verify_generate_compare_switch_configuration.md
- operations/network/management_network/canu/quick_start_guide_to_canu.md
- operations/network/management_network/dell/index.md
- operations/network/management_network/generate_switch_configs.md
- operations/network/management_network/index.md
- operations/network/management_network/mellanox/index.md
- operations/network/management_network/network_tests.md
- operations/network/management_network/validate_shcd.md
- operations/network/management_network/validate_switch_configs.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1578
> csm-1.2 backport: CASMINST-4531: More linting

- operations/index.md
- operations/kubernetes/Troubleshoot_Intermittent_503s.md
Add operational procedure for intermittent API 503 errors
* Resolves [CASMTRIAGE-3317](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3317)
Procedure was performed on vale.
* `vale`
Procedure was performed on vale.
Low
> Add operational procedure for intermittent API 503 errors

- operations/boot_orchestration/Customize_iPXE_Binary_Names.md
- operations/index.md
Add procedure to update iPXE binary names.
* Resolves [CASMCMS-7993](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7993)
> CASMCMS-7993 Add procedure to update iPXE name

- update_product_stream/index.md
- upgrade/1.2/Stage_0_Prerequisites.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1594
> csm-1.2 backport: CASMINST-4599: Download docs-csm RPM so that it overwrites existing copies

- upgrade/1.2/scripts/common/upgrade-state.sh
- fix double trap
* Resolves [[issue id](issue link)](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4605)
- Were new tests (or test issues/Jiras) created for this …
> fix double trap

- upgrade/1.2/scripts/common/ncn-common.sh
- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
- upgrade/1.2/scripts/upgrade/prepare-assets.sh
default output.log location should be /root
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4622
- Were the install/upgrade-based validation checks/tests run (goss …
> default output.log location should be /root

- upgrade/1.2/scripts/common/ncn-common.sh
- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
- upgrade/1.2/scripts/upgrade/prepare-assets.sh
> [backport] default output.log location should be /root

- .spelling
- operations/image_management/Build_a_New_UAN_Image_Using_the_Default_Recipe.md
- operations/image_management/Upload_and_Register_an_Image_Recipe.md
Backport PR of this main PR: https://github.com/Cray-HPE/docs-csm/pull/1616
> csm-1.2 backport: CASMINST-4624: Linting

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
csm-1.2 backport of https://github.com/Cray-HPE/docs-csm/pull/1622
> csm-1.2 backport: Corrections to install bootstrap PIT procedures

- .spelling
- operations/image_management/Build_a_New_UAN_Image_Using_the_Default_Recipe.md
- operations/image_management/Upload_and_Register_an_Image_Recipe.md
csm-1.0 backport of this main branch PR: https://github.com/Cray-HPE/docs-csm/pull/1616
> csm-1.0 backport: CASMINST-4624: Linting

- .spelling
- operations/image_management/Build_a_New_UAN_Image_Using_the_Default_Recipe.md
- operations/image_management/Upload_and_Register_an_Image_Recipe.md
Pure linting of two operational documents -- no content changes.
Backport PRs:
csm-1.2: https://github.com/Cray-HPE/docs-csm/pull/1617
csm-1.0: https://github.com/Cray-HPE/docs-csm/pull/1618
> CASMINST-4624: Linting

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
Backport of this PR: https://github.com/Cray-HPE/docs-csm/pull/1561
> (csm-1.2 backport) CASMINST-4589: Install document linting, corrections, and improvements

- install/deploy_management_nodes.md
- install/redeploy_pit_node.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
Backport of this PR: https://github.com/Cray-HPE/docs-csm/pull/1561
> csm-1.0 backport: CASMINST-4589: Install document linting, corrections, and improvements

- install/create_switch_metadata_csv.md
Fix mgmt network leaf-bmc switch naming.
CASMINST-4583
> CASMINST-4583 1.2

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
This adds a block to fresh installs for RemoteISOs and USB Sticks to ensure users make `system_config.yaml` to `pit-init`.
* Resolves [CASMTRIAGE-3342](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3342)
* Change will also be needed in `release/1.2` and `release/1.0`
* `redbull`
Doc step produced a useable `system_config.yaml` for `pit-init` to find. …
> CASMTRIAGE-3342 Ensure fresh installs copy system_config.yaml into place

- operations/validate_csm_health.md
- troubleshooting/known_issues/ssl_certificate_validation_issues.md
This adds additional documentation for common SSL Failures.
> CASMPET-5619 Update ssl certificate validation issues page

- operations/node_management/Configure_NTP_on_NCNs.md
Uses the full path for `csm_ntp.py`
* Resolves  CASMINST-4625
* 
N/A
Low
> Casminst 4625 main

- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
Reverts Cray-HPE/docs-csm#1637
> Revert "CASMTRIAGE-3336 run csm_ntp.py everytime during upgrade and wait for …"

- .github/config/markdown_style.yaml
- .spelling
- operations/validate_csm_health.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_1.md
- upgrade/1.2/Stage_2.md
- upgrade/1.2/Stage_3.md
- upgrade/1.2/Stage_4.md
- upgrade/1.2/Stage_5.md
- upgrade/index.md
Backport PR for https://github.com/Cray-HPE/docs-csm/pull/1653
> csm-1.2 backport: CASMINST-4644: Upgrade procedure linting, fixes, and improvements

- operations/network/dns/Troubleshoot_PowerDNS.md
Basic MitchLint -- no content changes.
csm-1.2 backport PR forthcoming.
> CASMINST-4666: Linting

- operations/network/dns/Troubleshoot_PowerDNS.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1675
> csm-1.2 backport: CASMINST-4666: Linting

- background/ncn_mounts_and_file_systems.md
- background/ncn_plan_of_record.md
The NCN behavior is a little less explicit and allows some freedom in the selection of OS disks.
Additionally NVME is fundamentally supported with the MTL-1748 changes.
Yes.
* Resolves [MTL-1747](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1747)
> MTL-1748 Update PoR to Align with NCN Behavior

- install/scripts/csm_services/steps/4.deploy_csm_application_and_services.yaml
- install/troubleshooting_installation.md
add PG troubleshooting link in installation troubleshooting doc
* Resolves CASMINST-4650
* 
> add PG troubleshoot link in installation troubleshooting doc

- install/deploy_management_nodes.md
- install/install_csm_services.md
- install/prepare_management_nodes.md
- operations/node_management/Reboot_NCNs.md
- operations/validate_csm_health.md
- upgrade/1.2/README.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_3.md
Most of these issues amount to linting or reorganizing procedures for clarity.
Backport PRs:
csm-1.2 https://github.com/Cray-HPE/docs-csm/pull/1673
csm-1.0 https://github.com/Cray-HPE/docs-csm/pull/1674
In the limited cases where commands were altered, I tested the revised commands on both hermod and hela.
Low risk. Most changes are minor and done to make things clearer and easier for installers.
> CASMINST-4665: Linting, fixes, and enhancements from issues found during CSM install

- install/deploy_management_nodes.md
- install/install_csm_services.md
- install/prepare_management_nodes.md
- operations/node_management/Reboot_NCNs.md
- operations/validate_csm_health.md
- upgrade/1.2/README.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_3.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1672
> csm-1.2 backport: CASMINST-4665: Linting, fixes, and enhancements from issues found during CSM install

- .github/config/markdown_link.json
- .spelling
- install/deploy_management_nodes.md
- install/index.md
- introduction/scenarios.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/CSM_product_management/Perform_NCN_Personalization.md
- upgrade/index.md
Updated all references to the 1.5 Getting Started Guide with the updated title and vanity link for the 22.06 release.
**NOTE:** The updated URL in this PR is a vanity URL. It is expected to be broken at the moment and will not be a functioning link until the GSG is actually published for the release.
* Resolves [CASMINST-4623](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4623)
> CASMINST-4623: Updated references to the GSG

- operations/configuration_management/Automatic_Session_Deletion_with_sessionTTL.md
- operations/configuration_management/Delete_CFS_Sessions.md
Backport of this PR: https://github.com/Cray-HPE/docs-csm/pull/1679
> csm-1.2 backport: CASMINST-4685: Linting

- operations/configuration_management/Automatic_Session_Deletion_with_sessionTTL.md
- operations/configuration_management/Delete_CFS_Sessions.md
Just pure linting. No content changes.
Backport PRs:
csm-1.2 https://github.com/Cray-HPE/docs-csm/pull/1680
csm-1.0 https://github.com/Cray-HPE/docs-csm/pull/1681
> CASMINST-4685: Linting

- operations/configuration_management/Automatic_Session_Deletion_with_sessionTTL.md
- operations/configuration_management/Delete_CFS_Sessions.md
Backport of this PR: https://github.com/Cray-HPE/docs-csm/pull/1679
> csm-1.0 backport: CASMINST-4685: Linting

- upgrade/1.2/README.md
document generic rerun strategy for upgrade failures
* Resolves CASMINST-4669
_Are there known issues with …
> CASMINST-4669 document generic rerun strategy for upgrade failures

- .spelling
- install/deploy_final_ncn.md
- operations/validate_csm_health.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1689
> csm-1.2 backport: CASMINST-4693: Install documentation improvements and linting

- .spelling
- install/redeploy_pit_node.md
- operations/validate_csm_health.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1689
> csm-1.0 backport: CASMINST-4693: Install documentation improvements and linting

- .spelling
- install/deploy_final_ncn.md
- operations/validate_csm_health.md
Fixing minor errors and making small improvements to the install documentation, based on the ongoing hermod install.
Backport PRs:
csm-1.2 https://github.com/Cray-HPE/docs-csm/pull/1690
csm-1.0 https://github.com/Cray-HPE/docs-csm/pull/1691
> CASMINST-4693: Install documentation improvements and linting

- operations/node_management/Reboot_NCNs.md
> egrep command to verify method of boot changed

- operations/node_management/Reboot_NCNs.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1708
> Casminst 4698 1.0 backport

- background/ncn_boot_workflow.md
- install/collecting_bmc_mac_addresses.md
- operations/boot_orchestration/Tools_for_Resolving_Boot_Issues.md
- operations/configuration_management/Version_Control_Service_VCS.md
- operations/node_management/Change_Settings_for_HMS_Collector_Polling_of_Air_Cooled_Nodes.md
- operations/node_management/Change_Settings_in_the_Bond.md
- operations/node_management/Check_the_BMC_Failover_Mode.md
- operations/node_management/Reboot_NCNs.md
- operations/node_management/Update_the_Gigabyte_Node_BIOS_Time.md
- operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
- operations/resiliency/Restore_System_Functionality_if_a_Kubernetes_Worker_Node_is_Down.md
- troubleshooting/kubernetes/Troubleshoot_Unresponsive_kubectl_Commands.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1693
> csm-1.0 backport: CASMINST-4695: Linting and other small corrections and improvement

- upgrade/1.2/scripts/rebuild/ncn-rebuild-worker-nodes.sh
- upgrade/1.2/scripts/upgrade/prerequisites.sh
Backport PR for https://github.com/Cray-HPE/docs-csm/pull/1701
> csm-1.2 backport: CASMINST-4707: Specify Cray CLI output format when it matters

- operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
> Added reference to docs for Token generation

- .spelling
Backported commit from: https://github.com/Cray-HPE/docs-csm/pull/1724
> Add Podman to spelling file

- install/csm_installation_failure.md
- install/install_csm_services.md
- install/scripts/csm_services/steps/6.set_management_NCN_to_use_unbound.yaml
- install/troubleshooting_installation.md
…during install
Documenting issue and workaround for an issue seen during fresh installs on 1.2
* ResolvesCASMINST-4651
* 1.2 cherry-pick of changes in https://github.com/Cray-HPE/docs-csm/pull/1717
Surtur
* Surtur
n/a
None
> Casminst 4651 doc changes for 1.2

- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
- upgrade/1.2/scripts/rebuild/prerequisites.sh
Cherry-pick of https://github.com/Cray-HPE/docs-csm/pull/1707
> Don't run ntp fix from ncn-m002 --> ncn-m001

- install/shcd_hmn_connections_rules.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1752
> [Backport release/1.0] Add blank lines after table block

- upgrade/1.2/Stage_2.md
> Added missing && in Copy Artifacts step

- install/configure_administrative_access.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/configure_cray_cli.md
I have noted some minor errors in the install docs during the csm-1.2.,0-rc.2 install of tyr. I'm correcting several of them with this ticket. These aren't showstoppers but should be fixed.
As is my way, there's also a heaping helping of linting.
Backport PRs forthcoming.
No procedural changes made.
> CASMINST-4759: Correct minor install docs issues

- install/configure_administrative_access.md
- operations/CSM_product_management/Configure_Non-Compute_Nodes_with_CFS.md
- operations/configure_cray_cli.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1749
> csm-1.0 backport: CASMINST-4759: Correct minor install docs issues

- operations/boot_orchestration/Sessions.md
Removing the 1.5 specific heading and doing some minor editing throughout the file.
* Resolves [STP-3180](https://jira-pro.its.hpecorp.net:8443/browse/STP-3180)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1686
N/A
N/A
N/A
None.
> STP-3180: Removing 1.5 specific heading in BOS topic

- operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
- upgrade/1.2/Stage_2.md
Add manual check before we rebuild/upgrade a worker node.  Note that this is only for 1.2 and in future releases, this issue would be addressed by code.
* Resolves CASMINST-4748
- …
> 1.2 only: add a note to manually move pods if necessary

- .github/config/markdown_style.yaml
- .spelling
- operations/boot_orchestration/Boot_UANs.md
- operations/boot_orchestration/Tools_for_Resolving_Boot_Issues.md
- operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md
- operations/configuration_management/View_Configuration_Session_Logs.md
- operations/image_management/Build_an_Image_Using_IMS_REST_Service.md
- operations/image_management/Convert_TGZ_Archives_to_SquashFS_Images.md
- operations/image_management/Create_UAN_Boot_Images.md
- operations/image_management/Customize_an_Image_Root_Using_IMS.md
- operations/image_management/Import_External_Image_to_IMS.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1775
> [Backport release/1.0] CASMINST-4780: Linting

- .spelling
- operations/kubernetes/Retrieve_Cluster_Health_Information_Using_Kubernetes.md
- operations/node_management/Troubleshoot_Loss_of_Console_Connections_and_Logs_on_Gigabyte_Nodes.md
- operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1801
> csm-1.2 backport: CASMINST-4712: Update outdated cray-conman references

- .spelling
- operations/kubernetes/Retrieve_Cluster_Health_Information_Using_Kubernetes.md
- operations/node_management/Troubleshoot_Loss_of_Console_Connections_and_Logs_on_Gigabyte_Nodes.md
- operations/security_and_authentication/Updating_the_Liquid-Cooled_EX_Cabinet_Default_Credentials_after_a_CEC_Password_Change.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1801
> csm-1.0 backport: CASMINST-4712: Update outdated cray-conman references

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Reverts Cray-HPE/docs-csm#1803
> Revert "Update anti-affinity for istio ingress gateways to required during upgrade"

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Reverts Cray-HPE/docs-csm#1810
> Revert "Revert "Update anti-affinity for istio ingress gateways to required during upgrade""

- upgrade/1.2/scripts/k8s/remove_istio_req_affinity.sh
- upgrade/1.2/scripts/upgrade/csm-upgrade.sh
In order for the istio chart to successfully install, the temporary required anti-affinity for ingress pods must be removed.
* Resolves [CASMINST-4789](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4789)
```
ncn-m001:/usr/share/doc/csm/upgrade/1.2/scripts/upgrade # ./prerequisites-brad.sh
************
*** NOTE ***
************
LOG_FILE is not specified; use default location: /root/output.log
====> POD_ANTI_AFFINITY ...
====> POD_ANTI_AFFINITY has been completed
[OK] - Successfully completed
```
```
ncn-m001:~/bklein # ./upgrade.sh
deployment.apps/istio-ingressgateway patched
Waiting for deployment spec update to be observed...
Waiting for deployment "istio-ingressgateway" rollout to finish: 0 out of 3 new replicas have been updated...
Waiting for deployment "istio-ingressgateway" …
```
> Remove istio required anti-affinity prior to chart install

- operations/network/management_network/dell/ntp.md
- operations/network/management_network/mellanox/ntp.md
The #1554 PR had several rebases and within these two merge conflicts were overlooked. This PR corrects those.
> MTL-1695 Fixup merge conflict in network/*/ntp.py files

- operations/utility_storage/Troubleshoot_System_Clock_Skew.md
- operations/validate_csm_health.md
- upgrade/1.2/README.md
- upgrade/1.2/resource_material/README.md
Add notes about how long it can take for NCN clocks to sync
> CASMISNT-4800: add notes about how long it can take for NCN clocks to sync

- upgrade/1.2/Stage_4.md
Need clarification for how to interpret output of ceph command (https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4643).
> Add clarification in stage 4 for ceph command output verification (CASMINST-4643)

- install/collect_mac_addresses_for_ncns.md
- operations/boot_orchestration/Boot_UANs.md
- operations/compute_rolling_upgrades/Upgrade_Compute_Nodes_with_CRUS.md
- operations/configuration_management/View_Configuration_Session_Logs.md
- operations/image_management/Convert_TGZ_Archives_to_SquashFS_Images.md
- operations/image_management/Import_External_Image_to_IMS.md
- upgrade/1.2/scripts/sls/expert_mode.md
Backport: https://github.com/Cray-HPE/docs-csm/pull/1847
> backport: CASMINST-4815: Linting and minor improvements

- operations/CSM_product_management/Post_Install_Customizations.md
The Prometheus and Grafana steps were improved. Added spaces to the "Kubernetes/Compute Resources/Pod" dashboard name, otherwise the search will not work properly in Grafana.
* Resolves [STP-3237](https://jira-pro.its.hpecorp.net:8443/browse/STP-3237)
> STP-3237 (1.0 backport): Clarified steps and updated links in post-install customizations

- troubleshooting/index.md
- troubleshooting/known_issues/SLS_Not_Working_During_Node_Rebuild.md
Backport of: https://github.com/Cray-HPE/docs-csm/pull/1866
> CASMINST-4820: Add troubleshooting/remediation steps for SLS postgres SyncFailed

- .spelling
- operations/hpe_pdu/hpe_pdu_admin_procedures.md
- operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md
- operations/validate_csm_health.md
Updated documentation for ServerTech and HPE PDU.
CASMHMS-5367
CASMHMS-5576
> CASMHMS-5367 Update to PDU documentation

- .spelling
- operations/hpe_pdu/hpe_pdu_admin_procedures.md
- operations/security_and_authentication/Change_Credentials_on_ServerTech_PDUs.md
- operations/validate_csm_health.md
Updated documentation for ServerTech and HPE PDU.
CASMHMS-5367
CASMHMS-5576
> CASMHMS-5367 PDU Document Changes

- install/pre-installation.md
These links had worked, I'm not sure how they broke but the `-` breaks the links.
> MTL-1695 Fix broken links

- scripts/operations/configuration/apply_csm_configuration.sh
Backport of: https://github.com/Cray-HPE/docs-csm/pull/1875
> CASMINST-4831: Add minimal argument checking to apply_csm_configuration.sh

- upgrade/1.2/scripts/upgrade/util/update-customizations.sh
This covers the upgrade scenario of the companion change to `csi`:
https://github.com/Cray-HPE/cray-site-init/pull/192
I modified this script to run locally and pointed it to hermod with the craycli:
```
-NETWORKSJSON=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" https://api-gw-service-nmn.local/apis/sls/v1/networks)
+ cray config use hermod
+NETWORKSJSON=$(cray sls networks list)
```
After running the script, I compared the values for the wlm section and saw the two new routes for HMN and HMNLB:
```
routes:
- dst: 10.106.0.0/17
gw: 10.252.0.1
- dst: 10.92.100.0/24
gw: 10.252.2.6
- dst: 10.101.3.0/25
gw: 10.252.0.1
routes:
- dst: 10.106.0.0/17
gw: 10.252.0.1
- dst: 10.101.3.0/25
gw: 10.252.0.1
- dst: 10.92.100.0/24
gw: 10.252.2.6
- dst: 10.254.0.0/17     <-- new HMN route
gw: …
```
> CASMUSER-3028: Add HMN and HMNLB blackhole route for the upgrade path

- .spelling
- install/index.md
- operations/system_management_health/Access_System_Management_Health_Services.md
- operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
- operations/validate_csm_health.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1903
> CASMINST-4847: Minor improvements related to CSM health validation

- install/install_csm_services.md
Backport of this PR:
https://github.com/Cray-HPE/docs-csm/pull/1929
> CASMINST-4857: Add manual step to create BSS Global bootparameters

- upgrade/1.2/scripts/common/ncn-rebuild-common.sh
CSM-1.2 images contain a pool.conf file that needs to be removed.
This is one of the things csm_ntp.py can fix, so invoke it before
attempting to sync the clock.
Also, add a wait loop like we have in prerequsites.sh.  The 5s wait
is not always enough.
This is ugly from a code duplication POV, but less risky than trying
to reorganize the code at this point in time.
> CASMINST-4863: run csm_ntp.py on a newly imaged/upgraded node

- .spelling
- operations/index.md
- operations/system_management_health/Grafana_Dashboards_by_Component.md
- troubleshooting/index.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1434
> CASMMON-129: Create listing of Grafana Dashboards by Component

- .spelling
- operations/index.md
- operations/system_management_health/Grafana_Dashboards_by_Component.md
- troubleshooting/index.md
Added Grafana Dashboard documentation
Update:
main backport: https://github.com/Cray-HPE/docs-csm/pull/1858
1.0 backport: https://github.com/Cray-HPE/docs-csm/pull/1925
> CASMMON-129 Added Grafana_Dashboards_by_Component.md documentation

- operations/node_management/Add_additional_Liquid-Cooled_Cabinets_to_a_System.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1902
> CASMINST-3806 - add management network steps for adding mountain cabinet 

- .shellcheck
- upgrade/1.2/scripts/common/ncn-common.sh
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3639
> CASMTRIAGE-3639 Increase sls health check timeout to allow for pg operator restart

- operations/security_and_authentication/Create_a_Service_Account_in_Keycloak.md
Since python 2 is no longer installed, this command no longer works. This updates the code snipppet to use python 3.
> CASMTRIAGE-3545 Update command to use python3

- .spelling
- install/README.md
- operations/system_management_health/Configure_Prometheus_Alerta_Alert_Notifications.md
- operations/system_management_health/Configure_Prometheus_Email_Alert_Notifications.md
As part of SMH integration with SMF integration Port Prometheus Alerts and Notifications.
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-127
CASMMON-127 : port Prometheus Alerts and Notifications to alerta
EPIC: CASM-1606 : https://jira-pro.its.hpecorp.net:8443/browse/CASM-1606
> CASMMON-127:port Prometheus Alerts and Notifications to alarta

- operations/CSM_product_management/Validate_Signed_RPMs.md
Backport changes of Jira STP-3179.
> STP:3179-release1.0: Backport changes

- .spelling
- operations/kyverno/Kyverno.md
Add kyverno documentation for end-user reference -> [CASMPET-5721](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5721)
> CASMPET-5721 Create Kyverno.md

- troubleshooting/known_issues/admin_client_auth_not_found.md
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4875
> Add troubleshooting doc for admin-client-auth secret not found

- upgrade/1.2/Stage_1.md
Context: upgrade
Note: this is not needed in the `main` branch.
> CASMINST-4874: add a bullet to the Known Issues for the clock skew test

- upgrade/1.2.6/README.md
- upgrade/1.2.6/scripts/update-customization.sh
> fix missing customizations

- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
Change for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3654
> CASMTRIAGE-3654 Correct order of keycloak password change encryption step

- operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
Change for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3654
> Correct order of keycloak password change encryption step

- .spelling
- upgrade/1.2/README.md
This adds a known issues section to the upgrade doc and includes a known issue for CASMTRIAGE-3591.
> CASMTRIAGE-3591 Add notice about kdump

- operations/network/management_network/load_saved_switch_config.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1945
> CASMTRIAGE-3641 add ACL reset procedure

- upgrade/1.2/README.md
> CASMTRAIGE-3591 (1.2): added kdump notice

- operations/network/management_network/aruba/check_bgp_and_metallb.md
- operations/network/management_network/aruba/check_dhcp_lease_is_getting_allocated.md
- operations/network/management_network/aruba/check_hsm.md
- operations/network/management_network/aruba/duplicate_ip.md
- operations/network/management_network/aruba/management_network_configuration_example.md
- operations/network/management_network/aruba/ncn_tcpdump.md
- operations/network/management_network/aruba/network_traffic_pattern.md
- operations/network/management_network/aruba/spine_leaf_architecture2.md
- operations/network/management_network/aruba/verify-switches_are_forwarding_dhcp_traffic.md
- operations/network/management_network/canu/initializing_canu.md
- operations/network/management_network/mellanox/large.md
- operations/network/management_network/mellanox/medium.md
- operations/network/management_network/mellanox/small.md
- operations/network/management_network/mellanox/very_large.md
- operations/network/management_network/validate_shcd.md
Just basic linting and other minor improvements. No substantive changes.
> CASMINST-4911: Linting

- .spelling
- install/collecting_bmc_mac_addresses.md
- install/configure_management_network.md
- install/install_csm_services.md
- operations/configuration_management/Ansible_Inventory.md
- operations/configuration_management/Create_an_Image_Customization_CFS_Session.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1992
> CASMINST-4913: Linting

- .github/config/markdown_style.yaml
- operations/firmware/FAS_CLI.md
- operations/firmware/FAS_Recipes.md
- operations/firmware/Updating_Firmware_without_FAS.md
- operations/kubernetes/Disaster_Recovery_Postgres.md
- operations/kubernetes/TDS_Lower_CPU_Requests.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/1991
> CASMINST-4912: Linting

- upgrade/1.2/scripts/upgrade/prerequisites.sh
remove steps in 1.3 upgrade that are not needed
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4922
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4925
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4928
> CASMINST-4922 - remove disable services repos

- upgrade/1.2/scripts/upgrade/prerequisites.sh
This will prevent needing to track specific versions by release and edit this script each time -- https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4941.
This will prevent needing to track specific versions by release and edit this script each time.
> CASMINST-4941 Refactor pre-caching of pre-upgrade nexus images

- operations/node_management/Add_a_Standard_Rack_Node.md
Link net docs to `Add_a_Standard_Rack_Node.md` procedure
> CASMTRIAGE-3101

- upgrade/Stage_4.md
Just getting the base doc updated.  we can adjust from here.
This introduces the cubs_tool.py script
> CASMINST-4946 Stage4 - ceph service upgrade rewrite draft

- upgrade/README.md
- upgrade/Stage_0_Prerequisites.md
- upgrade/Stage_1.md
- upgrade/Stage_2.md
- upgrade/Stage_3.md
- upgrade/scripts/rebuild/ncn-rebuild-master-nodes.sh
- upgrade/scripts/sls/README.SLS_Upgrade.md
- upgrade/scripts/upgrade/csm-upgrade.sh
- upgrade/scripts/upgrade/ncn-upgrade-ceph-nodes.sh
- upgrade/scripts/upgrade/ncn-upgrade-master-nodes.sh
- upgrade/scripts/upgrade/prepare-assets.sh
- upgrade/scripts/upgrade/prerequisites.sh
- upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
- upgrade/upgrade_ncn_nodes.md
> CASMINST-4967 fix hard coded path

- troubleshooting/interpreting_hms_health_check_results.md
This PR updates the Table of Contents for interpreting_hms_health_check_results.md to look more compact and fixes broken links in the document.
* Resolves CASMHMS-5619.
Low risk, test documentation update.
> CASMHMS-5619 Fix broken links in interpreting_hms_health_check_results.md Main

- .spelling
- background/certificate_authority.md
- background/ncn_bios.md
- background/ncn_mounts_and_file_systems.md
- operations/network/management_network/aruba/check_hsm.md
- operations/network/management_network/aruba/dhcp_decline.md
- operations/network/management_network/mellanox/check_hsm.md
- operations/network/management_network/mellanox/dhcp_decline.md
- operations/node_management/Adding_a_Liquid-cooled_blade_to_a_System.md
- operations/node_management/Swap_a_Compute_Blade_with_a_Different_System.md
- operations/security_and_authentication/Add_LDAP_User_Federation.md
- update_product_stream/index.md
Linting, and other linting-adjacent improvements and minor reorganizations.
> CASMINST-4973: Linting

- .spelling
- install/create_switch_metadata_csv.md
- install/shcd_hmn_connections_rules.md
- operations/node_management/Add_Remove_Replace_NCNs/Add_NCN_Data.md
- operations/node_management/Add_Remove_Replace_NCNs/Allocate_NCN_IP_Addresses.md
- operations/node_management/Add_a_Standard_Rack_Node.md
- operations/system_layout_service/Add_Liquid-Cooled_Cabinets_To_SLS.md
- scripts/operations/node_management/Add_Remove_Replace_NCNs/sls_utils/ipam.py
- upgrade/1.2/scripts/sls/README.SLS_Upgrade.md
- upgrade/1.2/scripts/sls/add_computes_to_chn.py
- upgrade/1.2/scripts/sls/csm_1_2_upgrade/sls_updates.py
- upgrade/1.2/scripts/sls/expert_mode.md
- upgrade/1.2/scripts/sls/sls_utils/README.md
- upgrade/1.2/scripts/sls/sls_utils/ipam.py
Backport of https://github.com/Cray-HPE/docs-csm/pull/2082
> CASMINST-5024: Correcting errors; linting

- scripts/nexus-export.sh
Add in check to the nexus export script to check there is enough space before taking the export.
> CASMPET-5823: Nexus export fix to check for space

- upgrade/scripts/upgrade/ncn-upgrade-worker-nodes.sh
- upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
- it should auto retry on rerun
- it should let use specify what to do (retry/rerun)
- it should not have used files with plaintext password
- it should be able to run from outside of m001
> CASMINST-5059 - rewrite worker upgrade script

- upgrade/1.2/scripts/upgrade/prerequisites.sh
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5107 -- bump chart timeout for pre-cache images daemonset.
```
apiVersion: manifests/v1beta1
metadata:
name: brad
spec:
charts:
- name: cray-precache-images
namespace: nexus
version: 0.5.6
timeout: 20m0s  <-----
values:
cacheImages:
- artifactory.algol60.net/csm-docker/stable/docker.io/weaveworks/weave-kube:2.8.1
- artifactory.algol60.net/csm-docker/stable/docker.io/weaveworks/weave-npc:2.8.1
- artifactory.algol60.net/csm-docker/stable/docker.io/nfvpe/multus:v3.7
. 
. 
. 
```
```
bash-5.1# /tmp/loftsman  ship --manifest-path /workspace/.cache/manifest.yaml --charts-path /workspace/.cache/charts --json-log-path /workspace/.cache/loftsman.json.log
2022-07-25T18:45:33Z INF Initializing the connection to the Kubernetes cluster …
```
> CASMINST-5107 Increase loftsman timeout for precache images chart

- upgrade/scripts/upgrade/prerequisites.sh
This new stage will set and delete kernel parameters for an upgrade.
Initially this adds the new parameters for MTL-1612 to enable pressure stats.
> MTL-1612 Add Kernel Paramter Update Stage

- operations/validate_csm_health.md
The issue requiring this workaround was fixed by [CASMNET-1674](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1674) and it is no longer necessary to force recreation of the zone once the HSM ethernetInterfaces data has been populated by Kea.
> CASMINST-5120 - Remove unnecessary PowerDNS workaround from internal SSH test

- background/ncn_boot_workflow.md
- install/collecting_ncn_mac_addresses.md
- operations/boot_orchestration/Tools_for_Resolving_Boot_Issues.md
- operations/conman/Troubleshoot_ConMan_Blocking_Access_to_a_Node_BMC.md
- operations/conman/Troubleshoot_ConMan_Failing_to_Connect_to_a_Console.md
- operations/hardware_state_manager/Set_BMC_Management_Role.md
- operations/node_management/Access_and_Update_the_Settings_for_Replacement_NCNs.md
- operations/node_management/Add_Remove_Replace_NCNs.md
- operations/node_management/Add_Remove_Replace_NCNs/Add_NCN_Data.md
- operations/node_management/Add_Remove_Replace_NCNs/Boot_NCN.md
- operations/node_management/Add_Remove_Replace_NCNs/Collect_NCN_MAC_Addresses.md
- operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_Data.md
- operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_from_Role.md
- operations/node_management/Change_Settings_for_HMS_Collector_Polling_of_Air_Cooled_Nodes.md
- operations/node_management/Check_the_BMC_Failover_Mode.md
- operations/node_management/Reboot_NCNs.md
- operations/node_management/Rebuild_NCNs/Power_Cycle_and_Rebuild_Nodes.md
- operations/node_management/Troubleshoot_Loss_of_Console_Connections_and_Logs_on_Gigabyte_Nodes.md
- operations/node_management/Update_the_Gigabyte_Node_BIOS_Time.md
- operations/power_management/Power_On_and_Start_the_Management_Kubernetes_Cluster.md
- operations/power_management/Shut_Down_and_Power_Off_the_Management_Kubernetes_Cluster.md
- operations/resiliency/Restore_System_Functionality_if_a_Kubernetes_Worker_Node_is_Down.md
- troubleshooting/kubernetes/Troubleshoot_Unresponsive_kubectl_Commands.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/2112
> CASMINST-5093: Linting

- operations/image_management/Create_UAN_Boot_Images.md
- operations/security_and_authentication/Update_NCN_Passwords.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/2137
> CASMINST-5134/CASMTRIAGE-3817: Corrections to password setting/changing procedures

- install/pre-installation.md
> CASMINST-5135 Make typescript in `admin/`

- scripts/nexus-space-usage.sh
This changes the reporting script to not need an external jar to get information needed to clean up nexus.
> CASMPET-5843: Change nexus-space-usage to not need external jar

- upgrade/scripts/upgrade/ncn-upgrade-worker-nodes.sh
- workflows/ncn/worker/worker.wipe-and-reboot.yaml
- make retry default
- handle edge case of endpoint-history
> CASMINST-5140 make retry default; handle edge case of endpoint-history

- operations/utility_storage/Troubleshoot_S3FS_Mounts.md
- troubleshooting/index.md
Add S3FS mount troubleshooting procedure (https://jira-pro.its.hpecorp.net:8443/browse/CAST-30646).
> CAST-30646 Add troubleshooting procedure for S3FS mount points

- operations/network/management_network/canu_install_update.md
- operations/network/management_network/fresh_install.md
- operations/network/management_network/index.md
- operations/network/management_network/reinstall.md
> CASMNET-1744 canu install/upgrade procedure "1.2"

- operations/network/management_network/README.md
- operations/network/management_network/canu_install_update.md
- operations/network/management_network/fresh_install.md
- operations/network/management_network/reinstall.md
> CASMNET-1744 canu install/upgrade procedure "main"

- install/pre-installation.md
> CASMINST-5174 Removed final exit typescript

- install/pre-installation.md
> CASMINST-5173 Fixed spelling error related to ncn-modification

- troubleshooting/README.md
Adding network troubleshoooting documentation and re-organizing content
> CASMNET-1746 | adding network troubleshoooting documentation and re-organizing content

- operations/validate_csm_health.md
- scripts/operations/validation/ncn121.sh
- troubleshooting/known_issues/ncn_resource_checks.md
Implemented POD and FS checks as part of 1.2
> CASMINST-5066 Implemented NCN resource checks

- upgrade/scripts/common/ncn-rebuild-common.sh
- remove auto retry
- use ipmi over ssh to reboot
surtur
> CASMINST-5202 remove auto retry; use ipmi over ssh to reboot

- operations/security_and_authentication/Restrict_Access_to_NCN_Images_S3_Bucket.md
Minor corrections to NCN image bucket restriction procedure
> CASMINST-5201: Minor corrections to NCN image bucket restriction procedure

- install/bootstrap_livecd_remote_iso.md
- install/bootstrap_livecd_usb.md
- install/deploy_final_ncn.md
- install/deploy_management_nodes.md
- install/install_csm_services.md
- operations/hardware_state_manager/Set_BMC_Management_Role.md
- upgrade/1.2/Stage_0_Prerequisites.md
- upgrade/1.2/Stage_5.md
- upgrade/prepare_for_upgrade.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/2196
Also includes some 1.2-specific changes based on recent 1.2 installs I performed.
> CASMINST-5205: Fixes, enhancements, and linting to install/upgrade docs

- upgrade/scripts/upgrade/prerequisites.sh
CASMINST-5049: AUTOMATION: Create Script to deploy kyverno/policies and run in a stage of prerequisites.sh
Signed-off-by: pradeepkumargl <80017325+pradeepkumargl@users.noreply.github.com>
First cut test logs are attached.
[prerequsites log.txt](https://github.com/Cray-HPE/docs-csm/files/9266422/prerequsites.log.txt)
> CASMINST-5049: Automation: Create Script to deploy kyverno/policies

- upgrade/scripts/common/ncn-rebuild-common.sh
> CASMINST-5202 remove dead code

- upgrade/prepare_for_upgrade.md
This adds a recommended step prior to starting the upgrade of taking a full export of Nexus
> CASMPET-5849: Add recommended export step prior to upgrade

- .spelling
- background/README.md
- background/certificate_authority.md
- background/ncn_boot_workflow.md
- background/ncn_images.md
- background/ncn_mounts_and_filesystems.md
- background/ncn_networking.md
- background/ncn_operating_system_releases.md
- background/ncn_plan_of_record.md
Add a new `README.md` page detailing all the kernel parameters.
Lint several of the background pages.
Include information about the Python installations in the overview page.
> New NCN Overview Page

- scripts/csm_rbd_tool.py
- upgrade/Stage_0_Prerequisites.md
- upgrade/Stage_3.md
Introduction of the csm_rbd_tool.py script to create and manage an rbd pool and device for use with installs and upgrades.
> CASMINST-5009

- upgrade/1.2.1/README.md
- upgrade/1.2.1/upgrade_network.md
Adding network upgrade instructions to /upgrade/1.2.1/README.md and adding a new network upgrade doc. 
> CASMNET-1780 | 1.2.1 upgrade network initial commit

- background/README.md
- background/ncn_mounts_and_filesystems.md
> typo corrections

- operations/argo/Using_the_Argo_UI.md
- upgrade/Stage_1.md
- upgrade/Stage_2.md
docs instructions for using Argo UI during upgrade
> CASMPET-5891 docs instructions for using Argo UI during upgrade

- upgrade/1.2.1/README.md
> CASMNET-1780

- operations/kubernetes/TDS_Lower_CPU_Requests.md
- operations/network/management_network/bican_enable.md
- operations/node_management/Reboot_NCNs.md
- operations/node_management/Rebuild_NCNs/Rebuild_NCNs.md
- troubleshooting/known_issues/SLS_Not_Working_During_Node_Rebuild.md
- CASMINST-5217 fix path issue
- CASMINST-5217 update worker rebuild doc
> CASMINST-5217 fix path issue

- background/index.md
- index.md
- install/index.md
- introduction/index.md
- operations/UAS_user_and_admin_topics/index.md
- operations/index.md
- operations/network/management_network/aruba/index.md
- operations/network/management_network/canu/index.md
- operations/network/management_network/dell/index.md
- operations/network/management_network/index.md
- operations/network/management_network/mellanox/index.md
- troubleshooting/index.md
- update_product_stream/index.md
- upgrade/index.md
- upgrade/resource_material/index.md
- upgrade/scripts/sls/sls_utils/index.md
The HTML render looks for `index.md`, this creates `index.md` symlinks for every `README.md` file.
> Add index.md symlinks for HTML render

- upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
- workflows/scripts/upload-worker-rebuild-templates.sh
- force k8s sync after uploading workflow files
fanta
> CASMINST-5197

- upgrade/scripts/upgrade/util/nls-keycloak-configure.py
- upgrade/scripts/upgrade/util/upgrade-cray-nls.sh
- CASMPET-5889  enable pipefail
- CASMPET-5889  add curl error handling
- CASMINST-5197 upload workflow files as part of nls deployment
Fanta
> CASMPET-5889

- install/bootstrap_livecd_usb.md
- install/wipe_ncn_disks_for_reinstallation.md
Backport of https://github.com/Cray-HPE/docs-csm/pull/2233
> CASMINST-5219: Corrections and improvements to install and upgrade documents

- upgrade/lib/validation/CASMREL-776-CSM12-NCN-boot-order-backport/scripts/metal-lib.sh
Fix the `grep` commands for posterity incase anyone uses these scripts in prior upgrades.
> MTL-1909 1.0 Validation Scripts

- operations/node_management/Repurpose_Compute_as_UAN.md
This PR adds a reference to the UAN docs for repurposing compute nodes as UANs.
- [NA] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [NA] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
> CASMUSER-3063: Add topic of repurposed compute nodes as UANs

- operations/network/management_network/generate_switch_configs.md
- operations/network/management_network/index.md
Updating CANU related commannds and release notes locations
> CASMNET-1803 | network upgrades for CANU specific things 1.2

- operations/network/management_network/1.2_to_1.3_upgrade.md
- operations/network/management_network/README.md
- operations/network/management_network/generate_switch_configs.md
Updating CANU related commannds and release notes locations
> CASMNET-1804 | network upgrades for CANU specific things 1.3
